### ISSUE TITLE
Please fix me this error

### ISSUE THREAD

**Issue by xaxathiena** [Unity-Technologies/ml-agents#1026]
(base) c:\ml-agents\python>python learn.py ball\ball --run-id=firstRun --train
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:unityagents:{'--curriculum': 'None',
 '--docker-target-name': 'Empty',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--run-id': 'firstRun',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<env>': 'ball\\ball'}
Traceback (most recent call last):
  File "learn.py", line 61, in <module>
    worker_id, keep_checkpoints, lesson, seed, docker_target_name, TRAINER_CONFIG_PATH)
  File "c:\ml-agents\python\unitytrainers\trainer_controller.py", line 77, in __init__
    curriculum=self.curriculum_file, seed=self.seed)
  File "c:\ml-agents\python\unityagents\environment.py", line 109, in __init__
    p = self._conn.recv(self._buffer_size).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 63: invalid start byte

**Comment by vincentpierre** [comment]
Hi, 
From the looks of this error, it seems you are using a python version of ML-Agents that is older than the Unity version. Please make sure the versions you are using in the Unity version and the python version are compatible.
Could you give more details on the issue you are getting? What are the versions of ml-agents, packages and Unity that you are using ?

**Comment by eshvk** [comment]
Thanks for reaching out to us. Hopefully you were able to resolve your issue.  We are closing this due to inactivity, but if you need additional assistance, feel free to reopen the issue.
