### ISSUE TITLE
Develop Branch: NameError: name 'env_path' is not defined

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#1113]
Just encountered this NameError on the Develop branch (commit 153bf0c53159e3152894350daf7d4881bd2d4218)
```
(ml-agents-d) D:\MPL\Repositories\ml-agents-develop\python>python learn.py banana --train --run-id=banana_multi_test


                    ▄▄▄▓▓▓▓
               ╓▓▓▓▓▓▓█▓▓▓▓▓
          ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
        ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
      ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
    ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
    ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
      ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
        '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
           ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
               `▀█▓▓▓▓▓▓▓▓▓▌
                    ¬`▀▀▀█▓


INFO:unityagents:{'--curriculum': 'None',
 '--docker-target-name': 'Empty',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-runs': '1',
 '--run-id': 'banana_multi_test',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<env>': 'banana'}
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\mpl\AppData\Local\conda\conda\envs\ml-agents-d\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\mpl\AppData\Local\conda\conda\envs\ml-agents-d\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\MPL\Repositories\ml-agents-develop\python\learn.py", line 47, in run_training
    tc = TrainerController(env_path, run_id + "-" + str(sub_id), save_freq, curriculum_file,
NameError: name 'env_path' is not defined

(ml-agents-d) D:\MPL\Repositories\ml-agents-develop\python>
```

**Comment by vincentpierre** [comment]
What if you add line 27 ? 
```python
env_path = run_options['<env>']
```

What is the machine you are using? I do not run into this issue on OSX.

**Comment by MarcoMeter** [comment]
I tried it and it didn't work.

Windows 10

**Comment by vincentpierre** [comment]
Hmmm, Can you put a print statement line 100 in `main` and display the value of `env_path` ? This error could be because somehow `run_training` is called before `main` but I do not know what could be causing this...

**Comment by MarcoMeter** [comment]
It prints "None" if I don't add the file path and it prints whatever file path I added, like "banana/banana.exe".

I reproduced this on another Windows 10 machine.

**Comment by vincentpierre** [comment]
I made a branch with the fix, can you check it out ?
