### ISSUE TITLE
Imitation Learning has error now in 0.5

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#1216]
Unity Academy name: Academy
        Number of Brains: 2
        Number of External Brains : 1
        Reset Parameters :
		
Unity brain name: EspecialistaOnlyOneAuto
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 56
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): []
        Vector Action descriptions: , , , , , , , , 
Unity brain name: Aprendiz
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 56
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [9]
        Vector Action descriptions: actions
2018-09-12 12:30:52.561068: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
INFO:mlagents.envs:Hyperparameters for the Imitation Trainer of brain Aprendiz: 
	brain_to_imitate:	EspecialistaOnlyOneAuto
	batch_size:	128
	time_horizon:	128
	graph_scope:	
	summary_freq:	1000
	max_steps:	10000
	batches_per_epoch:	5
	use_recurrent:	False
	hidden_units:	55
	learning_rate:	0.0003
	num_layers:	2
	sequence_length:	64
	memory_size:	256
Process Process-1:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\programdata\anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 47, in run_training
    tc.start_learning()
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 420, in start_learning
    trainer.update_policy()
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\bc\trainer.py", line 245, in update_policy
    run_out = self.policy.update(mini_batch, self.n_sequences)
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\bc\policy.py", line 86, in update
    run_out = self._execute_model(feed_dict, self.update_dict)
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\policy.py", line 78, in _execute_model
    network_out = self.sess.run(list(out_dict.values()), feed_dict=feed_dict)
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1109, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "c:\programdata\anaconda3\lib\site-packages\numpy\core\numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.

**Comment by icaro56** [comment]
HallwayIL Example does not work too. In this sample is missing inform branch size = 1 and branch_0 size = 5

**Comment by icaro56** [comment]
I Fix the problem based on HallwayIL Example.

It is missing configure branch_size in my specialist. I configured only in student.

Thanks developers! The ML-Agents plugin is getting better and better.

**Comment by awjuliani** [comment]
Hi @icaro56,

Would you be willing to make a PR with your fix?

**Comment by icaro56** [comment]
Hi @awjuliani 

I do not make PR, but if you explain me I could. But the fixes are very simple. It is only edit branch size in the editor.

**Comment by icaro56** [comment]
@awjuliani , Did I do it the right way?


https://github.com/Unity-Technologies/ml-agents/pull/1220
