### ISSUE TITLE
Linux server: The Unity environment took too long to respond

### ISSUE THREAD

**Issue by Linkaan** [Unity-Technologies/ml-agents#1296]
I followed the [guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-on-Amazon-Web-Service.md) to running ML-agents on a Linux system with a virtual X server.

I can run glxgears to confirm that the X server is working:
```
15770 frames in 5.0 seconds = 3153.887 FPS
16109 frames in 5.0 seconds = 3221.643 FPS
15762 frames in 5.0 seconds = 3152.289 FPS
11419 frames in 5.0 seconds = 2283.586 FPS
11261 frames in 5.0 seconds = 2252.118 FPS
11211 frames in 5.0 seconds = 2242.122 FPS
...
```

Result of nvidia-smi:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   36C    P8    16W / 250W |    225MiB / 11176MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   20C    P8     7W / 250W |    225MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4329      G   /usr/lib/xorg/Xorg                            10MiB |
|    0      4481      C   /home/deep/.virtualenvs/unity/bin/python3    205MiB |
|    1      4329      G   /usr/lib/xorg/Xorg                            10MiB |
|    1      4481      C   /home/deep/.virtualenvs/unity/bin/python3    205MiB |
+-----------------------------------------------------------------------------+

```

## The problem
I can train in headless mode with mlagents without any problems. However, if I try to run an example environment such as GridWorld I get this error:
```
Found path: /home/deep/ml-agents/GridWorld.x86_64
Mono path[0] = '/home/deep/ml-agents/GridWorld_Data/Managed'
Mono config path = '/home/deep/ml-agents/GridWorld_Data/MonoBleedingEdge/etc'
PlayerConnection initialized from /home/deep/ml-agents/GridWorld_Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55075
Multi-casting "[IP] 10.130.193.204 [Port] 55075 [Flags] 2 [Guid] 1839341276 [EditorId] 4123712109 [Version] 1048832 [Id] LinuxPlayer(10.130.193.204) [Debug] 0" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55075]
Preloaded 'ScreenSelector.so'
Preloaded 'libgrpc_csharp_ext.x64.so'
Preloaded 'liblibtensorflow.so'
Preloaded 'libtensorflow_framework.so'
PlayerConnection already initialized - listening to [0.0.0.0:55075]
Logging to /home/deep/.config/unity3d/Unity Technologies/Unity Environment/Player.log
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/deep/.virtualenvs/unity/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 46, in run_training
    docker_target_name, trainer_config_path, no_graphics)
  File "/home/deep/.virtualenvs/unity/lib/python3.6/site-packages/mlagents/trainers/trainer_controller.py", line 101, in __init__
    no_graphics=no_graphics)
  File "/home/deep/.virtualenvs/unity/lib/python3.6/site-packages/mlagents/envs/environment.py", line 67, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "/home/deep/.virtualenvs/unity/lib/python3.6/site-packages/mlagents/envs/environment.py", line 527, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "/home/deep/.virtualenvs/unity/lib/python3.6/site-packages/mlagents/envs/rpc_communicator.py", line 61, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Academy and the External Brain(s) are attached to objects in the Scene
         The environment and the Python interface have compatible versions.
```

I get the same error if I try to run it from python directly:
```python
from mlagents.envs import UnityEnvironment
env = UnityEnvironment("GridWorld")
```

## System
I am running Ubuntu 18.04 with the latest version of ML-agents and tensorflow 1.7 compiled with cuda support. I don't have any proxies installed either.

If I run the exact same executable on my desktop computer running Linux mint it works without any problems:
![unity](https://user-images.githubusercontent.com/11377980/46571312-107f4b80-c973-11e8-9194-038b7fe9e1df.png)

**Comment by xiaomaogy** [comment]
Hi @Linkaan , have you looked at your /home/deep/.config/unity3d/Unity Technologies/Unity Environment/Player.log? Maybe its content will be helpful. Also in your

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      4329      G   /usr/lib/xorg/Xorg                            10MiB |
|    0      4481      C   /home/deep/.virtualenvs/unity/bin/python3    205MiB |
|    1      4329      G   /usr/lib/xorg/Xorg                            10MiB |
|    1      4481      C   /home/deep/.virtualenvs/unity/bin/python3    205MiB |
```

You seems to have two Xorg. You should only launch one. 

Also have you made sure you have run 

`export DISPLAY=:0`

**Comment by itggot-linus-styren** [comment]
@xiaomaogy thanks for the reply. The machine is currently not functional so I can't verify that I have xorg correctly installed. However, I tried this setup on my other headless linux server with only one gtx 1080 GPU and everything worked first try.

My question is if having two GPUs will be an issue?

**Comment by OneFiveChen** [comment]
I meet the same problem 
`mlagents.envs.exception.UnityTimeOutException:  The Unity environment took too long to respond...`
Have you solved this problem?

**Comment by ZhukIvan** [comment]
After spending lot of time on this issue, I've found the solution. If you connect your display to videocard - you have specified:
`export DISPLAY=:1`

**Comment by OneFiveChen** [comment]
Hi, @xiaomaogy , I meet the same problem and in my `Play.log` it shows that 
```
Desktop is 1920 x 1040 @ 0 Hz
Unable to find a supported OpenGL core profile
Failed to create valid graphics context: please ensure you meet the minimum requirements
E.g. OpenGL core profile 3.2 or later for OpenGL Core renderer
Vulkan detection: 0
No supported renderers found, exiting

(Filename:  Line: 590)
```

And I use `glxinfo | grep "OpenGL version"
` 
`OpenGL version string: 1.4 (2.1 Mesa 10.5.4)`

So I want to update OpenGL but solutions I googled  don't work. Can you help me?

**Comment by xiaomaogy** [comment]
@itggot-linus-styren Two GPUs are fine.

**Comment by xiaomaogy** [comment]
@OneFiveChen I'm not sure how to upgrade OpenGL. Please google it yourself.

**Comment by mmattar** [comment]
Closing this issue due to lack of activity. If you run into any additional issues, please be sure to re-open or submit a new issue.
