### ISSUE TITLE
prompt-toolkit ContextualVersionConflict

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#1306]
As a request, could you update your dependencies to utilize prompt-toolkit 2.0.5 and not version 1.0.15?

The recent version of ipython and jupyter-console conflict with the dependencies of ml-agents.

This is the exception thrown on my jupyter notebook server:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (prompt-toolkit 2.0.5 (/opt/conda/lib/python3.6/site-packages), Requirement.parse('prompt-toolkit<2.0.0,>=1.0.15'), {'ipython'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/mlagents-learn", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'attrs>=17.4.0' distribution was not found and is required by pytest
```

To reproduce this behavior, install the Notebook using this Dockerfile:

```
FROM jupyter/scipy-notebook
LABEL maintainer="Marco Pleines <m.pleines@devbeyond.de>"

# Install Tensorflow and Keras
USER $NB_USER

RUN conda install --quiet --yes \
    'tensorflow=1.7*' && \
    conda clean -tipsy && \
fix-permissions $CONDA_DIR

# Install pip
USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
	curl \
	&& \
	curl -O https://bootstrap.pypa.io/get-pip.py && \
    	python get-pip.py && \
	rm get-pip.py


# Install Zip / Unzip
RUN apt-get install -y zip unzip
	
# Install Jupyter Tensorboard Plugin
USER $NB_USER
RUN pip install jupyter-tensorboard

# Retrieve and prepare ML-Agents Python files
USER root
ADD https://github.com/Unity-Technologies/ml-agents/archive/0.5.0.tar.gz /home/jovyan/

RUN pip install /home/jovyan/ml-agents-0.5.0/ml-agents/. \
	&& rm -r /home/jovyan/ml-agents-0.5.0/UnitySDK \
	&& fix-permissions /home/jovyan/ml-agents-0.5.0/*
	
# Add useful files
COPY Troubleshooting_Utilities.ipynb /home/jovyan
# Fix permissions
RUN chmod -R 777 /home/jovyan/*
# Override Jupyter Config
COPY jupyter_notebook_config.py /etc/jupyter/

USER $NB_USER
```

Downgrading to jupyter-console==5.0.0 solves the conflict.

**Comment by awjuliani** [comment]
Hi @MarcoMeter 

Are you still getting this issue in v0.6? We've updated our dependencies recently.

**Comment by MarcoMeter** [comment]
I have to get back to this next year.

**Comment by awjuliani** [comment]
As of v0.8 we are changing and expanding the supported python package versions. Closing this issue for now. Please feel free to re-open if you deem it necessary.
