### ISSUE TITLE
Two environments with the same seed bug

### ISSUE THREAD

**Issue by cyrilibrahim** [Unity-Technologies/ml-agents#1340]
Hi, 

I think there's a bug in the Python API (or maybe just with the Gym wrapper). If I create an environment with the seed 0, and then try to create another environment with the same seed (in a different application) this will cause the first environment to crash. I think the bug was introduced with the version 0.5. 

It's really a big issue, for example if you're training an agent with python, the training crash when you launch your environment in the Unity Editor. Here's the error that I get: 

```  ob, reward, done, info = self.env.step(action)
  File "/home/cyrili/gym/gym/core.py", line 330, in step
    return self.env.step(action)
  File "/home/cyrili/anaconda3/lib/python3.6/site-packages/gym_unity/envs/unity_env.py", line 131, in step
    info = self._env.step(action)[self.brain_name]
  File "/home/cyrili/anaconda3/lib/python3.6/site-packages/mlagents/envs/environment.py", line 384, in step
    self._n_agents[_b] = len(s[0][_b].agents)
KeyError: 'Brain'
ERROR:root:Exception calling application: could not find MARK
Traceback (most recent call last):
  File "/home/cyrili/anaconda3/lib/python3.6/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/home/cyrili/anaconda3/lib/python3.6/site-packages/mlagents/envs/rpc_communicator.py", line 27, in Exchange
    return self.child_conn.recv()
  File "/home/cyrili/anaconda3/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
_pickle.UnpicklingError: could not find MARK ```

**Comment by awjuliani** [comment]
Hi @cyrilibrahim,

I just tested this out on my own machine using v0.5, and was not able to reproduce this bug. It is possible to launch multiple concurrent instances of an environment on the same machine. Doing so however requires that the `worker_id` parameter be unique for each instance of the environment. This parameter corresponds to the port used for communication, and as such using the same value for multiple environments will lead to conflicts.

**Comment by cyrilibrahim** [comment]
Thanks for the quick answer! 
Yes I agree that each environment should have a different worker_id on the same machine, but if by error I launch another environment with the same worker_id, I'll loose my first environment. The new launched environment should crash and the first one continu to run no matter what happened in other applications. But the inverse happens, the first one crash and the new one continu to run. 

Maybe it's just a problem on my machine since you can't reproduce it. 

Thanks again !

**Comment by xiaomaogy** [comment]
Hi @cyrilibrahim , yes this is currently the case. If you launch the second environment with the same worker_id as the first one, the first one will crash without saving the model. We will mark this bug and try to fix it in later version.
