### ISSUE TITLE
struct.error: unpack requires a buffer of 16 bytes

### ISSUE THREAD

**Issue by AllenLeepy** [Unity-Technologies/ml-agents#1435]
C:\python\re>pyinstaller -F -i aa.ico test.py
102 INFO: PyInstaller: 3.4
103 INFO: Python: 3.6.5
104 INFO: Platform: Windows-10-10.0.10240-SP0
107 INFO: wrote C:\python\re\test.spec
112 INFO: UPX is not available.
115 INFO: Extending PYTHONPATH with paths
['C:\\python\\re', 'C:\\python\\re']
116 INFO: checking Analysis
118 INFO: Building Analysis because Analysis-00.toc is non existent
120 INFO: Initializing module dependency graph...
126 INFO: Initializing module graph hooks...
131 INFO: Analyzing base_library.zip ...
5630 INFO: running Analysis Analysis-00.toc
5652 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\administrator\anaconda3\python.exe
6485 INFO: Caching module hooks...
6492 INFO: Analyzing C:\python\re\test.py
7464 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
12583 INFO: Processing pre-safe import module hook   six.moves
14341 INFO: Loading module hooks...
14342 INFO: Loading module hook "hook-certifi.py"...
14345 INFO: Loading module hook "hook-cryptography.py"...
14837 INFO: Loading module hook "hook-encodings.py"...
14976 INFO: Loading module hook "hook-pydoc.py"...
14978 INFO: Loading module hook "hook-xml.py"...
15220 INFO: Looking for ctypes DLLs
15232 INFO: Analyzing run-time hooks ...
15248 INFO: Looking for dynamic libraries
15916 INFO: Looking for eggs
15916 INFO: Using Python library c:\users\administrator\anaconda3\python36.dll
15918 INFO: Found binding redirects:
[]
15928 INFO: Warnings written to C:\python\re\build\test\warn-test.txt
16007 INFO: Graph cross-reference written to C:\python\re\build\test\xref-test.html
16023 INFO: checking PYZ
16023 INFO: Building PYZ because PYZ-00.toc is non existent
16024 INFO: Building PYZ (ZlibArchive) C:\python\re\build\test\PYZ-00.pyz
16845 INFO: Building PYZ (ZlibArchive) C:\python\re\build\test\PYZ-00.pyz completed successfully.
16862 INFO: checking PKG
16863 INFO: Building PKG because PKG-00.toc is non existent
16863 INFO: Building PKG (CArchive) PKG-00.pkg
19402 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
19406 INFO: Bootloader c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
19407 INFO: checking EXE
19407 INFO: Building EXE because EXE-00.toc is non existent
19409 INFO: Building EXE from EXE-00.toc
19418 INFO: SRCPATH [('aa.ico', None)]
19419 INFO: Updating icons from ['aa.ico'] to C:\Users\ADMINI~1\AppData\Local\Temp\tmpm4ujzb1i
Traceback (most recent call last):
  File "c:\users\administrator\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Anaconda3\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 32, in <module>
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\building\api.py", line 433, in __init__
    self.__postinit__()
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\building\api.py", line 522, in assemble
    icon.CopyIcons(tmpnm, self.icon)
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\utils\win32\icon.py", line 177, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\utils\win32\icon.py", line 134, in CopyIcons_FromIco
    for i, f in enumerate(icons):
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\utils\win32\icon.py", line 104, in __init__
    entry.fromfile(file)
  File "c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\utils\win32\icon.py", line 65, in fromfile
    self._fields_ = list(struct.unpack(self._format_, data))
struct.error: unpack requires a buffer of 16 bytes

**Comment by generalhu** [comment]
图片的格式需要彻底改成ico格式的
the type of the picture need to be ico totally

**Comment by mmattar** [comment]
Closing this issue as it's not clear it related to ml-agents.
