### ISSUE TITLE
MemoryError happened in training

### ISSUE THREAD

**Issue by CicieChen** [Unity-Technologies/ml-agents#1444]
Hi, 
I met an issue about memory error after training for **a while**. 
I have two brains and 2 agents in my environment and 4 observation inputs to the ppo. However, i met the messages below:
```
Traceback (most recent call last):
File "c:\users\anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
self.run()
File "c:\users\anaconda3\lib\multiprocessing\process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "c:\users\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 47, in run_training
tc.start_learning()
File "c:\users\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 372, in start_learning
trainer.process_experiences(curr_info, new_info)
File "c:\users\anaconda3\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 290, in process_experiences
training_length=self.policy.sequence_length)
File "c:\users\anaconda3\lib\site-packages\mlagents\trainers\buffer.py", line 229, in append_update_buffer
self[agent_id][field_key].get_batch(batch_size=batch_size, training_length=training_length)
File "c:\users\anaconda3\lib\site-packages\mlagents\trainers\buffer.py", line 39, in extend                                       self += list(np.array(data))
MemoryError 
```

The version of ml-agents is 0.5.
Training configurations are: 
```
    batch_size: 2048
    beta: 5.0e-3
    buffer_size: 5120
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 1.0e-3
    max_steps: 30.0e4
    memory_size: 2048
    normalize: true
    num_epoch: 10
    num_layers: 3
    time_horizon: 64
    sequence_length: 64
    summary_freq: 3000
    use_recurrent: false
    use_curiosity: true
    curiosity_strength: 0.01
    curiosity_enc_size: 128
```  

Could you please tell me how to fix it? Thanks!

**Comment by CicieChen** [comment]
Hi,

This has been solved by restarting the machine. But I highly recommend moving the training to another machine due to the possible memory leak.
