### ISSUE TITLE
self._n_agents[_b] = len(s[0][_b].agents) error

### ISSUE THREAD

**Issue by liuyihunter** [Unity-Technologies/ml-agents#1456]
I try to train the game which wrote by myself, the EXE started and then crashed.  These are the error messages i got.  Is there any one know how to debug it？Thank you.

Traceback (most recent call last):
  File "e:\anaconda\envs\ml-agents\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "e:\anaconda\envs\ml-agents\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "e:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 47, in run_training
    tc.start_learning()
  File "e:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 316, in start_learning
    curr_info = self._reset_env()
  File "e:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 282, in _reset_env
    return self.env.reset(train_mode=self.fast_simulation)
  File "e:\anaconda\envs\ml-agents\lib\site-packages\mlagents\envs\environment.py", line 262, in reset
    self._n_agents[_b] = len(s[0][_b].agents)
KeyError: 'DecisionBrain'

**Comment by ervteng** [comment]
Hi @liuyihunter, have you resolved this issue? 

If not, are there errors in your Unity logs? It seems that the DecisionBrain agent is not being found by the Python code. Please try training using the Unity editor rather than an EXE, and report any messages you see in the Console.

**Comment by epsil0nzer0** [comment]
Hi @ervteng I have the same issue.
when i checked the control box in "Ball 3D Academy" script in 3D ball example the same issue happened to me. 
Here is the error message that mlagents-learn produced: 

Process Process-1:
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\user\Anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\htdocs\ai\ml-agents\ml-agents\mlagents\trainers\learn.py", line 52, in run_training
    tc.start_learning()
  File "d:\htdocs\ai\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 292, in start_learning
    curr_info = self._reset_env()
  File "d:\htdocs\ai\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 275, in _reset_env
    return self.env.reset(train_mode=self.fast_simulation)
  File "d:\htdocs\ai\ml-agents\ml-agents\mlagents\envs\environment.py", line 255, in reset
    self._n_agents[_b] = len(s[0][_b].agents)
KeyError: '3DBallLearning'

also I get this error in unity console which I suppose it's because ml-agent has exited and unity can not connect to it:
UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at Assets/ML-Agents/Scripts/Batcher.cs:91)
MLAgents.Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:321)
MLAgents.Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:230)

I lookd at line 255 of file ml-agents\mlagents\envs\environment.py and it seems rl_output does not exists in outputs object.

**Comment by ervteng** [comment]
Hi @epsil0nzer0, something to check - do all 12 of the Platform GameObjects have a 3DBallLearning Brain attached to them? Some of them might still be using a Player Brain. 
The easiest way to do this is to change the Brain in the Game Prefab.

**Comment by epsil0nzer0** [comment]
Yes I used prefab to attach brain to all 12 platform game objects.
I am not a python export but it seems to me that the response to rpc request does not come back in the expected format. 

this is the data I get in response to reset rpc request:
rl_initialization_output {
  name: "Platform"
  version: "API-6"
  brain_parameters {
    vector_observation_size: 8
    num_stacked_vector_observations: 1
    vector_action_size: 2
    vector_action_descriptions: ""
    vector_action_descriptions: ""
    vector_action_space_type: continuous
    brain_name: "3DBallLearning"
    is_training: true
  }
  environment_parameters {
  }
}

if you trace reset method of UnityEnvironment class (environment.py) you can see the response should have a different format. I suspect maybe its related to API version or something.

**Comment by ervteng** [comment]
Hmm, it's possible that the Python script version you have installed is different than the ML-Agents script you have within Unity; I haven't seen this issue using the 3D Ball environment. 

Try re-installing the ml-agents Python (`pip3 install -e .` in the ml-agents/ml-agents directory) https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md. It's possible that an older version was installed beforehand and is still being called by mlagents-learn.

**Comment by ervteng** [comment]
Closing this issue due to inactivity. Feel free to open a new issue if you still have a problem.

**Comment by egg-west** [comment]
I am using the latest version of mlagents and installed from the directory. 
Got the same problem. I print the `self._n_agents.keys()`, which is empty.
