### ISSUE TITLE
Linux Server : Unable to find a supported OpenGL core profile

### ISSUE THREAD

**Issue by OneFiveChen** [Unity-Technologies/ml-agents#1464]
I try to run ml-agents in Ubuntu 16.04 LTS and I meet the same problem with #1296 
I can train 3dball in no-graphics mode but error comes when I train without no-graphics
when it arrives `Logging to /home/ml/.config/unity3d/Unity Technologies/test/Player.log`
The background of the screen blacken.  And reduce immediately
Then
```
Logging to /home/ml/.config/unity3d/Unity Technologies/test/Player.log
Process Process-1:
Traceback (most recent call last):
  File "/home/ml/anaconda3/envs/mlagents_env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ml/anaconda3/envs/mlagents_env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ml/anaconda3/envs/mlagents_env/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 46, in run_training
    docker_target_name, trainer_config_path, no_graphics)
  File "/home/ml/anaconda3/envs/mlagents_env/lib/python3.6/site-packages/mlagents/trainers/trainer_controller.py", line 101, in __init__
    no_graphics=no_graphics)
  File "/home/ml/anaconda3/envs/mlagents_env/lib/python3.6/site-packages/mlagents/envs/environment.py", line 67, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "/home/ml/anaconda3/envs/mlagents_env/lib/python3.6/site-packages/mlagents/envs/environment.py", line 527, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "/home/ml/anaconda3/envs/mlagents_env/lib/python3.6/site-packages/mlagents/envs/rpc_communicator.py", line 61, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Academy and the External Brain(s) are attached to objects in the Scene
         The environment and the Python interface have compatible versions.
```

 and in my `Play.log` it shows that 
```
Desktop is 1920 x 1040 @ 0 Hz
Unable to find a supported OpenGL core profile
Failed to create valid graphics context: please ensure you meet the minimum requirements
E.g. OpenGL core profile 3.2 or later for OpenGL Core renderer
Vulkan detection: 0
No supported renderers found, exiting

(Filename:  Line: 590)
```

 `glxinfo | grep "OpenGL version"
` shows me the version
`OpenGL version string: 1.4 (2.1 Mesa 10.5.4)`

### The problem

So I want to update OpenGL but solutions I googled  don't work. 
How can I update OpenGL?

**Comment by xiaomaogy** [comment]
Hi @OneFiveChen , did you try with the https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-on-Amazon-Web-Service.md? I know that certain opengl doesn't work unless you update the OpenGL, but we don't have any suggestions on how to do that.

**Comment by OneFiveChen** [comment]
These days I try to update my NVIDIA-Driver, but it doesn't work. Then Searching in forum of Ubuntu NVIDIA OpenGL, it seems that all methods cannot work. But by chance, I connect the server with terminal of Ubuntu system. I get the feed back
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1080 Ti/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 390.12
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 390.12
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 390.12
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```
Amazing!
I use XStart in Windows10 to connect the Xserver , OpenGL version always shows 1.1
But when I use Ubuntu Terminal, OpenGL version is 4.6.0
I don‘t why, but it actually works
