### ISSUE TITLE
Got a SIGABRT error ?

### ISSUE THREAD

**Issue by MoMe36** [Unity-Technologies/ml-agents#1569]
Hello, 

I am running into an error when trying to create an executable for training. I am using the vanilla 3DBall environment and the process works fine when training without the building the exec. 

Here's my command line: 

```bash
mlagents-learn ../config/trainer_config.yaml --env=3DBall --run-id=Test --train 
```

And the error: 

```bash
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Process Process-1:
Traceback (most recent call last):
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 46, in run_training
    docker_target_name, trainer_config_path, no_graphics)
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/site-packages/mlagents/trainers/trainer_controller.py", line 112, in __init__
    no_graphics=no_graphics)
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/site-packages/mlagents/envs/environment.py", line 67, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/site-packages/mlagents/envs/environment.py", line 493, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/site-packages/mlagents/envs/rpc_communicator.py", line 77, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Academy and the External Brain(s) are attached to objects in the Scene
	 The environment and the Python interface have compatible versions.
^CTraceback (most recent call last):
  File "/home/mehdi/miniconda3/envs/ML/bin/mlagents-learn", line 11, in <module>
    sys.exit(main())
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 118, in main
    while process_queue.get() is not True:
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/mehdi/miniconda3/envs/ML/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
```

Any tips for solving this ? 

Thanks a lot !

**Comment by MoMe36** [comment]
It was Linux, and yes, 64 bit. 
I tried it again this morning, this time with success. I think the issue had to do with Unity version.

**Comment by MarcoMeter** [comment]
Which unity versions did you use?

**Comment by MoMe36** [comment]
It was 2018.3 I think. 
Now, with 2018.2.7f1, everything works smoothly !
