### ISSUE TITLE
Problem with large number of State Size

### ISSUE THREAD

**Issue by JinjinGuo** [Unity-Technologies/ml-agents#159]
As State Size is increased, the following error occurs. (When it approaches roughly 1000)

Traceback (most recent call last):
  File "test.py", line 79, in <module>
    new_info = trainer.take_action (info, env, brain_name)
  File "/Users/xxxxxxxxx/Desktop/unity/ml-agents-master/python/ppo/trainer.py", line 55, in take _ action
    new_info = env.step (actions, value = {brain_name: value}) [brain_name]
  File "/Users/xxxxxxxxx/Desktop/unity/ml-agents-master/python/unityguents/ environment.py", line 343, in step
    return self._get_state ()
  File "/Users/xxxxxxxxx/Desktop/unity/ml-agents-master/python/unityguents/ environment.py", line 211, in _get_state
    state_dict = self._get_state_dict ()
  File "/Users/xxxxxxxxx/Desktop/unity/ml-agents-master/python/unityguents/ environment.py", line 178, in _get_state_dict
    state_dict = json.loads (state)
  File "/Users/xxxxxxxxx/.pyenv/versions/anaconda3-4.1.1/envs/egpu/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode (s)
  File "/Users/xxxxxxxxx/.pyenv/versions/anaconda3-4.1.1/envs/egpu/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode (s, idx = _ w (s, 0). end ())
  File "/Users/xxxxxxxxx/.pyenv/versions/anaconda3-4.1.1/envs/egpu/lib/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError ("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 939 column 3 (char 16332)

Is there any solution?
(If the State Size is small, training will be successful.
Is the cause such as "Socket Receive" failing if State Size is large? )

**Comment by vincentpierre** [comment]
Hi @JinjinGuo, There is a fix for this on the development branch. Please try it out and let us know if that solved your problem.

**Comment by JinjinGuo** [comment]
Thank you for your reply!
With the development branch, I successfully trained with many State Size !!! (State Size = 1215 (per agent), Action Size = 177)
I really appreciate what you 've done.

Currently, I can train enough in my environment.
However, increasing my agent (number of Agents> 5) seems to have a new error.

Traceback (most recent call last):
  File "test.py", line 101, in <module>
    new_info = trainer.take_action (info, env, brain_name, steps)
  File "/Users/JinjinGuo/Desktop/unity/ml-agents-development/python/ppo/trainer.py", line 65, in take _ action
    self.model.running_variance)
  File "/Users/JinjinGuo/Desktop/unity/ml-agents-development/python/ppo/trainer.py", line 39, in running_average
    current_x = np.mean (data, axis = 0)
  File "/Users/JinjinGuo/.pyenv/versions/anaconda3-4.1.1/envs/egpu/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2909, in mean
    out = out, ** kwargs)
  File "/Users/JinjinGuo/.pyenv/versions/anaconda3-4.1.1/envs/egpu/lib/python3.6/site-packages/numpy/core/_methods.py", line 70, in _mean
    ret = umr_sum (arr, axis, dtype, out, keepdims)
TypeError: can not perform reduce with flexible type

I hope this will help the research that you are conducting now.

**Comment by vincentpierre** [comment]
I have never seen this error. Does it happen right after you start or does this happen randomly after a while ? Can you try to replace  File "/Users/JinjinGuo/Desktop/unity/ml-agents-development/python/ppo/trainer.py", line 39 
```
current_x = np.mean (data, axis = 0)
```
with
```
try:
      current_x = np.mean (data, axis = 0)
except:
      print(data)
```
In the trainer, we have a running mean and variance of the states, there could be an issue in the variable `data`. If we compare what `data` should be to what it is, we might be able to figure out what happened.

**Comment by kwea123** [comment]
Even with increased buffer size, the environment runs extremely slowly when the state size is big. I have a camera with resolution 900x600 (high resolution is required since I need to recognize people, etc.) and the environment is very laggy; I had to decrease that to 300x200 so that it works faster as usual. Do you have any idea to make the data transmission faster?

**Comment by mmattar** [comment]
We have since released ML-Agents version 0.3 which might address or clarify some of the earlier issues above. Regarding the transmission speed, we are exploring ways to better compress images from Unity to Python, but nothing planned at the moment. Let us know if you have any additional questions.
