### ISSUE TITLE
Problem in Installation of ml-agents

### ISSUE THREAD

**Issue by kushal98** [Unity-Technologies/ml-agents#1654]
I have been getting this error while installing ml-agents can someone help me out with this:

```
Traceback (most recent call last):
  File "D:\Anaconda\envs\MyWindowsCv\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents==0.6.0', 'console_scripts', 'mlagents-learn')()
  File "D:\Anaconda\envs\MyWindowsCv\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\Anaconda\envs\MyWindowsCv\lib\site-packages\pkg_resources\__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "D:\Anaconda\envs\MyWindowsCv\lib\site-packages\pkg_resources\__init__.py", line 2322, in load
    return self.resolve()
  File "D:\Anaconda\envs\MyWindowsCv\lib\site-packages\pkg_resources\__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "d:\anaconda\envs\mywindowscv\lib\site-packages\mlagents-0.6.0-py3.5.egg\mlagents\trainers\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "d:\anaconda\envs\mywindowscv\lib\site-packages\mlagents-0.6.0-py3.5.egg\mlagents\trainers\buffer.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "d:\anaconda\envs\mywindowscv\lib\site-packages\mlagents-0.6.0-py3.5.egg\mlagents\envs\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "d:\anaconda\envs\mywindowscv\lib\site-packages\mlagents-0.6.0-py3.5.egg\mlagents\envs\environment.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "d:\anaconda\envs\mywindowscv\lib\site-packages\mlagents-0.6.0-py3.5.egg\mlagents\envs\communicator_objects\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "d:\anaconda\envs\mywindowscv\lib\site-packages\mlagents-0.6.0-py3.5.egg\mlagents\envs\communicator_objects\agent_action_proto_pb2.py", line 10, in <module>
  File "d:\anaconda\envs\mywindowscv\lib\site-packages\google\protobuf\descriptor_pb2.py", line 1114, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "d:\anaconda\envs\mywindowscv\lib\site-packages\google\protobuf\descriptor.py", line 534, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.FileOptions.php_metadata_namespace"
```

**Comment by harperj** [comment]
Hi @kushal98,

This is a new issue for us and I'm not able to reproduce at this time.  Could you give me some context about your environment?

Perhaps you could share a `pip freeze`, or your Anaconda version.  Did you make any modifications to ML-Agents?

**Comment by harperj** [comment]
Just wanted to mention that I've seen other similar issues out there and people seemed to find reinstalling protobuf helpful:
```
pip install --force-reinstall --upgrade protobuf
```

**Comment by unityjeffrey** [comment]
hi @kushal98 - closing out the ticket due to inactivity.
