### ISSUE TITLE
Barracuda Upsample2D out of range

### ISSUE THREAD

**Issue by sam598** [Unity-Technologies/ml-agents#1784]
Very excited to hear about the new inference engine and it's possibilities.

I have been able to convert a few simple Keras models using the tensorflow_to_barracuda.py script and the instructions outlined here: https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/Barracuda.md

But I've run into a problem anytime an UpSampling2D layer is used. When executing the model, once it reaches the layer StridedSlice up_sampling2d_1/strided_slice an out of range exception happens.

```
IndexOutOfRangeException: Index was outside the bounds of the array.
Barracuda.TensorExtensions.ApplyStridedSlice (Barracuda.TensorShape shape, System.Int32[] starts, System.Int32[] ends, System.Int32[] stride) (at <1071b9a446b04698af9605e3e272de23>:0)
Barracuda.ReferenceCPUOps.StridedSlice (Barracuda.Tensor X, System.Int32[] starts, System.Int32[] ends, System.Int32[] stride) (at <1071b9a446b04698af9605e3e272de23>:0)
Barracuda.VerboseOps.Barracuda.IOps.StridedSlice (Barracuda.Tensor X, System.Int32[] starts, System.Int32[] ends, System.Int32[] strides) (at <1071b9a446b04698af9605e3e272de23>:0)
Barracuda.GenericWorker.Execute () (at <1071b9a446b04698af9605e3e272de23>:0)
Barracuda.GenericWorker.Execute (Barracuda.Tensor input) (at <1071b9a446b04698af9605e3e272de23>:0)
```

When running the conversion script it does ignore a layer that appears to be associated with UpSampling2D:
`IGNORED: Shape unknown layer`

It could be some kind of helper layer specific to Keras that isn't defined by barracuda which contains the reference to the layer shape that is causing the exception. I realize this is a super niche problem on an experimental beta plugin, but if that is the issue is there an alternative method for defining the shape for the UpSampling2D layer?

**Comment by sam598** [comment]
It looks like there were similar issues with the OpenCV neural net inference when using Keras' implementation of UpSampling2D:

https://github.com/opencv/opencv/issues/10106
https://github.com/opencv/opencv/issues/11886

**Comment by sam598** [comment]
It looks like the converter can interpret a "Shape" layer since it is included in a "known pattern" for flatten layers.

I've tried to create a new pattern for Upscale2D, but I can't really figure out how the pattern is supposed to be structured to export correctly for the Barracuda model. I've tried every variation I can think of, including removing additional layers and naming the patten ResizeNearestNeighbor. The same index out of range error keeps happening.

Am I looking in the right place, or is something broken with StridedSlices? Comments on lines 681 and 682 of tensorflow_to_barracuda.py say:

```
# TEMPORARY: until we implemented rank detection and StidedSlice at runtime
# HACK: skips trivial StridedSlices for rank=2 tensors
```

But it doesn't skip strided slices layers when converting, and it looks like there is a compute kernel for Upsample2D, so it's not clear if this is broken or just not implemented yet.

Is there any advice on what to try and fix? Or is this something planned in the roadmap? Thanks!

**Comment by dahburj** [comment]
I'm just getting started on Barracuda and I'm getting the same error on a model I'm trying out. Did your model convert to .bytes or .bc when you ran tensorflow_to_barracuda.py?

**Comment by sam598** [comment]
Mine converted to .bytes but I specified that in command line.

Simple networks I converted to .bytes without Upscale2D ran without the issue.

**Comment by dahburj** [comment]
Yeah other models I tried worked as well, I was even able to analyze .bc models, I can analyze and see all the layers in this model, even confirm my output and input names by printing and debuging the loaded models output/input, but it just throws the index outside bounds of array no matter what I try.

**Comment by mantasp** [comment]
@sam598, currently Unity Inference Engine supports only models created by ML Agents, but we are looking to support more in the future. Could you please share model you are trying to convert and we will look into it. Thanks!

**Comment by sam598** [comment]
Thanks for the response!

This python script creates a simple dummy convolution network with Keras that is exported as a protobuffer, and can be converted with tensorflow_to_barracuda.py and succesfully inferenced through BarracudaWorkerFactory. The model doesn't do anything, but it runs without error.

Uncommenting the line with Upsample2D causes the strided slice index error only on inference.

```
from __future__ import print_function, division
import scipy

import tensorflow as tf
import keras

from keras.layers import Input, Dense, Flatten
from keras.models import Model
from keras.optimizers import Adam
from keras.engine import InputSpec
from keras.layers import Conv2D, UpSampling2D

import datetime
import sys
import os

def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ''
        frozen_graph = tf.graph_util.convert_variables_to_constants(
            session, input_graph_def, output_names, freeze_var_names)
        return frozen_graph

keras.backend.set_learning_phase(0)

_input = Input(shape=(32,32,1))

d1 = Conv2D(16, kernel_size=4, strides=2, padding='same')(_input)
d2 = Conv2D(16, kernel_size=4, strides=2, padding='same')(d1)
d3 = Conv2D(16, kernel_size=4, strides=2, padding='same')(d2)
#d3 = UpSampling2D(size=(2,2))(d3)

flat = Flatten()(d3)
_output = Dense(32)(flat)

model = Model(_input, _output)
model.compile(loss=['mae'], loss_weights=[100], optimizer=Adam(0.0002, 0.5))

print(model.summary())

with keras.backend.get_session() as sess:
    graph = sess.graph
    with graph.as_default():
        graphdef_inf = tf.graph_util.remove_training_nodes(graph.as_graph_def())
        graphdef_frozen = tf.graph_util.convert_variables_to_constants(sess, graphdef_inf, [out.op.name for out in model.outputs])
        tf.train.write_graph(graphdef_frozen, './dummy_model', 'conv_graph.pb', as_text=False)
```

**Comment by mantasp** [comment]
Thank you, we will look into it.

**Comment by decoybitch** [comment]
I am trying to convert my protobuf file to use in unity inference engine. I ran:python tensorflow_to_barracuda.py obj.pb nn
but I am getting the error:
[tensors[0].data[0], 1, 1, tensors[0].data[1]]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by mantasp** [comment]
@decoybitch if you are using different model than described above, please create separate issue, it will help to track your issue.
Thanks!

**Comment by jmamath** [comment]
Hi there, I try to use the script tensorflow_to_barracuda on a tensorflow model "tf_model.pb" working on tensorflow 1.7.1 on python 3.6. but I get the following error:
The model uses custom layers and stacked GRU to do supervised learning. If I can't load it with Barracuda, what would be the solution to do inference with Unity, I tried the tensorflowsharp plugin using that tutorial: https://blog.goodaudience.com/tensorflow-unity-how-to-set-up-a-custom-tensorflow-graph-in-unity-d65cc1bd1ab1 but without much success.

```IGNORED: ZerosLike unknown layer
IGNORED: ExpandDims unknown layer
IGNORED: Tile unknown layer
IGNORED: Transpose unknown layer
IGNORED: Shape unknown layer
IGNORED: TensorArrayV3 unknown layer
IGNORED: TensorArrayV3 unknown layer
IGNORED: Shape unknown layer
IGNORED: Range unknown layer
IGNORED: TensorArrayScatterV3 unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Merge unknown layer
IGNORED: Merge unknown layer
IGNORED: Merge unknown layer
IGNORED: Merge unknown layer
IGNORED: Less unknown layer
IGNORED: Enter unknown layer
IGNORED: Less unknown layer
IGNORED: Enter unknown layer
IGNORED: LogicalAnd unknown layer
IGNORED: LoopCond unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: TensorArrayReadV3 unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: TensorArrayWriteV3 unknown layer
IGNORED: Enter unknown layer
IGNORED: NextIteration unknown layer
IGNORED: NextIteration unknown layer
IGNORED: NextIteration unknown layer
IGNORED: NextIteration unknown layer
IGNORED: Exit unknown layer
IGNORED: TensorArraySizeV3 unknown layer
IGNORED: Range unknown layer
IGNORED: TensorArrayGatherV3 unknown layer
IGNORED: Transpose unknown layer
IGNORED: ZerosLike unknown layer
IGNORED: ExpandDims unknown layer
IGNORED: Tile unknown layer
IGNORED: Transpose unknown layer
IGNORED: Shape unknown layer
IGNORED: TensorArrayV3 unknown layer
IGNORED: TensorArrayV3 unknown layer
IGNORED: Shape unknown layer
IGNORED: Range unknown layer
IGNORED: TensorArrayScatterV3 unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Merge unknown layer
IGNORED: Merge unknown layer
IGNORED: Merge unknown layer
IGNORED: Merge unknown layer
IGNORED: Less unknown layer
IGNORED: Enter unknown layer
IGNORED: Less unknown layer
IGNORED: Enter unknown layer
IGNORED: LogicalAnd unknown layer
IGNORED: LoopCond unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: TensorArrayReadV3 unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: TensorArrayWriteV3 unknown layer
IGNORED: Enter unknown layer
IGNORED: NextIteration unknown layer
IGNORED: NextIteration unknown layer
IGNORED: NextIteration unknown layer
IGNORED: NextIteration unknown layer
IGNORED: Exit unknown layer
IGNORED: TensorArraySizeV3 unknown layer
IGNORED: Range unknown layer
IGNORED: TensorArrayGatherV3 unknown layer
IGNORED: Transpose unknown layer
IGNORED: ZerosLike unknown layer
IGNORED: ExpandDims unknown layer
IGNORED: Tile unknown layer
IGNORED: Transpose unknown layer
IGNORED: Shape unknown layer
IGNORED: TensorArrayV3 unknown layer
IGNORED: TensorArrayV3 unknown layer
IGNORED: Shape unknown layer
IGNORED: Range unknown layer
IGNORED: TensorArrayScatterV3 unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Merge unknown layer
IGNORED: Merge unknown layer
IGNORED: Merge unknown layer
IGNORED: Merge unknown layer
IGNORED: Less unknown layer
IGNORED: Enter unknown layer
IGNORED: Less unknown layer
IGNORED: Enter unknown layer
IGNORED: LogicalAnd unknown layer
IGNORED: LoopCond unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: TensorArrayReadV3 unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: Enter unknown layer
IGNORED: TensorArrayWriteV3 unknown layer
IGNORED: Enter unknown layer
IGNORED: NextIteration unknown layer
IGNORED: NextIteration unknown layer
IGNORED: NextIteration unknown layer
IGNORED: NextIteration unknown layer
IGNORED: Exit unknown layer
IGNORED: TensorArraySizeV3 unknown layer
IGNORED: Range unknown layer
IGNORED: TensorArrayGatherV3 unknown layer
IGNORED: Transpose unknown layer
IGNORED: Shape unknown layer
IGNORED: Unpack unknown layer
IGNORED: Transpose unknown layer
IGNORED: Shape unknown layer
IGNORED: Unpack unknown layer
IGNORED: Transpose unknown layer
IGNORED: Shape unknown layer
IGNORED: Unpack unknown layer
IGNORED: Transpose unknown layer
IGNORED: Shape unknown layer
IGNORED: Pack unknown layer
IGNORED: Shape unknown layer
IGNORED: BroadcastArgs unknown layer
IGNORED: Shape unknown layer
Traceback (most recent call last):
  File "C:\Users\gsarr\ml-agents\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py", line 23, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "C:\Users\gsarr\ml-agents\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py", line 940, in convert
    process_model(i_model, args)
  File "C:\Users\gsarr\ml-agents\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py", line 887, in process_model
    process_layer(l, o_context, args)
  File "C:\Users\gsarr\ml-agents\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py", line 742, in process_layer
    for x in tensor_names]
  File "C:\Users\gsarr\ml-agents\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py", line 742, in <listcomp>
    for x in tensor_names]
  File "C:\Users\gsarr\ml-agents\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py", line 494, in get_tensor_data
    return np.array(data).reshape(dims)
UnboundLocalError: local variable 'data' referenced before assignment```

**Comment by mantasp** [comment]
Hi @sam598,
we have updated Barracuda in our development branch: https://github.com/Unity-Technologies/ml-agents/tree/develop-barracuda-0.2.0 . It should behave better with Upsample2D, please let us know if it improved it for you.
Thanks!

**Comment by sam598** [comment]
Thanks @mantasp!

That fixes the error and now I can run GANs written in Keras inside Unity.

This is bonkers.

Seriously.

Thank you for getting this to work and all of the work you and the ML team have put into this new release.

One issue I did catch running "tensorflow_to_barracuda.py" in the development branch does not work, and gives the error:
`AttributeError: module 'mlagents.trainers.barracuda' has no attribute 'fuse'`

However using the version of Barracuda 0.2.1 in your standalone repo does not have that error. I'm not sure what's causing that, but since it works and no longer has the out of range error, this issue is closed. Cheers!
