### ISSUE TITLE
ImportError: cannot import name 'UnityRLInput'

### ISSUE THREAD

**Issue by jilcky** [Unity-Technologies/ml-agents#1792]
(ml-agents) C:\ml-agents-master>mlagents-learn config/trainer_config.yaml --run-id=firstRun --train
Traceback (most recent call last):
  File "C:\Users\jilck\Anaconda3\envs\ml-agents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "C:\Users\jilck\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\jilck\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "C:\Users\jilck\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "C:\Users\jilck\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\ml-agents-master\ml-agents\mlagents\trainers\__init__.py", line 1, in <module>
    from .buffer import *
  File "c:\ml-agents-master\ml-agents\mlagents\trainers\buffer.py", line 3, in <module>
    from mlagents.envs.exception import UnityException
  File "c:\ml-agents-master\ml-agents\mlagents\envs\__init__.py", line 1, in <module>
    from .environment import *
  File "c:\ml-agents-master\ml-agents\mlagents\envs\environment.py", line 11, in <module>
    from .communicator_objects import UnityRLInput, UnityRLOutput, AgentActionProto, \
ImportError: cannot import name 'UnityRLInput'

(ml-agents) C:\ml-agents-master>

**Comment by harperj** [comment]
Hi @jilcky -- looks like you're working on developing ML-Agents from source.  To do this you'll need to build the protocol buffer definitions.  You can see this README for information about how: https://github.com/Unity-Technologies/ml-agents/blob/e3b86a27a2547cdd177bf9e848b4337aa71b887a/protobuf-definitions/README.md

**Comment by jilcky** [comment]
> 嗨@jilcky - 看起来你正在从源头开发ML-Agents。为此，您需要构建协议缓冲区定义。您可以参阅本自述文件以获取有关如何操作的信息：[https](https://github.com/Unity-Technologies/ml-agents/blob/e3b86a27a2547cdd177bf9e848b4337aa71b887a/protobuf-definitions/README.md)：[//github.com/Unity-Technologies/ml-agents/blob/e3b86a27a2547cdd177bf9e848b4337aa71b887a/protobuf-definitions/README.md](https://github.com/Unity-Technologies/ml-agents/blob/e3b86a27a2547cdd177bf9e848b4337aa71b887a/protobuf-definitions/README.md)

I can creat C:\ml-agents\UnitySDK\Assets\ML-Agents\Scripts\CommunicatorObjects
but Show ImportError: cannot import name 'UnityRLInput'

**Comment by xiaomaogy** [comment]
@jilcky Did you follow step by step the stuff on https://github.com/Unity-Technologies/ml-agents/blob/e3b86a27a2547cdd177bf9e848b4337aa71b887a/protobuf-definitions/README.md?

**Comment by xiaomaogy** [comment]
Thanks for reaching out to us. Hopefully you were able to resolve your issue.  We are closing this due to inactivity, but if you need additional assistance, feel free to reopen the issue.
