### ISSUE TITLE
ImportError: DLL load failed 

### ISSUE THREAD

**Issue by einstyle** [Unity-Technologies/ml-agents#1806]
D:\Documents\Unity3D\Testing\MachineLearning-Unity\ml-agents-0.7.0\ml-agents>mlagents-learn config/trainer_config.yaml --env=../../BUILDS-RollerBall/RollerBall --run-id=cob_1 --train
Traceback (most recent call last):
  File "D:\Program_Files\Python\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "d:\program_files\python\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "d:\program_files\python\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "d:\program_files\python\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "d:\program_files\python\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\documents\unity3d\testing\machinelearning-unity\ml-agents-0.7.0\ml-agents\mlagents\trainers\__init__.py", line 1, in <module>
    from .buffer import *
  File "d:\documents\unity3d\testing\machinelearning-unity\ml-agents-0.7.0\ml-agents\mlagents\trainers\buffer.py", line 3, in <module>
    from mlagents.envs.exception import UnityException
  File "d:\documents\unity3d\testing\machinelearning-unity\ml-agents-0.7.0\ml-agents\mlagents\envs\__init__.py", line 1, in <module>
    from .environment import *
  File "d:\documents\unity3d\testing\machinelearning-unity\ml-agents-0.7.0\ml-agents\mlagents\envs\environment.py", line 11, in <module>
    from .communicator_objects import UnityRLInput, UnityRLOutput, AgentActionProto, \
  File "d:\documents\unity3d\testing\machinelearning-unity\ml-agents-0.7.0\ml-agents\mlagents\envs\communicator_objects\__init__.py", line 1, in <module>
    from .agent_action_proto_pb2 import *
  File "d:\documents\unity3d\testing\machinelearning-unity\ml-agents-0.7.0\ml-agents\mlagents\envs\communicator_objects\agent_action_proto_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "d:\program_files\python\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by harperj** [comment]
Hi @einstyle -- it seems you're trying to install / run ml-agents from source.  To get that working you'll need to build the protocol buffer definitions: https://github.com/Unity-Technologies/ml-agents/tree/master/protobuf-definitions

**Comment by jinzhaochaliang** [comment]
may be use  (pip install protobuf==3.6.0) , that's how I solved this problem.

**Comment by einstyle** [comment]
@jinzhaochaliang It works now ! Thanks !!!
