### ISSUE TITLE
training mlagents and tensfor flow

### ISSUE THREAD

**Issue by EricFiore** [Unity-Technologies/ml-agents#1851]
I am following the guide posted here ( https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md ) on how to set up a starter environment. Everything is working up until the I have to train the agents.  I run the command 

> mlagents-learn <trainer-config-file> --env=<env_name> --train
 
as instructed and I get an tensor flow error.
https://imgur.com/QaZwC2h

from what I can tell by googling around I need to get the correct version of protobuf installed.  I have tensorflow 1.7.1 installed (as per instructions) and protobuf 3.4.0.  I am using Windows 10 without the CUDA packages installed.  Any help is appreciated.

**Comment by awjuliani** [comment]
Hi @EricFiore 

It looks like your TensorFlow installation is somewhat corrupted. I would recommend reinstalling tensorflow, and trying again. As you mentioned, there may be an issue with various incompatible dependencies, which doing a clean install may resolve.

**Comment by EricFiore** [comment]
thank you @awjuliani even though I did a complete reinstallation of Anaconda, tensorflow, resetup the Unity game and everything I still get same error. Not sure what is going on here.  Any advice is appreciated.
I am following the tutorial to a tee.  Still I get the error.  I am on Windows 10.  I am not using the Nvidia toolkit.  This is strictly CPU.  I can install everything fine but when I try to run the training I get the below output.
Any help is appreciated.

`(ml-agents) C:\Users\ericf\ml-agents>mlagents-learn config/trainer_config.yaml --run-id=firstRun --train
Traceback (most recent call last):
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\ericf\ml-agents\ml-agents\mlagents\trainers\__init__.py", line 4, in <module>
    from .models import *
  File "c:\users\ericf\ml-agents\ml-agents\mlagents\trainers\models.py", line 4, in <module>
    import tensorflow as tf
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\ericf\Anaconda3\envs\ml-agents\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by awjuliani** [comment]
Hi @EricFiore 

Can you confirm that the installation works with a tensorflow provided example? If not, it may be better to share this issue on the TensorFlow Github page.

**Comment by vincentpierre** [comment]
We are closing this issue due to inactivity. Feel free to reopen it if you’d like to continue the discussion.
