### ISSUE TITLE
Unity crash every time i try to train

### ISSUE THREAD

**Issue by djsdvg** [Unity-Technologies/ml-agents#1886]
When i check the box **Control** in my **Academy** and then try to run the scene, the program freeze and it is unable to communicate with **learn.py.**
I tried to reinstall everything but nothing change. 

**The error that i get is:**
_CrashReporter: initialized
Mono path[0] = '/Users/user/Documents/ml-agents/ml-agents/basic.app/Contents/Resources/Data/Managed'
Mono config path = '/Users/user/Documents/ml-agents/ml-agents/basic.app/Contents/MonoBleedingEdge/etc'
PlayerConnection initialized from /Users/user/Documents/ml-agents/ml-agents/basic.app/Contents/Resources/Data (debug = 0)_

_PlayerConnection initialized network socket : 0.0.0.0 55022
Multi-casting "[IP] 192.168.1.3 [Port] 55022 [Flags] 2 [Guid] 2883866427 [EditorId] 3815712834 [Version] 1048832 [Id] OSXPlayer(iMac-di-user.local) [Debug] 0 [PackageName] OSXPlayer" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55022]
PlayerConnection already initialized - listening to [0.0.0.0:55022]_

_Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/mlagents-learn", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "/Users/user/Documents/ml-agents/ml-agents/mlagents/trainers/learn.py", line 234, in main
    run_training(0, run_seed, options, Queue())
  File "/Users/user/Documents/ml-agents/ml-agents/mlagents/trainers/learn.py", line 71, in run_training
    env = init_environment(env_path, docker_target_name, no_graphics, worker_id + sub_id, fast_simulation, run_seed)
  File "/Users/user/Documents/ml-agents/ml-agents/mlagents/trainers/learn.py", line 171, in init_environment
    no_graphics=no_graphics
  File "/Users/user/Documents/ml-agents/ml-agents/mlagents/envs/environment.py", line 67, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "/Users/user/Documents/ml-agents/ml-agents/mlagents/envs/environment.py", line 493, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "/Users/user/Documents/ml-agents/ml-agents/mlagents/envs/rpc_communicator.py", line 81, in initialize_

_"The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Academy's Broadcast Hub is configured correctly
	 The Agents are linked to the appropriate Brains
	 The environment and the Python interface have compatible versions._

**Comment by ervteng** [comment]
Hi @djsdvg, do the example environments work? Make sure you've done everything at the bottom of the error message

**Comment by djsdvg** [comment]
When i press the run button on unity i didn't get any error message in the console because the program crash.
I can play with my BrainPlayer but if i try to run something with the Academy cntrol box selected Unity freeze up

**Comment by ervteng** [comment]
Hi @djsdvg, were you able to resolve the issue?

**Comment by djsdvg** [comment]
Hi @ervteng, I gave up and now i use windows instead of OSX

**Comment by xiaomaogy** [comment]
Thanks for reaching out to us. Hopefully you were able to resolve your issue.  We are closing this due to inactivity, but if you need additional assistance, feel free to reopen the issue.

**Comment by mnicolas94** [comment]
Hi, i have the same problem, i like to know if you did find the solution

**Comment by mnicolas94** [comment]
Same problem and i dont find any solution. I have windows 10 1803, cpu i5 6200U. I tested on unity 2018.3 and 2019.1, and with mlagents v0.7 and v0.9. it works for inference (control checkbox unchecked) but not for training (control checkbox checked)

**Comment by ervteng** [comment]
Hi @mnicolas94, you're using in-editor training, right?

**Comment by mnicolas94** [comment]
I tried both, editor and builded.

**Comment by ervteng** [comment]
There might be an issue with Windows Firewall - I'd check there and see if Unity is blocked. Did you get a message asking for access to your ports at any time?

**Comment by mnicolas94** [comment]
Nop, i have my firewall disabled. I'm using it on a computer without internet access. It is that a posible reason? Could it be a cpu issue?

**Comment by ervteng** [comment]
It shouldn't be a CPU issue. It looks like for some reason the environment and the Python aren't communicating. We've tested on both those Unity versions on Windows 10 with a Core i7 and it worked OK. By any chance could you post the output of the Player.log (https://docs.unity3d.com/Manual/LogFiles.html) after builded run and see if there are any errors?

**Comment by mnicolas94** [comment]
I solved it. I read the FAQ and there was the solution. Sorry for not looking there first. Apparently the problem was that i had the http_proxy and https_proxy environment variables setted. Thanks for your help
