### ISSUE TITLE
Docker image needed

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#191]
Hi,

I tried to run ML-Agents on AWS, and I found AWS image, but I could not understand whole installation procedure so could not do it.

Providing docker image will help many people.
I'm happy if you consider it.

Thank you.

**Comment by dora-gt** [comment]
It always outputs

```
Traceback (most recent call last):
  File "ppo.py", line 80, in <module>
    env = UnityEnvironment(file_name=env_name, worker_id=worker_id, curriculum=curriculum_file, lesson=lesson)
  File "/home/ubuntu/python/unityagents/environment.py", line 107, in __init__
    .format(str(file_name)))
unityagents.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure Car does not need user interaction to launch and that the Academy and the external Brain(s) are attached to objects in the Scene.
```

I don't know why...

**Comment by dora-gt** [comment]
I'm sorry, I followed these instruction
https://aichamp.wordpress.com/2016/11/09/updating-nvidia-cuda-to-8-0-x-in-ubuntu-16-04-ec2-gx-instance/
https://forum.unity.com/threads/solved-there-is-no-data-folder.364065/
and it worked finally.
