### ISSUE TITLE
pip install -e . => mlagents-envs 0.8.0 has requirement Pillow<=5.4.1,>=4.2.1, but you'll have pillow 6.0.0 which is incompatible.

### ISSUE THREAD

**Issue by hukaidong** [Unity-Technologies/ml-agents#1939]
I tried to run an example on mlagents-learning in version 0.8.0, when set up the experiment, I met following problem:

```Shell
+ srun mlagents-learn trainer_config.yaml --train --env=Test.x86 --no-graphic
Traceback (most recent call last):
  File "/home/***/.installed/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/home/***/.installed/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/***/.installed/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 6.0.0 (/cache/home/***/.installed/miniconda/lib/python3.6/site-packages), Requirement.parse('Pillow<=5.4.1,>=4.2.1'), {'mlagents-envs'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/***/.installed/miniconda/bin/mlagents-learn", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/.../.installed/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/home/***/.installed/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/home/***/.installed/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/***/.installed/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/***/.installed/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/***/.installed/miniconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 6.0.0 (/cache/home/***/.installed/miniconda/lib/python3.6/site-packages), Requirement.parse('Pillow<=5.4.1,>=4.2.1'), {'mlagents-envs'})
srun: error: task 0: Exited with exit code 1
srun: error: task 0: Exited with exit code 1
```

Any idea about this?

**Comment by mattinjersey** [comment]
I ran into similar problems including pillow and protobuf.
You can uninstall packages using pip3 uninstall pillow==6.0.0
You can install packages using pip3 install pillow==5.0.0

So using this sort of approach you could get pillow version 5.0.0 and protobuf version 3.6 which seems to be what it wants.

**Comment by eshvk** [comment]
Please try version 0.8.1 (just uploaded to pypi) and let us know if you still face issues.

**Comment by DVonk** [comment]
> Please try version 0.8.1 (just uploaded to pypi) and let us know if you still face issues.

I'm getting the exact same error installing 0.8.1 on a fresh machine.

**Comment by hukaidong** [comment]
I am concentrating in a version of 0.7.x so would not test 0.8.1 for a period. Since there are no more update from others about this, I assume it's already solved. Please reopen this issue if anyone still meets the same condition.

**Comment by coder-pikachu** [comment]
I faced the same issue but downgrading Pillow to 5.4.1 helped.
I performed the following operations:

`pip uninstall pillow==6.0.0`

And then

`pip install pillow==5.4.1`

**Comment by wandrzej** [comment]
This is still showing up with 0.9.1. pip uninstall/install, as mentioned above, helps.
