### ISSUE TITLE
Problem installing ml-agents in ubuntu

### ISSUE THREAD

**Issue by franvf** [Unity-Technologies/ml-agents#1945]
Hi everybody, i have ubuntu 18.04 and I want to install unity and ml-agents per hobby. I read the github documentation but I do not know what I do wrong because after doing the steps the ml-agents are not executed. I have installed ml-agents, unity and tensorflow but I do not know if it is properly installed. Someone can help me?

1. I'm downloaded Unity from this web beta.unity3d.com/download/dad990bf2728/public_download.html and execute the file for install.

2. Later i download the ml agents with git clone github.com/Unity-Technologies/ml-agents.git

3. cd ./ml-agents/ml-agents

4. pip install -e.

 The error that appears is the next: 
mlagents-learn --help
Traceback (most recent call last):
  File "/usr/local/bin/mlagents-learn", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/media/fran/Data/ml-agents/ml-agents/ml-agents/mlagents/trainers/__init__.py", line 2, in <module>
    from .buffer import *
  File "/media/fran/Data/ml-agents/ml-agents/ml-agents/mlagents/trainers/buffer.py", line 3, in <module>
    from mlagents.envs.exception import UnityException
ModuleNotFoundError: No module named 'mlagents.envs.exception'

**Comment by eshvk** [comment]
Hi @franvf: Can you clarify a couple of things:

- Are you cloning a version of ML-Agents that has the latest hotfix (merged in a couple of hours back)?
- If you are installing from source, have you done a `cd ml-agents/ml-agents-envs` and do a `pip install -e ./` before you install `ml-agents`?

**Comment by franvf** [comment]
Many thanks @eshvk, I have not executed the second step. But now I have a warning with a tensorflow, when I execute the command: mlagents-learn --help, the following warning appears:

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.

**Comment by djbyrne** [comment]
I am getting the same warning ModuleNotFoundError: No module named 'mlagents.envs.exception', when trying to install on my Mac

**Comment by franvf** [comment]
You need execute the next command: 
cd ml-agents/ml-agents-envs
pip install -e ./

**Comment by djbyrne** [comment]
This was when I was installing via pip. I tried installing it from source and it worked fine

**Comment by xiaomaogy** [comment]
Thanks for reaching out to us. Hopefully you were able to resolve your issue.  We are closing this due to inactivity, but if you need additional assistance, feel free to reopen the issue.
