### ISSUE TITLE
pip install -e . => mlagents-envs 0.8.1 has requirement Pillow<=5.4.1,>=4.2.1, but you'll have pillow 6.0.0 which is incompatible.

### ISSUE THREAD

**Issue by juva** [Unity-Technologies/ml-agents#1982]
E:\mobilework\ml-agents-master\ml-agents>mlagents-learn config/trainer_config.yaml --run-id=firstRun --train
Traceback (most recent call last):
  File "d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 6.0.0 (d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages), Requirement.parse('Pillow<=5.4.1,>=4.2.1'), {'mlagents-envs'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\jhfeng\AppData\Local\Programs\Python\Python36\Scripts\mlagents-learn-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3241, in <module>
    @_call_aside
  File "d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 6.0.0 (d:\users\jhfeng\appdata\local\programs\python\python36\lib\site-packages), Requirement.parse('Pillow<=5.4.1,>=4.2.1'), {'mlagents-envs'})

E:\mobilework\ml-agents-master\ml-agents>

like [https://github.com/Unity-Technologies/ml-agents/issues/1939](https://github.com/Unity-Technologies/ml-agents/issues/1939)

**Comment by Llain55** [comment]
had this problem myself at one point. You'll have to uninstall your current version of pillow using 
pip uninstall pillow
once it has uninstalled successfully reinstall using required version
pip install pillow==5.4.1

hopefully this works for you!

**Comment by harperj** [comment]
Hi @juva -- what @Llain55 said should work.  You might also consider using a virtualenv so that ML-Agents dependencies can be managed separately from your global dependencies.

**Comment by juva** [comment]
https://github.com/Llain55 https://github.com/harperj
thanks,it really works!

**Comment by juva** [comment]
@Llain55 @harperj 
thanks,it really works!
