### ISSUE TITLE
How to fix Unity Ml-Agents imitation error

### ISSUE THREAD

**Issue by Dia1304** [Unity-Technologies/ml-agents#2035]
I want resolve this error help me

this is errorcode in anaconda prompt
`(ml-agents) C:\Users\5084k\Desktop\Study\Unity ML Ball> mlagents-learn trainer_config.yaml --run-id=firstRun --train

                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓

INFO:mlagents.trainers:{'--base-port': '5005',
 '--curriculum': 'None',
 '--debug': False,
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-envs': '1',
 '--num-runs': '1',
 '--run-id': 'firstRun',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '<trainer-config-path>': 'trainer_config.yaml'}
c:\users\5084k\ml-agents\ml-agents\mlagents\trainers\learn.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  trainer_config = yaml.load(data_file)
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
INFO:mlagents.envs:
'BallAcademy' started successfully!
Unity Academy name: BallAcademy
        Number of Brains: 2
        Number of Training Brains : 1
        Reset Parameters :

Unity brain name: TeacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 6
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: Horizontal, Vertical
Unity brain name: LearnBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 6
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: Horizontal, Vertical
Traceback (most recent call last):
  File "C:\Users\5084k\Anaconda3\envs\ml-agents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "c:\users\5084k\ml-agents\ml-agents\mlagents\trainers\learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\5084k\ml-agents\ml-agents\mlagents\trainers\learn.py", line 95, in run_training
    tc.start_learning(env, trainer_config)
  File "c:\users\5084k\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 205, in start_learning
    self.initialize_trainers(trainer_config)
  File "c:\users\5084k\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 169, in initialize_trainers
    .format(brain_name))
mlagents.envs.exception.UnityEnvironmentException: The trainer config contains an unknown trainer type for brain LearnBrain
UnityEnvironment worker: keyboard interrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\users\5084k\anaconda3\envs\ml-agents\lib\multiprocessing\util.py", line 319, in _exit_function
    p.join()
  File "c:\users\5084k\anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "c:\users\5084k\anaconda3\envs\ml-agents\lib\multiprocessing\popen_spawn_win32.py", line 80, in wait
    res = _winapi.WaitForSingleObject(int(self._handle), msecs)
KeyboardInterrupt`

and this is trainer_config.yaml 
default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

LearnBrain:
    trainer: imitation
    brain_to_imitate: TeacherBrain
    max_steps: 5.0e4
    summary_freq: 1000
    batch_size: 1024
    batches_per_epoch: 5
    num_layers: 4
    hidden_units: 64
    sequence_length: 16
    buffer_size: 128

Please help me

**Comment by krishnanpc** [comment]
is your LearnBrain set to learning? and not player/heuristic?

**Comment by Dia1304** [comment]
> 
> 
> is your LearnBrain set to learning? and not player/heuristic?

this is my two brains setting

![image](https://user-images.githubusercontent.com/42935851/57660355-277ccf00-7621-11e9-84dc-8379d96dcf8b.png)
![image](https://user-images.githubusercontent.com/42935851/57660365-34012780-7621-11e9-86d5-d615b8966ccd.png)

**Comment by ervteng** [comment]
Hi @Dia1304, `imitation` is not a trainer type in the trainer_config YAML. You'll want to use `online_bc`.

**Comment by xiaomaogy** [comment]
Thank you for the discussion. We are closing this issue due to inactivity. Feel free to reopen it if you’d like to continue the discussion though.
