### ISSUE TITLE
Is normalization of observations still needed with normalize: true ?

### ISSUE THREAD

**Issue by roboserg** [Unity-Technologies/ml-agents#2052]
So [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md) you talk about observation normalization and even provide a formula to do it. But then [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-PPO.md) you say PPO has an option for normalization.

**1.** Now I understand the automatic normalization takes some time to figure out the maximum and scale properly. So my question is - do I still have to manually normalize observations with value / max_value or is it enough to just `normalize: true` in the `config.yaml`? 

**2.** Should the cumulative reward at the end of the episode be also from -1 to 1 or is it enough if only each individual reward is normalized? Right now I am tracking 4 values. Only at the end of the episode, I assign a reward = `4 - x1 - x2 - x3 -x4` where x is a number from 0 to 1. Obviously, I want the x to be 0. If an agent fails, I assign only -1 and the episode ends too. So in the best case, the agent gets a reward of 4 or something near 4. Should this 4 be scaled to -1 to 1?

**Comment by xiaomaogy** [comment]
Hi @roboserg, these are very good questions. 

1. If you manually normalize the observation, it will increase the training speed. 
Here is why: It will take some time for the model side to get the current mean and standard deviation of the data (for example the mean update rule is new_mean = old_mean + (new_mean - old_mean) / (n  + 1)). So before it catches up, your normalized observation might go outside of -1 to 1, which is a worse input to the neural network than the manually normalized input that are guaranteed to lie within -1 to 1.

2. It is enough that the individual reward to be -1 to 1, so that the cumulative reward are not some super crazy value. The reason why we want to restrict the individual reward is because if individual reward are already super large, the cumulative reward might be too large, so that it would be really hard for the neural network to correctly output such large value.

**Comment by roboserg** [comment]
Hi @xiaomaogy  and thanks for the reply! Sone follows up:

1. Do you update the `new_mean` at every step? What happens if I trained a model then continue training a new model with `--load`, will it take some time again to get the correct mean? If yes, it would suggest that not normalizing the observations and running for a low amount of steps is not optimal. 

2. So in my case, the agent gets either -1 or a value from 0 to 4 (`4 - x1 - x2 - x3 -x4`). Your answer would suggest I have to scale that 4 to be from 0 to 1, right? Since I assign this 0 - 4 reward in one step at the final step and then the episode ends.

3. @ervteng was mentioning I should ask you about automating agent training. Right now I train an agent. Then I have to _manually_ drag the .nn file to Unity, then assign that NN to an agent, then manually click on "control" in the academy and only now can I hit play in Unity. @ervteng said you could have some way of automating this. 

3.1. An ideal feature request to number 3 would be saving the NN model (.nn file) )every x steps so that I could see an agent playing in real-time. So say you train for 500.000 steps. A .nn file of the trained agent would get saved every 50.000 steps, meaning I could open another instance of Unity3d editor and watch the agent play in real time, to see if the behavior is desired.

**Comment by xiaomaogy** [comment]
Hi @roboserg 

1. Yes we update the new_mean at every step, but if you train a model with --load, the old mean will also be loaded. 
2. Yes, scale it to be 0 to 1 would be better. However as long as you total cumulative reward doesn't go to really large number, you should be fine. 
3. We currently have a way to toggle the "control" in the academy by code, but we still need to manually drag the .nn file to Unity, assign that NN to an agent manually. We don't have any plan to automate the later two steps in the near future. 

3.1 should be possible, it should just be a few line of python code. 
3.2 If you hit CTRL+C, the .nn file should be saved (if you use the newest version of ml-agents). On Windows we used to have that issue, then we fixed it. It that no longer the case?

**Comment by roboserg** [comment]
Hi @xiaomaogy  and thanks for the answers.

3.2 I am under Windows 10 64bit. If I hit CTRL+C during training the .nn file is NOT created.

**Comment by xiaomaogy** [comment]
Not sure what happens there.... It would be helpful if you post a snapshot of the output log.

**Comment by roboserg** [comment]
Video of the process - https://youtu.be/pp9i1N6N5f4
Log:

```
(ml-agents) I:\ml-agents-master>mlagents-learn config/config.yaml --train --run-id=test1D-11


                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓


INFO:mlagents.trainers:{'--base-port': '5005',
 '--curriculum': 'None',
 '--debug': False,
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-envs': '1',
 '--num-runs': '1',
 '--run-id': 'test1D-11',                                                                                                                           '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,                                                                                                                                   '<trainer-config-path>': 'config/config.yaml'}                                                                                                    c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  trainer_config = yaml.load(data_file)
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
INFO:mlagents.envs:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 2
        Number of Training Brains : 1
        Reset Parameters :

Unity brain name: LearningBrain1D
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 2
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [2]
        Vector Action descriptions:
Unity brain name: PlayerBrainDiscr
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 2
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [2]
        Vector Action descriptions:
2019-05-23 23:32:38.227982: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-05-23 23:32:38.397564: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1344] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.797
pciBusID: 0000:01:00.0                                                                                                                             totalMemory: 8.00GiB freeMemory: 6.64GiB                                                                                                           2019-05-23 23:32:38.404217: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1423] Adding visible gpu devices: 0
2019-05-23 23:32:39.004478: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-23 23:32:39.008542: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:917]      0
2019-05-23 23:32:39.010972: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:930] 0:   N
2019-05-23 23:32:39.013983: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6416 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:mlagents.envs:Hyperparameters for the PPO Trainer of brain LearningBrain1D:
        batch_size:     10
        beta:   0.005
        buffer_size:    100
        epsilon:        0.2
        gamma:  0.999
        hidden_units:   128
        lambd:  0.95
        learning_rate:  0.0003
        max_steps:      50000
        normalize:      True
        num_epoch:      3
        num_layers:     2
        time_horizon:   64
        sequence_length:        64
        summary_freq:   500
        use_recurrent:  False
        summary_path:   ./summaries/test1D-11-0_LearningBrain1D
        memory_size:    256
        use_curiosity:  False
        curiosity_strength:     0.01
        curiosity_enc_size:     128
        model_path:     ./models/test1D-11-0/LearningBrain1D
2019-05-23 23:32:39.602264: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1423] Adding visible gpu devices: 0
2019-05-23 23:32:39.605574: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-23 23:32:39.610535: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:917]      0
2019-05-23 23:32:39.613425: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:930] 0:   N
2019-05-23 23:32:39.616413: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6416 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:mlagents.trainers: test1D-11-0: LearningBrain1D: Step: 500. Time Elapsed: 11.320 s Mean Reward: -0.507. Std of Reward: 0.671. Training.
INFO:mlagents.trainers: test1D-11-0: LearningBrain1D: Step: 1000. Time Elapsed: 20.000 s Mean Reward: 0.433. Std of Reward: 0.582. Training.
UnityEnvironment worker: keyboard interrupt
INFO:mlagents.envs:Learning was interrupted. Please wait while the graph is generated.
Traceback (most recent call last):
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 218, in start_learning
    new_info = self.take_step(env, curr_info)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 297, in take_step
    trainer.update_policy()
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 334, in update_policy
    run_out = self.policy.update(buffer.make_mini_batch(start, end), n_sequences)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\ppo\policy.py", line 143, in update
    run_out = self._execute_model(feed_dict, self.update_dict)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\policy.py", line 126, in _execute_model
    network_out = self.sess.run(list(out_dict.values()), feed_dict=feed_dict)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\client\session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    run_metadata)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Roboserg\Anaconda3\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 95, in run_training
    tc.start_learning(env, trainer_config)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 230, in start_learning
    self._save_model_when_interrupted(steps=self.global_step)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 104, in _save_model_when_interrupted
    self._save_model(steps)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 98, in _save_model
    self.trainers[brain_name].save_model()
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer.py", line 165, in save_model
    self.policy.save_model(self.get_step)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\policy.py", line 183, in save_model
    'raw_graph_def.pb', as_text=False)
  File "c:\users\roboserg\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\framework\graph_io.py", line 73, in write_graph
    file_io.atomic_write_string_to_file(path, graph_def.SerializeToString())
KeyboardInterrupt

(ml-agents) I:\ml-agents-master>
(ml-agents) I:\ml-agents-master>

(ml-agents) I:\ml-agents-master>

(ml-agents) I:\ml-agents-master>
```

**Comment by roboserg** [comment]
Ok I figured it out. You have to "gently" press CNTRL+C only once. If you spam it several times the .nn will not be created.

**Comment by xiaomaogy** [comment]
Yes, if you do multiple times, it will interrupt the logic that saves the model.

**Comment by roboserg** [comment]
Yes, I had the habit of spamming it because the console does not always react to the first CNTRL+C input
