### ISSUE TITLE
When trying to run mlagents-learn: Import errors, DLL load failed, module not found

### ISSUE THREAD

**Issue by tommiteO** [Unity-Technologies/ml-agents#2083]
I have tried multiple different methods of installation with various different versions but I can't get beyond this stage. I try to run mlagents-learn and it comes up with errors along the following lines below, what should I do?

Traceback (most recent call last):
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\users\trials\appdata\local\programs\python\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "c:\users\trials\appdata\local\programs\python\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\trials\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\trials\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Trials\AppData\Local\Programs\Python\Python36\Scripts\mlagents-learn.exe\__main__.py", line 5, in <module>
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\mlagents\trainers\__init__.py", line 5, in <module>
    from .models import *
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\mlagents\trainers\models.py", line 4, in <module>
    import tensorflow as tf
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\users\trials\appdata\local\programs\python\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\trials\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "c:\users\trials\appdata\local\programs\python\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

**Comment by unityjeffrey** [comment]
hi @tommiteO - are you trying to run tensorflow-gpu?  also, can you provide your system information (version of Windows, etc..)?

**Comment by tommiteO** [comment]
Hi @unityjeffrey , no I am just trying to run it on my cpu (I only have the integrated graphics card) and sure:
Operating system: Windows 10 pro (64-bit)
Processor: Intel(R) Core(TM)2 Duo CPU P8600 @ 2.40GHz
RAM: 4 GB

Do you need anything else?

**Comment by unityjeffrey** [comment]
it looks to be an issue with tensorflow.  Are you using a separate conda environment to run mlagents-learn?

**Comment by tommiteO** [comment]
I have done, so in this case I am just doing it straight out of python, not using anaconda. However I have also tried it using anaconda, what do you mean by a separate environment to run mlagents-learn, I just tried to run it out of the ml-agents environment that I created. But yeah I think it's something to do with the install of tensorflow; when I was trying out of anaconda it would say that the packages were installed in the command prompt, however when I went to the navigator it didn't show them as installed. I could then install them from the navigator and it would work when I run "import tensorflow as tf", however when I then install the ml-agents it still wouldn't be able to run mlagents-learn for some reason. It may have been because from the navigator there didn't appear to be anyway of specifying the version that you install so they may not have been compatible, if I'm honest i don't really know though.

**Comment by tommiteO** [comment]
@unityjeffrey any ideas?

**Comment by unityjeffrey** [comment]
hmm, it's difficult to debug without actually being hands-on at your actual computer.  just confirming you tried this on a clean, separate conda env and followed all the instructions (i.e. pip install mlagents-learn, etc...)?

**Comment by unityjeffrey** [comment]
also - take a look at this https://github.com/Unity-Technologies/ml-agents/issues/1979

**Comment by xiaomaogy** [comment]
This is related to this issue. https://github.com/tensorflow/tensorflow/issues/11571

**Comment by ervteng** [comment]
Thanks for the comments - closing this issue due to inactivity. Feel free to open a new issue if you're still running into problems.
