### ISSUE TITLE
[beginner] How to propely load old models

### ISSUE THREAD

**Issue by Datguypotato** [Unity-Technologies/ml-agents#2137]
Hey guys,

So I followed the this [tutorial](https://github.com/Datguypotato/ml-agents/blob/master/docs/Learning-Environment-Create-New.md#making-a-new-learning-environment) and I wanted to keep training the ai with --train and load.

But I can't get it to work. Am I supposed to change the run-id to the map of the previous training?

This is what I run this command 
mlagents-learn config/trainer_config.yaml --run-id=BigTraining --train
BigTraining is the nn file name that I already have
`
INFO:mlagents.envs:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 2
        Number of Training Brains : 1
        Reset Parameters :

Unity brain name: RollerBallBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: ,
Unity brain name: RollerBallPlayer
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: ,
2019-06-16 17:25:42.577107: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
INFO:mlagents.trainers:Loading Model for brain RollerBallBrain
INFO:mlagents.trainers:The model ./models/Roller-0/RollerBallBrain could not be found. Make sure you specified the right --run-id
Traceback (most recent call last):
  File "d:\anaconda\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 95, in run_training
    tc.start_learning(env, trainer_config)
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 205, in start_learning
    self.initialize_trainers(trainer_config)
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 163, in initialize_trainers
    self.run_id)
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 45, in __init__
    self.is_training, load)
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\ppo\policy.py", line 41, in __init__
    self._load_graph()
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\policy.py", line 81, in _load_graph
    self.saver.restore(self.sess, ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'
`

**Comment by testContributor12** [comment]
I would also love to get some info on that, because right now i am using --train together with --load when trying to continue training  an existing model after adding the  .nn file to the brain.

**Comment by Datguypotato** [comment]
I just kept using --train and my ai got better
