### ISSUE TITLE
first-run give me: .conda\envs\ml\lib\multiprocessing\process.py", line 258, in _bootstrap

### ISSUE THREAD

**Issue by skei0** [Unity-Technologies/ml-agents#2146]
I get this error, when I start training. I search the issues heir but I could not find anything, what would fix my problem. I reinstall everything in a new conda evn, but no success. Can anybody help me ? THX

i try to run the 3DBall Example. (i'm new to Unity)

```cmd 
(ml) C:\Users\Kees\unity\ml-agents>mlagents-learn config/trainer_config.yaml --run-id=first-run --train


                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓


INFO:mlagents.trainers:{'--base-port': '5005',
 '--curriculum': 'None',
 '--debug': False,
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-envs': '1',
 '--num-runs': '1',
 '--run-id': 'first-run',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '<trainer-config-path>': 'config/trainer_config.yaml'}
c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\trainers\learn.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  trainer_config = yaml.load(data_file)
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
Process Process-1:
Traceback (most recent call last):
  File "c:\users\kees\.conda\envs\ml\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\users\kees\.conda\envs\ml\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\subprocess_environment.py", line 53, in worker
    env = env_factory(worker_id)
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\trainers\learn.py", line 192, in create_unity_environment
    base_port=start_port
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\environment.py", line 76, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\environment.py", line 538, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\rpc_communicator.py", line 80, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Academy's Broadcast Hub is configured correctly
         The Agents are linked to the appropriate Brains
         The environment and the Python interface have compatible versions.
Traceback (most recent call last):
  File "c:\users\kees\.conda\envs\ml\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Die Pipe wurde beendet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\subprocess_environment.py", line 38, in recv
    response: EnvironmentResponse = self.conn.recv()
  File "c:\users\kees\.conda\envs\ml\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "c:\users\kees\.conda\envs\ml\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kees\.conda\envs\ml\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kees\.conda\envs\ml\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kees\.conda\envs\ml\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\trainers\learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\trainers\learn.py", line 88, in run_training
    keep_checkpoints, lesson, env.external_brains,
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\subprocess_environment.py", line 173, in external_brains
    return self.envs[0].recv().payload
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\subprocess_environment.py", line 41, in recv
    raise KeyboardInterrupt
KeyboardInterrupt

```

**Comment by awjuliani** [comment]
Hi @skei0 

Can you try building the 3DBall environment and launching training using the `--env` flag instead of training from the editor?

**Comment by skei0** [comment]
Hi @awjuliani 
Thank you for your reply. I try it but I become the same error:

```cmd

(ml) C:\Users\Kees\unity\ml-agents>mlagents-learn config/trainer_config.yaml --env=C:\Users\Kees\unity\ml-agents\UnitySDK\buld_ball --run-id=test --train


                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓


INFO:mlagents.trainers:{'--base-port': '5005',
 '--curriculum': 'None',
 '--debug': False,
 '--docker-target-name': 'None',
 '--env': 'C:\\Users\\Kees\\unity\\ml-agents\\UnitySDK\\buld_ball',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-envs': '1',
 '--num-runs': '1',
 '--run-id': 'test',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '<trainer-config-path>': 'config/trainer_config.yaml'}
c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\trainers\learn.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  trainer_config = yaml.load(data_file)
Process Process-1:
Traceback (most recent call last):
  File "c:\users\kees\.conda\envs\ml\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\users\kees\.conda\envs\ml\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\subprocess_environment.py", line 53, in worker
    env = env_factory(worker_id)
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\trainers\learn.py", line 192, in create_unity_environment
    base_port=start_port
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\environment.py", line 67, in __init__
    self.executable_launcher(file_name, docker_training, no_graphics)
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\environment.py", line 197, in executable_launcher
    .format(true_filename))
mlagents.envs.exception.UnityEnvironmentException: Couldn't launch the buld_ball environment. Provided filename does not match any environments.
Traceback (most recent call last):
  File "c:\users\kees\.conda\envs\ml\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Die Pipe wurde beendet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\subprocess_environment.py", line 38, in recv
    response: EnvironmentResponse = self.conn.recv()
  File "c:\users\kees\.conda\envs\ml\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "c:\users\kees\.conda\envs\ml\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kees\.conda\envs\ml\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kees\.conda\envs\ml\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kees\.conda\envs\ml\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\trainers\learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\trainers\learn.py", line 88, in run_training
    keep_checkpoints, lesson, env.external_brains,
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\subprocess_environment.py", line 173, in external_brains
    return self.envs[0].recv().payload
  File "c:\users\kees\.conda\envs\ml\lib\site-packages\mlagents\envs\subprocess_environment.py", line 41, in recv
    raise KeyboardInterrupt
KeyboardInterrupt

```

**Comment by ervteng** [comment]
Closing this issue due to inactivity. Feel free to open another issue if you're still have issues.
