### ISSUE TITLE
Unity Freezes on Training

### ISSUE THREAD

**Issue by DuckLord25** [Unity-Technologies/ml-agents#2181]
Hi, I'm having some issues when I run the training.

So, I run the training command in the terminal, and it gives me an error saying:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/mlagents-learn", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 285, in main
    run_training(0, run_seed, options, Queue())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 98, in run_training
    env.external_brains,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents/envs/subprocess_environment.py", line 187, in external_brains
    self.envs[0].send("external_brains")
AttributeError: 'UnityEnvWorker' object has no attribute 'send'
```

Then goes on to tell me to press play in the editor, so I did...
Unity then freezes until I terminate the process in the terminal.
I'm following the Learning-Environment-Create-New.md tutorial in the Docs, so I set that up exactly as it says, the player brain working fine, but the learning process does not.

Any help would be *greatly* appreciated!

**Comment by xiaomaogy** [comment]
@DuckLord25 Did you just pull the latest master?

**Comment by DuckLord25** [comment]
Yeah, I did.

**Comment by xiaomaogy** [comment]
@DuckLord25 Maybe create a new conda environment and try again?

**Comment by DuckLord25** [comment]
> @DuckLord25 Maybe create a new conda environment and try again?

Sure, I'll try that.

**Comment by DuckLord25** [comment]
Got everything downloaded...   I've never used a conda environment before, but I have everything set up, but I just don't know how to *use* it...   Sorry for being incompetent, hahaha

**Comment by xiaomaogy** [comment]
@DuckLord25 Just do 
```
conda create -n <some random name> python=3.6
conda activate <same random name>
```

This will give you a clean python 3.6 environment that you can use to try again.

**Comment by xiaomaogy** [comment]
This might be due to a stale .pyc file. You can refer to this page for more detail. http://effbot.org/pyfaq/how-do-i-create-a-pyc-file.htm

So instead of using a new conda environment (which should definitely work, but might be bothersome), you can also try this command under the root directory of ml-agents folder. 

```
python -m compileall .
```

This command will recompile all of the .pyc files.

**Comment by thatindiannerd** [comment]
I am having the same problem. Any luck fixing this?

**Comment by ervteng** [comment]
Thanks for the discussion - closing this issue due to inactivity. Feel free to open a new issue if you're still running into problems.
