### ISSUE TITLE
Issue converting 2D image generator model to barracuda

### ISSUE THREAD

**Issue by Gylleus** [Unity-Technologies/ml-agents#2186]
Hi! I am trying to convert a pre-trained TensorFlow model to barracuda in order to import it into Unity to use with the inference engine. Running it in plain python with TensorFlow works great. From reading documentations and examples it seems that I should be able to use the following to convert the model.

```python
from mlagents.trainers import tensorflow_to_barracuda as tf2bc
...
tf2bc.convert(out_path + '/frozen_graph.bytes', out_path + '/brain.nn')
```

However, I get the following error:
```
Traceback (most recent call last):
  File "tfmain.py", line 31, in <module>
    ms.save_generator(modelPath + "generator")
  File "/repo/myown/spritegen/tftest/model_saver.py", line 34, in save_generator
    tf2bc.convert(out_path + '/frozen_graph.bytes', out_path + '/brain.nn')
  File "/home/ekargyl/anaconda3/lib/python3.6/site-packages/mlagents/trainers/tensorflow_to_barracuda.py", line 1039, in convert
    barracuda.write(o_model, target_file)
  File "/home/ekargyl/anaconda3/lib/python3.6/site-packages/mlagents/trainers/barracuda.py", line 477, in write
    assert(len(x.shape) == 4)
AssertionError
```
The model looks as follows for reference:

```python
class Generator(tf.keras.Model):
    self.fully_connected = tf.keras.layers.Dense(4*4*16, use_bias = False, input_shape=(100,), name="fully_connected")
    self.conv0 = tf.keras.layers.Conv2DTranspose(filters=16, kernel_size = 2, strides = 2, padding="VALID", use_bias = False, name="deconv0")
    self.conv1 = tf.keras.layers.Conv2DTranspose(filters=8, kernel_size = 2, strides = 2, padding="VALID", use_bias = False, name="deconv1")
    self.conv2 = tf.keras.layers.Conv2DTranspose(filters=3, kernel_size = 2, strides = 2, padding="VALID", use_bias = False, name="deconv2")

def call(self, z):
    x = self.fully_connected(z)
    x = tf.nn.relu(x)
    x = tf.reshape(x, [-1, 4, 4, 16])
    x = self.conv0(x)
    x = tf.nn.relu(x)
    x = self.conv1(x)
    x = tf.nn.relu(x)
    x = self.conv2(x)
    x = tf.nn.tanh(x, name="output_node")
    return x
```
From debugging the problem seems to be in `generator/deconv0/stack/3` as the length of its shape is equal to `1` so `assert(len(x.shape) == 4)` fails.

Any idea what might be going wrong here and what this assertion is supposed to check? Is it due to Conv2DTranspose layers not currently being supported? I looked in `tensorflow_to_barracuda.py` and saw that `known_classes` contains other types of layers but not this one.

**Comment by xiaomaogy** [comment]
@mantasp

**Comment by mantasp** [comment]
@Gylleus thanks, we will look into it.

**Comment by ervteng** [comment]
Thanks for the comments - closing this issue due to inactivity. Feel free to open a new issue if you're still running into problems.
