### ISSUE TITLE
Issues in ML-Agents Gym Wrapper (multi agents)

### ISSUE THREAD

**Issue by CicieChen** [Unity-Technologies/ml-agents#2196]
Hi,

I implement my own environment to the gym, and I want to train the baseline model DQN. However, I meet the issue of action size -- The environment was expecting **`action` to be a list**.

Here are the details:
the number of agents: 8
input is the visual observation
action has 4 branches

The code I used for train DQN

```
import gym
from baselines import deepq
from baselines import logger
from gym_unity.envs.unity_env import UnityEnv

def main():  
    env = UnityEnv("/0.8/ml-agents/dqn-env/8agent/8agent.x86_64", 0, use_visual=True, multiagent=True, flatten_branched=True, allow_multiple_visual_obs=True)

    logger.configure('./logs') # Çhange to log in a different directory
    act = deepq.learn(
        env,
        "cnn", # conv_only is also a good choice for GridWorld
        lr=2.5e-4,
        total_timesteps=1000000,
        buffer_size=50000,
        exploration_fraction=0.05,
        exploration_final_eps=0.1,
        print_freq=20,
        train_freq=5,
        learning_starts=20000,
        target_network_update_freq=50,
        gamma=0.99,
        prioritized_replay=False,
        checkpoint_freq=1000,
        checkpoint_path='./logs', # Change to save model in a different directory
        dueling=True)
    
    print("Saving model to dqn_model.pkl")
    act.save("dqn_model.pkl")

if __name__ == '__main__':
    main()
```

The output in the terminal

```
Found path: /0.8/ml-agents/dqn-env/8agent/8agent.x86_64
Mono path[0] = '/0.8/ml-agents/dqn-env/8agent/8agent_Data/Managed'
Mono config path = '/0.8/ml-agents/dqn-env/8agent/8agent_Data/MonoBleedingEdge/etc'
Preloaded 'ScreenSelector.so'
Preloaded 'libgrpc_csharp_ext.x64.so'
Preloaded 'liblibtensorflow.so'
Preloaded 'libtensorflow_framework.so'
Display 0 '0': 1280x1024 (primary device).
Display 1 '1': 1280x1024 (secondary device).
Display 2 '2': 1280x1024 (secondary device).
Display 3 '3': 1280x1024 (secondary device).
Logging to /.config/unity3d/Unity Technologies/Unity Environment/Player.log
INFO:mlagents.envs:
'GridAcademy' started successfully!
Unity Academy name: GridAcademy
        Number of Brains: 1
        Number of Training Brains : 1
        Reset Parameters :
                gridSize -> 3.0
Unity brain name: GridWorldLearning
        Number of Visual Observations (per agent): 1
        Vector Observation space size (per agent): 0
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [2, 2, 2, 2]
        Vector Action descriptions: , , , 
INFO:gym_unity:8 agents within environment.
Logging to ./logs
2019-06-27 01:29:33.383873: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-27 01:29:33.494703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0a:00.0
totalMemory: 10.92GiB freeMemory: 10.75GiB
2019-06-27 01:29:33.590438: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0b:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2019-06-27 01:29:33.690027: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 01:29:33.691697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 2 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:42:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2019-06-27 01:29:33.809422: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-27 01:29:33.810466: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 3 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:43:00.0
totalMemory: 10.91GiB freeMemory: 10.76GiB
2019-06-27 01:29:33.814900: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1, 2, 3
2019-06-27 01:29:35.037589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-27 01:29:35.037635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1 2 3 
2019-06-27 01:29:35.037642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y Y Y 
2019-06-27 01:29:35.037646: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N Y Y 
2019-06-27 01:29:35.037650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 2:   Y Y N Y 
2019-06-27 01:29:35.037659: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 3:   Y Y Y N 
2019-06-27 01:29:35.037989: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10397 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:0a:00.0, compute capability: 6.1)
2019-06-27 01:29:35.038421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10408 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:0b:00.0, compute capability: 6.1)
2019-06-27 01:29:35.038705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10408 MB memory) -> physical GPU (device: 2, name: GeForce GTX 1080 Ti, pci bus id: 0000:42:00.0, compute capability: 6.1)
2019-06-27 01:29:35.038938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10406 MB memory) -> physical GPU (device: 3, name: GeForce GTX 1080 Ti, pci bus id: 0000:43:00.0, compute capability: 6.1)
--------------------------------------------------------------------------
[[55113,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: ntu-cil-1900x

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/envs/cc-rs/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/cc-rs/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/0.8/ml-agents/train_dqn.py", line 37, in <module>
    main()
  File "/0.8/ml-agents/train_dqn.py", line 31, in main
    dueling=True)
  File "/0.8/baselines/baselines/deepq/deepq.py", line 282, in learn
    new_obs, rew, done, _ = env.step(env_action)
  File "/anaconda3/envs/cc-rs/lib/python3.6/site-packages/gym_unity/envs/unity_env.py", line 187, in step
    "The environment was expecting `action` to be a list."
gym_unity.envs.unity_env.UnityGymException: The environment was expecting `action` to be a list.
```

Look forward to your reply. Thanks!

**Comment by CicieChen** [comment]
BTW, I have tested the same setting in VisualBanana, but it has the same errors.

**Comment by unityjeffrey** [comment]
cc: @awjuliani ...

**Comment by awjuliani** [comment]
Hi @CicieChen 

I believe that the OpenAI trainer you are using does not work with multiple agents in a single scene, and hence the issue.

**Comment by Usmaniatech** [comment]
In order to work with multi agents, you can also try MADDPG.

**Comment by YuhangSong** [comment]
Or try our multi-agent platform based on ML-Agents: https://sites.google.com/view/arena-home/home

**Comment by CicieChen** [comment]
Sorry for the late reply, @awjuliani @Usmaniatech @YuhangSong thanks so much for you guys' suggestion. Currently, I am in travelling. I will update the results here when I come back. <3

**Comment by CicieChen** [comment]
Hi @awjuliani, I have tested my environment with PPO, it can work. But I can not use baselines algorithm to train it.

**Comment by CicieChen** [comment]
Hi @Usmaniatech, could you please give me some examples of how to train it with MADDPG? Can you work with version 0.8?

Hi @YuhangSong, is that possible to use my own environment in your platform with other baseline algorithms?

**Comment by Usmaniatech** [comment]
Unfortunately I am not able to work with 0.8 version of MLAgents to train using MADDPG. I am using 0.4 version to work with MADDPG. It don't work with versions > 0.4

**Comment by CicieChen** [comment]
Hi @Usmaniatech, thanks for your valuable comments. I have tested in version 0.6 and 0.8, it just can not work. I will test version 0.4 today. However, they did not offer the support of gym wrapper this version. Would you mind sharing your code or project?

**Comment by Usmaniatech** [comment]
I can't share my code, It's for a client. But if you face any issues, I''ll be happy to help. 
for refrence: https://github.com/katnoria/unityml-tennis

**Comment by Usmaniatech** [comment]
The mistake that many people do, is they install unityagents along with mlagents. They are the same, with different names. If you are working on 0.4, only install unityagents and If you are working on version > 0.4, only install mlagents according to version requirements.

**Comment by Usmaniatech** [comment]
I want to train the baseline model DQN on tennis example. Multi agent example using same brain. 
My code:

> import gym
> 
> from baselines import deepq
> from baselines import logger
> 
> from gym_unity.envs.unity_env import UnityEnv
> 
> def main():
>     env = UnityEnv("./envs/Tennis/Skyforge 8.2",0, use_visual= False, multiagent=True)
>     logger.configure('./logs') # Çhange to log in a different directory
>     act = deepq.learn(
>         env,
>         "cnn", # conv_only is also a good choice for GridWorld
>         lr=2.5e-4,
>         total_timesteps=1000,
>         buffer_size=50000,
>         exploration_fraction=0.05,
>         exploration_final_eps=0.1,
>         print_freq=20,
>         train_freq=5,
>         learning_starts=20000,
>         target_network_update_freq=50,
>         gamma=0.99,
>         prioritized_replay=False,
>         checkpoint_freq=1000,
>         checkpoint_path='./logs', # Change to save model in a different directory
>         dueling=True
>     )
>     print("Saving model to unity_model.pkl")
>     act.save("unity_model.pkl")
> 
> if __name__ == '__main__':
>     main()

But it's not working. Getting the error for no of actions i guess.
![error](https://user-images.githubusercontent.com/14370981/61542617-5cf7cb80-aa5b-11e9-8147-03fc50fd3b8c.PNG)
@CicieChen

**Comment by CicieChen** [comment]
@Usmaniatech Thanks so much for your kindly help.
Currently, my input is the visual input, as for the example codes, they are for the vector input. So the shape or type for the inputs is different. (This might be one of the questions)
Another is my agent number is more than two, when the actions passed to the network, the baselines algorithms only accept and send One action (but unity-gym requires a list of actions). 
Those are the questions I found for version 0.8.

However, I can not work in version 0.4 too. This might be visual input and the number of the agent. Any suggestions are welcome, and I will keep solving this.

**Comment by YuhangSong** [comment]
> Hi @Usmaniatech, could you please give me some examples of how to train it with MADDPG? Can you work with version 0.8?
> 
> Hi @YuhangSong, is that possible to use my own environment in your platform with other baseline algorithms?

Yes, the baseline part: https://github.com/YuhangSong/Arena-Baselines, does not restrict that the game should be built from https://github.com/YuhangSong/Arena-BuildingToolkit, you can plug your own game in.

The only restriction is that all agents should share the same action space, in order to support things like self-play.
