### ISSUE TITLE
BrokenPipeError during training

### ISSUE THREAD

**Issue by djsdvg** [Unity-Technologies/ml-agents#2199]
Training continues to crash due to this error :
```bash
INFO:mlagents.trainers: visual_v9-0: DiscreteLearning: Step: 123904. Time Elapsed: 16800.616 s Mean Reward: 0.125. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: visual_v9-0: DiscreteLearning: Step: 124928. Time Elapsed: 16862.672 s Mean Reward: 0.125. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: visual_v9-0: DiscreteLearning: Step: 125952. Time Elapsed: 16925.503 s Mean Reward: 0.125. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: visual_v9-0: DiscreteLearning: Step: 126976. Time Elapsed: 16984.877 s Mean Reward: 0.125. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: visual_v9-0: DiscreteLearning: Step: 128000. Time Elapsed: 17047.055 s Mean Reward: 0.125. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: visual_v9-0: DiscreteLearning: Step: 129024. Time Elapsed: 17109.185 s Mean Reward: 0.125. Std of Reward: 0.000. Training.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\mlagents2\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Pipe terminata

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\mlagents2\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\user\Anaconda3\envs\mlagents2\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\user\desktop\ml-agents\ml-agents-envs\mlagents\envs\subprocess_environment.py", line 62, in worker
    cmd: EnvironmentCommand = parent_conn.recv()
  File "C:\Users\user\Anaconda3\envs\mlagents2\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\user\Anaconda3\envs\mlagents2\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
```

these are the configuration parameters used:
```yaml
default:
    trainer: ppo
    batch_size: 512
    beta: 1.0e-4
    buffer_size:  8192
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 1024
    lambd: 0.95
    learning_rate: 5.0e-4
    max_steps: 2.0e6
    memory_size: 256
    normalize: false
    num_epoch: 5
    num_layers: 3
    time_horizon: 1024
    sequence_length: 64
    summary_freq: 1024
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128
```

I'm using a pc Windows and the latest version of MLAgents 0.8.2.
As you can see from the error, I installed MLAgents on a virtual environment using Anaconda.
Before the last update everythink worked fine so I think that the issue is linked to the upgrade

**Comment by unityjeffrey** [comment]
cc @harperj - this may have been introduced by your commit - https://github.com/Unity-Technologies/ml-agents/commit/f89b8ce5b90147dc21f52c78c79dad1f3216c56e#diff-bdd48b7df5962c50ef0fdc07437d1eb5

**Comment by harperj** [comment]
@djsdvg Are you able to reproduce this error with any of our example training environments?  We have limited ability to help with training issues related to custom environments.

Could you also share the exact `mlagents-learn` command you used to run this training session?

**Comment by djsdvg** [comment]
@harperj
I tried to reproduce the error with your exambple but i can't.
I don't remember the exact comand.

Could you publish the documentation for the code?
It is difficult to solve a problem without even an uml scheme.
If i have to put the hands on the code i need to know how the code is structured.

**Comment by ervteng** [comment]
Thanks for the discussion - closing this issue due to inactivity. Feel free to open a new issue if you're still running into problems.

**Comment by markus-weiss** [comment]
Hey guys, 

I got the same Error on training with the VisuallHallWay-example. I use tensorflow-gpu by the way. On every other example it works fine. Here my errorlog:

```
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
INFO:mlagents.envs:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Training Brains : 0
        Reset Parameters :


2019-12-16 12:48:22.495341: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-12-16 12:48:22.698308: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1344] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:23:00.0
totalMemory: 8.00GiB freeMemory: 6.64GiB
2019-12-16 12:48:22.704420: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1423] Adding visible gpu devices: 0
2019-12-16 12:48:23.316615: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-16 12:48:23.319443: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:917]      0
2019-12-16 12:48:23.321846: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:930] 0:   N
2019-12-16 12:48:23.324508: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6416 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:23:00.0, compute capability: 6.1)
INFO:mlagents.envs:Hyperparameters for the PPOTrainer of brain VisualHallway:
        trainer:        ppo
        batch_size:     64
        beta:   0.01
        buffer_size:    1024
        epsilon:        0.2
        hidden_units:   128
        lambd:  0.95
        learning_rate:  0.0003
        learning_rate_schedule: linear
        max_steps:      5.0e5
        memory_size:    256
        normalize:      False
        num_epoch:      3
        num_layers:     1
        time_horizon:   64
        sequence_length:        64
        summary_freq:   1000
        use_recurrent:  True
        vis_encode_type:        simple
        reward_signals:
          extrinsic:
            strength:   1.0
            gamma:      0.99
        summary_path:   ./summaries/firstRun_VisualHallway
        model_path:     ./models/firstRun-0/VisualHallway
        keep_checkpoints:       5
2019-12-16 12:48:24.583849: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1423] Adding visible gpu devices: 0
2019-12-16 12:48:24.586676: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-16 12:48:24.589644: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:917]      0
2019-12-16 12:48:24.591726: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:930] 0:   N
2019-12-16 12:48:24.594429: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6416 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:23:00.0, compute capability: 6.1)
2019-12-16 12:48:26.067053: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_dnn.cc:396] Loaded runtime CuDNN library: 7605 (compatibility version 7600) but source was compiled with 7003 (compatibility version 7000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
2019-12-16 12:48:26.076044: F T:\src\github\tensorflow\tensorflow\core\kernels\conv_ops.cc:712] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\marku\Anaconda3\envs\ml-agents-gpu\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Die Pipe wurde beendet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marku\Anaconda3\envs\ml-agents-gpu\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\marku\Anaconda3\envs\ml-agents-gpu\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\_github\ml-agents\ml-agents-envs\mlagents\envs\subprocess_env_manager.py", line 89, in worker
    cmd: EnvironmentCommand = parent_conn.recv()
  File "C:\Users\marku\Anaconda3\envs\ml-agents-gpu\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\marku\Anaconda3\envs\ml-agents-gpu\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

(ml-agents-gpu) C:\_GitHub\ml-agents>
```
