### ISSUE TITLE
Troubles when trying to run tensorflow-pretrained unet model on ios

### ISSUE THREAD

**Issue by hfnvbh** [Unity-Technologies/ml-agents#2224]
Hi
I have a trained in tensorflow Unet CNN and try to convert and run it in barracuda inference on ios.

First issue occured when I ran 
python tensorflow_to_barracuda.py freezed.pb freezed.nn

> traceback (most recent call last):
>  File "tensorflow_to_barracuda.py", line 26, in <module>
>    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
>  File "/Users/Documents/repos/ml-agents/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 1537, in convert
>    i_model, args
>  File "/Users/Documents/repos/ml-agents/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 1366, in process_model
>    nodes, var_tensors, const_tensors, o_context
>  File "/Users/Documents/repos/ml-agents/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 467, in <lambda>
>    int(by_name(tensors, "/axis").data[0]), context.layer_ranks[inputs[0]]
  File "/Users/Documents/repos/ml-agents/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 742, in axis_to_barracuda
>    assert axis < input_rank
AssertionError

I noticed that in lines 739-740
```
    if axis < 0:
        axis = input_rank - axis
```
in that case if axis equals -1, after this lines it become equals 5 and that lead to AssertionError
I changed the code to 
```
    if axis < 0:
        axis = input_rank + axis
```
then convert was successful with this output
>IGNORED: Shape unknown layer
>IGNORED: Pack unknown layer
>IGNORED: Shape unknown layer
>IGNORED: Pack unknown layer
>IGNORED: Shape unknown layer
>IGNORED: Pack unknown layer
>IGNORED: Shape unknown layer
>IGNORED: Pack unknown layer
>IN: 'input': [-1, 192, 320, 1] => 'layer1/conv_1/BiasAdd'
>OUT: 'final/Sigmoid'

then I try to run this .nn file on ios through barracuda
``` 
Model model;
IWorker worker;
Dictionary<string, Tensor> inputNodes = new Dictionary<string, Tensor>();
...
model = ModelLoader.LoadFromStreamingAssets(properties.filename + ".nn");
worker = BarracudaWorkerFactory.CreateWorker(BarracudaWorkerFactory.Type.ComputePrecompiled, model);
...
inputNodes[properties.inputNode] = floatBuffer;
worker.Execute(inputNodes);
var outputTensor = worker.Peek(properties.outputNode);
```
And got this error in runtime
>ArgumentException: Off-axis dimensions must match
  at Barracuda.TensorExtensions.Concat (Barracuda.TensorShape[] shapes, System.Int32 axis) [0x00000] in <00000000000000000000000000000000>:0 
  at Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes, System.Collections.Generic.IDictionary`2[System.String,Barracuda.TensorShape]& shapesByName) [0x00000] in <00000000000000000000000000000000>:0 
  at Barracuda.ModelAnalyzer.FindLargestNecessaryTensorShape (Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) [0x00000] in <00000000000000000000000000000000>:0 
  at Barracuda.GenericVarsWithPreallocation.PrepareStorage (Barracuda.Model model, Barracuda.IOps ops, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes) [0x00000] in <00000000000000000000000000000000>:0 
  at Barracuda.GenericWorker+<ExecuteAsync>d__26.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at Barracuda.GenericWorker.Execute () [0x00000] in <00000000000000000000000000000000>:0 
  at Barracuda.GenericWorker.Execute (System.Collections.Generic.IDictionary`2[TKey,TValue] inputs) [0x00000] in <00000000000000000000000000000000>:0 

**Environment:**
- MacOS Mojave 10.14.5
- IOS 12.3.1
- ML-Agents version: commit 3e6ba788 in develop-barracuda-0.2.0 branch, also tries commit 2b4a9610 in develop branch.
- Unity 2018.4.2f1

**Comment by xiaomaogy** [comment]
@mantasp

**Comment by mantasp** [comment]
cc: @rejunity

**Comment by AkhilRaja** [comment]
Hi @mantasp  @rejunity  I am also getting a similar error with the faster_rcnn_inception_resnet_v2_atrous_oid_v4_2018_12_12 data set from the tensorflow zoo training datasets. 

Here is the attached error log 


>     
IGNORED: Cast unknown layer
IGNORED: Shape unknown layer
IGNORED: Shape unknown layer
IGNORED: Enter unknown layer
WARNING: rank unknown for tensor SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/Switch:1 while processing node SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/Identity
Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 26, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "/Users/apappu/Downloads/ml-agents-master/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 1537, in convert
    i_model, args
  File "/Users/apappu/Downloads/ml-agents-master/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 1383, in process_model
    process_layer(node, o_context, args)
  File "/Users/apappu/Downloads/ml-agents-master/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 1198, in process_layer
    -1 not in input_ranks
AssertionError

**Comment by mantasp** [comment]
Best practice in such case would be cut the network in several parts and only execute core part of it in Barracuda and move postprocessing nodes like `SecondStagePostprocessor/BatchMultiClassNonMaxSuppression` to either C# or Unity Compute shader.

**Comment by hfnvbh** [comment]
What about my issue? I have no BatchMultiClassNonMaxSuppression and passed converting  after fix in converter code.

**Comment by mantasp** [comment]
@hfnvbh do you have link to your model?

**Comment by hfnvbh** [comment]
Hi @mantasp 
I attached archive with original .pb file and converted .nn.

[testcnn.zip](https://github.com/Unity-Technologies/ml-agents/files/3573950/testcnn.zip)
