### ISSUE TITLE
Can't train 3d Ball.  TypeError: string indices must be integers

### ISSUE THREAD

**Issue by johnorduno** [Unity-Technologies/ml-agents#2231]
Getting this error when trying to train the 3d ball per the guide.  This is what shows up in anaconda terminal:

INFO:mlagents.trainers:{'--base-port': '5005',
 '--curriculum': 'None',
 '--debug': False,
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-envs': '1',
 '--num-runs': '1',
 '--run-id': 'ppo',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': False,
 '<trainer-config-path>': 'C:\\Users\\J'}
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
INFO:mlagents.envs:
'Ball3DAcademy' started successfully!
Unity Academy name: Ball3DAcademy
        Number of Brains: 1
        Number of Training Brains : 1
        Reset Parameters :

Unity brain name: 3DBallLearning
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: ,
Traceback (most recent call last):
  File "c:\anaconda\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\anaconda\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 285, in main
    run_training(0, run_seed, options, Queue())
  File "c:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 107, in run_training
    tc.start_learning(env, trainer_config)
  File "c:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 231, in start_learning
    self.initialize_trainers(trainer_config)
  File "c:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 135, in initialize_trainers
    trainer_parameters = trainer_config["default"].copy()
TypeError: string indices must be integers

This doesn't seem to match up to the other problems people are having when trying to train the 3d ball.  I gave it a proper directory for the config file.  Anyone else have this problem?

**Comment by johnorduno** [comment]
<img width="478" alt="Capture" src="https://user-images.githubusercontent.com/19738435/60779255-e075fc00-a0ee-11e9-9088-69f41d48bc82.PNG">

This is the error that shows up in Unity

**Comment by roboserg** [comment]
Did you add a learning brain to the academy and the agent AND checked the box? https://puu.sh/DQ7i0/32fc1a5713.png

**Comment by johnorduno** [comment]
I did. Im wondering if i missed something. Will try it on .exe to see if it does the same.

**Comment by xiaomaogy** [comment]
Hi @johnorduno , the error message seems to indicate you have a broken trainer_config.yaml file. Did you change that file somehow?

**Comment by johnorduno** [comment]
Not that I'm aware of.  I will try replacing it with what's in the master file.

**Comment by johnorduno** [comment]
Didn't work.  Same error.

**Comment by xiaomaogy** [comment]
in that case I am not sure what happens..

**Comment by ervteng** [comment]
Thanks for the comments - closing this issue due to inactivity. Feel free to open a new issue if you're still running into problems.
