### ISSUE TITLE
unable to load checkpoint (action_output_shape)

### ISSUE THREAD

**Issue by Junggy** [Unity-Technologies/ml-agents#2241]
I interrupted training by stopping from unity (pressing play button to stop)
And when I try to load checkpoint, it complains that it cannot find Key "action_output_shape"
I have no idea.
I touched API little bit inside of model to do add some layers & some cropping & concating but I don't think that would cause this trouble. (I did it few time before there was no problem).

Is coming from the way I interrupted training ? (like somehow tensorflow is stopped before adding all variables to checkpoint etc?)

**When I stop training from unity side :**

UnityEnvironment worker: keyboard interrupt
INFO:mlagents.envs:Learning was interrupted. Please wait while the graph is generated.
INFO:mlagents.envs:Saved Model
INFO:mlagents.trainers:List of nodes to export for brain :TrackingBrain
INFO:mlagents.trainers: is_continuous_control
INFO:mlagents.trainers: version_number
INFO:mlagents.trainers: memory_size
INFO:mlagents.trainers: action_output_shape
INFO:mlagents.trainers: action_probs
INFO:mlagents.trainers: action
INFO:mlagents.trainers: value_estimate
INFO:tensorflow:Restoring parameters from ./models/test-0/TrackingBrain\model-89195.cptk
Traceback (most recent call last):
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value action_output_shape
         [[Node: _retval_action_output_shape_0_0 = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](action_output_shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kkk\anaconda3\envs\thesis\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kkk\Anaconda3\envs\thesis\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\learn.py", line 95, in run_training
    tc.start_learning(env, trainer_config)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\trainer_controller.py", line 237, in start_learning
    self._export_graph()
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\trainer_controller.py", line 120, in _export_graph
    self.trainers[brain_name].export_model()
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\trainer.py", line 171, in export_model
    self.policy.export_model()
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\policy.py", line 239, in export_model
    filename_tensor_name='save/Const:0')
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 256, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 155, in freeze_graph_with_def_protos
    variable_names_blacklist=variable_names_blacklist)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\framework\graph_util_impl.py", line 251, in convert_variables_to_constants
    returned_variables = sess.run(variable_names)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    run_metadata)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value action_output_shape
         [[Node: _retval_action_output_shape_0_0 = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](action_output_shape)]]

**When I tried to load weight** 

INFO:mlagents.trainers:Loading Model for brain TrackingBrain
INFO:tensorflow:Restoring parameters from ./models/test-0/TrackingBrain\model-89195.cptk
2019-07-10 17:48:30.649802: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key action_output_shape not found in checkpoint
Traceback (most recent call last):
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key action_output_shape not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kkk\anaconda3\envs\thesis\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kkk\Anaconda3\envs\thesis\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\learn.py", line 95, in run_training
    tc.start_learning(env, trainer_config)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\trainer_controller.py", line 207, in start_learning
    self.initialize_trainers(trainer_config)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\trainer_controller.py", line 164, in initialize_trainers
    self.run_id)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 45, in __init__
    self.is_training, load)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\ppo\policy.py", line 42, in __init__
    self._load_graph()
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\policy.py", line 90, in _load_graph
    self.saver.restore(self.sess, ckpt.model_checkpoint_path)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\training\saver.py", line 1775, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    run_metadata)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key action_output_shape not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "c:\users\kkk\anaconda3\envs\thesis\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kkk\Anaconda3\envs\thesis\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\learn.py", line 95, in run_training
    tc.start_learning(env, trainer_config)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\trainer_controller.py", line 207, in start_learning
    self.initialize_trainers(trainer_config)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\trainer_controller.py", line 164, in initialize_trainers
    self.run_id)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 45, in __init__
    self.is_training, load)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\ppo\policy.py", line 42, in __init__
    self._load_graph()
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\mlagents\trainers\policy.py", line 82, in _load_graph
    self.saver = tf.train.Saver(max_to_keep=self.keep_checkpoints)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\training\saver.py", line 1311, in __init__
    self.build()
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\training\saver.py", line 1320, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\training\saver.py", line 1357, in _build
    build_save=build_save, build_restore=build_restore)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\training\saver.py", line 809, in _build_internal
    restore_sequentially, reshape)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\training\saver.py", line 448, in _AddRestoreOps
    restore_sequentially)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\training\saver.py", line 860, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1541, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\framework\ops.py", line 3290, in create_op
    op_def=op_def)
  File "c:\users\kkk\anaconda3\envs\thesis\lib\site-packages\tensorflow\python\framework\ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key action_output_shape not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by Junggy** [comment]
Issue solved. I had to load pretrained model and I messed up the self.saver by only having my pretrained variables. I created other saver and problem solved.
