### ISSUE TITLE
'mlagents-learn' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by XanderKehoe** [Unity-Technologies/ml-agents#2304]
Im following this tutorial (https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md) and I am at the "Training the Environment" section. When I get to step 3/4, I input the given commands into my command line but I am met with:

"'mlagents-learn' is not recognized as an internal or external command,
operable program or batch file."

How to fix?

**Comment by ervteng** [comment]
Hi @thekiwininja99, did you follow the install instructions? You may have to activate your virtual environment before the command works. 

https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md

**Comment by thekiwininja99** [comment]
Re-installed the entire process and got a step further, but now I get an error running the command:

"Traceback (most recent call last):
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyName\.conda\envs\ml-agents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2434, in load
    return self.resolve()
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\MyName\downloads\ml-agents-master\ml-agents-master\ml-agents\mlagents\trainers\__init__.py", line 5, in <module>
    from .models import *
  File "c:\users\MyName\downloads\ml-agents-master\ml-agents-master\ml-agents\mlagents\trainers\models.py", line 4, in <module>
    import tensorflow as tf
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\MyName\.conda\envs\ml-agents\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help."

**Comment by harperj** [comment]
We are closing this issue due to inactivity. Feel free to reopen it if you’d like to continue the discussion.
