### ISSUE TITLE
Visual Observation out of range

### ISSUE THREAD

**Issue by Guidosalimbeni** [Unity-Technologies/ml-agents#2359]
I got this error message and I wonder if you can help me to find the cause of it. I am using 2 cameras as visual observation and a requestDecision for each agents. 

`
D:\AAA ml Agents\ml-agents-master>activate ml-agents

(ml-agents) D:\AAA ml Agents\ml-agents-master>mlagents-learn config/trainer_config.yaml --run-id=ACAVA10 --train --slow

                        ___¦¦¦¦
                   +¦¦¦¦¦¦¦¦¦¦¦¦
              ,___m¯¯¯'  ,¦¦¦¯¦¦_                           ¦¦¦  ¦¦¦
            _¦¦¦¯'      _¦¦¯  ¦¦¦      __     __ ,__ ____   ,__ _¦¦¦_ ___    ,__
          _¦¦¦¯        _¦¦¯   ¦¦¦¦     ¦¦¦   ¦¦¦ ¦¦¦¦¯¯¯¦¦¦ ¦¦¦ ¯¦¦¦¯ ^¦¦¦  +¦¦¦
        _¦¦¦¦¦________¦¦¦      ¦¯      ¦¦¦   ¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦   ¦¦¦_ ¦¦¦
        ¯¦¦¦¦¯¯¯¯¯¯¯¯¯¯¦¦_     ¦¦      ¦¦¦   ¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦    ¦¦¦¦¦¦
          ^¦¦¦¦        ¯¦¦_   ¦¦¦¦     ¦¦¦¦_¦¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦_    ¦¦¦¦`
            '¯¦¦¦_      ^¦¦¦  ¦¦¦       +¯¯¯¯ ¯¯ ^¯¯    `¯¯ `¯¯   '¯¯    ¦¦¦¦
               ¯¯¯¯¦___   ¦¦¦¦¦¦,                                      ¦¦¦¦¯
                   `¯¦¦¦¦¦¦¦¦¦¦¦
                        ¬`¯¯¯¦¦

INFO:mlagents.trainers:{'--base-port': '5005',
 '--curriculum': 'None',
 '--debug': False,
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-envs': '1',
 '--num-runs': '1',
 '--run-id': 'ACAVA10',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': True,
 '--train': True,
 '<trainer-config-path>': 'config/trainer_config.yaml'}
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
INFO:mlagents.envs:
'[ ACADEMY ]' started successfully!
Unity Academy name: [ ACADEMY ]
        Number of Brains: 3
        Number of Training Brains : 3
        Reset Parameters :

Unity brain name: CompAILearning_01_98
        Number of Visual Observations (per agent): 2
        Vector Observation space size (per agent): 0
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [7]
        Vector Action descriptions: position_rotation_nothing
Unity brain name: CompAILearning_02_98
        Number of Visual Observations (per agent): 2
        Vector Observation space size (per agent): 0
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [7]
        Vector Action descriptions: position_rotation_nothing
Unity brain name: CompAILearning_03_98
        Number of Visual Observations (per agent): 2
        Vector Observation space size (per agent): 0
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [7]
        Vector Action descriptions: position_rotation_nothing
2019-07-29 18:15:05.338757: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow bi
nary was not compiled to use: AVX2
INFO:mlagents.envs:Hyperparameters for the PPO Trainer of brain CompAILearning_01_98:
        batch_size:     1024
        beta:   0.005
        buffer_size:    10240
        epsilon:        0.2
        gamma:  0.99
        hidden_units:   128
        lambd:  0.95
        learning_rate:  0.0003
        max_steps:      5.0e4
        normalize:      False
        num_epoch:      3
        num_layers:     2
        time_horizon:   64
        sequence_length:        64
        summary_freq:   1000
        use_recurrent:  False
        summary_path:   ./summaries/ACAVA10-0_CompAILearning_01_98
        memory_size:    256
        use_curiosity:  False
        curiosity_strength:     0.01
        curiosity_enc_size:     128
        model_path:     ./models/ACAVA10-0/CompAILearning_01_98
INFO:mlagents.envs:Hyperparameters for the PPO Trainer of brain CompAILearning_02_98:
        batch_size:     1024
        beta:   0.005
        buffer_size:    10240
        epsilon:        0.2
        gamma:  0.99
        hidden_units:   128
        lambd:  0.95
        learning_rate:  0.0003
        max_steps:      5.0e4
        normalize:      False
        num_epoch:      3
        num_layers:     2
        time_horizon:   64
        sequence_length:        64
        summary_freq:   1000
        use_recurrent:  False
        summary_path:   ./summaries/ACAVA10-0_CompAILearning_02_98
        memory_size:    256
        use_curiosity:  False
        curiosity_strength:     0.01
        curiosity_enc_size:     128
        model_path:     ./models/ACAVA10-0/CompAILearning_02_98
INFO:mlagents.envs:Hyperparameters for the PPO Trainer of brain CompAILearning_03_98:
        batch_size:     1024
        beta:   0.005
        buffer_size:    10240
        epsilon:        0.2
        gamma:  0.99
        hidden_units:   128
        lambd:  0.95
        learning_rate:  0.0003
        max_steps:      5.0e4
        normalize:      False
        num_epoch:      3
        num_layers:     2
        time_horizon:   64
        sequence_length:        64
        summary_freq:   1000
        use_recurrent:  False
        summary_path:   ./summaries/ACAVA10-0_CompAILearning_03_98
        memory_size:    256
        use_curiosity:  False
        curiosity_strength:     0.01
        curiosity_enc_size:     128
        model_path:     ./models/ACAVA10-0/CompAILearning_03_98
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 285, in main
    run_training(0, run_seed, options, Queue())
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 107, in run_training
    tc.start_learning(env, trainer_config)
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 244, in start_learning
    new_info = self.take_step(env, curr_info)
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 315, in take_step
    curr_info, new_info, take_action_outputs[brain_name]
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 236, in add_experiences
    curr_to_use = self.construct_curr_info(next_info)
  File "c:\programdata\anaconda3\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 164, in construct_curr_info
    visual_observations[i].append(
IndexError: list index out of range
UnityEnvironment worker: keyboard interrupt

(ml-agents) D:\AAA ml Agents\ml-agents-master>
(ml-agents) D:\AAA ml Agents\ml-agents-master>`

**Comment by harperj** [comment]
Hi @Guidosalimbeni -- it would be helpful for us if you could fill out the bug report from the issue template.  You can see the form including the bug report template here: https://github.com/Unity-Technologies/ml-agents/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by vincentpierre** [comment]
Thank you for the discussion. We are closing this issue due to inactivity.
