### ISSUE TITLE
[Barracuda]UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by stefanpantic** [Unity-Technologies/ml-agents#2390]
**Describe the bug**
When I try to convert a TF model to Bararcuda I get the following error
```
Converting /home/stefan/Documents/work/asr/reproduce_bug/tmp/frozen.pb to fz.nn
Traceback (most recent call last):
  File "/home/stefan/Documents/work/wgym/api/tensorflow_to_barracuda.py", line 26, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "/home/stefan/Documents/work/wgym/api/tensorflow_to_barracuda.py", line 1552, in convert
    i_model, args
  File "/home/stefan/Documents/work/wgym/api/tensorflow_to_barracuda.py", line 1397, in process_model
    process_layer(node, o_context, args)
  File "/home/stefan/Documents/work/wgym/api/tensorflow_to_barracuda.py", line 1150, in process_layer
    for x in tensor_names
  File "/home/stefan/Documents/work/wgym/api/tensorflow_to_barracuda.py", line 1150, in <listcomp>
    for x in tensor_names
  File "/home/stefan/Documents/work/wgym/api/tensorflow_to_barracuda.py", line 697, in get_tensor_data
    return np.array(data).reshape(dims)
UnboundLocalError: local variable 'data' referenced before assignment
```
regarding the ```mean``` and ```epsilon``` variables in ```BatchNormalization```.

**To Reproduce**
Standalone script required for reproducing the bug.

```
import os

import tensorflow as tf
from tensorflow.python.keras.datasets import mnist
from tensorflow.python.tools import freeze_graph


class Model:
    def __init__(self):
        self._conv = tf.keras.layers.Conv2D(filters=64, kernel_size=5, activation=tf.nn.relu)
        self._batch_norm = tf.keras.layers.BatchNormalization()
        self._flatten = tf.keras.layers.Flatten()
        self._logits = tf.keras.layers.Dense(units=10)

    def forward(self, inputs):
        with tf.name_scope('model'):
            conv_out = self._conv(inputs)
            norm_out = self._batch_norm(conv_out, training=True)
            flat_out = self._flatten(norm_out)
            logits = self._logits(flat_out)

        return tf.identity(logits, name='logits')

    @staticmethod
    def loss(logits, labels):
        with tf.name_scope('loss'):
            loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)

        return loss


def train():
    def map_fn(x, y):
        return tf.expand_dims(tf.math.divide(tf.cast(x, tf.float32), 255), axis=2), tf.cast(y, tf.int32)

    (x_train, y_train), (_, _) = mnist.load_data()

    dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
    dataset = dataset.map(map_fn).batch(128).repeat(10)

    iterator = dataset.make_one_shot_iterator()
    inputs, labels = iterator.get_next()

    model = Model()
    logits = model.forward(inputs)
    loss = model.loss(logits, labels)

    with tf.name_scope('optimizer'):
        optimizer = tf.train.AdamOptimizer(learning_rate=1e4).minimize(loss,
                                                                       global_step=tf.train.get_or_create_global_step())

    with tf.train.MonitoredTrainingSession(checkpoint_dir='./tmp') as sess:
        while not sess.should_stop():
            print(sess.run([optimizer, loss])[1])


def export():
    tf.reset_default_graph()

    export_dir = './tmp/frozen'
    model = Model()

    inputs = tf.placeholder(dtype=tf.float32, shape=[None, 28, 28, 1], name='input_placeholder')
    _ = model.forward(inputs)

    with open('./tmp/checkpoint') as f:
        line = f.readline()
        checkpoint = line[line.find('"') + 1:line.rfind('"')]
        print(checkpoint)

    with tf.Session(graph=tf.get_default_graph()) as sess:
        saver = tf.train.Saver()

        sess.run(tf.global_variables_initializer())
        print(os.path.join('./tmp', checkpoint))
        saver.restore(sess, os.path.join('./tmp', checkpoint))

        builder = tf.saved_model.Builder('./tmp/frozen')
        builder.add_meta_graph_and_variables(sess, [tf.saved_model.tag_constants.SERVING], strip_default_attrs=True)
        builder.save()

        graph = tf.graph_util.remove_training_nodes(sess.graph.as_graph_def(), protected_nodes=['logits'])

        freeze_graph.freeze_graph_with_def_protos(
            input_graph_def=graph,
            input_saver_def=None,
            input_saved_model_dir=export_dir,
            saved_model_tags=[tf.saved_model.tag_constants.SERVING],
            input_checkpoint=os.path.join('./tmp', checkpoint),
            output_node_names='logits',
            output_graph=os.path.join('./tmp', 'frozen.pb'),
            clear_devices=True,
            initializer_nodes='',
            restore_op_name='',
            filename_tensor_name='')


if __name__ == '__main__':
    train()
    export()

```

**Environment (please complete the following information):**
I am currently using a ```conda``` environment with the following libraries installed.

```
name: asr
channels:
- defaults
- conda-forge
dependencies:
- python==3.6.7
- pip==19.0.3
- autopep8==1.4.3
- numpy==1.15.4
- flatbuffers==1.11
- pep8==1.7.1
- tensorflow-gpu==1.13.1
- click==7.0
- pip:
    - python-speech-features==0.6
    - librosa==0.7.0
    - SoundFile==0.10.2
    - tqdm==4.32.2

```

Environment:
```
conda env create --file environment.yaml
```

**Comment by stefanpantic** [comment]
The provided script will create a frozen.pb frozen graph file that should then be converted to Barracuda using ```tensorflow_to_barracuda.py```

**Comment by mantasp** [comment]
Added this to our internal bugtracker. cc: @rejunity @FlorentGuinier

**Comment by weizhuang-93** [comment]
Hi, i encountered similar problems but i do not know if it is the same bug. i have a cnn model, using DataFrmt NHWC, and named input and output. When i try to convert the .pb file with barracuda, i get the following error.
`(ml-agents) C:\Users\Wei Zhuang>python ml-agents-0.9.1\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py D:\MasterArbeit\05_Programm_und_Code\TFSharpTest\Assets\CNN_TF_1-7-1_BNAxis-1.pb D:\MasterArbeit\05_Programm_und_Code\TFSharpTest\Assets\CNN_TF_1-7-1_BNAxis-1.nn
Converting D:\MasterArbeit\05_Programm_und_Code\TFSharpTest\Assets\CNN_TF_1-7-1_BNAxis-1.pb to D:\MasterArbeit\05_Programm_und_Code\TFSharpTest\Assets\CNN_TF_1-7-1_BNAxis-1.nn
Traceback (most recent call last):
  File "ml-agents-0.9.1\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py", line 26, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "C:\Users\Wei Zhuang\ml-agents-0.9.1\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py", line 1606, in convert
    data=np.reshape(get_tensor_data(o_model.tensors[x]), shape).astype(
  File "C:\Users\Wei Zhuang\ml-agents-0.9.1\ml-agents\mlagents\trainers\tensorflow_to_barracuda.py", line 697, in get_tensor_data
    return np.array(data).reshape(dims)
UnboundLocalError: local variable 'data' referenced before assignment`

any ideas why this happen? i am new to ml-agents and have been experimenting with tensorflow since may. i am out of idea. i am using:
tensorflow-gpu = 1.7.1,
[CNN_TF_1-7-1_BNAxis-1.zip](https://github.com/Unity-Technologies/ml-agents/files/3558900/CNN_TF_1-7-1_BNAxis-1.zip)
python 3.6.6
windows 10, visual studio 17

**Comment by weizhuang-93** [comment]
Hi @mantasp , is there a workaround to this problem?

**Comment by fmannhardt** [comment]
For anyone getting this issue, in my case this was a BatchNormalization layer that had the flag 'trainable' set to `True` manually, so that the standard `tf.keras.backend.set_learning_phase(0)` to switch the BatchNormalization layer to test mode was not applied.

This apparently leads to the BatchNorm weights not being frozen and, thus, the Barracuda converter fails since the BatchNorm layer does not have the expected data.

Probably it would be good to make sure that `data` is initalized in `get_tensor_data` anyway and fail with some informative error message instead of the error:

```
def get_tensor_data(tensor):
    if isinstance(tensor, np.ndarray):
        return tensor.astype(float)

    dims = get_tensor_dims(tensor)
    elems = np.product(dims)
    
    if tensor.tensor_content:
        # TODO: support other types
        dataType = get_tensor_dtype(tensor)
        if dataType == "DT_FLOAT":
            data = struct.unpack('<'+str(elems)+'f', tensor.tensor_content)
        elif dataType == "DT_INT32":
            data = struct.unpack('<'+str(elems)+'i', tensor.tensor_content)
        elif dataType == "DT_BOOL":
            data = struct.unpack('<'+str(elems)+'?', tensor.tensor_content)
        else:
            print('UNSUPPORTED: data type', dataType)
    
    if tensor.float_val:
        data = tensor.float_val
    if tensor.int_val:
        data = np.array(tensor.int_val, dtype=float)
    if tensor.bool_val:
        data = np.array(tensor.bool_val, dtype=float)

    return np.array(data).reshape(dims)
```
