### ISSUE TITLE
Error when trying to use a demo brain with Gail

### ISSUE THREAD

**Issue by DooblyNoobly** [Unity-Technologies/ml-agents#2401]
**Describe the bug**
When using a demo brain with gail, mlagents throws an error after pressing play in the editor.

```
File "C:\Users\andre\.conda\envs\ml\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\learn.py", line 319, in main
    run_training(0, run_seed, options, Queue())
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\learn.py", line 118, in run_training
    tc.start_learning(env, trainer_config)
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 283, in start_learning
    self.initialize_trainers(trainer_config, env_manager.external_brains)
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 206, in initialize_trainers
    run_id=self.run_id,
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\ppo\trainer.py", line 68, in __init__
    self.policy = PPOPolicy(seed, brain, trainer_parameters, self.is_training, load)
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\ppo\policy.py", line 57, in __init__
    self, reward_signal, config
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\components\reward_signals\reward_signal_factory.py", line 40, in create_reward_signal
    class_inst = rcls(policy, **config_entry)
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\components\reward_signals\gail\signal.py", line 53, in __init__
    _, self.demonstration_buffer = demo_to_buffer(demo_path, policy.sequence_length)
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\demo_loader.py", line 64, in demo_to_buffer
    demo_buffer = make_demo_buffer(brain_infos, brain_params, sequence_length)
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\demo_loader.py", line 49, in make_demo_buffer
    0, batch_size=None, training_length=sequence_length
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\buffer.py", line 272, in append_update_buffer
    batch_size=batch_size, training_length=training_length
  File "d:\github\ml-agents\ml-agents\mlagents\trainers\buffer.py", line 126, in get_batch
    padding = np.array(self[-1]) * self.padding_value
IndexError: list index out of range
```

config:

```yaml
default:
    trainer: ppo
    batch_size: 128
    beta: 0.0001
    buffer_size: 64000
    epsilon: 0.2
    hidden_units: 256
    lambd: 0.95
    learning_rate: 0.002
    max_steps: Infinity
    memory_size: 512
    normalize: True
    num_epoch: 2
    num_layers: 1
    time_horizon: 400
    sequence_length: 32
    summary_freq: 1000
    use_recurrent: True
    reward_signals:
        extrinsic:
            strength: 1
            gamma: 0.99
        gail:
            strength: 0.1
            gamma: 0.99
            encoding_size: 128
            demo_path: demos/BigBotBrain.demo
```

**To Reproduce**
1. Record a demonstration on the player brain (up to 500 steps)
2. Add the demo brain path and gail reward parameters to config
3. Disable player brain, enable Learningbrain and add to Academy with control
4. Start mlagents-learn and press play in editor
5. See error

**Environment (please complete the following information):**
- Win_10
- _ML-Agents version_: v0.9 latest master as of today

**Note: I updated mlagents in the anaconda environment by pulling the latest from master and running the commands as outlined in windows install guide:
```bash
cd ml-agents-envs
pip install -e .
cd ..
cd ml-agents
pip install -e .
```

Screenshot of Demo Asset:

![image](https://user-images.githubusercontent.com/20813925/62597410-5907ec80-b929-11e9-9808-c066f8ae4ed6.png)

**Comment by arixlin** [comment]
Describe the bug
When using a visual demo brain with gail, mlagents throws an error after pressing play in the editor.
```
Traceback (most recent call last):
  File "e:\program files\anaconda\envs\mlagents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\program files\anaconda\envs\mlagents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Program Files\anaconda\envs\mlagents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\learn.py", line 319, in main
    run_training(0, run_seed, options, Queue())
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\learn.py", line 118, in run_training
    tc.start_learning(env, trainer_config)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 283, in start_learning
    self.initialize_trainers(trainer_config, env_manager.external_brains)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 206, in initialize_trainers
    run_id=self.run_id,
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 68, in __init__
    self.policy = PPOPolicy(seed, brain, trainer_parameters, self.is_training, load)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\ppo\policy.py", line 57, in __init__
    self, reward_signal, config
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\components\reward_signals\reward_signal_factory.py", line 40, in create_reward_signal
    class_inst = rcls(policy, **config_entry)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\components\reward_signals\gail\signal.py", line 51, in __init__
    policy.model, 128, learning_rate, encoding_size, use_actions, use_vail
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\components\reward_signals\gail\model.py", line 41, in __init__
    self.make_inputs()
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\components\reward_signals\gail\model.py", line 125, in make_inputs
    False,
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\models.py", line 249, in create_visual_observation_encoder
    name="conv_1",
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\layers\convolutional.py", line 619, in conv2d
    return layer.apply(inputs)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\layers\base.py", line 825, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\layers\base.py", line 696, in __call__
    self.build(input_shapes)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\layers\convolutional.py", line 144, in build
    dtype=self.dtype)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\layers\base.py", line 546, in add_variable
    partitioner=partitioner)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\training\checkpointable.py", line 415, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1297, in get_variable
    constraint=constraint)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1093, in get_variable
    constraint=constraint)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 439, in get_variable
    constraint=constraint)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 408, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 747, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable stream_0_visual_obs_encoder/conv_1/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\framework\ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\framework\ops.py", line 3290, in create_op
    op_def=op_def)
  File "e:\program files\anaconda\envs\mlagents\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
```

**Comment by ervteng** [comment]
Hi @DooblyNoobly, thanks for raising this issue. Could you try with the latest `master` branch? `develop` is the bleeding edge and may have issues. 

@arixlin, are you on `develop` or `master`? If `master` this seems like a bug and we'll investigate. Thanks!

**Comment by arixlin** [comment]
@ervteng  on release v0.9 Thanks

**Comment by DooblyNoobly** [comment]
@ervteng my mistake, turns out I was already on latest master. I'll edit my bug report:

![image](https://user-images.githubusercontent.com/20813925/62602948-3cbf7c00-b938-11e9-8c47-0f592d4a6afa.png)

**Comment by ervteng** [comment]
@DooblyNoobly - I wasn't able to replicate your issue on the sample environments, unfortunately. Could you try on the Hallway example and see if you're getting the same behavior? Thanks!

@arixlin - I was able to replicate this issue, it's a naming conflict between Curiosity and GAIL. It will be fixed in a patch in the next couple days. For now, I'd use GAIL only - usually, curiosity + GAIL doesn't add too much value.

**Comment by DooblyNoobly** [comment]
I just confirmed that hallway example works fine. I have even tested recording a new demonstration and there wasn't any problem. Must be something I'm doing specifically with my project.

**Comment by arixlin** [comment]
@ervteng  Thanks for your work.

**Comment by ervteng** [comment]
@DooblyNoobly it really does seem like a bug in the demo loader from your error message though 🤔. The only thing I can think of is if any of the brain settings changed between recording and training. Anyways, feel free to re-open the issue if you're unable to get it to work.

**Comment by TiNovTec** [comment]
I seem to have the same problem like @arixlin. I use the master from last week. Without curiosity it works.

Errors in Anaconda:
Traceback (most recent call last):
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\twi\AppData\Local\Continuum\anaconda3\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 319, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 118, in run_training
    tc.start_learning(env, trainer_config)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 283, in start_learning
    self.initialize_trainers(trainer_config, env_manager.external_brains)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 206, in initialize_trainers
    run_id=self.run_id,
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 68, in __init__
    self.policy = PPOPolicy(seed, brain, trainer_parameters, self.is_training, load)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\ppo\policy.py", line 57, in __init__
    self, reward_signal, config
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\components\reward_signals\reward_signal_factory.py", line 40, in create_reward_signal
    class_inst = rcls(policy, **config_entry)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\components\reward_signals\gail\signal.py", line 51, in __init__
    policy.model, 128, learning_rate, encoding_size, use_actions, use_vail
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\components\reward_signals\gail\model.py", line 41, in __init__
    self.make_inputs()
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\components\reward_signals\gail\model.py", line 125, in make_inputs
    False,
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\models.py", line 249, in create_visual_observation_encoder
    name="conv_1",
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\layers\convolutional.py", line 619, in conv2d
    return layer.apply(inputs)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\layers\base.py", line 825, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\layers\base.py", line 696, in __call__
    self.build(input_shapes)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\layers\convolutional.py", line 144, in build
    dtype=self.dtype)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\layers\base.py", line 546, in add_variable
    partitioner=partitioner)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\training\checkpointable.py", line 415, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1297, in get_variable
    constraint=constraint)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1093, in get_variable
    constraint=constraint)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 439, in get_variable
    constraint=constraint)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 408, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 747, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable stream_0_visual_obs_encoder/conv_1/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\framework\ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\framework\ops.py", line 3290, in create_op
    op_def=op_def)
  File "c:\users\twi\appdata\local\continuum\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)

gail_config.yaml:

GridWorldLearning:
    summary_freq: 2000
    time_horizon: 5
    batch_size: 32
    normalize: false
    buffer_size: 2048
    hidden_units: 256
    num_layers: 1
    beta: 5.0e-3
    max_steps: 5.0e4
    num_epoch: 3
    pretraining:
        demo_path: ./demos/GridWorldTrained.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: ./demos/GridWorldTrained.demo
