### ISSUE TITLE
Trying to train on Azure "Permission Error"

### ISSUE THREAD

**Issue by GitLinko** [Unity-Technologies/ml-agents#2488]
Hello,
I'm trying to set up my Azure VM to train Agents on it.
I've followed the guide in the documentation. First of all it says in the documentation that you need to check "headless" but I don't see that option anywhere. So what's that about? Anyway when I try to create my executable Enviroment using
env = UnityEnvironment("PushBlock")
or using the mlagents-learn command I get the following:

Traceback (most recent call last):
  File "/data/anaconda/envs/mlg/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/anaconda/envs/mlg/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/anaconda/envs/mlg/lib/python3.6/site-packages/mlagents/envs/subprocess_environment.py", line 53, in worker
    env = env_factory(worker_id)
  File "/data/anaconda/envs/mlg/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 192, in create_unity_environment
    base_port=start_port
  File "/data/anaconda/envs/mlg/lib/python3.6/site-packages/mlagents/envs/environment.py", line 67, in __init__
    self.executable_launcher(file_name, docker_training, no_graphics)
  File "/data/anaconda/envs/mlg/lib/python3.6/site-packages/mlagents/envs/environment.py", line 208, in executable_launcher
    [launch_string, '--port', str(self.port)])
  File "/data/anaconda/envs/mlg/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/data/anaconda/envs/mlg/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/data/home/linko994/dqn/PushBlock16/PushBlock16.x86_64'
Traceback (most recent call last):
  File "/data/anaconda/envs/mlg/bin/mlagents-learn", line 10, in <module>
    sys.exit(main())
  File "/data/anaconda/envs/mlg/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "/data/anaconda/envs/mlg/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 88, in run_training
    keep_checkpoints, lesson, env.external_brains,
  File "/data/anaconda/envs/mlg/lib/python3.6/site-packages/mlagents/envs/subprocess_environment.py", line 173, in external_brains
    return self.envs[0].recv().payload
  File "/data/anaconda/envs/mlg/lib/python3.6/site-packages/mlagents/envs/subprocess_environment.py", line 38, in recv
    response: EnvironmentResponse = self.conn.recv()
  File "/data/anaconda/envs/mlg/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/data/anaconda/envs/mlg/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/data/anaconda/envs/mlg/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by chriselion** [comment]
Hi @linko994,
"Headless mode" should be an option in the Build Settings for your scene:
![image](https://user-images.githubusercontent.com/6877802/64211098-efacc800-ce59-11e9-9b4b-5270228a3b91.png)

As for the exceptions, I think the first thing to solve is
`PermissionError: [Errno 13] Permission denied: '/data/home/linko994/dqn/PushBlock16/PushBlock16.x86_64'`
You'll need to debug this on your own, but my guess is either the file doesn't have execute permissions, or it was build for the wrong platform. 

For reference, the relevant parts of the code where the extensions are checked are here:
https://github.com/Unity-Technologies/ml-agents/blob/fe97df800b6c39e70beeb321abe4f9ed59ef8bfa/ml-agents-envs/mlagents/envs/environment.py#L187-L208

**Comment by linko994** [comment]
Huh. @chriselion This is how the build menu looks for me (Using Unity Editor 2018.3.11f19):

![Unity_2019-09-04_01-06-52](https://user-images.githubusercontent.com/3768115/64214345-712f4500-ceb0-11e9-97a7-dc9dda2ed58b.png)

I'm a newbie when it comes to Linux and VMs. "the file doesn't have execute permissions" how do I fix this?

**Comment by chriselion** [comment]
So you got the permissions straightened out? Here's a basic guide https://www.tutorialspoint.com/unix/unix-file-permission.htm but the short answer is that you'll probably need to run `chmod a+x [your file name]` to make the file executable.

I think for now, you can use "Server Build" instead of "Headless Build". I'll do some more digging into when "Headless Build" was removed from the build settings, and update the documentation accordingly.

**Comment by linko994** [comment]
In the Unity Documentation it says that "Server Build" was added in 2018.3, so maybe it replaced Headless? Headless is still listed as an option in the documentation for 2018.3 as well as the 2019 Versions so I don't know.

**Comment by chriselion** [comment]
Sorry for the delay on this. I confirmed with our platform team that "Headless" needs to be removed from the documentation (e.g. https://docs.unity3d.com/2019.3/Documentation/Manual/BuildSettings.html). "Server Build" is what you should be using instead; I'll update our docs to reflect this.

**Comment by chriselion** [comment]
I've added a request to update the documentation around this to our internal tracker with the ID MLA-18. I’m going to close this issue for now, but we’ll ping back with any updates
