### ISSUE TITLE
dev-trainer branch: learn.py and PPO.ipynb do not work

### ISSUE THREAD

**Issue by HappySlice** [Unity-Technologies/ml-agents#249]
I was excited about the ability to use multiple brains and tried to use this branch to train the Tennis and Wall examples.

The PPO.ipynb does not appear to be updated to use the new/renamed scripts in python/trainers.
The learn.py script appears to be able to train the 3DBall example but gives the following error for the Tennis and Wall examples. Which appears to be saying that the feed_dict is a giant vector versus a tensor which has a shape related to the number of states the respective example has.

```
Traceback (most recent call last):
  File "learn.py", line 210, in <module>
    trainer.update_model()
  File "C:\Users\david\Downloads\ml-agents-dev-trainer\ml-agents-dev-trainer\python\trainers\ppo_trainer.py", line 329, in update_model
    self.model.update_batch], feed_dict=feed_dict)
  File "C:\Users\david\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Users\david\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (512, 1) for Tensor 'state:0', which has shape '(?, 8)'
```

**Comment by vincentpierre** [comment]
I just pushed a change. It was a typo in the ppo_trainer.py code. Thank you for testing this feature and let us know if you find an issue on this branch.
