### ISSUE TITLE
ValueError: Cannot feed value of shape 

### ISSUE THREAD

**Issue by leobol96** [Unity-Technologies/ml-agents#2577]
Hello,
I have this error using learning by demostration.
This is the error message:

INFO:mlagents.envs:Hyperparameters for the OfflineBCTrainer of brain RightBrain:
trainer: offline_bc
batch_size: 256
summary_freq: 1000
max_steps: 5.0e6
batches_per_epoch: 10
use_recurrent: True
hidden_units: 256
learning_rate: 0.0003
num_layers: 3
sequence_length: 32
memory_size: 256
demo_path: nodescription_1.demo
summary_path: ./summaries/ppo_RightBrain
model_path: ./models/ppo-0/RightBrain
keep_checkpoints: 5

Traceback (most recent call last):
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Users\Leonardo\Anaconda3\envs\ml-agents\Scripts\mlagents-learn.exe_main.py", line 9, in
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 337, in main
run_training(0, run_seed, options, Queue())
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 132, in run_training
tc.start_learning(env)
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 202, in start_learning
n_steps = self.advance(env_manager)
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\site-packages\mlagents\envs\timers.py", line 261, in wrapped
return func(*args, **kwargs)
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 292, in advance
trainer.update_policy()
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\bc\trainer.py", line 138, in update_policy
run_out = self.policy.update(mini_batch, self.n_sequences)
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\bc\policy.py", line 95, in update
run_out = self._execute_model(feed_dict, self.update_dict)
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tf_policy.py", line 148, in _execute_model
network_out = self.sess.run(list(out_dict.values()), feed_dict=feed_dict)
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
run_metadata_ptr)
File "c:\users\leonardo\anaconda3\envs\ml-agents\lib\site-packages\tensorflow\python\client\session.py", line 1116, in _run
str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (8, 5) for Tensor 'teacher_action:0', which has shape '(?, 4)'

**Comment by awjuliani** [comment]
Hi @leobol96 

It seems that your teacher and student brains have different action spaces.

**Comment by leobol96** [comment]
@awjuliani

I checked and the brains have: 
- Same action spaces.
- Same environment with 28 obs.

![Hbrain](https://user-images.githubusercontent.com/36326039/65075792-e06c6500-d997-11e9-87c5-b47fe120b9c0.PNG)

![lbrain](https://user-images.githubusercontent.com/36326039/65075801-e5311900-d997-11e9-8767-100454b61eb6.PNG)

**Comment by djsdvg** [comment]
@leobol96  I had a very similar issue where the error was :
`InvalidArgumentError (see above for traceback): Incompatible shapes: [64,11] vs. [80,11]`

I found out that **64** was my `batch_size` in the `offline_bc_config.yaml`
So i tried to increase it till the error has disappear
Now my `batch_size` is 10000

**Comment by leobol96** [comment]
@djsdvg @awjuliani 
Same for me , the error disappear with a batch size of 1000000.

**Comment by djsdvg** [comment]
I tried several training with a large `batch_size`to avoid   the error but the training is not learning. 
It seems that the policy is never updated.
In fact on Tensorboard the graph under the policy section is empty

**Comment by awjuliani** [comment]
Hi all,

We have depreciated the online and offline BC trainers in favor of a new approach which can work concurrently with RL training. It should also resolve the issues that have been described here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Imitation-Learning.md.

**Comment by djsdvg** [comment]
ok
