### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by avatcc** [Unity-Technologies/ml-agents#2579]
when i try to train my model, this error shows.
(ml-agents) C:\Users\chenchet\Downloads\ml-agents>mlagents-learn config/trainer_config.yaml --curriculum=config/curricula/penguin/ --run-id=penguin_1 --train

                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓

INFO:mlagents.trainers:{'--base-port': '5005',
 '--curriculum': 'config/curricula/penguin/',
 '--debug': False,
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--multi-gpu': False,
 '--no-graphics': False,
 '--num-envs': '1',
 '--num-runs': '1',
 '--run-id': 'penguin_1',
 '--sampler': 'None',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '<trainer-config-path>': 'config/trainer_config.yaml'}
Traceback (most recent call last):
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "c:\users\chenchet\downloads\ml-agents\ml-agents\mlagents\trainers\learn.py", line 337, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\chenchet\downloads\ml-agents\ml-agents\mlagents\trainers\learn.py", line 85, in run_training
    trainer_config = load_config(trainer_config_path)
  File "c:\users\chenchet\downloads\ml-agents\ml-agents\mlagents\trainers\learn.py", line 206, in load_config
    trainer_config = yaml.safe_load(data_file)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "config/trainer_config.yaml", line 292, column 1

**Comment by awjuliani** [comment]
Hi @avatcc 

Can you share your trainer config file? It seems that there was an error reading it.

**Comment by avatcc** [comment]
I have copied them below. The interesting thing is I don't even have line 292 in my trainer_config.yaml
`default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

BananaLearning:
    normalize: false
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    max_steps: 1.0e5

BouncerLearning:
    normalize: true
    max_steps: 5.0e5
    num_layers: 2
    hidden_units: 64

PushBlockLearning:
    max_steps: 5.0e4
    batch_size: 128
    buffer_size: 2048
    beta: 1.0e-2
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 64
    num_layers: 2

SmallWallJumpLearning: 
    max_steps: 1.0e6
    batch_size: 128
    buffer_size: 2048
    beta: 5.0e-3
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 128
    num_layers: 2
    normalize: false

BigWallJumpLearning: 
    max_steps: 1.0e6
    batch_size: 128
    buffer_size: 2048
    beta: 5.0e-3
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 128
    num_layers: 2
    normalize: false

StrikerLearning:
    max_steps: 5.0e5
    learning_rate: 1e-3
    batch_size: 128
    num_epoch: 3
    buffer_size: 2000
    beta: 1.0e-2
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 128
    num_layers: 2
    normalize: false

GoalieLearning:
    max_steps: 5.0e5
    learning_rate: 1e-3
    batch_size: 320
    num_epoch: 3
    buffer_size: 2000
    beta: 1.0e-2
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 128
    num_layers: 2
    normalize: false

PyramidsLearning:
    use_curiosity: true
    summary_freq: 2000
    curiosity_strength: 0.01
    curiosity_enc_size: 256
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 1.0e-2
    max_steps: 5.0e5
    num_epoch: 3

VisualPyramidsLearning:
    use_curiosity: true
    curiosity_strength: 0.01
    curiosity_enc_size: 256
    time_horizon: 128
    batch_size: 64
    buffer_size: 2024
    hidden_units: 256
    num_layers: 1
    beta: 1.0e-2
    max_steps: 5.0e5
    num_epoch: 3

3DBallLearning:
    normalize: true
    batch_size: 64
    buffer_size: 12000
    summary_freq: 1000
    time_horizon: 1000
    lambd: 0.99
    gamma: 0.995
    beta: 0.001

3DBallHardLearning:
    normalize: true
    batch_size: 1200
    buffer_size: 12000
    summary_freq: 1000
    time_horizon: 1000
    max_steps: 5.0e5
    gamma: 0.995
    beta: 0.001

TennisLearning:
    normalize: true
    max_steps: 2e5

CrawlerStaticLearning:
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2024
    buffer_size: 20240
    gamma: 0.995
    max_steps: 1e6
    summary_freq: 3000
    num_layers: 3
    hidden_units: 512

CrawlerDynamicLearning:
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2024
    buffer_size: 20240
    gamma: 0.995
    max_steps: 1e6
    summary_freq: 3000
    num_layers: 3
    hidden_units: 512

WalkerLearning:
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2048
    buffer_size: 20480
    gamma: 0.995
    max_steps: 2e6
    summary_freq: 3000
    num_layers: 3
    hidden_units: 512

ReacherLearning:
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2024
    buffer_size: 20240
    gamma: 0.995
    max_steps: 1e6
    summary_freq: 3000

HallwayLearning:
    use_recurrent: true
    sequence_length: 64
    num_layers: 2
    hidden_units: 128
    memory_size: 256
    beta: 1.0e-2
    gamma: 0.99
    num_epoch: 3
    buffer_size: 1024
    batch_size: 128
    max_steps: 5.0e5
    summary_freq: 1000
    time_horizon: 64

VisualHallwayLearning:
    use_recurrent: true
    sequence_length: 64
    num_layers: 1
    hidden_units: 128
    memory_size: 256
    beta: 1.0e-2
    gamma: 0.99
    num_epoch: 3
    buffer_size: 1024
    batch_size: 64
    max_steps: 5.0e5
    summary_freq: 1000
    time_horizon: 64

VisualPushBlockLearning:
    use_recurrent: true
    sequence_length: 32
    num_layers: 1
    hidden_units: 128
    memory_size: 256
    beta: 1.0e-2
    gamma: 0.99
    num_epoch: 3
    buffer_size: 1024
    batch_size: 64
    max_steps: 5.0e5
    summary_freq: 1000
    time_horizon: 64

GridWorldLearning:
    batch_size: 32
    normalize: false
    num_layers: 1
    hidden_units: 256
    beta: 5.0e-3
    gamma: 0.9
    buffer_size: 256
    max_steps: 5.0e5
    summary_freq: 2000
    time_horizon: 5

BasicLearning:
    batch_size: 32
    normalize: false
    num_layers: 1
    hidden_units: 20
    beta: 5.0e-3
    gamma: 0.9
    buffer_size: 256
    max_steps: 5.0e5
    summary_freq: 2000
    time_horizon: 3

PenguinLearning:
    use_curiosity: true
	summary_freq: 5000
	time_horizon: 128
	batch_size: 128
	buffer_size: 2048
	hidden_units: 256
	beta: 1.0e-2
	max_steps: 1.0e6
`

**Comment by TiNovTec** [comment]
http://www.immersivelimit.com/tutorials/unity-ml-agents-penguins

**Comment by chriselion** [comment]
Hi @avatcc,
Any update on this? We should have some better reporting of errors like this in version 0.10.0. If you're still having problems with your yaml file, I'd suggest a tool like http://www.yamllint.com/ to validate the file.

**Comment by avatcc** [comment]
@chriselion Hi,
I tried another demo and it still has the same problem:
INFO:mlagents.trainers:CommandLineOptions(debug=False, num_runs=1, seed=-1, env_path=None, run_id='pig_tutorial_01', load_model=False, train_model=True, save_freq=50000, keep_checkpoints=5, base_port=5005, num_envs=1, curriculum_folder='config/curricula/pig/', lesson=0, slow=False, no_graphics=False, multi_gpu=False, trainer_config_path='config/trainer_config.yaml', sampler_file_path=None, docker_target_name=None, env_args=None)
Traceback (most recent call last):
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "c:\users\chenchet\ml-agents\ml-agents\mlagents\trainers\learn.py", line 417, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\chenchet\ml-agents\ml-agents\mlagents\trainers\learn.py", line 205, in run_training
    trainer_config = load_config(trainer_config_path)
  File "c:\users\chenchet\ml-agents\ml-agents\mlagents\trainers\trainer_util.py", line 117, in load_config
    return _load_config(data_file)
  File "c:\users\chenchet\ml-agents\ml-agents\mlagents\trainers\trainer_util.py", line 134, in _load_config
    return yaml.safe_load(fp)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "config/trainer_config.yaml", line 292, column 1

**Comment by chriselion** [comment]
Did you try the link I sent? Can you attach (don't copy and paste because it loses whitespace) your yaml file here?

**Comment by avatcc** [comment]
@chriselion  i fixed the problem thank you!

**Comment by chriselion** [comment]
Glad you got it working. Can I ask what the problem was? Anything we can to do make it easier to detect and fix in the future?

**Comment by avatcc** [comment]
@chriselion I think I was using tab instead of space in the trainer_config.yaml. Maybe if you could make a comment in the file, next time the user will know that they should use space in the yaml file
