### ISSUE TITLE
Getting null error on Play

### ISSUE THREAD

**Issue by kamicazer** [Unity-Technologies/ml-agents#2663]
I'm on the final step of getting started with the toolkit but I'm getting a null error for 'CommunicatorObjects.UnityInput input' when I press play, after anaconda runs "mlagents-learn config/trainer_config.yaml --run-id=firstRun --train".

I'm not able to figure out why.

```
NullReferenceException: Object reference not set to an instance of an object
MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at D:/DownloadsD/ml-agents-master/ml-agents-master/UnitySDK/Assets/ML-Agents/Scripts/Batcher.cs:96)
```

In the command log I am getting the following message:

```
mlagents.envs.exception.UnityEnvironmentException:  : .The API number is not compatible between Unity and python. Python API : API-10, Unity API
Please go to https://github.com/Unity-Technologies/ml-agents to download the latest version of ML-Agents.
Traceback (most recent call last):
  File "d:\anaconda\envs\ml-agents\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\envs\subprocess_env_manager.py", line 59, in recv
    response: EnvironmentResponse = self.conn.recv()
  File "d:\anaconda\envs\ml-agents\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "d:\anaconda\envs\ml-agents\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 417, in main
    run_training(0, run_seed, options, Queue())
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 219, in run_training
    options.sampler_file_path, env.reset_parameters, run_seed
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\envs\subprocess_env_manager.py", line 225, in reset_parameters
    return self.env_workers[0].recv().payload
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\envs\subprocess_env_manager.py", line 62, in recv
    raise UnityCommunicationException("UnityEnvironment worker: recv failed.")
mlagents.envs.exception.UnityCommunicationException: UnityEnvironment worker: recv failed
```

Seems like Unity API is empty, but I'm pretty sure I followed all the steps from the guide properly, anyone has any idea on what might be missing?

**Comment by ervteng** [comment]
Hi @kamicazer, have you added your Learning Brain into the Broadcast Hub (in Unity, under the Academy) and checked the Control checkbox? This occasionally happens if that's not checked.

**Comment by kamicazer** [comment]
Hi @ervteng , thank you for taking the time to answer.

Yes, I believe so
![image](https://user-images.githubusercontent.com/12896365/66156152-0856fc00-e619-11e9-814f-a885245b7d90.png)

this is the Ball3DAcademy gameobject inside the 3DBall scene.

**Comment by surfnerd** [comment]
`The API number is not compatible between Unity and python. Python API : API-10, Unity API`
Looks like you may need to update your UnitySDK.

**Comment by kamicazer** [comment]
spot on @surfnerd , that did the trick for me, sorry about taking up time. Have a nice one.

**Comment by surfnerd** [comment]
glad it worked for you @kamicazer! I'm going to close this issue.  Please reopen it if you run into this issue again.
