### ISSUE TITLE
Error when I tried to train 

### ISSUE THREAD

**Issue by avatcc** [Unity-Technologies/ml-agents#2681]
`(ml-agents) C:\Users\chenchet\ml-agents> mlagents-learn config/trainer_config.yaml --curriculum=config/curricula/pig/ --run-id=pig_tutorial_01 --train
Traceback (most recent call last):
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\Scripts\mlagents-learn-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 3241, in <module>
    @_call_aside
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mlagents' distribution was not found and is required by the application`

**Comment by smshehryar** [comment]
did you go through the installation of the mlagents properly and check that if it is installed?

**Comment by avatcc** [comment]
Hi @smshehryar 
Yes I doubled checked and I have a new issue now:
INFO:mlagents.trainers:CommandLineOptions(debug=False, num_runs=1, seed=-1, env_path=None, run_id='pig_tutorial_01', load_model=False, train_model=True, save_freq=50000, keep_checkpoints=5, base_port=5005, num_envs=1, curriculum_folder='config/curricula/pig/', lesson=0, slow=False, no_graphics=False, multi_gpu=False, trainer_config_path='config/trainer_config.yaml', sampler_file_path=None, docker_target_name=None, env_args=None)
Traceback (most recent call last):
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "c:\users\chenchet\ml-agents\ml-agents\mlagents\trainers\learn.py", line 417, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\chenchet\ml-agents\ml-agents\mlagents\trainers\learn.py", line 205, in run_training
    trainer_config = load_config(trainer_config_path)
  File "c:\users\chenchet\ml-agents\ml-agents\mlagents\trainers\trainer_util.py", line 117, in load_config
    return _load_config(data_file)
  File "c:\users\chenchet\ml-agents\ml-agents\mlagents\trainers\trainer_util.py", line 134, in _load_config
    return yaml.safe_load(fp)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\chenchet\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\yaml\scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "config/trainer_config.yaml", line 292, column 1

**Comment by smshehryar** [comment]
for this error seems like you need to check your trainer_config.yaml file for any problems with unfimiliar syntax or format.

**Comment by avatcc** [comment]
@smshehryar i fixed the problem! thank you!

**Comment by Rohit-v-raj** [comment]
> @smshehryar i fixed the problem! thank you!

how did u fix it?
