### ISSUE TITLE
Error starting Training

### ISSUE THREAD

**Issue by DuckLord25** [Unity-Technologies/ml-agents#2749]
Hi! I'm having an error while trying to train.
I'm following the ml-agents/docs/Basic-Guide.md tutorial.

Here's the output when I run 
`mlagents-learn config/trainer_config.yaml --run-id=firstRun --train`
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/mlagents-learn", line 7, in <module>
    from mlagents.trainers.learn import main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents/trainers/__init__.py", line 2, in <module>
    from .buffer import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents/trainers/buffer.py", line 3, in <module>
    from mlagents.envs.exception import UnityException
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents/envs/__init__.py", line 2, in <module>
    from .environment import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents/envs/environment.py", line 13, in <module>
    from .communicator_objects import UnityRLInput, UnityRLOutput, AgentActionProto, \
ImportError: cannot import name 'UnityRLInput'
```

Any help is _greatly_ appreciated!

p.s. Sorry I'm kind of a noob lol

**Comment by chriselion** [comment]
Hi @DuckLord25,
That's definitely strange. What version of ml-agents and ml-agents envs are you using? I'm pretty sure it's an older version based on how the imports are happening (we got rid of the `import *`'s before version 0.10.1). Can you try uninstalling both packages and reinstalling the latest versions?
