### ISSUE TITLE
no max steps, .nn file sometimes not created with Ctrl-C

### ISSUE THREAD

**Issue by mistermotomax** [Unity-Technologies/ml-agents#2750]
Environment:
- Windows 10]
- _ML-Agents version 0.8 (recent)
- Python 3.7
- TensorFlow 2.0.0
- Default installation as in the guide

Problem:
Max steps do not halt the process. I'm forced to use Ctrl-C to stop it, and then it sometimes produces the .nn file (3dBall), and sometimes not (Basic, FoodCollector). frozen_graph_def.pb gets created. The "deprecated" warnings are totally meaningless on my Mac, so I ignored this.

Here is the output after stopping the process:
```
INFO:mlagents.trainers: FoodCollectorLearning: FoodCollectorLearning: Step: 16000. Time Elapsed: 270.206 s Mean Reward: 0.050. Std of Reward: 0.805. Training.
UnityEnvironment worker: environment stopping.
INFO:mlagents.envs:Learning was interrupted. Please wait while the graph is generated.
WARNING:tensorflow:From c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tf_policy.py:212: The name tf.train.write_graph is deprecated. Please use tf.io.write_graph instead.

WARNING:tensorflow:From c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tf_policy.py:212: The name tf.train.write_graph is deprecated. Please use tf.io.write_graph instead.

INFO:mlagents.envs:Saved Model
INFO:mlagents.trainers:List of nodes to export for brain :FoodCollectorLearning
INFO:mlagents.trainers: is_continuous_control
INFO:mlagents.trainers: version_number
INFO:mlagents.trainers: memory_size
INFO:mlagents.trainers: action_output_shape
INFO:mlagents.trainers: action_probs
INFO:mlagents.trainers: action
WARNING:tensorflow:From c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tf_policy.py:225: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tf_policy.py:225: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\tensorflow_core\python\framework\graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
WARNING:tensorflow:From c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\tensorflow_core\python\framework\graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 12 variables.
INFO:tensorflow:Froze 12 variables.
INFO:tensorflow:Converted 12 variables to const ops.
INFO:tensorflow:Converted 12 variables to const ops.
Converting ./models/FoodCollectorLearning-0/FoodCollectorLearning/frozen_graph_def.pb to ./models/FoodCollectorLearning-0/FoodCollectorLearning.nn
WARNING:tensorflow:From c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tensorflow_to_barracuda.py:1538: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tensorflow_to_barracuda.py:1538: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

IGNORED: AddV2 unknown layer
IGNORED: AddV2 unknown layer
IGNORED: AddV2 unknown layer
IGNORED: AddV2 unknown layer
IGNORED: AddV2 unknown layer
Traceback (most recent call last):
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\users\xxx\Anaconda3\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 417, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 255, in run_training
    tc.start_learning(env)
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 219, in start_learning
    self._export_graph()
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 129, in _export_graph
    self.trainers[brain_name].export_model()
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer.py", line 152, in export_model
    self.policy.export_model()
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tf_policy.py", line 230, in export_model
    tf2bc.convert(frozen_graph_def_path, self.model_path + ".nn")
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tensorflow_to_barracuda.py", line 1552, in convert
    i_model, args
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tensorflow_to_barracuda.py", line 1397, in process_model
    process_layer(node, o_context, args)
  File "c:\users\xxx\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\tensorflow_to_barracuda.py", line 1220, in process_layer
    assert all_elements_equal(input_ranks)
AssertionError
```

**Comment by chriselion** [comment]
Hi @mistermotomax,
We're still in the process of enabling support for tensorflow 2.0. But we do have a fix for this particular conversion error; the fix was made on the `develop` branch here: https://github.com/Unity-Technologies/ml-agents/pull/2703

Can you try that out and let me know if it fixes things?

**Comment by mistermotomax** [comment]
That was quick, thanks! Now in this version, the academy doesn't have the "Control" checkbox, that was very intuitive in the recent version. I don't know how tell Python that I want to train. (I do research about it later but don't know it for now)

**Comment by chriselion** [comment]
Yeah, things have changed a lot in the last week weeks. The [migration guide](https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Migrating.md#important-changes) explains some of the changes, but it might be easiest to just cherry-pick that fix into a checkout of the 0.10.2 release branch instead.

**Comment by mistermotomax** [comment]
I'm sorry, cherrypicking didn't help (or I failed in doing it). I think I'll downgrade TensorFlow. Thanks for your effort, this is becoming an amazing piece of software!

**Comment by chriselion** [comment]
`git cherry-pick` might be too heavy-weight. It's a one-line change so you could probably just do it manually. But I can't guarantee that there won't be some other tensorflow 2.0 bugs (I still need to run more tests on my branch) so downgrading is probably best for now...
