### ISSUE TITLE
ModuleNotFoundError : No module named tensorflow.contrib

### ISSUE THREAD

**Issue by smkplus** [Unity-Technologies/ml-agents#2756]
![image](https://user-images.githubusercontent.com/16706911/67126100-29b40c80-f203-11e9-85d9-ffd41a547c8c.png)

**Comment by chriselion** [comment]
What version of tensorflow are you using? We don't support 2.0 yet (but hope to soon).

**Comment by smkplus** [comment]
tensorflow 2.0
oh ok thanks I will try again

**Comment by smkplus** [comment]
I installed tensorflow 1.4 but not work :(

```
(base) C:\Users\Smkgames>mlagents-learn config/trainer_config.yaml --run-id=firs
tRun --train
2019-10-19 08:55:22.995702: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64
_100.dll not found
2019-10-19 08:55:22.995922: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]
 Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-su
nset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



                        ___¦¦¦¦
                   +¦¦¦¦¦¦¦¦¦¦¦¦
              ,___m¯¯¯'  ,¦¦¦¯¦¦_                           ¦¦¦  ¦¦¦
            _¦¦¦¯'      _¦¦¯  ¦¦¦      __     __ ,__ ____   ,__ _¦¦¦_ ___    ,__

          _¦¦¦¯        _¦¦¯   ¦¦¦¦     ¦¦¦   ¦¦¦ ¦¦¦¦¯¯¯¦¦¦ ¦¦¦ ¯¦¦¦¯ ^¦¦¦  +¦¦¦

        _¦¦¦¦¦________¦¦¦      ¦¯      ¦¦¦   ¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦   ¦¦¦_ ¦¦¦
        ¯¦¦¦¦¯¯¯¯¯¯¯¯¯¯¦¦_     ¦¦      ¦¦¦   ¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦    ¦¦¦¦¦¦
          ^¦¦¦¦        ¯¦¦_   ¦¦¦¦     ¦¦¦¦_¦¦¦¦ ¦¦¦    ¦¦¦ ¦¦¦  ¦¦¦_    ¦¦¦¦`
            '¯¦¦¦_      ^¦¦¦  ¦¦¦       +¯¯¯¯ ¯¯ ^¯¯    `¯¯ `¯¯   '¯¯    ¦¦¦¦
               ¯¯¯¯¦___   ¦¦¦¦¦¦,                                      ¦¦¦¦¯
                   `¯¦¦¦¦¦¦¦¦¦¦¦
                        ¬`¯¯¯¦¦


INFO:mlagents.trainers:CommandLineOptions(debug=False, num_runs=1, seed=-1, env_
path=None, run_id='firstRun', load_model=False, train_model=True, save_freq=5000
0, keep_checkpoints=5, base_port=5005, num_envs=1, curriculum_folder=None, lesso
n=0, slow=False, no_graphics=False, multi_gpu=False, trainer_config_path='config
/trainer_config.yaml', sampler_file_path=None, docker_target_name=None, env_args
=None)
Traceback (most recent call last):
  File "d:\programfiles\anaconda3\lib\site-packages\mlagents\trainers\trainer_ut
il.py", line 116, in load_config
    with open(config_path) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/trainer_config.y
aml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programfiles\anaconda3\lib\runpy.py", line 193, in _run_module_as_mai
n
    "__main__", mod_spec)
  File "d:\programfiles\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramFiles\Anaconda3\Scripts\mlagents-learn.exe\__main__.py", line
7, in <module>
  File "d:\programfiles\anaconda3\lib\site-packages\mlagents\trainers\learn.py",
 line 417, in main
    run_training(0, run_seed, options, Queue())
  File "d:\programfiles\anaconda3\lib\site-packages\mlagents\trainers\learn.py",
 line 205, in run_training
    trainer_config = load_config(trainer_config_path)
  File "d:\programfiles\anaconda3\lib\site-packages\mlagents\trainers\trainer_ut
il.py", line 120, in load_config
    f"Config file could not be found at {config_path}."
mlagents.envs.exception.UnityEnvironmentException: Config file could not be foun
d at config/trainer_config.yaml.
```

**Comment by smkplus** [comment]
![image](https://user-images.githubusercontent.com/16706911/67140870-8fd47a00-f26b-11e9-941a-5061cbd0dc3d.png)


Please help me

**Comment by chriselion** [comment]
Hi,
That version of tensorflow should be OK (although 1.14 is the highest that we've tested with currently).

The main problem right now is this:
```
FileNotFoundError: [Errno 2] No such file or directory: 'config/trainer_config.yaml'
```
You need specify a valid file in the commandline. If you cloned ml-agents from github, the file should be in the config directory; otherwise you can get it from here: https://github.com/Unity-Technologies/ml-agents/blob/master/config/trainer_config.yaml

**Comment by smkplus** [comment]
@chriselion Hi that's right my path was wrong!
but I have new problem that I reported as a new bug

![image](https://user-images.githubusercontent.com/16706911/67163287-ffd12600-f379-11e9-9425-8fe76c1d63b7.png)

**Comment by chriselion** [comment]
Let's continue the discussion in https://github.com/Unity-Technologies/ml-agents/issues/2763
