### ISSUE TITLE
UnityAgentsException: "The number of states does not match for agent: Was expecting 1 continuous states but received 0."

### ISSUE THREAD

**Issue by nicolasjulioflores** [Unity-Technologies/ml-agents#282]
I think this is a fairly basic error, but I can't seem to understand why it is occurring. I was able to run my program before without issue, but after adding a few things to the environment and then rebuilding, I ran into this issue. I am trying to use an 'external' Brain. **I will be monitoring the issue, so please ask if you want more information**. Here is the full error: 

`
Exception
UnityAgentsException: The number of states does not match for agent BalanceAgent:
Was expecting 1 continuous states but received 0.
Brain.CollectStates ()
ExternalCommunicator.giveBrainInfo (.Brain brain)
CoreBrainExternal.SendState ()
Brain.SendState ()
Academy.SendState ()
Academy.Step ()
Academy.RunMdp ()
Academy.FixedUpdate ()

ERROR:unityagents:An error might have occured in the environment. You can check the logfile for more information at C:\Users\Nick2\Documents\Machine Learning\Research\Unity\BalanceBallML\python/unity-environment.log
Traceback (most recent call last):
  File "C:\Users\Nick2\Anaconda3\lib\site-packages\unityagents\environment.py", line 205, in _recv_bytes
    s = self._conn.recv(self._buffer_size)
socket.timeout: timed out
`

and here is the traceback:

`
Traceback (most recent call last):
  File "Q_Learn_Ball_Balance.py", line 13, in <module>
    ENV.reset(False, config=None)
  File "C:\Users\Nick2\Anaconda3\lib\site-packages\unityagents\environment.py", line 266, in reset
    return self._get_state()
  File "C:\Users\Nick2\Anaconda3\lib\site-packages\unityagents\environment.py", line 277, in _get_state
    state_dict = self._get_state_dict()
  File "C:\Users\Nick2\Anaconda3\lib\site-packages\unityagents\environment.py", line 230, in _get_state_dict
    state = self._recv_bytes().decode('utf-8')
  File "C:\Users\Nick2\Anaconda3\lib\site-packages\unityagents\environment.py", line 211, in _recv_bytes
    raise UnityTimeOutException("The environment took too long to respond.", self._log_path)
unityagents.exception.UnityTimeOutException: The environment took too long to respond.
`

**Comment by LeSphax** [comment]
Hello, I am having the same problem when using ppo.py directly instead of the jupyter notebook. How did you manage to solve it?
