### ISSUE TITLE
Environment unable to start when setting use_recurrent to true

### ISSUE THREAD

**Issue by migberbay** [Unity-Technologies/ml-agents#3002]
Hi I'm trying to train a turn based rpg-like battle between 2 agents, and i want them to be able to have memory for them to be able to know if certain events happened (for example i have used my health and mana potions this instance so using it again doesnt help.)

The thing is that whenever I set use_recurrent: true in the trainer .yaml file and try to train the environment i get the following stack trace:

```
INFO:mlagents.trainers:{'--base-port': '5005',
 '--curriculum': 'None',
 '--debug': False,
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--multi-gpu': False,
 '--no-graphics': False,
 '--num-envs': '1',
 '--num-runs': '1',
 '--run-id': 'rpgtestrecurrent',
 '--sampler': 'None',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '<trainer-config-path>': 'config/trainer_config.yaml'}
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
INFO:mlagents.envs:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 2
        Number of Training Brains : 2
        Reset Parameters :

Unity brain name: BossLearningBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 10
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [3]
        Vector Action descriptions: actions
Unity brain name: PlayerLearningBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 10
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [7]
        Vector Action descriptions: actions
2019-11-30 19:46:00.329198: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
INFO:mlagents.envs:Hyperparameters for the PPOTrainer of brain BossLearningBrain:
        use_recurrent:  True
        sequence_length:        64
        memory_size:    256
        trainer:        ppo
        batch_size:     1024
        beta:   0.005
        buffer_size:    10240
        epsilon:        0.2
        hidden_units:   128
        lambd:  0.95
        learning_rate:  0.0003
        max_steps:      20000
        normalize:      False
        num_epoch:      10
        num_layers:     2
        time_horizon:   64
        summary_freq:   2000
        vis_encode_type:        simple
        reward_signals:
          extrinsic:
            strength:   1.0
            gamma:      0.99
        summary_path:   ./summaries/rpgtestrecurrent_BossLearningBrain
        model_path:     ./models/rpgtestrecurrent-0/BossLearningBrain
        keep_checkpoints:       5
INFO:mlagents.envs:Hyperparameters for the PPOTrainer of brain PlayerLearningBrain:
        use_recurrent:  True
        sequence_length:        64
        memory_size:    256
        trainer:        ppo
        batch_size:     1024
        beta:   0.005
        buffer_size:    10240
        epsilon:        0.2
        hidden_units:   128
        lambd:  0.95
        learning_rate:  0.0003
        max_steps:      20000
        normalize:      False
        num_epoch:      10
        num_layers:     2
        time_horizon:   64
        summary_freq:   2000
        vis_encode_type:        simple
        reward_signals:
          extrinsic:
            strength:   1.0
            gamma:      0.99
        summary_path:   ./summaries/rpgtestrecurrent_PlayerLearningBrain
        model_path:     ./models/rpgtestrecurrent-0/PlayerLearningBrain
        keep_checkpoints:       5
Traceback (most recent call last):
  File "c:\users\magic mike\.conda\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\magic mike\.conda\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Magic Mike\.conda\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\magic mike\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 337, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\magic mike\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 132, in run_training
    tc.start_learning(env)
  File "c:\users\magic mike\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 202, in start_learning
    n_steps = self.advance(env_manager)
  File "c:\users\magic mike\.conda\envs\ml-agents\lib\site-packages\mlagents\envs\timers.py", line 261, in wrapped
    return func(*args, **kwargs)
  File "c:\users\magic mike\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 279, in advance
    step_info.brain_name_to_action_info[brain_name].outputs,
  File "c:\users\magic mike\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\rl_trainer.py", line 152, in add_experiences
    curr_to_use = self.construct_curr_info(next_info)
  File "c:\users\magic mike\.conda\envs\ml-agents\lib\site-packages\mlagents\trainers\rl_trainer.py", line 103, in construct_curr_info
    memories = np.vstack(memories)
  File "c:\users\magic mike\.conda\envs\ml-agents\lib\site-packages\numpy\core\shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate

```

I've tried to reproduce this behaviour with the examples scenes provided but I cannot get it to do it.

Here is some of the scripts that are in play on the scene:
-The academy is empty.
```
public class BossAgent : Agent{
    //Variables
    public float bossHealth;
    public float bossMana;
    public float playerMana;
    public float playerHealth;
    public float playerArmor;
    public float playerMagicRes;
    public float bossArmor;
    public float bossMagicRes;
    public bool playerUsedHealthPot;
    public bool playerUsedManaPot;

    //enviroment;
    public BossDataContainerTraining boss;
    public PlayerDataContainerTraining player;

    public override void AgentReset(){
        boss.health = 600;
        boss.mana = 200;
        boss.physicalDefense = 1;
        boss.magicDefense = 1;
        boss.buffduration[0] = 0;
    }

     public override void CollectObservations(){
        //to be implemented.
        bossHealth = boss.health;
        bossMana = boss.mana;
        bossMagicRes = boss.magicDefense;
        bossArmor = boss.physicalDefense;
        playerHealth = player.health;
        playerMana = player.mana;
        playerArmor = player.physicalDefense;
        playerMagicRes = player.magicDefense;
        List<float> observations = new List<float> {bossHealth, bossMana, bossMagicRes, bossArmor, playerMana, playerHealth, playerArmor, playerMagicRes};
        AddVectorObs(observations);
        AddVectorObs(playerUsedHealthPot);
        AddVectorObs(playerUsedManaPot);
        
    }

    public override void AgentAction(float[] vectorAction, string textAction){
        Debug.Log("boss chosen action: "+ Mathf.FloorToInt(vectorAction[0]));
        boss.ExecuteAction(Mathf.FloorToInt(vectorAction[0]));
        if(playerHealth <= 0 || bossHealth <= 0){
            if(playerHealth <= 0){
                SetReward(1);
            }
            if(bossHealth <= 0){
                SetReward(0);
            }
            Done();
        }else{
            SetReward(CalculateReward());
        }
    }
        
    private float CalculateReward(){
        return ((bossHealth/600) - (playerHealth/100));
    }
}
```
There is a playerAgent as well with similar code and here is the execute action code:
```
  public void ExecuteAction (int actionId){
        applyBuffs();
        reduceBuffDuration();
        string action = actions[actionId];
        chosenAction = actionId;
        //Debug.Log("chosen action: "+ action);
        chat.addMesage("You used "+ action);
        //Debug.Log("requesting decision from Boss");
        bossAgent.RequestDecision();
        boss.updateBoss();
        switch (action){
            case "attack":
            //isDamaged, useSkill, attack, dies
                animationController.PlayerAnimations("attack");
                boss.applyDamage(30,0);                
            break;
            case "fireball":
            if(mana >= 30){
                animationController.PlayerAnimations("attack");
                boss.applyDamage(0,50);
                mana -= 30;
            }else{
                animationController.PlayerAnimations("attack");
                chat.addMesage("You tried to use "+ action +" but not enough mana so attack instead");
                boss.applyDamage(0,30);
            }
                
            break;
            case "magicShield":
            if(mana >= 20){
                animationController.PlayerAnimations("useSkill");
                updateBuffs("magic shield",4);
                mana -= 20;
            }else{
                animationController.PlayerAnimations("attack");
                chat.addMesage("You tried to use "+ action +" but not enough mana so attack instead");
                boss.applyDamage(0,30);
            }
            break;
            case "ironclad":
            if(mana >= 20){
                animationController.PlayerAnimations("useSkill");
                updateBuffs("ironclad",4);
                mana -= 20;
            }else{
                animationController.PlayerAnimations("attack");
                chat.addMesage("You tried to use "+ action +" but not enough mana so attack instead");
                boss.applyDamage(0,30);
            }
            break;
            case "defend":
                animationController.PlayerAnimations("useSkill");
                updateBuffs("defend",2);
            break;
            case "healthPotion":
            if(!healthPotUsed){
                 health = 100;
                 healthPotUsed = true;
            }
                chat.addMesage("You tried to use "+ action +" but you're out so attack instead");
                boss.applyDamage(0,30);
                //controller.DisablePotionButton("health");
            break;
            case "manaPotion":
            if(!manaPotUsed){
                mana = 100;
                healthPotUsed = true;
            }
                chat.addMesage("You tried to use "+ action +" but you're out so attack instead");
                boss.applyDamage(0,30);
                //controller.DisablePotionButton("mana");
            break;
        }
        updatePlayer();
        boss.updateBoss();
        playerAgent.nextActionReady = true;
    }
```
these are both the brains used in the agents:
![image](https://user-images.githubusercontent.com/19336405/69905027-ac0d2000-13ae-11ea-8072-8aa912ddd7fa.png)

![image](https://user-images.githubusercontent.com/19336405/69905034-b9c2a580-13ae-11ea-8e62-9f38c94e8411.png)

Enviroment:
- OS + version: Windows 10
- _ML-Agents version_: whichever was in effect september of 2019
- _TensorFlow version_: 1.7.1
- _Environment_: custom environment.

**Comment by unityjeffrey** [comment]
hi @migberbay - does training work when you set use_recurrent to false (or remove it)?

**Comment by migberbay** [comment]
> hi @migberbay - does training work when you set use_recurrent to false (or remove it)?

Hi @unityjeffrey, yes it does train normally if use_recurrent is set to false or not present.

**Comment by migberbay** [comment]
Hi again @unityjeffrey, Its been a while and i guess you're very busy but i was hoping to know if there has been anything helpful regarding this topic. Thanks.

**Comment by vincentpierre** [comment]
Hi @migberbay 
Do you still have this issue? Do you still observe it in more recent versions of ML-Agents?

**Comment by miguel-bermudo** [comment]
Hi, It is not happening anymore, this was a pre-release issue

**Comment by maryamhonari** [comment]
Thanks, Closing the issue for now.
