### ISSUE TITLE
Issue connecting unity

### ISSUE THREAD

**Issue by wightwhale** [Unity-Technologies/ml-agents#3009]
Hey does anyone know how to fix this error? I moved a project to a new computer and now I'm having trouble getting the connection to work.
```
(ml-agents9) D:\Documents\GitHub\ml-agents>mlagents-learn config/trainer_config.yaml --run-id=orbit_0 --train
2019-12-02 10:15:35.768195: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2019-12-02 10:15:35.779365: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓


INFO:mlagents.trainers:CommandLineOptions(debug=False, num_runs=1, seed=-1, env_path=None, run_id='orbit_0', load_model=False, train_model=True, save_freq=50000, keep_checkpoints=5, base_port=5005, num_envs=1, curriculum_folder=None, lesson=0, slow=False, no_graphics=False, multi_gpu=False, trainer_config_path='config/trainer_config.yaml', sampler_file_path=None, docker_target_name=None, env_args=None, cpu=False)
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
Process Process-1:
Traceback (most recent call last):
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\site-packages\mlagents\envs\subprocess_env_manager.py", line 82, in worker
    env = env_factory(worker_id)
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\site-packages\mlagents\trainers\learn.py", line 359, in create_unity_environment
    args=env_args,
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\site-packages\mlagents\envs\environment.py", line 105, in __init__
    aca_output = self.send_academy_parameters(rl_init_parameters_in)
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\site-packages\mlagents\envs\environment.py", line 689, in send_academy_parameters
    return self.communicator.initialize(inputs)
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\site-packages\mlagents\envs\rpc_communicator.py", line 88, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Agents are linked to the appropriate Brains
         The environment and the Python interface have compatible versions.
Traceback (most recent call last):
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\site-packages\mlagents\envs\subprocess_env_manager.py", line 59, in recv
    response: EnvironmentResponse = self.conn.recv()
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ww31785\AppData\Local\Continuum\anaconda3\envs\ml-agents9\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\site-packages\mlagents\trainers\learn.py", line 408, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\site-packages\mlagents\trainers\learn.py", line 222, in run_training
    options.sampler_file_path, env.reset_parameters, run_seed
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\site-packages\mlagents\envs\subprocess_env_manager.py", line 225, in reset_parameters
    return self.env_workers[0].recv().payload
  File "c:\users\ww31785\appdata\local\continuum\anaconda3\envs\ml-agents9\lib\site-packages\mlagents\envs\subprocess_env_manager.py", line 62, in recv
    raise UnityCommunicationException("UnityEnvironment worker: recv failed.")
mlagents.envs.exception.UnityCommunicationException: UnityEnvironment worker: recv failed.
```

**Comment by robinerd** [comment]
Strange.. There was a similar issue just a few days ago, #2981

**Comment by unityjeffrey** [comment]
hi all - we are taking a look.

**Comment by unityjeffrey** [comment]
hi - we think the problem is that we switched the port for training in 0.11.  And if you had a version mismatch between the C# SDK and Python, it would never hit this error because of the port change.

Can you make sure both the C# code and Python code is updated using the same version and see if that fixes your issue?

**Comment by wightwhale** [comment]
I have now updated to the latest versions and verified the files and both reports v12. However my anaconda environment wont connect to unity still. I downloaded the latest version of unity 2019.2.15f1 as well.

**Comment by wightwhale** [comment]
I've discovered this is probably proxy related. I'm behind a corporate proxy and it's causing all kinds of issues with package manager currently and it seems to interfere with the newer implementation of ml agents. I see you mentioned changing the port, do you think this could have to do with my new issue. I was operating on lower <.10 version of ml-agents without this issue. 
I noticed in your docs 

Cause: You have assigned HTTP_PROXY and HTTPS_PROXY values in your environment variables. Solution: Remove these values and try again.

However these values are suggested to be enabled for the package manager and unity hub.

Configuring your proxy server
When using a proxy server, configure the HTTP_PROXY and HTTPS_PROXY environment variables for the Unity Package Manager to use when performing requests against the Unity package registry.
https://docs.unity3d.com/Manual/upm-network.html
