### ISSUE TITLE
'pkg_resources.VersionConflict' - when using tensorboard 

### ISSUE THREAD

**Issue by Xavier-KS-WDS** [Unity-Technologies/ml-agents#3459]
**Describe the bug**
The bug happens happens at when I try to type in the command:'tensorboard --logdir=summaries --port=6006'

**Console logs / stack traces**
Traceback (most recent call last):
  File "D:\01 Working Softwares\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\01 Working Softwares\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\34388\python-envs\sample-env\Scripts\tensorboard.exe\__main__.py", line 7, in <module>
  File "c:\users\34388\python-envs\sample-env\lib\site-packages\tensorboard\main.py", line 59, in run_main
    default.get_plugins() + default.get_dynamic_plugins(),
  File "c:\users\34388\python-envs\sample-env\lib\site-packages\tensorboard\default.py", line 110, in get_dynamic_plugins
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "c:\users\34388\python-envs\sample-env\lib\site-packages\tensorboard\default.py", line 110, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "c:\users\34388\python-envs\sample-env\lib\site-packages\pkg_resources\__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "c:\users\34388\python-envs\sample-env\lib\site-packages\pkg_resources\__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "c:\users\34388\python-envs\sample-env\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (setuptools 40.6.2 (<Local>\python-envs\sample-env\lib\site-packages), Requirement.parse('setuptools>=41.0.0'))

**Environment (please complete the following information):**
- OS + version: Win 10
- _ML-Agents version_: ML-Agents v0.14.0
- _TensorFlow version_: 2.0.1

Please help me with the issue..

**Comment by chriselion** [comment]
Could you please post this on the Unity forums? We're trying to keep questions related to installation (like this one) there instead of on Github.

**Comment by Xavier-KS-WDS** [comment]
@chriselion Sure! I will close it for now.

**Comment by chriselion** [comment]
Thanks, I'll keep an eye out for it, but feel free to link to the forum thread here too.
