### ISSUE TITLE
Problem loading demo file recorded with 14.1

### ISSUE THREAD

**Issue by JimZeeKing** [Unity-Technologies/ml-agents#3655]
Hello,

I get an error when trying pressing play and trying to play a demo file to train my agent.

**Console logs / stack traces**
```
TypeError: float() argument must be a string or a number, not 'google.protobuf.pyext._message.RepeatedScalarContainer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 479, in main
    run_cli(parse_command_line())
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 475, in run_cli
    run_training(run_seed, options)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 320, in run_training
    tc.start_learning(env_manager)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 213, in start_learning
    self._create_trainers_and_managers(env_manager, new_behavior_ids)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 200, in _create_trainers_and_managers
    self._create_trainer_and_manager(env_manager, behavior_id)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 180, in _create_trainer_and_manager
    policy = trainer.create_policy(env_manager.external_brains[name_behavior_id])
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 240, in create_policy
    self.load,
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\ppo\policy.py", line 51, in __init__
    self.create_reward_signals(reward_signal_configs)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\ppo\policy.py", line 136, in create_reward_signals
    self, self.model, reward_signal, config
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\components\reward_signals\reward_signal_factory.py", line 44, in create_reward_signal     
    class_inst = rcls(policy, policy_model, **config_entry)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\components\reward_signals\gail\signal.py", line 48, in __init__
    _, self.demonstration_buffer = demo_to_buffer(demo_path, policy.sequence_length)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents_envs\timers.py", line 262, in wrapped
    return func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\demo_loader.py", line 89, in demo_to_buffer
    demo_buffer = make_demo_buffer(info_action_pair, group_spec, sequence_length)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents_envs\timers.py", line 262, in wrapped
    return func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\demo_loader.py", line 69, in make_demo_buffer
    demo_processed_buffer, batch_size=None, training_length=sequence_length
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\buffer.py", line 283, in resequence_and_append
    batch_size=batch_size, training_length=training_length
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\buffer.py", line 106, in get_batch
    dtype=np.float32,
ValueError: setting an array element with a sequence.
```

**Screenshots**
What's weird is that my recorded file shows the wrong vector observation number in the inspector : 
![image](https://user-images.githubusercontent.com/19315887/77029650-a6921080-6972-11ea-8166-d0e6965a94e6.png)
When i have in fact 14 : 
![image](https://user-images.githubusercontent.com/19315887/77029700-cfb2a100-6972-11ea-89df-9c575946f06d.png)

**Environment:**
- Windows 10 19
- ML-Agents version_: 14.1
- TensorFlow version_: 2.0.1

**Comment by ervteng** [comment]
Hi @JimZeeKing, can you send us the Protobuf demo file that is causing the issue? If you don't feel comfortable attaching it here you can send it to ml-agents at unity3d.com.

Does the same issue happen when recording and using demos from the example environments? I'd try 3d ball as that seems the most similar.

**Comment by JimZeeKing** [comment]
@ervteng  I'll try with example as soon as i can. Meanwhile, here is the demo file :
[ScrollerJim4.zip](https://github.com/Unity-Technologies/ml-agents/files/4359425/ScrollerJim4.zip)

**Comment by moonsh** [comment]
@JimZeeKing  I faced the same error. Did you find a solution ?

**Comment by ervteng** [comment]
Closing this issue due to inactivity. If you're still having problems, feel free to post in the [Unity Forums](https://forum.unity.com/forums/ml-agents.453/) or repost the issue.
