### ISSUE TITLE
problems when installing on MacOS

### ISSUE THREAD

**Issue by buboprog** [Unity-Technologies/ml-agents#3682]
Hi, I'm a newbie,
I am following the steps in this documentation for the Unity + mlagents installation, but I have a problem specifically in the next step:
`mlagents-learn <trainer-config-path> --run-id=<run-identifier> --train`

The terminal returns

-bash: trainer-config-path: No such file or directory

___

and if I run

`mlagents-learn config/trainer_config.yaml --run-id=firstRun --train`

The terminal returns

WARNING:tensorflow:From /Users/macos/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/compat/v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/Users/macos/opt/anaconda3/lib/python3.7/site-packages/mlagents/trainers/trainer_util.py", line 170, in load_config
    with open(config_path) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/trainer_config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macos/opt/anaconda3/bin/mlagents-learn", line 8, in <module>
    sys.exit(main())
  File "/Users/macos/opt/anaconda3/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 495, in main
    run_cli(parse_command_line())
  File "/Users/macos/opt/anaconda3/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 242, in parse_command_line
    return RunOptions.from_argparse(args)
  File "/Users/macos/opt/anaconda3/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 215, in from_argparse
    argparse_args["trainer_config"] = load_config(trainer_config_path)
  File "/Users/macos/opt/anaconda3/lib/python3.7/site-packages/mlagents/trainers/trainer_util.py", line 174, in load_config
    raise TrainerConfigError(f"Config file could not be found at {abs_path}.")
mlagents.trainers.exception.TrainerConfigError: Config file could not be found at /Users/macos/config/trainer_config.yaml.
______________________

**Environment**
- MacOS Mojave 10.14.3
- mlagents 0.15.0
- Tensorflow 2.1.0
- Python 3.7.6
- conda 4.8.3

______________________

Within Unity, trained agents work fine, but I can't get to the step to train "3dBall"

**Comment by buboprog** [comment]
I have fixed it, the problem was with the path
**config/trainer_config.yaml**

instead, I manually searched for the file and dragged it to the terminal for a correct path, being as follows:
`mlagents-learn /Users/macos/ml-agents/config/trainer_config.yaml --run-id=firstRun --train`

3DBall was trained! (I struggled for days with this problem)

thanks
