### ISSUE TITLE
Generalized Reinforcement Learning Agents Crashing

### ISSUE THREAD

**Issue by sniffle6** [Unity-Technologies/ml-agents#3686]
**Describe the bug**
When I create a new project, currently using a project very similar to this one [here](https://github.com/Unity-Technologies/ml-agents/blob/0.15.0/docs/Learning-Environment-Create-New.md) , and try to do a --sampler=config/mySample.yaml 99% of the time it crashes on the first resample. I can get the value no problem on start and all the way up to the first resample, then it crashes and my cmd displays the following
. It seemed to stop doing it when I removed the Heuristic method, but then after 2 or 3 runs, it started crashing again.

![image](https://user-images.githubusercontent.com/25136904/77507770-75688300-6e3f-11ea-9940-87a3adace3e6.png)

**To Reproduce**
1. Create a new project outside ML_Agents folder (the premade projects seem to work fine)
2. Add a new Agent scrip (can just use the project in the previous link)
3. *optional* add `Academy.Instance.FloatProperties.GetPropertyWithDefault("floor", 1f)` to `Initialize` and `OnEpisodeBegin`
4. use the command to start training 
`mlagents-learn config/trainer_config.yaml --sampler=config/ballroller_gerneral.yaml --run-id=MultiPlat_01 --train`

**Console logs / stack traces**
```
Traceback (most recent call last):
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sniff\anaconda3\envs\ml-agents_v15\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents\trainers\learn.py", line 495, in main
    run_cli(parse_command_line())
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents\trainers\learn.py", line 491, in run_cli
    run_training(run_seed, options)
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents\trainers\learn.py", line 329, in run_training
    tc.start_learning(env_manager)
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents_envs\timers.py", line 258, in wrapped
    return func(*args, **kwargs)
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents\trainers\trainer_controller.py", line 210, in start_learning
    self.reset_env_if_ready(env_manager, global_step)
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents\trainers\trainer_controller.py", line 261, in reset_env_if_ready
    self.end_trainer_episodes(env, lessons_incremented)
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents\trainers\trainer_controller.py", line 227, in end_trainer_episodes
    self._reset_env(env)
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents_envs\timers.py", line 258, in wrapped
    return func(*args, **kwargs)
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents\trainers\trainer_controller.py", line 142, in _reset_env
    env.reset(config=sampled_reset_param)
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents\trainers\env_manager.py", line 54, in reset
    manager.end_episode()
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents\trainers\agent_processor.py", line 205, in end_episode
    self._clean_agent_data(_gid)
  File "c:\users\sniff\anaconda3\envs\ml-agents_v15\lib\site-packages\mlagents\trainers\agent_processor.py", line 184, in _clean_agent_data
    del self.episode_rewards[global_id]
KeyError: '$0-56'
```

**Screenshots**
ballroller_gerneral.yaml
![image](https://user-images.githubusercontent.com/25136904/77508129-50284480-6e40-11ea-8420-79c577c7342f.png)

**Environment (please complete the following information):**
- OS + version:  Windows 10
- _ML-Agents version_: v15
- _TensorFlow version_: 2.0.1
- _Environment_: Error doesn't persist in the premade projects, make the project from the provided link that is inside the documents. The simple ball roller project and do it outside the ML_Agents folder

**Comment by surfnerd** [comment]
Hey @sniffle6, 
Could you try this on master?  It may be fixed there.  There will be a hotfix release coming soon.

**Comment by sniffle6** [comment]
It seems to be fine on the master branch
