### ISSUE TITLE
Docker build error: pip out of date

### ISSUE THREAD

**Issue by JoachimVeulemans** [Unity-Technologies/ml-agents#3880]
**Describe the bug**
Building the Dockerfile produces and error because pip is not up to date.

**To Reproduce**
1. docker build -t mlagents .

**Console logs / stack traces**
```
Step 15/20 : RUN pip install -e .
 ---> Running in fdc05b614c43
Obtaining file:///ml-agents-envs
Collecting cloudpickle (from mlagents-envs==0.14.1)
  Downloading https://files.pythonhosted.org/packages/ae/09/b3f6458d134f1ce597e1db52f09d0fa499c87ba789093c7e043f9caba92a/cloudpickle-1.4.0-py3-none-any.whl
Collecting grpcio>=1.11.0 (from mlagents-envs==0.14.1)
  Downloading https://files.pythonhosted.org/packages/cf/7a/9744998129fce7e29c5f2d8b0f545913b7383e65d8366fc0ae98d11936af/grpcio-1.28.1.tar.gz (19.5MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-adkcrk_h/grpcio/setup.py", line 191, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-build-adkcrk_h/grpcio/setup.py", line 152, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cc': 'cc'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-adkcrk_h/grpcio/
You are using pip version 9.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install -e .' returned a non-zero code: 1
```

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents versions: ML-Agents v0.15.1

**Proposed solution:**
Updating pip by inserting
```
# Upgrade pip to latest version
RUN pip install --upgrade pip
```
on line 125 & 126 in `Dockerfile`.

**Comment by anupambhatnagar** [comment]
@JoachimVeulemans If you would like to use a docker image with the latest version of ML-Agents, you can use [this](https://github.com/Unity-Technologies/ml-agents/blob/develop-dockerfile/ml-agents.Dockerfile) Dockerfile. The command to build the file is given at the bottom of the file. I would like to hear your feedback on it.

**Comment by JoachimVeulemans** [comment]
@anupambhatnagar I have made my suggestions on the [PR#3900](https://github.com/Unity-Technologies/ml-agents/pull/3900). I hope you find them useful.
