### ISSUE TITLE
Trainer Config Errors when Running mlagents-learn. Any Advice?

### ISSUE THREAD

**Issue by tailzdafox** [Unity-Technologies/ml-agents#4028]
I have been following the tutorials for training with a built executable scene, but I am getting the following errors:

Traceback (most recent call last):
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\site-packages\mlagents\trainers\trainer_controller.py", line 175, in _create_trainer_and_manager
    trainer = self.trainers[brain_name]
KeyError: '3DBall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tailz\Anaconda3\envs\tensorflow-gpu\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\site-packages\mlagents\trainers\learn.py", line 554, in main
    run_cli(parse_command_line())
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\site-packages\mlagents\trainers\learn.py", line 550, in run_cli
    run_training(run_seed, options)
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\site-packages\mlagents\trainers\learn.py", line 407, in run_training
    tc.start_learning(env_manager)
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\site-packages\mlagents\trainers\trainer_controller.py", line 227, in start_learning
    self._create_trainers_and_managers(env_manager, new_behavior_ids)
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\site-packages\mlagents\trainers\trainer_controller.py", line 213, in _create_trainers_and_managers
    self._create_trainer_and_manager(env_manager, behavior_id)
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\site-packages\mlagents\trainers\trainer_controller.py", line 177, in _create_trainer_and_manager
    trainer = self.trainer_factory.generate(brain_name)
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\site-packages\mlagents\trainers\trainer_util.py", line 61, in generate
    self.multi_gpu,
  File "c:\users\tailz\anaconda3\envs\tensorflow-gpu\lib\site-packages\mlagents\trainers\trainer_util.py", line 100, in initialize_trainer
    f'Trainer config must have either a "default" section, or a section for the brain name ({brain_name}). '
mlagents.trainers.exception.TrainerConfigError: Trainer config must have either a "default" section, or a section for the brain name (3DBall). See config/trainer_config.yaml for an example.

While troubleshooting I found I was on version 0.16 of mlagents, so I have tried switching to 0.17.
![image](https://user-images.githubusercontent.com/8409745/83029745-edfbe380-a02a-11ea-8e2d-77cf126b5c25.png)

However, even though pip3 list shows that 0.17 is installed and that 0.16 is successfully uninstalled, mlagents-learn shows that it's still using 0.16:
![image](https://user-images.githubusercontent.com/8409745/83029865-108dfc80-a02b-11ea-9817-5492251009f4.png)

Any ideas on how these errors can be resolved?

Thanks.

**Comment by maybeabhishek** [comment]
I am facing a similar issue though I have pulled the master repository instead of branch_release_2. Could it be that in the master branch the config files are not parsed properly and the default parameter in the .yaml file is still needed?

**Comment by tailzdafox** [comment]
I messed around with both branch_release_1, branch_release_2, and master. I also tinkered with adding in the default tag and it didn't seem to make any difference whatsoever
