### ISSUE TITLE
ModuleNotFoundError: No module named 'mlagents_envs.communicator_objects.agent_info_pb2'

### ISSUE THREAD

**Issue by kegoru** [Unity-Technologies/ml-agents#4032]
**Describe the bug**
ModuleNotFoundError: No module named 'mlagents_envs.communicator_objects.agent_info_pb2'

**To Reproduce**
1. Download ml-agents-master
2. run
pip3 install -e ml-agents-envs/
pip3 install -e ml-agents/
3. run 
mlagents-learn config/sac/3DBall.yaml --run-id=MyFirstAI 

**Console logs / stack traces**
```
C:\Projects Unity3d\ml-agents-master>mlagents-learn config/sac/3DBall.yaml --run-id=MyFirstAI                         c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                                   _np_qint8 = np.dtype([("qint8", np.int8, 1)])                                                                       c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                                   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])                                                                    c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                                   _np_qint16 = np.dtype([("qint16", np.int16, 1)])                                                                    c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                                   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])                                                                 c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                                   _np_qint32 = np.dtype([("qint32", np.int32, 1)])                                                                    c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.                                                                   np_resource = np.dtype([("resource", np.ubyte, 1)])                                                                 Traceback (most recent call last):                                                                                      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts\mlagents-learn-script.py", line 11, in <module>                                                                                                              load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()                                                 File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point                                                                                          return get_distribution(dist).load_entry_point(group, name)                                                         File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point                                                                                         return ep.load()                                                                                                    File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\pkg_resources\__init__.py", line 2443, in load                                                                                                     return self.resolve()                                                                                               File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve                                                                                                  module = __import__(self.module_name, fromlist=['__name__'], level=0)                                               File "c:\projects unity3d\ml-agents-master\ml-agents\mlagents\trainers\learn.py", line 14, in <module>                  from mlagents.trainers.trainer_controller import TrainerController                                                  File "c:\projects unity3d\ml-agents-master\ml-agents\mlagents\trainers\trainer_controller.py", line 15, in <module>     from mlagents.trainers.env_manager import EnvManager                                                                File "c:\projects unity3d\ml-agents-master\ml-agents\mlagents\trainers\env_manager.py", line 11, in <module>            from mlagents.trainers.brain import BrainParameters                                                                 File "c:\projects unity3d\ml-agents-master\ml-agents\mlagents\trainers\brain.py", line 1, in <module>                   from mlagents_envs.communicator_objects.agent_info_pb2 import AgentInfoProto                                      ModuleNotFoundError: No module named 'mlagents_envs.communicator_objects.agent_info_pb2'
```

**Environment**
- Unity Version: 2020.1.0b7.3556 Pesonal
- OS + version: Windows 10
- _ML-Agents version_: mlagents-envs-0.17.0.dev0 , mlagents 0.17.0.dev0
- _TensorFlow version_: 1.13.1   
- _Environment_: Python 3.6.10 (tried both with conda and without, the results are the same)

PS I tried ml-agents-release_2 (mlagents-envs 0.16.1 and mlagents 0.16.1), everything works as a magic.

**Comment by aqifilyaskhan** [comment]
facing same issue? any solution

**Comment by aqifilyaskhan** [comment]
mine problem solved writing here hopefully it will help someone
first go to this folder "ml-agents-envs" then call it

# %cd /content/ml-agents-release_8/ml-agents-envs
from mlagents_envs.environment import UnityEnvironment
