### ISSUE TITLE
Issues about the path

### ISSUE THREAD

**Issue by thelittleone1984** [Unity-Technologies/ml-agents#4044]
Traceback (most recent call last):
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python38\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "c:\ross\ml\ml-agents-release_2\ml-agents\mlagents\trainers\learn.py", line 554, in main
    run_cli(parse_command_line())
  File "c:\ross\ml\ml-agents-release_2\ml-agents\mlagents\trainers\learn.py", line 320, in parse_command_line
    return RunOptions.from_argparse(args)
  File "c:\ross\ml\ml-agents-release_2\ml-agents\mlagents\trainers\learn.py", line 292, in from_argparse
    argparse_args["trainer_config"] = load_config(trainer_config_path)
  File "c:\ross\ml\ml-agents-release_2\ml-agents\mlagents\trainers\trainer_util.py", line 190, in load_config
    raise TrainerConfigError(f"Config file could not be found at {abs_path}.")
mlagents.trainers.exception.TrainerConfigError: Config file could not be found at C:\Users\Ross\config\rollerball_config.yaml.

Hi I keep receiving this bug, it could be fixed by just write the full path of this .yaml file. But the output file goes to the root path which is "c:\ross" in my case. Is there any way to config this path and others like models and summaries? I know there should be somewhere but I just can't find it...

**Comment by anupambhatnagar** [comment]
@thelittleone1984 could you please run the mlagents-learn command from the root of the repo and place the config file in a subfolder. Then the models and summaries will be generated in the repo folder.
