### ISSUE TITLE
Error when training process is started

### ISSUE THREAD

**Issue by hecticmonke** [Unity-Technologies/ml-agents#4061]
After I start the training, the environment.py connects to the brains, gets their hyperparameters for the related brains and then, I encounter with an error like the one below and the training stops itself. Also I use ml-agents-release-1

Traceback (most recent call last):
File "C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\multiprocessing\connection.py", line 312, in _recv_bytes
nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109]

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\multiprocessing\process.py", line 297, in _bootstrap
self.run()
File "C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\multiprocessing\process.py", line 99, in run
self._target(*self._args, **self._kwargs)
File "c:\users\user\desktop\ml-agents-15.0-capstone\ml-agents-release_1\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 151, in worker
req: EnvironmentRequest = parent_conn.recv()
File "C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\multiprocessing\connection.py", line 250, in recv
buf = self._recv_bytes()
File "C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\multiprocessing\connection.py", line 321, in _recv_bytes
raise EOFError
EOFError

**Comment by andrewcoh** [comment]
Hi @hecticmonke 

Can you provide the whole stack trace including the command you used to launch?

**Comment by hecticmonke** [comment]
hi, @andrewcoh 

Here is the whole stack trace;

(mlagentsrelease1) C:\Users\user\Desktop\ml-agents-15.0-capstone\ml-agents-release_1>mlagents-learn config/space_shooter_trainer_config.yaml --run-id=theRun1 --train
WARNING:tensorflow:From C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term


                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓


 Version information:
  ml-agents: 0.16.0,
  ml-agents-envs: 0.16.0,
  Communicator API: 1.0.0,
  TensorFlow: 2.0.0
2020-06-03 18:37:13 WARNING [learn.py:534] The --train option has been deprecated. Train mode is now the default. Use --inference to run in inference mode.
WARNING:tensorflow:From C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-06-03 18:37:15 INFO [environment.py:201] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
2020-06-03 18:37:20 INFO [environment.py:111] Connected to Unity environment with package version 1.0.0-preview and communication version 1.0.0
2020-06-03 18:37:21 INFO [environment.py:342] Connected new brain:
WarAgent?team=3
2020-06-03 18:37:21 INFO [environment.py:342] Connected new brain:
ContinuousAgent?team=1
2020-06-03 18:37:21.398975: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-06-03 18:37:21 INFO [stats.py:130] Hyperparameters for behavior name theRun1_WarAgent:
        summary_path:   theRun1_WarAgent
        model_path:     ./models/theRun1/WarAgent
        keep_checkpoints:       5
        trainer:        ppo
        batch_size:     1024
        beta:   0.005
        buffer_size:    10240
        epsilon:        0.2
        hidden_units:   128
        lambd:  0.95
        learning_rate:  0.0003
        learning_rate_schedule: linear
        max_steps:      0
        memory_size:    128
        normalize:      False
        num_epoch:      3
        num_layers:     2
        time_horizon:   64
        sequence_length:        64
        summary_freq:   10000
        use_recurrent:  False
        vis_encode_type:        simple
        save_steps:     40000
        window: 10
        reward_signals:
          extrinsic:
            strength:   1.0
            gamma:      0.99
2020-06-03 18:37:23 INFO [stats.py:130] Hyperparameters for behavior name theRun1_ContinuousAgent:
        summary_path:   theRun1_ContinuousAgent
        model_path:     ./models/theRun1/ContinuousAgent
        keep_checkpoints:       5
        trainer:        ppo
        batch_size:     2048
        buffer_size:    20480
        hidden_units:   512
        learning_rate_schedule: linear
        max_steps:      0
        time_horizon:   2048
        num_epoch:      3
        save_steps:     40000
        summary_freq:   10000
        window: 10
        reward_signals:
          extrinsic:
            strength:   1.0
            gamma:      0.99
          curiosity:
            strength:   0.02
            gamma:      0.99
            encoding_size:      128
2020-06-03 18:37:23 INFO [model_serialization.py:221] List of nodes to export for brain :WarAgent?team=3
2020-06-03 18:37:23 INFO [model_serialization.py:223]   is_continuous_control
2020-06-03 18:37:23 INFO [model_serialization.py:223]   version_number
2020-06-03 18:37:23 INFO [model_serialization.py:223]   memory_size
2020-06-03 18:37:23 INFO [model_serialization.py:223]   action_output_shape
2020-06-03 18:37:23 INFO [model_serialization.py:223]   action
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Boru sonlandı

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\user\desktop\ml-agents-15.0-capstone\ml-agents-release_1\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 151, in worker
    req: EnvironmentRequest = parent_conn.recv()
  File "C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\user\anaconda3\envs\mlagentsrelease1\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

**Comment by hecticmonke** [comment]
I even changed the agents yet I still get this error. I searched it and found the other ml-agents users that encountered the same error yet there is no solution

**Comment by escgreen** [comment]
I'm getting a similar error.

I have tried two versions of Python (3.6.7 and 3.7.9). But they show the same result.

  Windows10 64bit.

 Version information:
  ml-agents: 0.21.0,
  ml-agents-envs: 0.21.0,
  Communicator API: 1.2.0,
  TensorFlow: 2.3.1
