### ISSUE TITLE
Invalid yaml file

### ISSUE THREAD

**Issue by AzkabanPresident** [Unity-Technologies/ml-agents#4112]
**Describe the bug**
I want to train 3dball,when I down load release3.I cant find  trainer_config.yaml.So I down load from here:  git clone --branch release_1 https://github.com/Unity-Technologies/ml-agents.git. But the error is : The option default was specified in your YAML file,but is invalid.

**To Reproduce**
1. Open powershell and go to current proj path
2. Input : mlagents-learn config/trainer_config.yaml --run-id=first3DBallRun

**Console logs / stack traces**
PS E:\Study\Simulation\ml-agents> mlagents-learn config/trainer_config.yaml --run-id=first3DBallRun
2020-06-11 18:15:36.562350: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic libra
ry 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-06-11 18:15:36.562350: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do n
ot have a GPU set up on your machine.
WARNING:tensorflow:From c:\users\Wxw\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\com
pat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be re
moved in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "c:\users\Wxw\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\Wxw\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Wxw\AppData\Local\Programs\Python\Python36\Scripts\mlagents-learn.exe\__main__.py", line 9, in <mo
dule>
  File "c:\users\Wxw\appdata\local\programs\python\python36\lib\site-packages\mlagents\trainers\learn.py", line 322
, in main
    run_cli(parse_command_line())
  File "c:\users\Wxw\appdata\local\programs\python\python36\lib\site-packages\mlagents\trainers\learn.py", line 56,
 in parse_command_line
    return RunOptions.from_argparse(args)
  File "c:\users\Wxw\appdata\local\programs\python\python36\lib\site-packages\mlagents\trainers\settings.py", line
351, in from_argparse
    key
mlagents.trainers.exception.TrainerConfigError: The option default was specified in your YAML file, but is invalid.

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: [ Unity 2018.4.17f1]
- OS + version: [ Windows 7 sp1+]
- _ML-Agents version_: ( ML-Agents v0.17.0)
- _TensorFlow version_: (2.2.0)
- _Environment_: (python v3.6.3)

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by DVonk** [comment]
The structure of the yaml files has changed (that's also mentioned in the migration guide). Just download this one manually:

https://github.com/Unity-Technologies/ml-agents/blob/master/config/ppo/3DBall.yaml

**Comment by theInsomniacGameMaker** [comment]
Did you find a solution for this?

**Comment by xiaomaogy** [comment]
@theInsomniacGameMaker @AzkabanPresident Please refer to @DVonk's solution.
