### ISSUE TITLE
Keyerror[Behavior name]

### ISSUE THREAD

**Issue by SamirAlSkaf** [Unity-Technologies/ml-agents#4249]
I'm running 
mlagents-learn config/trainer_config.yaml --run-id=PPO_Default --force
or
mlagents-learn config/Thesis.yaml --run-id=PPO_Default --force

- in folder config: both trainer_config.yaml and Thesis.yaml exist
- trainer_config.yaml has a block called 'Thesis'
- Thesis.yaml has a block called 'default'
- behavior name in Editor is 'Thesis'

Python 3.7.7
---------------------------------------------------------------------------------------------------------------------------------------------

`2020-07-19 16:25:13.352141: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-19 16:25:13.357846: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓

 Version information:
  ml-agents: 0.16.0,
  ml-agents-envs: 0.16.0,
  Communicator API: 1.0.0,
  TensorFlow: 2.2.0
2020-07-19 16:25:15.992118: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-19 16:25:15.998788: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-07-19 16:25:17 INFO [environment.py:201] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
2020-07-19 16:25:23 INFO [environment.py:111] Connected to Unity environment with package version 1.0.0-preview and communication version 1.0.0
2020-07-19 16:25:23 INFO [environment.py:342] Connected new brain:
Thesis?team=0
2020-07-19 16:25:23.930509: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-07-19 16:25:23.949184: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x249e77f99f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-19 16:25:23.957543: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-19 16:25:23.963734: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-07-19 16:25:23.969921: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-19 16:25:23.985625: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: SamirAl-Skaf-X1-Carbon
2020-07-19 16:25:23.992191: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: SamirAl-Skaf-X1-Carbon
2020-07-19 16:25:24 INFO [stats.py:130] Hyperparameters for behavior name PPO_Default_Thesis:
        trainer:        ppo
        batch_size:     1024
        beta:   0.005
        buffer_size:    10240
        epsilon:        0.2
        hidden_units:   128
        lambd:  0.95
        learning_rate:  3e-4
        learning_rate_schedule: linear
        max_steps:      1000000
        normalize:      False
        num_epoch:      3
        num_layers:     2
        time_horizon:   64
        summary_freq:   5000
        vis_encode_type:        simple
        reward_signals:
          extrinsic:
            strength:   1.0
            gamma:      0.99
        summary_path:   PPO_Default_Thesis
        model_path:     ./models/PPO_Default/Thesis
        keep_checkpoints:       5
Traceback (most recent call last):
  **File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 175, in _**create_trainer_and_manager
    trainer = self.trainers[brain_name]
KeyError: 'Thesis'****

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\SamirAlSkaf\AppData\Local\Programs\Python\Python37\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 554, in main
    run_cli(parse_command_line())
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 550, in run_cli
    run_training(run_seed, options)
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 407, in run_training
    tc.start_learning(env_manager)
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 227, in start_learning
    self._create_trainers_and_managers(env_manager, new_behavior_ids)
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 213, in _create_trainers_and_managers
    self._create_trainer_and_manager(env_manager, behavior_id)
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 177, in _create_trainer_and_manager
    trainer = self.trainer_factory.generate(brain_name)
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_util.py", line 61, in generate
    self.multi_gpu,
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_util.py", line 153, in initialize_trainer
    run_id,
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 70, in __init__
    self._check_param_keys()
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 76, in _check_param_keys
    super()._check_param_keys()
  File "c:\users\samiralskaf\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer\trainer.py", line 68, in _check_param_keys
    "brain {2}.".format(k, self.__class__, self.brain_name)
mlagents.trainers.exception.UnityTrainerException: The hyper-parameter sequence_length could not be found for the <class 'mlagents.trainers.ppo.trainer.PPOTrainer'> trainer of brain Thesis.
`

**Comment by vincentpierre** [comment]
Hi @SamirAlSkaf 
What version of ML-Agents are you on? I suspect you are on `release_1`, can you give me your commit number to be sure. Also, did you modify any of the Python code before running it? 
The reason I ask is because according to the log, the behavior `Thesis?team=0` connected but the trainer that was created was for `PPO_Default_Thesis`. These two names should always be the same but they are not (and so the trainer is confused and thinks `Thesis` is a missing key).
