### ISSUE TITLE
Camera Observation crashes training before it starts

### ISSUE THREAD

**Issue by kritonpc** [Unity-Technologies/ml-agents#4537]
**Describe the bug**
When adding a camera observation the trainer crashes immediately after starting, while without it there is no problem at all.

**To Reproduce**
Before adding the camera sensor the program runs. When I add the camera sensor and attaching the camera to it, it runs and crashes.

**Console logs / stack traces**
```
 Version information:
  ml-agents: 0.20.0,
  ml-agents-envs: 0.20.0,
  Communicator API: 1.1.0,
  TensorFlow: 2.2.0
2020-10-02 14:24:48 INFO [learn.py:272] run_seed set to 446
2020-10-02 14:24:48.964968: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
WARNING:tensorflow:From c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-10-02 14:24:50 INFO [environment.py:203] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
2020-10-02 14:24:53 WARNING [environment.py:103] WARNING: The communication API versions between Unity and python differ at the minor version level. Python API: 1.1.0, Unity API: 1.0.
This means that some features may not work unless you upgrade the package with the lower version.Please find the versions that work best together from our release page.
https://github.com/Unity-Technologies/ml-agents/releases
2020-10-02 14:24:54 INFO [environment.py:269] Connected new brain:
CarAgent?team=0
2020-10-02 14:24:54.168585: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-02 14:24:54.177189: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2d0fb20a1b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-02 14:24:54.178314: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-02 14:24:54.179373: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-02 14:24:54.180012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7845GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2020-10-02 14:24:54.180726: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-10-02 14:24:54.186136: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-10-02 14:24:54.190183: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-10-02 14:24:54.192178: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-10-02 14:24:54.196995: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-10-02 14:24:54.200500: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-10-02 14:24:54.200844: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-02 14:24:54.202643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-10-02 14:24:54.699781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-02 14:24:54.700145: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-10-02 14:24:54.701236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-10-02 14:24:54.702141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4831 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-10-02 14:24:54.706220: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2d09efad1d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-02 14:24:54.706561: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1060 6GB, Compute Capability 6.1
2020-10-02 14:24:54 INFO [stats.py:126] Hyperparameters for behavior name CarAgent:
        trainer_type:   ppo
        hyperparameters:
          batch_size:   256
          buffer_size:  12000
          learning_rate:        0.0003
          beta: 0.001
          epsilon:      0.3
          lambd:        0.99
          num_epoch:    3
          learning_rate_schedule:       linear
        network_settings:
          normalize:    True
          hidden_units: 128
          num_layers:   5
          vis_encode_type:      simple
          memory:       None
        reward_signals:
          extrinsic:
            gamma:      0.99
            strength:   1.0
        init_path:      None
        keep_checkpoints:       5
        checkpoint_interval:    500000
        max_steps:      50000000
        time_horizon:   1000
        summary_freq:   12000
        threaded:       True
        self_play:      None
        behavioral_cloning:     None
        framework:      tensorflow
2020-10-02 14:24:54.721908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7845GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2020-10-02 14:24:54.722307: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-10-02 14:24:54.722976: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-10-02 14:24:54.724021: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-10-02 14:24:54.724963: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-10-02 14:24:54.725934: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-10-02 14:24:54.726586: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-10-02 14:24:54.727663: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-02 14:24:54.728409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-10-02 14:24:54.729093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-02 14:24:54.729565: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-10-02 14:24:54.730058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-10-02 14:24:54.730599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4831 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-10-02 14:24:57.302875: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-10-02 14:24:57.490026: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-02 14:24:58.602428: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.1 but source was compiled with: 7.6.5.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2020-10-02 14:24:58.605188: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.1 but source was compiled with: 7.6.5.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2020-10-02 14:24:59 INFO [model_serialization.py:205] List of nodes to export for behavior :CarAgent
2020-10-02 14:24:59 INFO [model_serialization.py:207]   is_continuous_control
2020-10-02 14:24:59 INFO [model_serialization.py:207]   trainer_major_version
2020-10-02 14:24:59 INFO [model_serialization.py:207]   trainer_minor_version
2020-10-02 14:24:59 INFO [model_serialization.py:207]   trainer_patch_version
2020-10-02 14:24:59 INFO [model_serialization.py:207]   version_number
2020-10-02 14:24:59 INFO [model_serialization.py:207]   memory_size
2020-10-02 14:24:59 INFO [model_serialization.py:207]   action_output_shape
2020-10-02 14:24:59 INFO [model_serialization.py:207]   action
Converting results\carRL_camera\CarAgent/frozen_graph_def.pb to results\carRL_camera\CarAgent\CarAgent-0.nn
IGNORED: Cast unknown layer
GLOBALS: 'is_continuous_control', 'trainer_major_version', 'trainer_minor_version', 'trainer_patch_version', 'version_number', 'memory_size', 'action_output_shape'
IN: 'vector_observation': [-1, 1, 1, 146] => 'sub_2'
IN: 'visual_observation_0': [-1, 80, 80, 3] => 'policy/main_graph_0_encoder0/conv_1/BiasAdd'
IN: 'action_masks': [-1, 1, 1, 7] => 'policy_1/strided_slice'
IN: 'action_masks': [-1, 1, 1, 7] => 'policy_1/strided_slice_1'
IN: 'action_masks': [-1, 1, 1, 7] => 'policy_1/strided_slice_2'
OUT: 'policy/concat/concat', 'action'
DONE: wrote results\carRL_camera\CarAgent\CarAgent-0.nn file.
2020-10-02 14:24:59 INFO [model_serialization.py:87] Exported results\carRL_camera\CarAgent\CarAgent-0.nn
2020-10-02 14:24:59 INFO [tf_model_saver.py:163] Copied results\carRL_camera\CarAgent\CarAgent-0.nn to results\carRL_camera\CarAgent.nn.
2020-10-02 14:24:59 INFO [trainer_controller.py:84] Saved Model
Traceback (most recent call last):
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node policy/main_graph_0_encoder0/conv_1/Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node policy/main_graph_0_encoder0/conv_1/Conv2D}}]]
         [[policy_1/Sum_3/_77]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\learn.py", line 277, in main
    run_cli(parse_command_line())
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\learn.py", line 273, in run_cli
    run_training(run_seed, options)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\learn.py", line 150, in run_training
    tc.start_learning(env_manager)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\trainer_controller.py", line 174, in start_learning
    n_steps = self.advance(env_manager)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\trainer_controller.py", line 232, in advance
    new_step_infos = env_manager.get_steps()
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\env_manager.py", line 112, in get_steps
    new_step_infos = self._step()
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 255, in _step
    self._queue_steps()
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 248, in _queue_steps
    env_action_info = self._take_step(env_worker.previous_step)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 349, in _take_step
    step_tuple[0], last_step.worker_id
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\policy\tf_policy.py", line 269, in get_action
    decision_requests, global_agent_ids
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\policy\tf_policy.py", line 246, in evaluate
    run_out = self._execute_model(feed_dict, self.inference_dict)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\policy\tf_policy.py", line 296, in _execute_model
    network_out = self.sess.run(list(out_dict.values()), feed_dict=feed_dict)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\client\session.py", line 958, in run
    run_metadata_ptr)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\client\session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node policy/main_graph_0_encoder0/conv_1/Conv2D (defined at c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\tf\models.py:334) ]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node policy/main_graph_0_encoder0/conv_1/Conv2D (defined at c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\tf\models.py:334) ]]
         [[policy_1/Sum_3/_77]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node policy/main_graph_0_encoder0/conv_1/Conv2D:
 visual_observation_0 (defined at c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\tf\models.py:101)

Input Source operations connected to node policy/main_graph_0_encoder0/conv_1/Conv2D:
 visual_observation_0 (defined at c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\tf\models.py:101)

Original stack trace for 'policy/main_graph_0_encoder0/conv_1/Conv2D':
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\learn.py", line 277, in main
    run_cli(parse_command_line())
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\learn.py", line 273, in run_cli
    run_training(run_seed, options)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\learn.py", line 150, in run_training
    tc.start_learning(env_manager)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\trainer_controller.py", line 172, in start_learning
    self._reset_env(env_manager)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\trainer_controller.py", line 110, in _reset_env
    self._register_new_behaviors(env_manager, env_manager.first_step_infos)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\trainer_controller.py", line 266, in _register_new_behaviors
    self._create_trainers_and_managers(env_manager, new_behavior_ids)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\trainer_controller.py", line 164, in _create_trainers_and_managers
    self._create_trainer_and_manager(env_manager, behavior_id)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\trainer_controller.py", line 140, in _create_trainer_and_manager
    trainer.add_policy(parsed_behavior_id, policy)
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\ppo\trainer.py", line 286, in add_policy
    self.optimizer = self.create_ppo_optimizer()
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\ppo\trainer.py", line 265, in create_ppo_optimizer
    cast(TFPolicy, self.policy), self.trainer_settings  # type: ignore
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\ppo\optimizer_tf.py", line 21, in __init__
    policy.create_tf_graph()
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\policy\tf_policy.py", line 124, in create_tf_graph
    self.vis_encode_type,
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\policy\tf_policy.py", line 180, in _create_encoder
    vis_encode_type,
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\tf\models.py", line 648, in create_observation_streams
    False,  # reuse
  File "c:\users\mr.gamio\downloads\ml-agents-release_7\ml-agents\mlagents\trainers\tf\models.py", line 334, in create_visual_observation_encoder
    name="conv_1",
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\layers\convolutional.py", line 424, in conv2d
    return layer.apply(inputs)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 1695, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\layers\base.py", line 547, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 262, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 492, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 346, in _call_unconverted
    return f(*args, **kwargs)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 207, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1106, in __call__
    return self.conv_op(inp, filter)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 638, in __call__
    return self.call(inp, filter)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 237, in __call__
    name=self.name)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2014, in conv2d
    name=name)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 969, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Screenshots**
![image](https://user-images.githubusercontent.com/693201/94919991-18204f00-04be-11eb-802c-e5441ae24b67.png)

**Environment (please complete the following information):**
- Unity Version: Unity 2019.4.10f1
- OS + version: Windows 10
- _ML-Agents version_: 0.7
- _TensorFlow version_: 2.2.0
- _Environment_: custom car driving environment

**Comment by hvpeteet** [comment]
Thanks, this is likely an issue with your Tensorflow / NVIDIA drivers. Can you run `nvidia-smi` to see if you have a working install?

**Comment by kritonpc** [comment]
I have a working nvidia driver. nvidia-smi gives this:
```
Sat Oct 03 03:58:18 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 452.06       Driver Version: 452.06       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106... WDDM  | 00000000:01:00.0  On |                  N/A |
| 24%   55C    P0    32W / 120W |   1424MiB /  6144MiB |     14%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by hvpeteet** [comment]
Thanks, can you run the following in the same python environment? This should help determine if this is an issue with ml-agents or with TF. 

```
import tensorflow as tf
with tf.Graph().as_default():
    a = tf.constant(1)
    b = tf.constant(2)
    with tf.compat.v1.Session() as sess:
        sess.run(a+b)
```

**Comment by kritonpc** [comment]
Tensorflow doesn't have any issues. I've been training agents without the camera properly. Here's the output of the commands you suggested:

`Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-10-07 14:20:45.990011: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
>>> with tf.Graph().as_default():
...     a = tf.constant(1)
...     b = tf.constant(2)
...     with tf.compat.v1.Session() as sess:
...         sess.run(a+b)
...
2020-10-07 14:20:55.017588: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-07 14:20:55.035223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7845GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2020-10-07 14:20:55.035389: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-10-07 14:20:55.078774: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-10-07 14:20:55.104331: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-10-07 14:20:55.119620: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-10-07 14:20:55.160498: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-10-07 14:20:55.187117: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-10-07 14:20:55.260227: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-07 14:20:55.260657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-10-07 14:20:55.264893: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-07 14:20:55.284949: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2527b6ff0e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-07 14:20:55.285070: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-07 14:20:55.286755: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7845GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2020-10-07 14:20:55.288157: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-10-07 14:20:55.288872: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-10-07 14:20:55.289275: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-10-07 14:20:55.289747: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-10-07 14:20:55.290162: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-10-07 14:20:55.290551: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-10-07 14:20:55.291063: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-07 14:20:55.291518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-10-07 14:20:56.646646: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-07 14:20:56.646846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0
2020-10-07 14:20:56.647866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N
2020-10-07 14:20:56.649667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4831 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-10-07 14:20:56.654352: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x25220178680 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-07 14:20:56.654473: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1060 6GB, Compute Capability 6.1
3`

**Comment by hvpeteet** [comment]
Thanks for the follow up, I am asking around internally but while I do that have you tried setting `export TF_FORCE_GPU_ALLOW_GROWTH=true` in your terminal before running? There are similar issues that have been discussed on the TF forums[[1](https://github.com/tensorflow/tensorflow/issues/24828), [2](https://github.com/tensorflow/tensorflow/issues/28326)]

**Comment by hvpeteet** [comment]
Any updates?

**Comment by Dastyn** [comment]
Hello,

I have the same issue with:
  ml-agents: 0.23.0,
  ml-agents-envs: 0.23.0,
  Communicator API: 1.3.0,
  PyTorch: 1.7.1+cu101
Connected to Unity environment with package version 1.7.2-preview and communication version 1.3.0
OS: Windows 10

My command line is:
mlagents-learn my.yaml --run-id Visual --force --env myenv.exe --no-graphics 
The crash is raised as exposed by @kritonpc

However, if the "--no-graphics" option is removed from the command line, it then works properly (no crash is raised).

Any help please?
