### ISSUE TITLE
Training Hallway using PyTorch -> RuntimeError: rnn: hx is not contiguous

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#4555]
Hallway and VisualHallway throw a RuntimeError while starting the training using PyTorch.

**To Reproduce**
`mlagents-learn ./config/ppo/Hallway.yaml --torch`

**Stack traces**
```Traceback (most recent call last):
  File "C:\Users\Marco\.conda\envs\ml-agents-7\Scripts\mlagents-learn-script.py", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\learn.py", line 277, in main
    run_cli(parse_command_line())
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\learn.py", line 273, in run_cli
    run_training(run_seed, options)
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\learn.py", line 150, in run_training
    tc.start_learning(env_manager)
  File "d:\repositories\ml-agents\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 174, in start_learning
    n_steps = self.advance(env_manager)
  File "d:\repositories\ml-agents\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 232, in advance
    new_step_infos = env_manager.get_steps()
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\env_manager.py", line 112, in get_steps
    new_step_infos = self._step()
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 255, in _step
    self._queue_steps()
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 248, in _queue_steps
    env_action_info = self._take_step(env_worker.previous_step)
  File "d:\repositories\ml-agents\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 349, in _take_step
    step_tuple[0], last_step.worker_id
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\policy\torch_policy.py", line 228, in get_action
    decision_requests, global_agent_ids
  File "d:\repositories\ml-agents\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\policy\torch_policy.py", line 193, in evaluate
    vec_obs, vis_obs, masks=masks, memories=memories
  File "d:\repositories\ml-agents\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\policy\torch_policy.py", line 134, in sample_actions
    vec_obs, vis_obs, masks, memories, seq_len
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\torch\networks.py", line 392, in get_dist_and_value
    vec_inputs, vis_inputs, memories=memories, sequence_length=sequence_length
  File "C:\Users\Marco\.conda\envs\ml-agents-7\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\torch\networks.py", line 106, in forward
    encoding, memories = self.lstm(encoding, memories)
  File "C:\Users\Marco\.conda\envs\ml-agents-7\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\repositories\ml-agents\ml-agents\mlagents\trainers\torch\layers.py", line 181, in forward
    lstm_out, hidden_out = self.lstm(input_tensor, hidden)
  File "C:\Users\Marco\.conda\envs\ml-agents-7\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Marco\.conda\envs\ml-agents-7\lib\site-packages\torch\nn\modules\rnn.py", line 559, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: rnn: hx is not contiguous
```

**Environment:**
- Unity 2018.4.28f1
- Windows 10
- ML-Agents Release 7
- PyTorch v1.4
- Hallway / VisualHallway

**Potential Fix**
Call contiguous() on the hidden state and hidden cell.
/ml-agents/ml-agents/mlagents/trainers/torch/layers.py:180
`hidden = (h0.contiguous(), c0.contiguous())`

I'm not sure if this is a favorable solution. I just started training and hopefully it results in a reasonable behavior.

**Comment by andrewcoh** [comment]
Hi @MarcoMeter 

I notice you are using PyTorch v1.4. Can you try upgrading to >=1.5?  Did you modify the trainer/environment code in any way or is this happening on a clean install?

I am unable to reproduce with release 7 or current master i.e everything seems to run/train with no issues. If upgrading your version of torch doesn't help, please let me know so I can look into it further.

**Comment by MarcoMeter** [comment]
I updated PyTorch to v1.6 (CPU only). The problem does not occur using that version.
I didn't try it with CUDA yet (originally I tested with v1.4 and CUDA 10.1), because of the necessity of upgrading CUDA as well.
