### ISSUE TITLE
Release 10 Training using Hummingbird : RuntimeError: rnn: hx is not contiguous

### ISSUE THREAD

**Issue by Sh3yn3** [Unity-Technologies/ml-agents#4761]
**Describe the bug**
The training start and work for several minutes. The moment the second lines of feedback shown in the anaconda console the error happens and the unity training stop itself few seconds later at the end of the episode.

**To Reproduce**
1. Go to https://learn.unity.com/course/ml-agents-hummingbirds?uv=2019.3 and download the full project sample under material called "HummingbirdCompleteProject-1.0-release.zip" [Direct-link](https://connect-prd-cdn.unity.com/20200529/43b5e65b-4cce-46fd-8860-c55a7e09bc04/HummingbirdCompleteProject-1.0-release.zip)
2. Launch it with unity 2019.4.16
3. Install the ml-agents package from the package manager preview 1.6 (To be compatible with the release-10)
4. Download and unzipp the latest https://github.com/Unity-Technologies/ml-agents/releases (release-10)
5. create a new anaconda environment using "conda create -n ml-agents python=3.7"
6. Go into your anaconda environment and use the "pip3 install torch==1.7.0 -f https://download.pytorch.org/whl/torch_stable.html" command to install pytorch 1.7 (To be compatible with the release-10)
7. Create a new config file named Hummingbird.yaml to fit the release-10 yaml files template
```
behaviors:
  Hummingbird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256 #128
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
```
8. Move in your release-10 unzipped folder and launch the command "mlagents-learn config/ppo/Hummingbird.YAML" or wherever you put the Hummingbird.yaml file.
9. Press play on unity and wait several minutes.

**Console logs / stack traces**
```
2020-12-15 19:59:53 INFO [stats.py:139] Hummingbird. Step: 10000. Time Elapsed: 139.271 s. Mean Reward: -0.278. Std of Reward: 0.786. Training.
2020-12-15 20:02:01 INFO [stats.py:139] Hummingbird. Step: 20000. Time Elapsed: 266.883 s. Mean Reward: 0.000. Std of Reward: 0.000. Training.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "E:\Anaconda\envs\sheyne\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\Anaconda\envs\sheyne\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\bouch\downloads\mlagent\ml-agents-release_10\ml-agents\mlagents\trainers\trainer_controller.py", line 298, in trainer_update_func
    trainer.advance()
  File "c:\users\bouch\downloads\mlagent\ml-agents-release_10\ml-agents\mlagents\trainers\trainer\rl_trainer.py", line 317, in advance
    if self._update_policy():
  File "c:\users\bouch\downloads\mlagent\ml-agents-release_10\ml-agents\mlagents\trainers\ppo\trainer.py", line 206, in _update_policy
    buffer.make_mini_batch(i, i + batch_size), n_sequences
  File "c:\users\bouch\downloads\mlagent\ml-agents-release_10\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\bouch\downloads\mlagent\ml-agents-release_10\ml-agents\mlagents\trainers\ppo\optimizer_torch.py", line 165, in update
    seq_len=self.policy.sequence_length,
  File "c:\users\bouch\downloads\mlagent\ml-agents-release_10\ml-agents\mlagents\trainers\policy\torch_policy.py", line 181, in evaluate_actions
    vec_obs, vis_obs, masks, memories, seq_len
  File "c:\users\bouch\downloads\mlagent\ml-agents-release_10\ml-agents\mlagents\trainers\torch\networks.py", line 477, in get_dist_and_value
    masks=masks,
  File "c:\users\bouch\downloads\mlagent\ml-agents-release_10\ml-agents\mlagents\trainers\torch\networks.py", line 322, in get_dists
    vec_inputs, vis_inputs, memories=memories, sequence_length=sequence_length
  File "E:\Anaconda\envs\sheyne\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\users\bouch\downloads\mlagent\ml-agents-release_10\ml-agents\mlagents\trainers\torch\networks.py", line 106, in forward
    encoding, memories = self.lstm(encoding, memories)
  File "E:\Anaconda\envs\sheyne\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\users\bouch\downloads\mlagent\ml-agents-release_10\ml-agents\mlagents\trainers\torch\layers.py", line 187, in forward
    lstm_out, hidden_out = self.lstm(input_tensor, hidden)
  File "E:\Anaconda\envs\sheyne\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda\envs\sheyne\lib\site-packages\torch\nn\modules\rnn.py", line 582, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: rnn: hx is not contiguous
```

**Environment (please complete the following information):**
- Unity Version: Unity 2019.4.16
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents Release 10
- _Torch version_: 1.7.0+cu110
- _Environment_: Hummingbird https://learn.unity.com/course/ml-agents-hummingbirds?uv=2019.3

**Comment by surfnerd** [comment]
Hi @Sh3yn3,
We have logged this internally as  MLA-1662 and will update this ticket once we have a resolution for it.  Thank you for your feedback.

**Comment by akTwelve** [comment]
I got the same error on a separate project as soon as I added "memory" to my yaml file. Same Torch version and ML-Agents release.

**Comment by surfnerd** [comment]
Thank for the info @akTwelve.  This may help narrow the bug down.

**Comment by ervteng** [comment]
Hi @Sh3yn3, @akTwelve, are both these projects using continuous actions by any chance?

**Comment by akTwelve** [comment]
Mine is using discrete.

Adam Kelly

Sent from my mobile
________________________________

**Comment by ervteng** [comment]
Are you by any chance using GPU training? Windows? Just trying to narrow the bug down.

**Comment by ervteng** [comment]
It seems to be a re-emergence of this bug, which happened with Torch 1.4.0: https://github.com/Unity-Technologies/ml-agents/issues/4555 
I haven't been able to replicate on Mac with Torch 1.7.0 and the Hallway environment that uses discrete-LSTM.

**Comment by akTwelve** [comment]
I'm not using "--cpu", so I think that means I'm using GPU training right? Yes Windows 10. I am able to replicate with the Hallway example.
`mlagents-learn config\ppo\Hallway.yaml --run-id hallway`

**Comment by akTwelve** [comment]
Just tried out the change from @dongruoping and it fixed the error for me. I no longer get the error on Hallway nor the other project I was originally trying to us it on. Nice!

**Comment by ervteng** [comment]
Glad that fixed the issue! We'll get it merged in to the next hotfix.
