### ISSUE TITLE
Problem with Banana Collectors Imitation example

### ISSUE THREAD

**Issue by claychinasky** [Unity-Technologies/ml-agents#497]
Hello, 

I tried to run this scene with tensorflow, followed the steps from documents.

Teacher agent in client fails to recognize action values which given by the player, so it doesn't move. It only recognizes the keys 'R' and 'C'. 
I'm running learn.py with --train --slow
I didn't change anything in trainer_config.yaml file because the settings were correct and present.

Anyone successfully ran this training ? Thanks!

**Comment by claychinasky** [comment]
ok, after waiting for 15 secs or so, exception starts to pup up,

`Exception
NullReferenceException: Object reference not set to an instance of an object
BananaAgent.CollectObservations () (at <bcf1a2d1385b4b6d92a6a38698962e06>:0)
Agent.SendInfoToBrain () (at <bcf1a2d1385b4b6d92a6a38698962e06>:0)
Agent.SendInfo () (at <bcf1a2d1385b4b6d92a6a38698962e06>:0)
Academy.EnvironmentStep () (at <bcf1a2d1385b4b6d92a6a38698962e06>:0)
Academy.FixedUpdate () (at <bcf1a2d1385b4b6d92a6a38698962e06>:0)

ERROR:unityagents:An error might have occured in the environment. You can check the logfile for more information at D:\unity projects\ml-agents-0.3.0\python/unity-environment.log
Traceback (most recent call last):
  File "D:\unity projects\ml-agents-0.3.0\python\unityagents\environment.py", line 218, in _recv_bytes
    s = self._conn.recv(self._buffer_size)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "learn.py", line 62, in <module>
    tc.start_learning()
  File "D:\unity projects\ml-agents-0.3.0\python\unitytrainers\trainer_controller.py", line 230, in start_learning
    curr_info = self.env.reset(train_mode=self.fast_simulation)
  File "D:\unity projects\ml-agents-0.3.0\python\unityagents\environment.py", line 276, in reset
    return self._get_state()
  File "D:\unity projects\ml-agents-0.3.0\python\unityagents\environment.py", line 287, in _get_state
    state_dict, end_of_message = self._get_state_dict()
  File "D:\unity projects\ml-agents-0.3.0\python\unityagents\environment.py", line 243, in _get_state_dict
    state = self._recv_bytes().decode('utf-8')
  File "D:\unity projects\ml-agents-0.3.0\python\unityagents\environment.py", line 224, in _recv_bytes
    raise UnityTimeOutException("The environment took too long to respond.", self._log_path)
unityagents.exception.UnityTimeOutException: The environment took too long to respond.
`

**Comment by vincentpierre** [comment]
Thank you, let us know if it is resolved on 0.3.0a.

**Comment by claychinasky** [comment]
Yes, it's working now, Thank you.
