### ISSUE TITLE
Error when adding curiosity to hyperparameters

### ISSUE THREAD

**Issue by preuschhi** [Unity-Technologies/ml-agents#5004]
Hello. My Agents is stuck at a specific point and does not hunt the target as it should. So i thought i add curiosity. 
The Problem I have now is that i get this error when ich start the Training, or try starting:

```
Traceback (most recent call last):
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\bmxle\AppData\Local\Programs\Python\Python37\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 280, in main
    run_cli(parse_command_line())
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 56, in parse_command_line
    return RunOptions.from_argparse(args)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\settings.py", line 811, in from_argparse
    final_runoptions = RunOptions.from_dict(configured_dict)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\settings.py", line 824, in from_dict
    return cattr.structure(options_dict, RunOptions)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\cattr\converters.py", line 192, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\cattr\converters.py", line 314, in structure_attrs_fromdict
    dispatch(type_)(val, type_) if type_ is not None else val
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\settings.py", line 643, in dict_to_defaultdict
    cattr.structure(d, Dict[str, TrainerSettings])
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\cattr\converters.py", line 192, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\cattr\converters.py", line 367, in _structure_dict
    for k, v in obj.items()
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\cattr\converters.py", line 367, in <dictcomp>
    for k, v in obj.items()
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\settings.py", line 682, in structure
    d_copy[key] = check_and_structure(key, val, t)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\settings.py", line 40, in check_and_structure
    f"**The option {key} was specified in your YAML file for {class_type.__name__}, but is invalid."
mlagents.trainers.exception.TrainerConfigError: The option curiosity was specified in your YAML file for TrainerSettings, but is invalid.**
```
These are my hyperparameters:
```
%YAML 1.2
--- 
behaviors: 
  EnemyMovement: 
    trainer_type: ppo
    hyperparameters: 
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings: 
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
    reward_signals: 
      extrinsic: 
        gamma: 0.99
        strength: 1.0
    curiosity: 
      strength: 0.02
      gamma: 0.99
      encoding_size: 256
      learning_rate: "3.0e-4"
```

**Comment by chriselion** [comment]
Note: I updated your post to use triple-backticks (```) for the log and yaml. Will reply in a minute.

**Comment by chriselion** [comment]
The problem is a bit more obvious when the yaml is formatted mono-spaced. The `curiosity` section should be a key in the `reward_signals` dictionary, so you basically need to add 2 spaces in front of the last 5 lines of your file:
```
%YAML 1.2
--- 
behaviors: 
  EnemyMovement: 
    trainer_type: ppo
    hyperparameters: 
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings: 
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 50000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
    reward_signals: 
      extrinsic: 
        gamma: 0.99
        strength: 1.0
      curiosity: 
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: "3.0e-4"
```

**Comment by preuschhi** [comment]
Thank you for your quick help.
