### ISSUE TITLE
Unity Freezes during Training, then the training stops.

### ISSUE THREAD

**Issue by preuschhi** [Unity-Technologies/ml-agents#5009]
The Training gets usntable after about 300 000 steps. At like 300 000 - 500 000 steps unity freezes and the traning stops.
I never had a Training getting past 500 000 steps. My total stepcount is above 500 000 .
Here is the message i get in the cmd: 

```
2021-02-25 11:49:02 INFO [subprocess_env_manager.py:186] UnityEnvironment worker 0: environment stopping.
2021-02-25 11:49:20 INFO [model_serialization.py:104] Converting to results\CPU_ShootingTraining_DumbTarget_1.6\EnemyMovement\EnemyMovement-390677.onnx
2021-02-25 11:49:59 INFO [model_serialization.py:116] Exported results\CPU_ShootingTraining_DumbTarget_1.6\EnemyMovement\EnemyMovement-390677.onnx
2021-02-25 11:50:18 INFO [torch_model_saver.py:116] Copied results\CPU_ShootingTraining_DumbTarget_1.6\EnemyMovement\EnemyMovement-390677.onnx to results\CPU_ShootingTraining_DumbTarget_1.6\EnemyMovement.onnx.
2021-02-25 11:50:18 INFO [trainer_controller.py:85] Saved Model
Traceback (most recent call last):
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\bmxle\AppData\Local\Programs\Python\Python37\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 280, in main
    run_cli(parse_command_line())
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 276, in run_cli
    run_training(run_seed, options)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\learn.py", line 153, in run_training
    tc.start_learning(env_manager)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 176, in start_learning
    n_steps = self.advance(env_manager)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\trainer_controller.py", line 234, in advance
    new_step_infos = env_manager.get_steps()
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\env_manager.py", line 113, in get_steps
    new_step_infos = self._step()
  File "c:\users\bmxle\appdata\local\programs\python\python37\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 276, in _step
    raise env_exception
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Agents' Behavior Parameters > Behavior Type is set to "Default"
         The environment and the Python interface have compatible versions.

```
This is really annoying because i can not just leave it alone let it train for a couple iof hours.

**Comment by surfnerd** [comment]
Hi @preuschhi,
Without any indication of what your code is doing, it's really hard to figure out why this is happening.  Can you share your code with us to help us diagnose this?

**Comment by chriselion** [comment]
You can also resume training from where you left off by passing `--resume` to `mlagents-learn`

**Comment by preuschhi** [comment]
This is my code. I left out the heuristic method so it is not so messy. There are probably some mistakes, i am still working on it.

I know i can resume the training. But the problem is, that not only Unity Freezes. 
1. Unity Freezes 2. At the same time my whole system gets slower, and most of the time i must restart it. But sometimes it is enough to restart Unity.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.MLAgents;
using Unity.MLAgents.Actuators;
using Unity.MLAgents.Sensors;

public class EnemyMovement : Agent {

    private float health;
    private bool isShooting;
    private float shotsTaken;

  

    //getting a reference to the dumbTarget
    public GameObject dumbTarget;
    DumbTarget dumbTargetScript;

    private void Start()
    {
      //Reference to dumbTarget
        dumbTargetScript = dumbTarget.GetComponent<DumbTarget>();
    }
    public override void OnEpisodeBegin() {
        //New Positions etc. for agentTarget
        transform.localPosition = new Vector2(Random.Range(-47.52f, 48.5f), Random.Range(48.1f, -46.42f));
        shotsTaken = 0f;
        health = 100f;


        //deleting all bullets
        GameObject[] bullets = GameObject.FindGameObjectsWithTag("Bullet");
        foreach (GameObject bullet in bullets)
            GameObject.Destroy(bullet);


        //dumbTarget
        dumbTargetScript.health = 100f;
    }

    public Material winMaterial;
    public Material loseMaterial;
    public SpriteRenderer wallMeshRenderer;

    public override void CollectObservations(VectorSensor sensor) {
        sensor.AddObservation(transform.rotation);
        sensor.AddObservation(transform.localPosition);

        //observations for dumbTarget
        sensor.AddObservation(dumbTarget.transform.localPosition);
    }

    //saves the last Rotation after the agents stopped moving
    Quaternion currentRotation;
    public float moveSpeed = 10f;

    public override void OnActionReceived(ActionBuffers actions) {
        //Getting input for playerMovement
        float xMovement = actions.ContinuousActions[0];
        float yMovement = actions.ContinuousActions[1];

        //Moving the player
        transform.GetComponent<Rigidbody2D>().velocity = new Vector2(xMovement * moveSpeed, yMovement * moveSpeed);

        //Rotating the player
        Vector3 movement = new Vector3(xMovement, yMovement, 0);
        Quaternion lookRotation = Quaternion.LookRotation(Vector3.forward, movement);
        Vector3 rotation = lookRotation.eulerAngles;
        transform.rotation = Quaternion.Euler(0f, 0f, rotation.z);
        

        //as long as the agent is moving, the current rotation gets saved
        if ((xMovement != 0f) || (yMovement != 0f)) {
            currentRotation = transform.rotation;
            Debug.Log("Test" + currentRotation);
        }

        //if the agent stops moving the last saved rotaion will be used => fixed the snapping-back bug
        if ((xMovement == 0f) && (yMovement == 0f)) {
            Debug.Log("Stop");;
            transform.rotation = currentRotation;
        }

        //Agent gets penalty for every step
        int firstStepCount = StepCount;
        if (firstStepCount < StepCount)
        {
            SetReward(-0.1f);
        }
        //Agent gets huge penalty if it does not reach the goal/kills target
        if (StepCount == MaxStep)
        {
            SetReward(-2f);
            EndEpisode();
        }

        //shooting
        float distanceBetween = Vector3.Distance(transform.position, dumbTarget.transform.localPosition);
        if (distanceBetween <= 30f)
        {
            SetReward(+4f);
            float shooting = actions.ContinuousActions[2];
            if (shooting > 0.4f)
            {
                SetReward(-0.5f);
            shotsTaken++;
            GameObject bullet = Instantiate(bulletPrefab, shootingPoint.position, shootingPoint.rotation);
            Rigidbody2D rbbullet = bullet.GetComponent<Rigidbody2D>();
            rbbullet.AddForce(shootingPoint.up * shootingForce, ForceMode2D.Impulse);
            }
        }


        //Agent gets big reward if it kills the target
        if (dumbTargetScript.health <= 0f)
        {
            wallMeshRenderer.material = winMaterial;
            SetReward(+7f);
            EndEpisode();
        }

        //If the dumbTargetCurrentHealth is lower that dumbTargetScript.health, then the dumbTarget was hit
        float dumbTargetCurrentHealth = dumbTargetScript.health;
        if (dumbTargetCurrentHealth > dumbTargetScript.health)
        {
            SetReward(+1f);
        }

        ////reduces the amount of shots the agent should take
        float firstShotsTakenCount = shotsTaken;
        if (firstShotsTakenCount < shotsTaken)
        {
            SetReward(-2f);
        }

    }


   
    private void OnTriggerEnter2D(Collider2D other) {
      ////when agent hits wall
        if (other.tag == "Border") {
            SetReward(-1f);
            wallMeshRenderer.material = loseMaterial;
            EndEpisode();
        }


        if (other.tag == "Bullet")
        {
            health -= 25f;
            Debug.Log("Playerhealth " + health);
            SetReward(-1f);

            if (health <= 0f)
            {
                Debug.Log("Player is dead");
                wallMeshRenderer.material = loseMaterial;
                SetReward(-4f);
                EndEpisode();
            }
        }
    }

     
    
}
```

**Comment by surfnerd** [comment]
`GameObject bullet = Instantiate(bulletPrefab, shootingPoint.position, shootingPoint.rotation);`

Doing this in fixed update could potentially mean that you are instantiating a whole lot of bullets.  I don't know if that's the source of the issue, but if your neural network learns to shoot and then gets close to the target to keep shooting I could see why your environment would freeze.

Also, `FindGameObejctWithTag`is very slow.  You would be better off caching the bullets in a list and destroying them in OnEpisodeBegin.

That being said, you may want to limit the number of bullets that are instantiated.  Calling Instantiate and Destroy are also very slow operations.  You may want to consider object pooling for this case.

**Comment by chriselion** [comment]
Are there any warnings/errors in the editor log around the time Unity freezes? Are you able to attach a debugger and see where it's stuck?
