### ISSUE TITLE
Sorter env. exception when training with GAIL demo

### ISSUE THREAD

**Issue by Dastyn** [Unity-Technologies/ml-agents#5054]
Hi All,

When training the Sorter environment (using Attention mechanism) with a GAIL section in the yaml configuration file, and an "expert" demo file (generated by a DemonstrationRecorder component), an exception is raised:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".../mlagents/trainers/trainer_controller.py", line 297, in trainer_update_func
    trainer.advance()
  File ".../mlagents/trainers/trainer/rl_trainer.py", line 274, in advance
    self._process_trajectory(t)
  File ".../mlagents/trainers/ppo/trainer.py", line 103, in _process_trajectory
    reward_signal.evaluate(agent_buffer_trajectory) * reward_signal.strength
  File ".../mlagents/trainers/torch/components/reward_providers/gail_reward_provider.py", line 37, in evaluate
    estimates, _ = self._discriminator_network.compute_estimate(
  File ".../mlagents/trainers/torch/components/reward_providers/gail_reward_provider.py", line 149, in compute_estimate
    hidden, _ = self.encoder(inputs, action_inputs)
  File "/home/lub/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File ".../mlagents/trainers/torch/networks.py", line 134, in forward
    attention_embedding = self.rsa(qkv, masks)
  File "/home/lub/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File ".../mlagents/trainers/torch/attention.py", line 285, in forward
    output, _ = self.attention(query, key, value, num_ent, num_ent, mask)
  File "/home/lub/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File ".../mlagents/trainers/torch/attention.py", line 84, in forward
    query = query.reshape(
RuntimeError: shape '[-1, 20, 4, 130]' is invalid for input of size 1461600
```

The corresponding yaml configuration file is the following:

```
behaviors:
  Sorter:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant 
    network_settings:
      normalize: False
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        demo_path: Alpha/Assets/Demonstrations/demoSorter.demo
        encoding_size: 512
        gamma: 0.9
        learning_rate: 0.0009
        strength: 0.4
        use_actions: 1
        use_vail: false        
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 256
    summary_freq: 1000
    threaded: true
```

Please note that Behavioral Cloning works fine with the Sorter example and the very same generated demo file.

To Reproduce
mlagents-learn .\ml-agents\config\ppo\Sorter_GAIL.yaml
(change num_envs: 8 to 1, to make it work in editor mode).

The demoSorter.demo can be generated by any DemonstrationRecorder run (user inputs do not matter).

Environment:
    Unity Version: Unity 2019.4.12f1
    OS + version: Linux 64b
    ML-Agents version: recent develop branch 
      ml-agents: 0.25.0.dev0,
      ml-agents-envs: 0.25.0.dev0,
  Communicator API: 1.5.0,
  PyTorch: 1.7.1
  Environment: Sorter

**Comment by Dastyn** [comment]
Hi @vincentpierre 
Thanks for your efforts!
Good news, after pulling the very last release, it works fine: BC and/or GAIL enabled in the yaml config file with Sorter demo files can now learn.

For the record, please find below the pull history:
```
$ git reflog --date=iso
d0b3e9966 (HEAD -> main, origin/main, origin/HEAD) HEAD@{2021-03-09 18:36:48 +0100}: pull: Fast-forward
5e87e2cf9 HEAD@{2021-03-07 10:34:16 +0100}: clone: from https://github.com/Unity-Technologies/ml-agents.git
```
Thanks again for your reactivity.
Dastyn
