### ISSUE TITLE
run_logs not generated

### ISSUE THREAD

**Issue by George056** [Unity-Technologies/ml-agents#5174]
When training I am unable to proceeded past the first move because it tries to access run_logs\timers.json which does not exist.
This is on a custom turn based project. I have it set to self-play, but the problem happens regardless of the scene being set up for self-play or play against a human.

```
behaviors:
    Node_AI:
        trainer_type: sac
        summary_freq: 50000
        time_horizon: 128
        max_steps: 5.0e6
        keep_checkpoints: 5
        checkpoint_interval: 500000
        init_path: none
        threaded: true
        hyperparameters:
            learning_rate: 3e-4
            batch_size: 100 
            buffer_size: 50000
            learning_rate_schedule: constant
            buffer_init_steps: 0
            init_entcoef: 0.5
            save_replay_buffer: true
            tau: 0.005
            steps_per_update: 1
        network_settings:
            hidden_units: 256
            num_layers: 2 
            normalize: false
            vis_encoder_type: match3
        self_play:
            save_steps: 20000
            team_change: 80000
            swap_steps: 5000
            play_against_latest_model_ratio: 0.5
            window: 10

```

```
2021-03-22 16:51:11 WARNING [learn.py:185] Unable to save to results\node_004\run_logs\timers.json. Make sure the directory exists
Traceback (most recent call last):
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 153, in run_training
    tc.start_learning(env_manager)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 174, in start_learning
    self._reset_env(env_manager)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 111, in _reset_env
    self._register_new_behaviors(env_manager, env_manager.first_step_infos)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 268, in _register_new_behaviors
    self._create_trainers_and_managers(env_manager, new_behavior_ids)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 165, in _create_trainers_and_managers
    self._create_trainer_and_manager(env_manager, behavior_id)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\trainer_controller.py", line 138, in _create_trainer_and_manager
    policy = trainer.create_policy(
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\ghost\trainer.py", line 330, in create_policy
    self.trainer.add_policy(parsed_behavior_id, internal_trainer_policy)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\sac\trainer.py", line 417, in add_policy
    self.model_saver.initialize_or_load()
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\model_saver\torch_model_saver.py", line 70, in initialize_or_load
    self._load_model(
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\model_saver\torch_model_saver.py", line 83, in _load_model
    saved_state_dict = torch.load(model_path)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'none\\checkpoint.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\capstone\.conda\envs\ml-agents-node\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 280, in main
    run_cli(parse_command_line())
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 276, in run_cli
    run_training(run_seed, options)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 158, in run_training
    write_training_status(run_logs_dir)
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\learn.py", line 176, in write_training_status
    GlobalTrainingStatus.save_state(os.path.join(output_dir, TRAINING_STATUS_FILE_NAME))
  File "c:\users\capstone\.conda\envs\ml-agents-node\lib\site-packages\mlagents\trainers\training_status.py", line 101, in save_state
    with open(path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results\\node_004\\run_logs\\training_status.json'
```

- Unity Version: 2020.2.3f1
- OS + version: Windows 10
- _ML-Agents version_: .23
- _Torch version_: 1.7.1

**Comment by chriselion** [comment]
> `init_path: none`

I think you need `init_path: null` instead. From the logs:
```
FileNotFoundError: [Errno 2] No such file or directory: 'none\\checkpoint.pt'
```

**Comment by chriselion** [comment]
To clarify:
``` 
FileNotFoundError: [Errno 2] No such file or directory: 'none\\checkpoint.pt'
```
is the first error. We probably also need to make sure that the path for `training_status.json` exists before trying to save there (or just skip saving in this case), but that happens _after_ the exception caused by your bad configuration.

**Comment by George056** [comment]
Thanks, it's working now.
