### ISSUE TITLE
'poca' is not a valid TrainerType

### ISSUE THREAD

**Issue by Hlev1** [Unity-Technologies/ml-agents#5180]
**Describe the bug**
I am using a config file similar to the poca/PushBlockCollab.yaml. However, when I try to learn using this config, I get the error: 

`ValueError: 'poca' is not a valid TrainerType`

**To Reproduce**
1. Using this config file:

```
behaviors:
  Encircle:
    trainer_type: poca

    hyperparameters:
      batch_size: 1024
      buffer_size: 100000
      learning_rate: 0.0001
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant

    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 50000
    threaded: true
```

2. run the command `mlagents-learn Encircle.yaml --force`
3. See error

**Console logs / stack traces**

```
ValueError: 'poca' is not a valid TrainerType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/bin/mlagents-learn", line 8, in <module>
    sys.exit(main())
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 280, in main
    run_cli(parse_command_line())
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 56, in parse_command_line
    return RunOptions.from_argparse(args)
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/mlagents/trainers/settings.py", line 811, in from_argparse
    final_runoptions = RunOptions.from_dict(configured_dict)
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/mlagents/trainers/settings.py", line 824, in from_dict
    return cattr.structure(options_dict, RunOptions)
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/cattr/converters.py", line 192, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/cattr/converters.py", line 314, in structure_attrs_fromdict
    dispatch(type_)(val, type_) if type_ is not None else val
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/mlagents/trainers/settings.py", line 643, in dict_to_defaultdict
    cattr.structure(d, Dict[str, TrainerSettings])
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/cattr/converters.py", line 192, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/cattr/converters.py", line 367, in _structure_dict
    for k, v in obj.items()
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/cattr/converters.py", line 367, in <dictcomp>
    for k, v in obj.items()
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/mlagents/trainers/settings.py", line 682, in structure
    d_copy[key] = check_and_structure(key, val, t)
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/mlagents/trainers/settings.py", line 43, in check_and_structure
    return cattr.structure(value, attr_fields_dict[key].type)
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/cattr/converters.py", line 192, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/Users/harrylevick/Documents/GitHub/WildfireSimulator/simulation/Venv/lib/python3.7/site-packages/cattr/converters.py", line 264, in _structure_call
    return cl(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 569, in __new__
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 553, in __new__
    result = cls._missing_(value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 582, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'poca' is not a valid TrainerType
```

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: Unity 2019.4.13f1
- OS + version: macOS Big Sur 11.2
- _ML-Agents version_: 0.23.0
- _Torch version_: 1.7.0
- _Environment_: custom

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by surfnerd** [comment]
Hi,
You are using the ml-agents python package at version 0.23.3 and the POCA trainer was released at version 0.25.0.

Please read the release notes for release 15 (when POCA) was released and review the table of packages and versions required to use the latest features.  

Push block Collab is a new environment trained with POCA.
