### ISSUE TITLE
Aparent problem with serialization

### ISSUE THREAD

**Issue by Sposito** [Unity-Technologies/ml-agents#523]
```
PS C:\Users\ThiagoAlexandriaSpos\Documents\GitHub\ml-agents\python> python ppo.py tableFoot.exe --train
{'--batch-size': '64',
 '--beta': '2.5e-3',
 '--buffer-size': '2048',
 '--curriculum': 'None',
 '--epsilon': '0.2',
 '--gamma': '0.99',
 '--help': False,
 '--hidden-units': '64',
 '--keep-checkpoints': '5',
 '--lambd': '0.95',
 '--learning-rate': '3e-4',
 '--load': False,
 '--max-steps': '1e6',
 '--normalize': False,
 '--num-epoch': '5',
 '--num-layers': '2',
 '--run-path': 'ppo',
 '--save-freq': '50000',
 '--summary-freq': '10000',
 '--time-horizon': '2048',
 '--train': True,
 '--worker-id': '0',
 '<env>': 'tableFoot.exe'}
INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of brains: 1
        Reset Parameters :

Unity brain name: Brain
        Number of observations (per agent): 0
        State space type: continuous
        State space size (per agent): 30
        Action space type: continuous
        Action space size (per agent): 6
        Memory space size (per agent): 0
        Action descriptions: , , , , ,
2018-03-21 10:47:47.947515: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
2018-03-21 10:47:48.311234: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.96GiB
2018-03-21 10:47:48.321282: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:unityagents:
----------------------
Exception
JsonSerializationException: Unexpected end when deserializing array. Path 'value.Brain[22]', line 1, position 4380.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Object currentObject, System.String message) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList (System.Collections.IList list, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary (System.Collections.IDictionary dictionary, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonDictionaryContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value) (at <ca9d8d8bb33348708c9d738f817326f6>:0)
ExternalCommunicator.UpdateActions () (at C:/Users/ThiagoAlexandriaSpos/Unity Projects/ml-agents/unity-environment/Assets/ML-Agents/Scripts/ExternalCommunicator.cs:309)
Academy.DecideAction () (at C:/Users/ThiagoAlexandriaSpos/Unity Projects/ml-agents/unity-environment/Assets/ML-Agents/Scripts/Academy.cs:244)
Academy.RunMdp () (at C:/Users/ThiagoAlexandriaSpos/Unity Projects/ml-agents/unity-environment/Assets/ML-Agents/Scripts/Academy.cs:342)
Academy.FixedUpdate () (at C:/Users/ThiagoAlexandriaSpos/Unity Projects/ml-agents/unity-environment/Assets/ML-Agents/Scripts/Academy.cs:259)

ERROR:unityagents:An error might have occured in the environment. You can check the logfile for more information at C:\Users\ThiagoAlexandriaSpos\Documents\GitHub\ml-agents\python/unity-environment.log
Traceback (most recent call last):
  File "C:\Users\ThiagoAlexandriaSpos\Documents\GitHub\ml-agents\python\unityagents\environment.py", line 209, in _recv_bytes
    s += self._conn.recv(self._buffer_size)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ppo.py", line 132, in <module>
    new_info = trainer.take_action(info, env, brain_name, steps, normalize)
  File "C:\Users\ThiagoAlexandriaSpos\Documents\GitHub\ml-agents\python\ppo\trainer.py", line 76, in take_action
    new_info = env.step(actions, value={brain_name: value})[brain_name]
  File "C:\Users\ThiagoAlexandriaSpos\Documents\GitHub\ml-agents\python\unityagents\environment.py", line 440, in step
    return self._get_state()
  File "C:\Users\ThiagoAlexandriaSpos\Documents\GitHub\ml-agents\python\unityagents\environment.py", line 277, in _get_state
    state_dict = self._get_state_dict()
  File "C:\Users\ThiagoAlexandriaSpos\Documents\GitHub\ml-agents\python\unityagents\environment.py", line 230, in _get_state_dict
    state = self._recv_bytes().decode('utf-8')
  File "C:\Users\ThiagoAlexandriaSpos\Documents\GitHub\ml-agents\python\unityagents\environment.py", line 211, in _recv_bytes
    raise UnityTimeOutException("The environment took too long to respond.", self._log_path)
unityagents.exception.UnityTimeOutException: The environment took too long to respond.
PS C:\Users\ThiagoAlexandriaSpos\Documents\GitHub\ml-agents\python>
```

The projects can be found in  my form of ml agents:
[https://github.com/Sposito/ml-agents](https://github.com/Sposito/ml-agents)

I have no clue what the problem is =/

**Comment by xiaomaogy** [comment]
Could you please provide more details regarding this question?
