### ISSUE TITLE
Error When using Imitation Learning (RuntimeError: Class values must be non-negative.)

### ISSUE THREAD

**Issue by MTegarAsta** [Unity-Technologies/ml-agents#5323]
**Describe the bug**
I was training my AI with reinforcement learning and after 8 hours, I noticed the AI doesn't reach the goal I want, so I decide to use imitation learning to help the AI, but after 10000 steps the Editor Freezing, and I notice this error on cmd.

**Console logs / stack traces**
``` Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "e:\unity\machine learning\venv\lib\site-packages\mlagents\trainers\trainer_controller.py", line 297, in trainer_update_func
    trainer.advance()
  File "e:\unity\machine learning\venv\lib\site-packages\mlagents\trainers\trainer\rl_trainer.py", line 312, in advance
    if self._update_policy():
  File "e:\unity\machine learning\venv\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 211, in _update_policy
    update_stats = self.optimizer.bc_module.update()
  File "e:\unity\machine learning\venv\lib\site-packages\mlagents\trainers\torch\components\bc\module.py", line 93, in update
    run_out = self._update_batch(mini_batch_demo, self.n_sequences)
  File "e:\unity\machine learning\venv\lib\site-packages\mlagents\trainers\torch\components\bc\module.py", line 176, in _update_batch
    selected_actions, log_probs, expert_actions
  File "e:\unity\machine learning\venv\lib\site-packages\mlagents\trainers\torch\components\bc\module.py", line 118, in _behavioral_cloning_loss
    self.policy.behavior_spec.action_spec.discrete_branches,
  File "e:\unity\machine learning\venv\lib\site-packages\mlagents\trainers\torch\utils.py", line 277, in actions_to_onehot
    for i, _act in enumerate(discrete_actions.long().T)
  File "e:\unity\machine learning\venv\lib\site-packages\mlagents\trainers\torch\utils.py", line 277, in <listcomp>
    for i, _act in enumerate(discrete_actions.long().T)
RuntimeError: Class values must be non-negative. 
```
**.yaml File**
```
behaviors:
  ShootTarget:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
      gail:
        strength: 0.5
        demo_path: Demos/ThisIsHowToShoot.demo
    behavioral_cloning:
        strength: 0.5
        demo_path: Demos/ThisIsHowToShoot.demo
    max_steps: 2500000
    time_horizon: 64
    summary_freq: 10000
```

![image](https://user-images.githubusercontent.com/59899986/116383125-27475f80-a849-11eb-8fcb-7296598ab5ff.png)

**Environment**

- Unity Version: Unity 2020.3.2f1
- OS + version: Windows 10
- _ML-Agents version_(Python): 0.25.1
- _ML-Agents version_(Unity): 1.9.1
- _Torch version_: 1.7.0

**Comment by vincentpierre** [comment]
I would need from you a minimal way to reproduce it (like the issue template asks) so I can help.
My current guess is that the demo file contains an illegal action and when trying to encode it into onehot, it causes this issue.

**Comment by MTegarAsta** [comment]
you right, when I try using different learning scenario and different demo in the same environment it's working just fine.
is the learning scenario that causes this issue, because when I using the old learning scenario(Which causing the problem) and using the different demo it keeps crashing.

**Comment by vincentpierre** [comment]
I cannot know for sure without a way to reproduce it. All I know is that the error is happening when the trainer is processing discrete demo actions. I tried to reproduce with invalid actions but I was unable to. Please share a way to reproduce this issue.

**Comment by MTegarAsta** [comment]
I'm trying to make the AI shoot a target
To Reproduce:
1. I'm Following the tutorial on youtube to set up the environment and the imitation learning (by CodeMonkey)
2. Record the demo
3. then put in on the yaml file
4. run in cmd (mlagents-learn config/Shooting.yaml --force --time-scale 1)
5. and After 10000-20000 steps it's freeze and the error showing.

```
public override void OnActionReceived(ActionBuffers actions)
    {
        int directionX = actions.DiscreteActions[0];
        int directionY = actions.DiscreteActions[1];
        
        
        rotationTr.LookAt (new Vector3 (directionX,directionY,transform.position.z));
        int shoot = actions.DiscreteActions[2];
        if (shoot == 1 && timeToShoot <= Time.time)
        {
            Shoot ();
            timeToShoot = Time.time + (1f / fireRate);
        }
        AddReward (-1f / MaxStep);
    }

    public override void Heuristic(in ActionBuffers actionsOut)
    {
        ActionSegment<int> actionSegment = actionsOut.DiscreteActions;
        if (Input.GetKey (KeyCode.Space))
        {
            actionSegment[2] = 1;
        }
        else
        {
            actionSegment[2] = 0;
        }
        Ray ray = Camera.main.ScreenPointToRay (Input.mousePosition);
        RaycastHit hit;
        if (Physics.Raycast (ray, out hit))
        {
            Vector3 look = hit.point;
            look.z = 0;
            rotationTr.LookAt (look);
            actionSegment[0] = Mathf.Clamp(Mathf.RoundToInt(look.x),-24,24);
            actionSegment[1] = Mathf.Clamp (Mathf.RoundToInt (look.y), -24, 24);
        }
    }
```

**Comment by vincentpierre** [comment]
I think this line is problematic : `actionSegment[0] = Mathf.Clamp(Mathf.RoundToInt(look.x),-24,24);`
Discrete actions with a branch size of 50 will expect integers between 0 and 49, not between -24 and 24.
