### ISSUE TITLE
Errors with gym-unity

### ISSUE THREAD

**Issue by MrOCW** [Unity-Technologies/ml-agents#5330]
**Describe the bug**

**To Reproduce**
1. Installed baselines tf2 branch
2. Followed gym-unity example for DQN Baseline and PPO2 baseline

Error from DQN Baseline
```
2021-04-29 21:15:07.892841: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Found path: /home/ocw/mlagents/./envs/3DBallVisual.x86_64
2021-04-29 21:15:11 INFO [environment.py:113] Connected to Unity environment with package version 1.9.1-preview and communication version 1.5.0
Traceback (most recent call last):
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ocw/mlagents/train_unity.py", line 35, in <module>
    main()
  File "/home/ocw/mlagents/train_unity.py", line 11, in main
    env = UnityToGymWrapper(unity_env, 0, uint8_visual=True)
TypeError: __init__() got multiple values for argument 'uint8_visual'
```

Based on source code (__init__.py), i removed 0 and the new error is

```
2021-04-29 21:17:38.682177: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Found path: /home/ocw/mlagents/./envs/3DBallVisual.x86_64
2021-04-29 21:17:42 INFO [environment.py:113] Connected to Unity environment with package version 1.9.1-preview and communication version 1.5.0
2021-04-29 21:17:43 INFO [environment.py:282] Connected new brain:
Visual3DBall?team=0
Logging to ./logs
Traceback (most recent call last):
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ocw/mlagents/train_unity.py", line 35, in <module>
    main()
  File "/home/ocw/mlagents/train_unity.py", line 29, in main
    dueling=True
  File "/home/ocw/baselines/baselines/deepq/deepq.py", line 125, in learn
    num_actions=env.action_space.n,
AttributeError: 'Box' object has no attribute 'n'
2021-04-29 21:17:45 INFO [environment.py:429] Environment shut down with return code 0.
```
Error from PPO2 exactly the same
```
2021-04-29 21:19:04.853812: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-04-29 21:19:06.559333: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Found path: /home/ocw/mlagents/./envs/3DBallVisual.x86_64
2021-04-29 21:19:10 INFO [environment.py:113] Connected to Unity environment with package version 1.9.1-preview and communication version 1.5.0
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ocw/baselines/baselines/common/vec_env/subproc_vec_env.py", line 9, in worker
    env = env_fn_wrapper.x()
  File "/home/ocw/mlagents/train_unity.py", line 23, in _thunk
    env = UnityToGymWrapper(unity_env, rank, uint8_visual=True)
```
After removing the 'rank' argument from UnityToGymWrapper:
```
2021-04-29 21:20:17.914220: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-04-29 21:20:19.455085: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Found path: /home/ocw/mlagents/./envs/3DBallVisual.x86_64
2021-04-29 21:20:23 INFO [environment.py:113] Connected to Unity environment with package version 1.9.1-preview and communication version 1.5.0
2021-04-29 21:20:23 INFO [environment.py:282] Connected new brain:
Visual3DBall?team=0
Logging to /tmp/openai-2021-04-29-21-20-23-714866
input shape is (84, 84, 12)
2021-04-29 21:20:23.729393: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-29 21:20:23.730323: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-04-29 21:20:23.763294: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-29 21:20:23.763826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7715GHz coreCount: 10 deviceMemorySize: 5.93GiB deviceMemoryBandwidth: 178.99GiB/s
2021-04-29 21:20:23.763877: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-04-29 21:20:23.766867: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-04-29 21:20:23.766964: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-04-29 21:20:23.768839: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-04-29 21:20:23.769149: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-04-29 21:20:23.771563: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-04-29 21:20:23.772125: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-04-29 21:20:23.772298: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-04-29 21:20:23.772427: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-29 21:20:23.772862: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-29 21:20:23.773235: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-04-29 21:20:23.773684: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-29 21:20:23.773800: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-29 21:20:23.774151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7715GHz coreCount: 10 deviceMemorySize: 5.93GiB deviceMemoryBandwidth: 178.99GiB/s
2021-04-29 21:20:23.774179: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-04-29 21:20:23.774234: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-04-29 21:20:23.774272: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-04-29 21:20:23.774308: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-04-29 21:20:23.774326: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-04-29 21:20:23.774344: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-04-29 21:20:23.774362: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-04-29 21:20:23.774380: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-04-29 21:20:23.774440: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-29 21:20:23.774846: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-29 21:20:23.775168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-04-29 21:20:23.775210: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-04-29 21:20:24.232438: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-29 21:20:24.232472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-04-29 21:20:24.232479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-04-29 21:20:24.232680: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-29 21:20:24.233115: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-29 21:20:24.233493: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-29 21:20:24.233843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4953 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ocw/mlagents/train_unity.py", line 43, in <module>
    main()
  File "/home/ocw/mlagents/train_unity.py", line 39, in main
    lr=1e-3,
  File "/home/ocw/baselines/baselines/ppo2/ppo2.py", line 143, in learn
    obs, returns, masks, actions, values, neglogpacs, states, epinfos = runner.run() #pylint: disable=E0632
  File "/home/ocw/baselines/baselines/ppo2/runner.py", line 31, in run
    actions, values, self.states, neglogpacs = self.model.step(obs)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3887, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/ocw/baselines/baselines/common/policies.py:61 step  *
        vf = tf.squeeze(self.value_fc(value_latent), axis=1)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:4431 squeeze_v2
        return squeeze(input, axis, name)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:538 new_func
        return func(*args, **kwargs)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:4379 squeeze
        return gen_array_ops.squeeze(input, axis, name)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py:10173 squeeze
        "Squeeze", input=input, squeeze_dims=axis, name=name)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:750 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:592 _create_op_internal
        compute_device)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:3536 _create_op_internal
        op_def=op_def)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:2016 __init__
        control_input_ops, op_def)
    /home/ocw/anaconda3/envs/mlagents/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1856 _create_c_op
        raise ValueError(str(e))

    ValueError: Can not squeeze dim[1], expected a dimension of 1, got 84 for '{{node Squeeze}} = Squeeze[T=DT_FLOAT, squeeze_dims=[1]](dense_1/BiasAdd)' with input shapes: [1,84,84,1].

Exception ignored in: <function SubprocVecEnv.__del__ at 0x7f4303b18050>
Traceback (most recent call last):
  File "/home/ocw/baselines/baselines/common/vec_env/subproc_vec_env.py", line 107, in __del__
    self.close()
  File "/home/ocw/baselines/baselines/common/vec_env/vec_env.py", line 98, in close
    self.close_extras()
  File "/home/ocw/baselines/baselines/common/vec_env/subproc_vec_env.py", line 91, in close_extras
    remote.send(('close', None))
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/ocw/anaconda3/envs/mlagents/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Environment:**
- Unity Version: Unity 2020.3.5f1
- OS + version: Ubuntu 18.04
- _ML-Agents version_: ML-Agents v1.9.1
- _Torch version_: 1.8.1
- _Environment_: Visual3DBall

**Comment by vincentpierre** [comment]
> Error from DQN Baseline

Looks like you were able to fix the error

> Based on source code (init.py), i removed 0 and the new error is

It looks like DQN is expecting a discrete action space (illustrated by the `.n`) but the gym environment provided a continuous action space (Box). I. think you need either make your environment discrete or somehow discretize your action space to be able to use DQN. I am able to train with an environment that has a single discrete action

Regarding the error with PPO2, I do not know what this error is. It looks like the observation is of the wrong dimension. The training seemed to start properly for me with an environment with a single visual observation and 4 discrete actions (on a single branch). But I had to change the environment creation method : 
```
    def make_env(rank, use_visual=True): # pylint: disable=C0111
        def _thunk():
            unity_env = UnityEnvironment(env_directory, base_port=5000 + rank)
            env = UnityToGymWrapper(unity_env, uint8_visual=True)
            env = Monitor(env, logger.get_dir() and os.path.join(logger.get_dir(), str(rank)))
            return env
```

**Comment by MrOCW** [comment]
Thanks @vincentpierre , following your code, PPO2 is running on my own environment with 2 continuous actions and 1 CameraSensor. However, while running, i dont seem to get any logs of the results while training. I tried setting this as the arguments,
```
ppo2.learn(
        network="cnn",
        env=env,
        total_timesteps=5000,
        lr=1e-3,
        log_interval=1000,
        save_interval=25000)
```

Only at the end of training, I get this
-------------------------------------------------
| eplenmean                      | 25.5        |
| eprewmean                     | 1.17        |
| fps                                   | 42           |
| loss/approxkl                   | 0.00469  |
| loss/clipfrac                     | 0.0546    |
| loss/policy_entropy         | 2.84        |
| loss/policy_loss               | -0.0039   |
| loss/value_loss                | 2.75        |
| misc/explained_variance | -0.0158   |
| misc/nupdates                 | 1              |
| misc/serial_timesteps      | 2.05e+03 |
| misc/time_elapsed           | 96.2         |
| misc/total_timesteps        | 4.1e+03   |
--------------------------------------------------
Saving to ./logs/checkpoints/00001

What is that 00001 file and how do I use it for inference?

Could you also provide an example of using DDPG as well? or even better, integrate it into mlagents

**Comment by vincentpierre** [comment]
Hi @MrOCW I am glad you were able to run PPO2 !

> What is that 00001 file

I do not know, I think this is a question more suitable for the baseline authors. My guess is that this is where the weights of the models are being saved.

> how do I use it for inference

We do not support running inference on models that have not been trained with our trainers. I think it would be possible if you converted the model to ONNX and renamed all the inputs and outputs of the models in our format but we do not support this use case.

> Could you also provide an example of using DDPG as well? or even better, integrate it into mlagents

Integrating our own implementation of DDPG would be a relatively important amount of work without a clear benefit to our users. What are some benefits you see in having an implementation of DDPG in addition to PPO and SAC?

**Comment by MrOCW** [comment]
> Integrating our own implementation of DDPG would be a relatively important amount of work without a clear benefit to our users. What are some benefits you see in having an implementation of DDPG in addition to PPO and SAC?

I'm working on a project which I hope to be able to compare several RL algorithms on top of PPO and SAC but of course, no complaints with what ML-Agents is already offering, just being a little greedy here :P 

Thanks so much @vincentpierre !
