### ISSUE TITLE
Environment shut down with return code

### ISSUE THREAD

**Issue by hyuDev** [Unity-Technologies/ml-agents#5357]
hi I train the model with example code.
Until yesterday, mlagents-learn worked well, but suddenly it didn't work with this error code.

  File "c:\dev\ml-agents-release_14\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 98, in recv
    raise env_exception
mlagents_envs.exception.UnityEnvironmentException: Environment shut down with return code xxx.

I haven't updated anything, and nothing has changed, what's wrong with you?
The returned code is 0 or 3221225477.

**Comment by chriselion** [comment]
Please don't spam the same question in [multiple](https://github.com/Unity-Technologies/ml-agents/issues/5349#issuecomment-840347064) [places](https://github.com/Unity-Technologies/ml-agents/pull/4880#issuecomment-840249346).

SIGABRT (from one of your other messages) means the environment crashed. You'll need to look in the player logs for a better idea of what caused that.

If you're running VisualPushBlock, it's likely a problem with your graphics setup.

**Comment by hyuDev** [comment]
@chriselion 
Hi I know already that SIGABRT (from one of your other messages) means the environment crashed.
I don't know why the environment crashed, because I didn't fix anything, and all the settings are in the state where the project is saved. 
If my graphic setting(or setup) is a problem, where and how should I fix it? the problem happened all os( window, ubuntu, mac os) What information do you think it will be easy for me to solve this problem? 

Just in case, I'm leaving behind the command and debug results.

(ml-agents) BBookPro:python B$ mlagents-learn /Users/B/Downloads/ml-agents-release_14/config/ppo/VisualPushBlock.yaml  --env="vi14_0513" --run-id=push_051 --debug


                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓

        
 Version information:
  ml-agents: 0.24.1,
  ml-agents-envs: 0.24.1,
  Communicator API: 1.4.0,
  PyTorch: 1.7.1
2021-05-14 09:55:25 DEBUG [learn.py:220] Configuration for this run:
2021-05-14 09:55:25 DEBUG [learn.py:221] {
    "default_settings": null,
    "behaviors": {
        "VisualPushBlock": {
            "trainer_type": "ppo",
            "hyperparameters": {
                "batch_size": 64,
                "buffer_size": 1024,
                "learning_rate": 0.0003,
                "beta": 0.01,
                "epsilon": 0.2,
                "lambd": 0.95,
                "num_epoch": 3,
                "learning_rate_schedule": "linear"
            },
            "network_settings": {
                "normalize": false,
                "hidden_units": 128,
                "num_layers": 1,
                "vis_encode_type": "simple",
                "memory": {
                    "sequence_length": 32,
                    "memory_size": 128
                }
            },
            "reward_signals": {
                "extrinsic": {
                    "gamma": 0.99,
                    "strength": 1.0
                }
            },
            "init_path": null,
            "keep_checkpoints": 5,
            "checkpoint_interval": 500000,
            "max_steps": 3000000,
            "time_horizon": 64,
            "summary_freq": 60000,
            "threaded": true,
            "self_play": null,
            "behavioral_cloning": null
        }
    },
    "env_settings": {
        "env_path": "vi14_0513",
        "env_args": null,
        "base_port": 5005,
        "num_envs": 1,
        "seed": -1
    },
    "engine_settings": {
        "width": 84,
        "height": 84,
        "quality_level": 5,
        "time_scale": 20,
        "target_frame_rate": -1,
        "capture_frame_rate": 60,
        "no_graphics": false
    },
    "environment_parameters": null,
    "checkpoint_settings": {
        "run_id": "push_051",
        "initialize_from": null,
        "load_model": false,
        "resume": false,
        "force": true,
        "train_model": false,
        "inference": false,
        "results_dir": "results"
    },
    "torch_settings": {
        "device": null
    },
    "debug": true
}
2021-05-14 09:55:25 INFO [learn.py:245] run_seed set to 7444
2021-05-14 09:55:25 INFO [torch.py:58] default Torch device: cpu
2021-05-14 09:55:25 DEBUG [stats_writer.py:59] Initializing StatsWriter plugins: default
2021-05-14 09:55:25 DEBUG [stats_writer.py:63] Found 3 StatsWriters for plugin default
2021-05-14 09:55:25 DEBUG [env_utils.py:33] The true file name is vi14_0513
2021-05-14 09:55:25 DEBUG [env_utils.py:105] The launch string is /Users/B/Downloads/ml-agents-release_14/python/vi14_0513.app/Contents/MacOS/UnityEnvironment
2021-05-14 09:55:25 DEBUG [env_utils.py:106] Running with args ['--mlagents-port', '5005', '-logFile', '/Users/B/Downloads/ml-agents-release_14/python/results/push_051/run_logs/Player-0.log']
2021-05-14 09:55:26 INFO [environment.py:112] Connected to Unity environment with package version 1.8.1-preview and communication version 1.4.0
2021-05-14 09:55:32 INFO [subprocess_env_manager.py:220] UnityEnvironment worker 0: environment stopping.
2021-05-14 09:55:32 DEBUG [subprocess_env_manager.py:234] UnityEnvironment worker 0 closing.
2021-05-14 09:55:32 INFO [trainer_controller.py:188] Learning was interrupted. Please wait while the graph is generated.
2021-05-14 09:55:32 INFO [trainer_controller.py:81] Saved Model
2021-05-14 09:55:32 DEBUG [subprocess_env_manager.py:368] SubprocessEnvManager closing.
2021-05-14 09:55:32 INFO [environment.py:426] Environment shut down with return code -6 (SIGABRT).
2021-05-14 09:55:32 DEBUG [subprocess_env_manager.py:237] UnityEnvironment worker 0 done.
Traceback (most recent call last):
  File "/Users/B/opt/anaconda3/envs/ml-agents/bin/mlagents-learn", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents/mlagents/trainers/learn.py", line 250, in main
    run_cli(parse_command_line())
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents/mlagents/trainers/learn.py", line 246, in run_cli
    run_training(run_seed, options)
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents/mlagents/trainers/learn.py", line 125, in run_training
    tc.start_learning(env_manager)
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents/mlagents/trainers/trainer_controller.py", line 197, in start_learning
    raise ex
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents/mlagents/trainers/trainer_controller.py", line 173, in start_learning
    self._reset_env(env_manager)
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents/mlagents/trainers/trainer_controller.py", line 105, in _reset_env
    env_manager.reset(config=new_config)
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents/mlagents/trainers/env_manager.py", line 68, in reset
    self.first_step_infos = self._reset_env(config)
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 333, in _reset_env
    ew.previous_step = EnvironmentStep(ew.recv().payload, ew.worker_id, {}, {})
  File "/Users/B/Downloads/ml-agents-release_14/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 98, in recv
    raise env_exception
mlagents_envs.exception.UnityEnvironmentException: Environment shut down with return code -6 (SIGABRT).

**Comment by chriselion** [comment]
You'll need to look in the player logs for more details; generally there will be a stack trace. This line tells you where they are saved:
```
2021-05-14 09:55:25 DEBUG [env_utils.py:106] Running with args ['--mlagents-port', '5005', '-logFile', '/Users/B/Downloads/ml-agents-release_14/python/results/push_051/run_logs/Player-0.log']
```
