### ISSUE TITLE
RollerBall cant be trained 

### ISSUE THREAD

**Issue by Albert950207** [Unity-Technologies/ml-agents#5518]
Hi, I followed the instructions in Design a New Learning Environment to build a Rollerball project. I did 3-D ball demo before. Training model and run pre-trained  model can totally work in that demo but when I trained the rollerball agent  I got these error:

Version information:
  ml-agents: 0.27.0,
  ml-agents-envs: 0.27.0,
  Communicator API: 1.5.0,
  PyTorch: 1.8.1+cu102
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
[INFO] Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0
[INFO] Connected new brain: RollerBall?team=0
[INFO] Hyperparameters for behavior name RollerBall: 
	trainer_type:	ppo
	hyperparameters:	
	  batch_size:	10
	  buffer_size:	100
	  learning_rate:	0.0003
	  beta:	0.0005
	  epsilon:	0.2
	  lambd:	0.99
	  num_epoch:	3
	  learning_rate_schedule:	linear
	network_settings:	
	  normalize:	False
	  hidden_units:	128
	  num_layers:	2
	  vis_encode_type:	simple
	  memory:	None
	  goal_conditioning_type:	hyper
	reward_signals:	
	  extrinsic:	
	    gamma:	0.99
	    strength:	1.0
	    network_settings:	
	      normalize:	False
	      hidden_units:	128
	      num_layers:	2
	      vis_encode_type:	simple
	      memory:	None
	      goal_conditioning_type:	hyper
	init_path:	None
	keep_checkpoints:	5
	checkpoint_interval:	500000
	max_steps:	500000
	time_horizon:	64
	summary_freq:	10000
	threaded:	False
	self_play:	None
	behavioral_cloning:	None
[INFO] Exported results/RollerBall1/RollerBall/RollerBall-0.onnx
[INFO] Copied results/RollerBall1/RollerBall/RollerBall-0.onnx to results/RollerBall1/RollerBall.onnx.
Traceback (most recent call last):
  File "/home/bohan/anaconda3/bin/mlagents-learn", line 8, in <module>
    sys.exit(main())
  File "/home/bohan/anaconda3/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 250, in main
    run_cli(parse_command_line())
  File "/home/bohan/anaconda3/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 246, in run_cli
    run_training(run_seed, options)
  File "/home/bohan/anaconda3/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 125, in run_training
    tc.start_learning(env_manager)
  File "/home/bohan/anaconda3/lib/python3.7/site-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/bohan/anaconda3/lib/python3.7/site-packages/mlagents/trainers/trainer_controller.py", line 176, in start_learning
    n_steps = self.advance(env_manager)
  File "/home/bohan/anaconda3/lib/python3.7/site-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/bohan/anaconda3/lib/python3.7/site-packages/mlagents/trainers/trainer_controller.py", line 234, in advance
    new_step_infos = env_manager.get_steps()
  File "/home/bohan/anaconda3/lib/python3.7/site-packages/mlagents/trainers/env_manager.py", line 124, in get_steps
    new_step_infos = self._step()
  File "/home/bohan/anaconda3/lib/python3.7/site-packages/mlagents/trainers/subprocess_env_manager.py", line 310, in _step
    raise env_exception
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents' Behavior Parameters > Behavior Type is set to "Default"
	 The environment and the Python interface have compatible versions.

Environment (please complete the following information):
- Unity Version: 2021.1.15f
- OS + version:  Ubuntu 20.04
  ml-agents: 0.27.0,
  ml-agents-envs: 0.27.0,
  Communicator API: 1.5.0,
  PyTorch: 1.8.1+cu102

**Comment by mmattar** [comment]
@Albert950207 - to confirm, did you add a DecisionRequester component to your agent as outlined in the [Final Step](https://github.com/Unity-Technologies/ml-agents/blob/release_18_docs/docs/Learning-Environment-Create-New.md#final-agent-setup-in-editor)?

**Comment by RedTachyon** [comment]
@Albert950207 Do you have http_proxy and/or https_proxy environment variables set to something? I just had a similar problem, and I had to remove them for a training to work.

**Comment by mmattar** [comment]
Closing this issue due to lack of activity - but please feel free to re-open or post a new one if you're still running into issues. Thanks!
