### ISSUE TITLE
PyTorch Reserving All Available RAM as Training Progresses

### ISSUE THREAD

**Issue by Nirav-Madhani** [Unity-Technologies/ml-agents#5524]
**Describe the bug**
As I leave my environment to train and some time passes, more and more ram is being eaten up and after some steps training process stops. I think there is some problem somewhere with de allocating the memory.

**To Reproduce**
1.Use ml-agents version:

  ml-agents: 0.27.0,
  ml-agents-envs: 0.27.0,
  Communicator API: 1.5.0,
  PyTorch: 1.8.1+cu102
Try training any agent that uses camera sensor.

My config file.
```
behaviors:
  TRC:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2560
      learning_rate: 0.003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: resnet
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003      
    keep_checkpoints: 5
    max_steps: 15000
    time_horizon: 64   
    summary_freq: 250
```

**Console logs / stack traces**
```
Traceback (most recent call last):
  File "/usr/local/bin/mlagents-learn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/learn.py", line 250, in main
    run_cli(parse_command_line())
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/learn.py", line 246, in run_cli
    run_training(run_seed, options)
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/learn.py", line 125, in run_training
    tc.start_learning(env_manager)
  File "/usr/local/lib/python3.7/dist-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/trainer_controller.py", line 176, in start_learning
    n_steps = self.advance(env_manager)
  File "/usr/local/lib/python3.7/dist-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/trainer_controller.py", line 251, in advance
    trainer.advance()
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/trainer/rl_trainer.py", line 315, in advance
    if self._update_policy():
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/ppo/trainer.py", line 202, in _update_policy
    buffer.make_mini_batch(i, i + batch_size), n_sequences
  File "/usr/local/lib/python3.7/dist-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/ppo/optimizer_torch.py", line 136, in update
    sequence_length=self.policy.sequence_length,
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/torch/networks.py", line 475, in critic_pass
    inputs, memories=memories, sequence_length=sequence_length
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/torch/networks.py", line 487, in forward
    inputs, actions, memories, sequence_length
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/torch/networks.py", line 238, in forward
    encoded_self = self.observation_encoder(inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/torch/networks.py", line 111, in forward
    processed_obs = processor(obs_input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/torch/encoders.py", line 296, in forward
    hidden = self.sequential(visual_obs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mlagents/trainers/torch/encoders.py", line 264, in forward
    return input_tensor + self.layers(input_tensor)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 11.17 GiB total capacity; 10.13 GiB already allocated; 59.81 MiB free; 10.67 GiB reserved in total by PyTorch)
```

**Screenshots**
Not Applicable

**Environment (please complete the following information):**
ml-agents: 0.27.0,
ml-agents-envs: 0.27.0,
Communicator API: 1.5.0,
PyTorch: 1.8.1+cu102
OS : Windows 10 (Same problem while training on Google Colab [some Linux ig])

**Comment by mmattar** [comment]
Thanks for sharing this @Nirav-Madhani. Do you recall how much memory was being utilized? Additionally, I presume you were experiencing this with one of our demo environments or was it your own environment?

**Comment by Nirav-Madhani** [comment]
Percent wise? Almost above 95 on Both my PC and Colab.. that would be about 14 and 10.5 approx. And it was my custom environment. I can try to reproduce again with demo environment if u want.

**Comment by Nirav-Madhani** [comment]
For anyone facing the same problem, I've found temporary work around, just: run train command multiple times, with help of shell script or just copy paste something like this in shell
```
mlagents-learn config\ppo\TRC.yaml --run-id=TRC --force --time-scale 10
mlagents-learn config\ppo\TRC.yaml --run-id=TRC --resume  --time-scale 10
mlagents-learn config\ppo\TRC.yaml --run-id=TRC --resume  --time-scale 10
mlagents-learn config\ppo\TRC.yaml --run-id=TRC --resume  --time-scale 10
mlagents-learn config\ppo\TRC.yaml --run-id=TRC --resume  --time-scale 10
mlagents-learn config\ppo\TRC.yaml --run-id=TRC --resume  --time-scale 10
mlagents-learn config\ppo\TRC.yaml --run-id=TRC --resume  --time-scale 10
 
```

Depending on how soon Full ram is consumed, it will last a little longer, maybe in some cases long enough to finish max steps.
