### ISSUE TITLE
Env Error Ubuntu server

### ISSUE THREAD

**Issue by hxx1996** [Unity-Technologies/ml-agents#5551]
I put my executable env and config yaml in ubuntu server
The file directory is this:(These are all under userhome file)
![image](https://user-images.githubusercontent.com/38696314/134874277-c0e96e86-10ce-49b1-aa40-a616b174028c.png)
The run code is:
root@hanxx20210927-0:/userhome# mlagents-learn config/Tank-ppo.yaml --env=/userhome/envs/gridshell9/ppo_sp_9_gridshell.x86_64 --run-id=simple_shell9 --no-graphics --time-scale=40
 
The error:
Version information:
  ml-agents: 0.27.0,
  ml-agents-envs: 0.27.0,
  Communicator API: 1.5.0,
  PyTorch: 1.7.1+rocm3.8
[INFO] Learning was interrupted. Please wait while the graph is generated.
Traceback (most recent call last):
  File "/userhome/anaconda3/envs/unity/bin/mlagents-learn", line 8, in <module>
    sys.exit(main())
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 250, in main
    run_cli(parse_command_line())
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 246, in run_cli
    run_training(run_seed, options)
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 125, in run_training
    tc.start_learning(env_manager)
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents/trainers/trainer_controller.py", line 198, in start_learning
    raise ex
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents/trainers/trainer_controller.py", line 173, in start_learning
    self._reset_env(env_manager)
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents/trainers/trainer_controller.py", line 105, in _reset_env
env_manager.reset(config=new_config)
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents/trainers/env_manager.py", line 68, in reset
    self.first_step_infos = self._reset_env(config)
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents/trainers/subprocess_env_manager.py", line 333, in _reset_env
    ew.previous_step = EnvironmentStep(ew.recv().payload, ew.worker_id, {}, {})
  File "/userhome/anaconda3/envs/unity/lib/python3.7/site-packages/mlagents/trainers/subprocess_env_manager.py", line 98, in recv
    raise env_exception
mlagents_envs.exception.UnityEnvironmentException: Environment shut down with return code 1.

It's all debugged code.
I don't understand what went wrong, and there seems no doc about how to train on linux server

**Comment by mahon94** [comment]
Hi @hxx1996,
Can you verify if this does happen in one of our example environments?
