### ISSUE TITLE
Environment stops training - Error 3221225477

### ISSUE THREAD

**Issue by yiorgosl** [Unity-Technologies/ml-agents#5675]
Hello.
I have created a Unity environment with agents, and I want to train for 15.000.000 steps.
Though when I start training (on development build - no graphics), it always stops at
3.725.000 steps. And it give me this log:
[INFO] Learning was interrupted. Please wait while the graph is generated.
Traceback (most recent call last):
File "C:\Users\User\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\User\anaconda3\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\User\anaconda3\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
File "C:\Users\User\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 250, in main
run_cli(parse_command_line())
File "C:\Users\User\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 246, in run_cli
run_training(run_seed, options)
File "C:\Users\User\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 125, in run_training
tc.start_learning(env_manager)
File "C:\Users\User\anaconda3\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
return func(*args, **kwargs)
File "C:\Users\User\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 198, in start_learning
raise ex
File "C:\Users\User\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 176, in start_learning
n_steps = self.advance(env_manager)
File "C:\Users\User\anaconda3\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
return func(*args, **kwargs)
File "C:\Users\User\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 234, in advance
new_step_infos = env_manager.get_steps()
File "C:\Users\User\anaconda3\lib\site-packages\mlagents\trainers\env_manager.py", line 124, in get_steps
new_step_infos = self._step()
File "C:\Users\User\anaconda3\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 310, in _step
raise env_exception
mlagents_envs.exception.UnityEnvironmentException: Environment shut down with return code 3221225477.

I have latest versions of Unity, Ml agents etc.
Thank you.

**Comment by kkalera** [comment]
I'm not entirely sure about the issue but I have a few things in mind that you could check:

1. If you used a demonstration recorder , make sure that it's not still active. If your recorder is set to record 3.725.000 steps, it will interrupt the training when its recording has finished.
2. Make sure you don't have a memory leak. I've had an issue in the past when changing materials using `renderer.Material` causing a memory leak and interrupting learning after a large number of steps. If this is something that's used in your code, change it to `renderer.SharedMaterial`

Hope this helps

**Comment by yiorgosl** [comment]
Thanks for the answer.
I will try to look into them.
Its true I have a material change, so i will try to change that.
