### ISSUE TITLE
Python 3.9.10 causes mlagents-learn not to work

### ISSUE THREAD

**Issue by jimlbeaver** [Unity-Technologies/ml-agents#5689]
using mlagents-learn  on python 3.9.10 on windows causes the following error:
"TypeError: Invalid first argument to `register()`. typing.Dict[mlagents.trainers.settings.RewardSignalType, mlagents.trainers.settings.RewardSignalSettings] is not a class."

reported here:
https://forum.unity.com/threads/cant-train-3dball-or-anything-else.1228128/

From release notes of 3.9.10:
bpo-46032: The registry() method of functools.singledispatch() functions checks now the first argument or the first parameter annotation and raises a TypeError if it is not supported. Previously unsupported “types” were ignored (e.g. typing.List[int]) or caused an error at calling time (e.g. list[int]).

bug tracker from python:
https://bugs.python.org/issue46032

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2020.3f1]
- OS + version: [e.g. Windows 10]
- _ML-Agents version_:  branch 19 (same thing happened on branch 18)

**Comment by jimlbeaver** [comment]
call stack:


Python: 3.9.10
Torch: 1.7.1+cu110

Is there anyone that have an idea of what's going on?



(env) C:\Exjobb\ml-agents\ml-agents-main>mlagents-learn config/ppo/3DBall.yaml --run-id=fi

Traceback (most recent call last):

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "C:\Exjobb\unity\env\Scripts\mlagents-learn.exe\__main__.py", line 4, in <module>

  File "C:\Exjobb\unity\env\lib\site-packages\mlagents\trainers\learn.py", line 2, in <module>

    from mlagents import torch_utils

  File "C:\Exjobb\unity\env\lib\site-packages\mlagents\torch_utils\__init__.py", line 1, in <module>

    from mlagents.torch_utils.torch import torch as torch  # noqa

  File "C:\Exjobb\unity\env\lib\site-packages\mlagents\torch_utils\torch.py", line 6, in <module>

    from mlagents.trainers.settings import TorchSettings

  File "C:\Exjobb\unity\env\lib\site-packages\mlagents\trainers\settings.py", line 644, in <module>

    class TrainerSettings(ExportableSettings):

  File "C:\Exjobb\unity\env\lib\site-packages\mlagents\trainers\settings.py", line 667, in TrainerSettings

    cattr.register_structure_hook(

  File "C:\Exjobb\unity\env\lib\site-packages\cattr\converters.py", line 207, in register_structure_hook

    self._structure_func.register_cls_list([(cl, func)])

  File "C:\Exjobb\unity\env\lib\site-packages\cattr\dispatch.py", line 55, in register_cls_list

    self._single_dispatch.register(cls, handler)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\functools.py", line 855, in register

    raise TypeError(

TypeError: Invalid first argument to `register()`. typing.Dict[mlagents.trainers.settings.RewardSignalType, mlagents.trainers.settings.RewardSignalSettings] is not a class.

**Comment by maryamhonari** [comment]
### **Hi** [**jimlbeaver**](https://github.com/jimlbeaver)**,**

**Thanks for bringing up this issue. Python 3.9.10 is fairly new and while we're looking into it, I suggest installing with an older version of python if possible.**

**Comment by ignace-shoeib** [comment]
this also happens in python 3.10.2

**Comment by maryamhonari** [comment]
new python version mlagents==0.29.0 and mlagents_env==0.29.0 should fix this issue.
