### ISSUE TITLE
Got RuntimeError: Class values must be smaller than num_classes when using demo file

### ISSUE THREAD

**Issue by liu1700** [Unity-Technologies/ml-agents#5700]
Here is the whole trace.

Traceback (most recent call last):
  File "C:\Users\YCL\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\YCL\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Projects\BattleBots\venv\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\learn.py", line 260, in main
    run_cli(parse_command_line())
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\learn.py", line 256, in run_cli
    run_training(run_seed, options, num_areas)
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\learn.py", line 132, in run_training
    tc.start_learning(env_manager)
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\trainer_controller.py", line 176, in start_learning
    n_steps = self.advance(env_manager)
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\trainer_controller.py", line 251, in advance
    trainer.advance()
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\trainer\rl_trainer.py", line 315, in advance
    if self._update_policy():
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 212, in _update_policy
    update_stats = self.optimizer.bc_module.update()
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\torch\components\bc\module.py", line 93, in update
    run_out = self._update_batch(mini_batch_demo, self.n_sequences)
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\torch\components\bc\module.py", line 175, in _update_batch
    bc_loss = self._behavioral_cloning_loss(
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\torch\components\bc\module.py", line 116, in _behavioral_cloning_loss
    one_hot_expert_actions = ModelUtils.actions_to_onehot(
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\torch\utils.py", line 285, in actions_to_onehot
    onehot_branches = [
  File "D:\Projects\BattleBots\venv\lib\site-packages\mlagents\trainers\torch\utils.py", line 286, in <listcomp>
    torch.nn.functional.one_hot(_act.T, action_size[i]).float()
RuntimeError: Class values must be smaller than num_classes.`

Here is my training config:

behaviors:
  BattleBot:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
      gail:
        gamma: 0.99
        strength: 1
        demo_path: BattleBotBrain/BattleSeeker.demo
    behavioral_cloning:
      strength: 1
      demo_path: BattleBotBrain/BattleSeeker.demo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000

And I attached my demo file

[BattleSeeker.zip](https://github.com/Unity-Technologies/ml-agents/files/7999371/BattleSeeker.zip)

**Comment by miguelalonsojr** [comment]
Hi! Thanks for reaching out. Unfortunately, we are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue. This would help us determine track the issue down an determine if it's within the ML-Agents toolkit.
