### ISSUE TITLE
The option ï»¿behaviors was specified in your YAML file, but is invalid.

### ISSUE THREAD

**Issue by dherault** [Unity-Technologies/ml-agents#5710]
**Describe the bug**
When launching training, the following message appears:
```
The option ï»¿behaviors was specified in your YAML file, but is invalid.
```

**To Reproduce**
1. Use a python environment
2. Install using the installation instructions
3. Use this config:
```yaml
behaviors:
  MobAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 29836
      num_layers: 6
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 12000
```
4. Run `mlagents-learn MobAgent.yaml --run-id=chanceRun`

**Console logs / stack traces**
```
 mlagents-learn MobAgent.yaml --run-id=chanceRun
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shadow\phenomenom\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\shadow\phenomenom\lib\site-packages\mlagents\trainers\learn.py", line 260, in main
    run_cli(parse_command_line())
  File "c:\users\shadow\phenomenom\lib\site-packages\mlagents\trainers\learn.py", line 52, in parse_command_line
    return RunOptions.from_argparse(args)
  File "c:\users\shadow\phenomenom\lib\site-packages\mlagents\trainers\settings.py", line 929, in from_argparse
    key
mlagents.trainers.exception.TrainerConfigError: The option ï»¿behaviors was specified in your YAML file, but is invalid.
```

**Environment:**
- Unity Version: 2020.3.28f1
- OS + version: Windows 10
  ml-agents: 0.28.0,
  ml-agents-envs: 0.28.0,
  Communicator API: 1.5.0,
  PyTorch: 1.7.1+cu110

**Comment by jrupert-unity** [comment]
Your editor might be adding these characters that are giving the ml-agents trainer problems.  Have a look at [this link](https://stackoverflow.com/questions/3255993/how-do-i-remove-%C3%AF-from-the-beginning-of-a-file) and see if it helps you address the problem.

**Comment by dherault** [comment]
That helped and fixed it.
On rider, choose file --> encoding --> utf-8
Thanks @jrupert-unity
