### ISSUE TITLE
Import Error: incompatible architecture (have 'x86_64', need 'arm64e')

### ISSUE THREAD

**Issue by Antoine-Lee** [Unity-Technologies/ml-agents#5754]
Hi everyone, 

I'm having an issue when running mlagents-learn on an M1 Macbook Pro. There is an import error regarding incompatible architecture. 

```
Traceback (most recent call last):
  File "/Users/antoinelee/Desktop/Unity/ESPR Asymmetrical Game 2/venv/bin/mlagents-learn", line 7, in <module>
    from mlagents.trainers.learn import main
  File "/Users/antoinelee/Desktop/Unity/ESPR Asymmetrical Game 2/venv/lib/python3.8/site-packages/mlagents/trainers/learn.py", line 2, in <module>
    from mlagents import torch_utils
  File "/Users/antoinelee/Desktop/Unity/ESPR Asymmetrical Game 2/venv/lib/python3.8/site-packages/mlagents/torch_utils/__init__.py", line 1, in <module>
    from mlagents.torch_utils.torch import torch as torch  # noqa
  File "/Users/antoinelee/Desktop/Unity/ESPR Asymmetrical Game 2/venv/lib/python3.8/site-packages/mlagents/torch_utils/torch.py", line 34, in <module>
    import torch  # noqa I201
  File "/Users/antoinelee/Desktop/Unity/ESPR Asymmetrical Game 2/venv/lib/python3.8/site-packages/torch/__init__.py", line 196, in <module>
    from torch._C import *
ImportError: dlopen(/Users/antoinelee/Desktop/Unity/ESPR Asymmetrical Game 2/venv/lib/python3.8/site-packages/torch/_C.cpython-38-darwin.so, 0x0002): tried: '/Users/antoinelee/Desktop/Unity/ESPR Asymmetrical Game 2/venv/lib/python3.8/site-packages/torch/_C.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_C.cpython-38-darwin.so' (no such file), '/usr/lib/_C.cpython-38-darwin.so' (no such file)
```

- Unity Version: Unity 2021.3.4f1
- OS + version: macOS Monterey Version 12.2.1
- ML-Agents version: 0.27.0
- Torch version: 1.8.1

Does anyone know a solution to this? 
Thank you!

**Comment by miguelalonsojr** [comment]
We currently do not have full support for M1 macs. We'll be looking into adding support over the next few quarters.
