### ISSUE TITLE
Error with "mlagents-learn"

### ISSUE THREAD

**Issue by yasinmasmoudi** [Unity-Technologies/ml-agents#5800]
Hello,
I just started with ML Agents and when I try to run "mlagents-learn" I get the following error :

 Version information:
  ml-agents: 0.28.0,
  ml-agents-envs: 0.28.0,
  Communicator API: 1.5.0,
  PyTorch: 1.7.1+cu110
Traceback (most recent call last):
  File "C:\Users\Yasin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Yasin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Arbeit\IMA\BauML\ML-Agent First Steps\ML-Agent-FirstSteps\venv\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "D:\Arbeit\IMA\BauML\ML-Agent First Steps\ML-Agent-FirstSteps\venv\lib\site-packages\mlagents\trainers\learn.py", line 260, in main
    run_cli(parse_command_line())
  File "D:\Arbeit\IMA\BauML\ML-Agent First Steps\ML-Agent-FirstSteps\venv\lib\site-packages\mlagents\trainers\learn.py", line 256, in run_cli
    run_training(run_seed, options, num_areas)
  File "D:\Arbeit\IMA\BauML\ML-Agent First Steps\ML-Agent-FirstSteps\venv\lib\site-packages\mlagents\trainers\learn.py", line 89, in run_training
    stats_writers = register_stats_writer_plugins(options)
  File "D:\Arbeit\IMA\BauML\ML-Agent First Steps\ML-Agent-FirstSteps\venv\lib\site-packages\mlagents\plugins\stats_writer.py", line 47, in register_stats_writer_plugins
    if ML_AGENTS_STATS_WRITER not in importlib_metadata.entry_points():
  File "D:\Arbeit\IMA\BauML\ML-Agent First Steps\ML-Agent-FirstSteps\venv\lib\site-packages\importlib_metadata\__init__.py", line 260, in __eq__
    return self._key() == other._key()
AttributeError: 'str' object has no attribute '_key'

This is what I did so far :
I am using windows, I opened Cmd in my project directory and executed the following commands :
- py -m venv venv
- venv\scripts\activate
- py -m pip install --upgrade pip
- pip3 --no-cache-dir install torch~=1.7.1 -f https://download.pytorch.org/whl/torch_stable.html
- python -m pip install mlagents==0.28.0

I tried mlagents-learn --help and got the following :
![image](https://user-images.githubusercontent.com/74429356/195846250-5dd89595-7d3e-4098-9a7d-b7bbf8afc477.png)
![image](https://user-images.githubusercontent.com/74429356/195846316-a240b2d5-d2c0-4ec9-8f7d-3b95b1fda0c4.png)
![image](https://user-images.githubusercontent.com/74429356/195846455-d3fdbc3b-17f8-483a-a859-c1a6b422d402.png)

I am using : Python 3.7.8rc1 (tags/v3.7.8rc1:5f3933d61d, Jun 17 2020, 16:59:29) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by yasinmasmoudi** [comment]
I got to solve the Porblem thx to @LeezPayne on this post : https://github.com/Unity-Technologies/ml-agents/issues/5794

Quote "It seems that ml-agents depends on the old importlib-metadata library. I solved this issue by pip install importlib-metadata==4.4"
