### ISSUE TITLE
Unable to run mlagents-learn

### ISSUE THREAD

**Issue by pedrosantos704** [Unity-Technologies/ml-agents#5809]
I followed the installation instructions, running mlagents-learn --help works.

But when I try to actually run 

> mlagents-learn

I get the error: 

 Version information:
  ml-agents: 0.29.0,
  ml-agents-envs: 0.29.0,
  Communicator API: 1.5.0,
  PyTorch: 1.7.1+cu110
Traceback (most recent call last):
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pedro\Dropbox (INESC-ID)\Ensino\Aulas\IAJ\IAJ 2022\5-Learning\ml-agents-release_19\venv\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\pedro\dropbox (inesc-id)\ensino\aulas\iaj\iaj 2022\5-learning\ml-agents-release_19\venv\lib\site-packages\mlagents\trainers\learn.py", line 260, in main
    run_cli(parse_command_line())
  File "c:\users\pedro\dropbox (inesc-id)\ensino\aulas\iaj\iaj 2022\5-learning\ml-agents-release_19\venv\lib\site-packages\mlagents\trainers\learn.py", line 256, in run_cli
    run_training(run_seed, options, num_areas)
  File "c:\users\pedro\dropbox (inesc-id)\ensino\aulas\iaj\iaj 2022\5-learning\ml-agents-release_19\venv\lib\site-packages\mlagents\trainers\learn.py", line 89, in run_training
    stats_writers = register_stats_writer_plugins(options)
  File "c:\users\pedro\dropbox (inesc-id)\ensino\aulas\iaj\iaj 2022\5-learning\ml-agents-release_19\venv\lib\site-packages\mlagents\plugins\stats_writer.py", line 47, in register_stats_writer_plugins
    if ML_AGENTS_STATS_WRITER not in importlib_metadata.entry_points():
  File "c:\users\pedro\dropbox (inesc-id)\ensino\aulas\iaj\iaj 2022\5-learning\ml-agents-release_19\venv\lib\site-packages\importlib_metadata\__init__.py", line 260, in __eq__
    return self._key() == other._key()
AttributeError: 'str' object has no attribute '_key'

Unity version: 2021.3.10f1
OS: Windows 11
Python 3.7.9
Pip3 list: 
Package                 Version
----------------------- -----------
absl-py                 1.3.0
attrs                   22.1.0
cachetools              5.2.0
cattrs                  1.0.0
certifi                 2022.9.24
charset-normalizer      2.1.1
cloudpickle             2.2.0
filelock                3.8.0
google-auth             2.13.0
google-auth-oauthlib    0.4.6
grpcio                  1.50.0
gym                     0.26.2
gym-notices             0.0.8
Gymnasium               0.26.3
gymnasium-notices       0.0.1
h5py                    3.7.0
idna                    3.4
importlib-metadata      5.0.0
Markdown                3.4.1
MarkupSafe              2.1.1
mlagents                0.29.0
mlagents-envs           0.29.0
numpy                   1.21.2
oauthlib                3.2.2
PettingZoo              1.22.1
Pillow                  9.3.0
pip                     22.3
protobuf                3.19.6
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pypiwin32               223
pywin32                 304
PyYAML                  6.0
requests                2.28.1
requests-oauthlib       1.3.1
rsa                     4.9
setuptools              47.1.0
six                     1.16.0
tensorboard             2.10.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
torch                   1.7.1+cu110
typing_extensions       4.4.0
urllib3                 1.26.12
Werkzeug                2.2.2
wheel                   0.37.1
zipp                    3.10.0

**Comment by ChristopherMopp** [comment]
I'm also experiencing this issue. Please assist ASAP

**Comment by pedrosantos704** [comment]
Later I found the workaround described in this thread, and it solved the situation:

https://github.com/Unity-Technologies/ml-agents/issues/5794
pip install importlib-metadata==4.4

Never-the-less, either the bug should be corrected, or the instructions updated. I spent hours trying to install mlagents and getting different errors due to version incompatibilities which are not documented...

**Comment by thisisbaiy** [comment]
> Later I found the workaround described in this thread, and it solved the situation:
> 
> #5794 pip install importlib-metadata==4.4
> 
> Never-the-less, either the bug should be corrected, or the instructions updated. I spent hours trying to install mlagents and getting different errors due to version incompatibilities which are not documented...

very thank you, god, i almost getting crazy, already read lots of blogs but find no solutions. For almost 3 days, god. Thank you for this important message.

**Comment by Maxawa** [comment]
> Later I found the workaround described in this thread, and it solved the situation:
> 
> #5794 pip install importlib-metadata==4.4
> 
> Never-the-less, either the bug should be corrected, or the instructions updated. I spent hours trying to install mlagents and getting different errors due to version incompatibilities which are not documented...

actual god
half want to build a temple for you
