### ISSUE TITLE
Environment took too long to respond error

### ISSUE THREAD

**Issue by TobGab97** [Unity-Technologies/ml-agents#5821]
**Describe the bug**
After pressing the Play button i got those errors. There is no specific error just that's environment took too long to respond so it's hard to find solution.  Did you got this error too?

**Console logs / stack traces**
```(venv2) C:\Users\tobia\Desktop\ML-Agents1>mlagents-learn --run-id=test-tutorial --force

            ┐  ╖
        ╓╖╬│╡  ││╬╖╖
    ╓╖╬│││││┘  ╬│││││╬╖
 ╖╬│││││╬╜        ╙╬│││││╖╖                               ╗╗╗
 ╬╬╬╬╖││╦╖        ╖╬││╗╣╣╣╬      ╟╣╣╬    ╟╣╣╣             ╜╜╜  ╟╣╣
 ╬╬╬╬╬╬╬╬╖│╬╖╖╓╬╪│╓╣╣╣╣╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╒╣╣╖╗╣╣╣╗   ╣╣╣ ╣╣╣╣╣╣ ╟╣╣╖   ╣╣╣
 ╬╬╬╬┐  ╙╬╬╬╬│╓╣╣╣╝╜  ╫╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╟╣╣╣╙ ╙╣╣╣  ╣╣╣ ╙╟╣╣╜╙  ╫╣╣  ╟╣╣
 ╬╬╬╬┐     ╙╬╬╣╣      ╫╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╟╣╣╬   ╣╣╣  ╣╣╣  ╟╣╣     ╣╣╣┌╣╣╜
 ╬╬╬╜       ╬╬╣╣      ╙╝╣╣╬      ╙╣╣╣╗╖╓╗╣╣╣╜ ╟╣╣╬   ╣╣╣  ╣╣╣  ╟╣╣╦╓    ╣╣╣╣╣
 ╙   ╓╦╖    ╬╬╣╣   ╓╗╗╖            ╙╝╣╣╣╣╝╜   ╘╝╝╜   ╝╝╝  ╝╝╝   ╙╣╣╣    ╟╣╣╣
   ╩╬╬╬╬╬╬╦╦╬╬╣╣╗╣╣╣╣╣╣╣╝                                             ╫╣╣╣╣
      ╙╬╬╬╬╬╬╬╣╣╣╣╣╣╝╜
          ╙╬╬╬╣╣╣╜
             ╙

 Version information:
  ml-agents: 0.28.0,
  ml-agents-envs: 0.28.0,
  Communicator API: 1.5.0,
  PyTorch: 1.7.1+cu110
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
Traceback (most recent call last):
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\tobia\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\lib\site-packages\mlagents\trainers\learn.py", line 260, in main
    run_cli(parse_command_line())
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\lib\site-packages\mlagents\trainers\learn.py", line 256, in run_cli
    run_training(run_seed, options, num_areas)
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\lib\site-packages\mlagents\trainers\learn.py", line 132, in run_training
    tc.start_learning(env_manager)
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\lib\site-packages\mlagents\trainers\trainer_controller.py", line 173, in start_learning
    self._reset_env(env_manager)
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\lib\site-packages\mlagents\trainers\trainer_controller.py", line 105, in _reset_env
    env_manager.reset(config=new_config)
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\lib\site-packages\mlagents\trainers\env_manager.py", line 68, in reset
    self.first_step_infos = self._reset_env(config)
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 446, in _reset_env
    ew.previous_step = EnvironmentStep(ew.recv().payload, ew.worker_id, {}, {})
  File "C:\Users\tobia\Desktop\ML-Agents1\venv2\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 101, in recv
    raise env_exception
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Agents' Behavior Parameters > Behavior Type is set to "Default"
         The environment and the Python interface have compatible versions.
         If you're running on a headless server without graphics support, turn off display by either passing --no-graphics option or build your Unity executable as server build. 
```

**Screenshots**
![obraz_2022-11-21_192253656](https://user-images.githubusercontent.com/102920753/203131212-5894a43c-6e52-408d-9f01-478bea07f709.png)
![obraz_2022-11-21_191221052](https://user-images.githubusercontent.com/102920753/203129495-2d7d7b0d-d04c-4e61-81bb-f26501bf7de6.png)

**Environment:**
- Unity Version: [Unity 2020.3.1f1]
- OS + version: [Windows 10]
- _ML-Agents version_: (2.1.0-exp.1)
- _Torch version_: (1.7.1)

**Comment by jrupert-unity** [comment]
The first error in the Unity log looks like the one to focus on for the environment timeout.  Something is wrong with your gRPC library.  This [forum post](https://forum.unity.com/threads/mlagents-unexpected-exception-when-trying-to-initialize-communication.1112350/) describes a similar case.
