### ISSUE TITLE
Ma-Poca Environment Learn Script Fails to Launch Environment

### ISSUE THREAD

**Issue by rkaundinya** [Unity-Technologies/ml-agents#5893]
**Describe the bug**
Attempting to launch Ma-Poca Unity environment via mapoca-learn and running into a http URL error post Unity Splash Screen

**To Reproduce**
1. Follow installation steps for ma-poca
2. attempt mapoca-learn config/<algorithm>/<env>.yaml --env=<env> --run-id=<idnum>
3. See following error message

**Console logs / stack traces**
```Version information:
ml-agents: 0.1,
ml-agents-envs: 0.27.0,
Communicator API: 1.5.0,
PyTorch: 2.0.0+cpu
[WARNING] Attempt 1 / 5: Failed to download and extract binary.
[WARNING] Attempt 2 / 5: Failed to download and extract binary.
[WARNING] Attempt 3 / 5: Failed to download and extract binary.
[WARNING] Attempt 4 / 5: Failed to download and extract binary.
[ERROR] UnityEnvironment worker 0: environment raised an unexpected exception.
Traceback (most recent call last):
File "d:\development\paper-ml-agents-main\paper-ml-agents-main\ma-poca\mapoca\mapoca\trainers\subprocess_env_manager.py", line 160, in worker
env = env_factory(worker_id, side_channels)
File "d:\development\paper-ml-agents-main\paper-ml-agents-main\ma-poca\mapoca\mapoca\trainers\learn.py", line 174, in create_unity_environment
return mapoca_registry[env_name].make(
File "D:\Downloads\anaconda3\envs\mlagents20\lib\site-packages\mlagents_envs\registry\remote_registry_entry.py", line 61, in make
path = get_local_binary_path(self.identifier, url)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\site-packages\mlagents_envs\registry\binary_utils.py", line 40, in get_local_binary_path
download_and_extract_zip(url, name)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\site-packages\mlagents_envs\registry\binary_utils.py", line 131, in download_and_extract_zip
request = urllib.request.urlopen(url, timeout=30)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 523, in open
response = meth(req, response)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 632, in http_response
response = self.parent.error(
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 561, in error
return self._call_chain(*args)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 494, in _call_chain
result = func(*args)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 641, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found https://storage.googleapis.com/mlagents-test-environments/ma-poca/win/Startup.zip
[INFO] Learning was interrupted. Please wait while the graph is generated.
Traceback (most recent call last):
File "D:\Downloads\anaconda3\envs\mlagents20\lib\multiprocessing\queues.py", line 245, in _feed
obj = _ForkingPickler.dumps(obj)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\multiprocessing\reduction.py", line 51, in dumps
cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object
Process Process-1:
Traceback (most recent call last):
File "d:\development\paper-ml-agents-main\paper-ml-agents-main\ma-poca\mapoca\mapoca\trainers\subprocess_env_manager.py", line 160, in worker
env = env_factory(worker_id, side_channels)
File "d:\development\paper-ml-agents-main\paper-ml-agents-main\ma-poca\mapoca\mapoca\trainers\learn.py", line 174, in create_unity_environment
return mapoca_registry[env_name].make(
File "D:\Downloads\anaconda3\envs\mlagents20\lib\site-packages\mlagents_envs\registry\remote_registry_entry.py", line 61, in make
path = get_local_binary_path(self.identifier, url)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\site-packages\mlagents_envs\registry\binary_utils.py", line 40, in get_local_binary_path
download_and_extract_zip(url, name)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\site-packages\mlagents_envs\registry\binary_utils.py", line 131, in download_and_extract_zip
request = urllib.request.urlopen(url, timeout=30)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 523, in open
response = meth(req, response)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 632, in http_response
response = self.parent.error(
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 561, in error
return self._call_chain(*args)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 494, in _call_chain
result = func(*args)
File "D:\Downloads\anaconda3\envs\mlagents20\lib\urllib\request.py", line 641, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found https://storage.googleapis.com/mlagents-test-environments/ma-poca/win/Startup.zip```

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2020.1f1]
- OS + version: Windows 10
- _ML-Agents version_: 0.27.0
- _Torch version_: 2.0.0
- _Environment_: BatonPass

**Comment by rkaundinya** [comment]
It seems like the only valid link used to load in the environment zip is the mac link in the registry_entries.py; no other link appears active on the storage.googleapis.com URL path
![image](https://user-images.githubusercontent.com/34527220/229001255-9b51cb8a-7f26-419c-abdb-9fe333cbccc3.png)

**Comment by miguelalonsojr** [comment]
Can you post the link to the instructions that you are following?

**Comment by rkaundinya** [comment]
Hi Miguel - I'm just following the instructions on the paper-ml-agents/ma-poca github repo. Here's the link:
https://github.com/Unity-Technologies/paper-ml-agents/tree/main/ma-poca

**Comment by Penguin963** [comment]
Have you solved this problem?
