### ISSUE TITLE
torch

### ISSUE THREAD

**Issue by ufodriverr** [Unity-Technologies/ml-agents#5895]
**Describe the bug**
pip install torch~=1.7.1 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch~=1.7.1 (from versions: 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118)
ERROR: No matching distribution found for torch~=1.7.1
Gives error as seen above.
U used: pip3 install torch torchvision torchaudio and it worked. So i guess its nice to update documentation.

But that didnt solve all issues. Because right after that, when you try to run
mlagents-learn --help it gives error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Scripts\mlagents-learn.exe\__main__.py", line 4, in <module>
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Lib\site-packages\mlagents\trainers\learn.py", line 2, in <module>
    from mlagents import torch_utils
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Lib\site-packages\mlagents\torch_utils\__init__.py", line 1, in <module>
    from mlagents.torch_utils.torch import torch as torch  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Lib\site-packages\mlagents\torch_utils\torch.py", line 6, in <module>
    from mlagents.trainers.settings import TorchSettings
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Lib\site-packages\mlagents\trainers\settings.py", line 25, in <module>
    from mlagents.trainers.cli_utils import StoreConfigFile, DetectDefault, parser
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Lib\site-packages\mlagents\trainers\cli_utils.py", line 5, in <module>
    from mlagents_envs.environment import UnityEnvironment
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Lib\site-packages\mlagents_envs\environment.py", line 12, in <module>
    from mlagents_envs.side_channel.side_channel import SideChannel
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Lib\site-packages\mlagents_envs\side_channel\__init__.py", line 5, in <module>
    from mlagents_envs.side_channel.default_training_analytics_side_channel import (  # noqa
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Lib\site-packages\mlagents_envs\side_channel\default_training_analytics_side_channel.py", line 7, in <module>
    from mlagents_envs.communicator_objects.training_analytics_pb2 import (
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Lib\site-packages\mlagents_envs\communicator_objects\training_analytics_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\ufodr\Desktop\Projects\MLLearning1\venv\Lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**To Reproduce**
1. Follow instalation instructions
2. Install latest python
3. Try install pytorch using: pip install torch~=1.7.1 -f https://download.pytorch.org/whl/torch_stable.html
5. install pytorch using: pip3 install torch torchvision torchaudio
6. install pip install mlagents
7. See another error above

**Console logs / stack traces**
ERROR: Could not find a version that satisfies the requirement torch~=1.7.1 (from versions: 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118)

**Environment (please complete the following information):**
- Windows 11
- ML-Agents 2.3.0-exp.3
- _Torch version_: 1.7.1

**Comment by miguelalonsojr** [comment]
Can you do a clean install using the github repo from the release 20 tag? We deprecated torch 1.7. https://github.com/Unity-Technologies/ml-agents/releases/tag/release_20

**Comment by ufodriverr** [comment]
@miguelalonsojr @KhalfounMehdi Will try those solutions later. Have no time for now =( But will try do them this weekend.

**Comment by ufodriverr** [comment]
@miguelalonsojr 
![image](https://user-images.githubusercontent.com/7818629/235268902-52dd8edf-1fae-4011-a6e3-5649e286c899.png)
https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Getting-Started.md#installation
https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Installation.md
It still tells to install torch 1.7.1

**Comment by Prakhar-Bhartiya** [comment]
@KhalfounMehdi Solution : `pip install protobuf==3.20 ` worked for me. Thanks!

**Comment by Germano123** [comment]
I'm facing the same issue now... Installing protobuf==3.20 didn't help.

**Comment by Kontra21** [comment]
Same overall issue, different error
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\shiyo\AppData\Local\Programs\Python\Python311\Scripts\mlagents-learn.exe\__main__.py", line 4, in <module>
  File "C:\Users\shiyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlagents\trainers\learn.py", line 2, in <module>
    from mlagents import torch_utils
  File "C:\Users\shiyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlagents\torch_utils\__init__.py", line 1, in <module>
    from mlagents.torch_utils.torch import torch as torch  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shiyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlagents\torch_utils\torch.py", line 6, in <module>
    from mlagents.trainers.settings import TorchSettings
  File "C:\Users\shiyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlagents\trainers\settings.py", line 644, in <module>
    class TrainerSettings(ExportableSettings):
  File "C:\Users\shiyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlagents\trainers\settings.py", line 667, in TrainerSettings
    cattr.register_structure_hook(
  File "C:\Users\shiyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\cattr\converters.py", line 207, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "C:\Users\shiyo\AppData\Local\Programs\Python\Python311\Lib\site-packages\cattr\dispatch.py", line 55, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "C:\Users\shiyo\AppData\Local\Programs\Python\Python311\Lib\functools.py", line 864, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. typing.Dict[mlagents.trainers.settings.RewardSignalType, mlagents.trainers.settings.RewardSignalSettings] is not a class or union type.`

**Comment by kkohno** [comment]
same bug

**Comment by Etonio99** [comment]
I'm getting the same error message as @Kontra21. Installing protobuf didn't help for me either.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ebrei\OneDrive\Documents\Unity\ML Platformer Testing\venv\Scripts\mlagents-learn.exe\__main__.py", line 4, in <module>
  File "C:\Users\ebrei\OneDrive\Documents\Unity\ML Platformer Testing\venv\Lib\site-packages\mlagents\trainers\learn.py", line 2, in <module>
    from mlagents import torch_utils
  File "C:\Users\ebrei\OneDrive\Documents\Unity\ML Platformer Testing\venv\Lib\site-packages\mlagents\torch_utils\__init__.py", line 1, in <module>
    from mlagents.torch_utils.torch import torch as torch  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ebrei\OneDrive\Documents\Unity\ML Platformer Testing\venv\Lib\site-packages\mlagents\torch_utils\torch.py", line 6, in <module>
    from mlagents.trainers.settings import TorchSettings
  File "C:\Users\ebrei\OneDrive\Documents\Unity\ML Platformer Testing\venv\Lib\site-packages\mlagents\trainers\settings.py", line 644, in <module>
    class TrainerSettings(ExportableSettings):
  File "C:\Users\ebrei\OneDrive\Documents\Unity\ML Platformer Testing\venv\Lib\site-packages\mlagents\trainers\settings.py", line 667, in TrainerSettings
    cattr.register_structure_hook(
  File "C:\Users\ebrei\OneDrive\Documents\Unity\ML Platformer Testing\venv\Lib\site-packages\cattr\converters.py", line 207, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "C:\Users\ebrei\OneDrive\Documents\Unity\ML Platformer Testing\venv\Lib\site-packages\cattr\dispatch.py", line 55, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\functools.py", line 864, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. typing.Dict[mlagents.trainers.settings.RewardSignalType, mlagents.trainers.settings.RewardSignalSettings] is not a class or union type.
```

**Comment by johan237** [comment]
Has anyone manged to solve the bug???

**Comment by dariooo512** [comment]
Still waiting for news on this

**Comment by johan237** [comment]
I was able to solve it. The problem lies on the python version. When creating an environment say with conda, ensure your python version is compatible with pytorch. You can watch this video that helped and ensure to download thesame python version as he did when creating his conda environment [Youtube Video on ML agents Unity setup](https://www.youtube.com/watch?v=Dj-BsYtANE0&t=1s ).

**Comment by Bruno-Vasa** [comment]
I have the same issue. Installing protobuf==3.20 didn't solve the issue for me. 
The installation documentation only says "3.10.12 or higher", so we expect everything works no matter the Python version is, since it's higher than 3.10.12.
