### ISSUE TITLE
Unable to start training

### ISSUE THREAD

**Issue by YashJaveri** [Unity-Technologies/ml-agents#5904]
When I try to run "mlagents-learn stock_config.yaml --run-id=stockTrainer1 --train" and then hit the Play button in Unity editor, I get the following error:

[WARNING] The --train option has been deprecated. Train mode is now the default. Use --inference to run in inference mode.
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
[INFO] Connected to Unity environment with package version 2.0.1 and communication version 1.5.0
[INFO] Connected new brain: StockExchange?team=0
zsh: illegal hardware instruction  mlagents-learn stock_config.yaml --run-id=stockTrainer1 --train
(stock_venv) yashjaveri@Yashs-Air TrainingConfigs % [ERROR] UnityEnvironment worker 0: environment raised an unexpected exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mlagents/trainers/subprocess_env_manager.py", line 175, in worker
    req: EnvironmentRequest = parent_conn.recv()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mlagents/trainers/subprocess_env_manager.py", line 175, in worker
    req: EnvironmentRequest = parent_conn.recv()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mlagents/trainers/subprocess_env_manager.py", line 235, in worker
    _send_response(EnvironmentCommand.ENV_EXITED, ex)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mlagents/trainers/subprocess_env_manager.py", line 150, in _send_response
    parent_conn.send(EnvironmentResponse(cmd_name, worker_id, payload))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
  
I have tried almost everything but still no hopes. I tried multiple versions of python as well. I have also tried running this in the example environment but I received the same error. Any help would be highly appreciated!

Some fyi:
I am using a python venv
Python version- 3.9.0
mlagents verision - 0.30.0
ML Agents Unity Package's version - 2.0.1
Unity version- 2021.3.18

I have tried installing the dependencies manually as well as using the setup.py of the repo.

**Comment by AM800Mats** [comment]
any fix?

**Comment by miguelalonsojr** [comment]
You should be using ML-Agents from the repo, not from the package manager. Version 2.01. of the Unity package does not work with version 0.30.0 of the python package. You can either use the develop branch of the repo for bleeding edge, or our last release https://github.com/Unity-Technologies/ml-agents/releases/tag/release_20 . It will be a while before a new package is available through the package manager in the editor.

**Comment by YashJaveri** [comment]
I cloned the repository and extracted the ml-agents folder into my unity project. I used the setup.py to install the dependencies. It has at least started training for now.
