### ISSUE TITLE
RuntimeError: Continuous NaN action detected

### ISSUE THREAD

**Issue by LionChen-WORK** [Unity-Technologies/ml-agents#5925]
Training crashed after a long running time.

- The training had run around 160M steps when it crashed.
- The resulting .onnx file was unusable in inference.
- Resuming the training would trigger the same error immediately.

Related forums thread: [Training crashes after multiple days running, unable to resume or recover.](https://forum.unity.com/threads/training-crashes-after-multiple-days-running-unable-to-resume-or-recover.1419761/)

## Console logs / stack traces

```
> mlagents-learn ./configs/Training-0.yaml --run-id=Training-0-2 --num-areas=4 --num-envs=2 --env="D:\Unity\mygame\Builds\mygame.exe"

(Had run about 160M steps...)

Traceback (most recent call last):
  File "D:\Unity\mygame\python-envs\default\Scripts\mlagents-learn-script.py", line 33, in <module>
    sys.exit(load_entry_point('mlagents==0.30.0', 'console_scripts', 'mlagents-learn')())
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\learn.py", line 264, in main
    run_cli(parse_command_line())
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\learn.py", line 260, in run_cli
    run_training(run_seed, options, num_areas)
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\learn.py", line 136, in run_training
    tc.start_learning(env_manager)
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\trainer_controller.py", line 175, in start_learning
    n_steps = self.advance(env_manager)
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\trainer_controller.py", line 233, in advance
    new_step_infos = env_manager.get_steps()
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\env_manager.py", line 124, in get_steps
    new_step_infos = self._step()
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 408, in _step
    self._queue_steps()
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 302, in _queue_steps
    env_action_info = self._take_step(env_worker.previous_step)
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 543, in _take_step
    all_action_info[brain_name] = self.policies[brain_name].get_action(
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\policy\torch_policy.py", line 132, in get_action
    self.check_nan_action(run_out.get("action"))
  File "D:\Unity\mygame\python-envs\default\lib\site-packages\mlagents\trainers\policy\policy.py", line 126, in check_nan_action
    raise RuntimeError("Continuous NaN action detected.")
RuntimeError: Continuous NaN action detected.
```

## Environment

- Unity: `2021.2.13f1`
- OS: `Windows 11`
- ML-Agents: `0.30.0`
- Torch: `1.13.1+cu117`

**Comment by miguelalonsojr** [comment]
We are unable to help reproduce bugs with custom environments. Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.
