### ISSUE TITLE
MLAgent always restarts when I stop Unity Editor

### ISSUE THREAD

**Issue by pjmatuck** [Unity-Technologies/ml-agents#5931]
**Describe the bug**
I'm trying to run the samples available in mlagents repo. I open the Basic scene in Unity  (located in: Assets/ML-Agents/Examples/Basic/Scenes/Basic.unity), start running and everything goes fine. When I stop my Unity Editor execution, the MLAgent always restarts with the following message:

[WARNING] Restarting worker[0] after 'Communicator has exited.'
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.

Than, I start again the same scene on Unity Editor, it reconnects normally in MLAgent but when I stop I get the following:

[INFO] Connected to Unity environment with package version 2.3.0-exp.3 and communication version 1.5.0
[INFO] Connected new brain: Basic?team=0
[ERROR] Worker 0 exceeded the allowed number of restarts.

Checking the code, it raises an exception at this point:
class: subprocess_env_manager.py
```
step: EnvironmentResponse = self.step_queue.get_nowait()
                    if step.cmd == EnvironmentCommand.ENV_EXITED:
                        # If even one env exits try to restart all envs that failed.
                        self._restart_failed_workers(step)
                        # Clear state and restart this function.
                        worker_steps.clear()
                        step_workers.clear()
                        self._queue_steps()
```
                        
When Unity stops, it sends the EnvironmentCommand ENV_EXITED (6) and it try to restart.

**To Reproduce**
1. Open any sample scene in MLAgent project
2. Start the MLAgent with mlagents-learn --force
3. Play the scene in Unity Editor
4. Stop the scene in Unity Editor
5. Check the MLAgent log in console
6. Start again the Unity Editor
7. Check again the MLAgent log

**Console logs / stack traces**
```
(venv) C:\Users\pjmat\Unity Projects>mlagents-learn --force

            ┐  ╖
        ╓╖╬│╡  ││╬╖╖
    ╓╖╬│││││┘  ╬│││││╬╖
 ╖╬│││││╬╜        ╙╬│││││╖╖                               ╗╗╗
 ╬╬╬╬╖││╦╖        ╖╬││╗╣╣╣╬      ╟╣╣╬    ╟╣╣╣             ╜╜╜  ╟╣╣
 ╬╬╬╬╬╬╬╬╖│╬╖╖╓╬╪│╓╣╣╣╣╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╒╣╣╖╗╣╣╣╗   ╣╣╣ ╣╣╣╣╣╣ ╟╣╣╖   ╣╣╣
 ╬╬╬╬┐  ╙╬╬╬╬│╓╣╣╣╝╜  ╫╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╟╣╣╣╙ ╙╣╣╣  ╣╣╣ ╙╟╣╣╜╙  ╫╣╣  ╟╣╣
 ╬╬╬╬┐     ╙╬╬╣╣      ╫╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╟╣╣╬   ╣╣╣  ╣╣╣  ╟╣╣     ╣╣╣┌╣╣╜
 ╬╬╬╜       ╬╬╣╣      ╙╝╣╣╬      ╙╣╣╣╗╖╓╗╣╣╣╜ ╟╣╣╬   ╣╣╣  ╣╣╣  ╟╣╣╦╓    ╣╣╣╣╣
 ╙   ╓╦╖    ╬╬╣╣   ╓╗╗╖            ╙╝╣╣╣╣╝╜   ╘╝╝╜   ╝╝╝  ╝╝╝   ╙╣╣╣    ╟╣╣╣
   ╩╬╬╬╬╬╬╦╦╬╬╣╣╗╣╣╣╣╣╣╣╝                                             ╫╣╣╣╣
      ╙╬╬╬╬╬╬╬╣╣╣╣╣╣╝╜
          ╙╬╬╬╣╣╣╜
             ╙

 Version information:
  ml-agents: 0.30.0,
  ml-agents-envs: 0.30.0,
  Communicator API: 1.5.0,
  PyTorch: 2.0.1+cu118
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
[INFO] Connected to Unity environment with package version 2.3.0-exp.3 and communication version 1.5.0
[INFO] Connected new brain: Basic?team=0
[WARNING] Behavior name Basic does not match any behaviors specified in the trainer configuration file. A default configuration will be used.
[WARNING] Deleting TensorBoard data events.out.tfevents.1686437525.Megazord2.7180.0 that was left over from a previous run.
[INFO] Hyperparameters for behavior name Basic:
        trainer_type:   ppo
        hyperparameters:
          batch_size:   1024
          buffer_size:  10240
          learning_rate:        0.0003
          beta: 0.005
          epsilon:      0.2
          lambd:        0.95
          num_epoch:    3
          shared_critic:        False
          learning_rate_schedule:       linear
          beta_schedule:        linear
          epsilon_schedule:     linear
        network_settings:
          normalize:    False
          hidden_units: 128
          num_layers:   2
          vis_encode_type:      simple
          memory:       None
          goal_conditioning_type:       hyper
          deterministic:        False
        reward_signals:
          extrinsic:
            gamma:      0.99
            strength:   1.0
            network_settings:
              normalize:        False
              hidden_units:     128
              num_layers:       2
              vis_encode_type:  simple
              memory:   None
              goal_conditioning_type:   hyper
              deterministic:    False
        init_path:      None
        keep_checkpoints:       5
        checkpoint_interval:    500000
        max_steps:      500000
        time_horizon:   64
        summary_freq:   50000
        threaded:       False
        self_play:      None
        behavioral_cloning:     None
[WARNING] Restarting worker[0] after 'Communicator has exited.'
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
[INFO] Connected to Unity environment with package version 2.3.0-exp.3 and communication version 1.5.0
[INFO] Connected new brain: Basic?team=0
[ERROR] Worker 0 exceeded the allowed number of restarts.
[INFO] Learning was interrupted. Please wait while the graph is generated.
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

[ERROR] SubprocessEnvManager had workers that didn't signal shutdown
Traceback (most recent call last):
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\torch\onnx\_internal\onnx_proto_utils.py", line 219, in _add_onnxscript_fn
    import onnx
ModuleNotFoundError: No module named 'onnx'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pjmat\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pjmat\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pjmat\Unity Projects\venv\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents\trainers\learn.py", line 264, in main
    run_cli(parse_command_line())
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents\trainers\learn.py", line 260, in run_cli
    run_training(run_seed, options, num_areas)
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents\trainers\learn.py", line 136, in run_training
    tc.start_learning(env_manager)
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents\trainers\trainer_controller.py", line 200, in start_learning
    self._save_models()
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents\trainers\trainer_controller.py", line 80, in _save_models
    self.trainers[brain_name].save_model()
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents\trainers\trainer\rl_trainer.py", line 172, in save_model
    model_checkpoint = self._checkpoint()
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents\trainers\trainer\rl_trainer.py", line 144, in _checkpoint
    export_path, auxillary_paths = self.model_saver.save_checkpoint(
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents\trainers\model_saver\torch_model_saver.py", line 60, in save_checkpoint
    self.export(checkpoint_path, behavior_name)
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents\trainers\model_saver\torch_model_saver.py", line 65, in export
    self.exporter.export_policy_model(output_filepath)
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\mlagents\trainers\torch_entities\model_serialization.py", line 164, in export_policy_model
    torch.onnx.export(
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\torch\onnx\utils.py", line 1620, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "C:\Users\pjmat\Unity Projects\venv\lib\site-packages\torch\onnx\_internal\onnx_proto_utils.py", line 221, in _add_onnxscript_fn
    raise errors.OnnxExporterError("Module onnx is not installed!") from e
torch.onnx.errors.OnnxExporterError: Module onnx is not installed!
```

**Environment (please complete the following information):**
- Unity Version: Unity 2021.3.11f1
- OS + version: Windows 10
- _ML-Agents version_:   ml-agents: 0.30.0, ml-agents-envs: 0.30.0, Communicator API: 1.5.0
- _Torch version_: PyTorch: 2.0.1+cu118
- _Environment_: Unity 2021, Python 3.9.9, Command Prompt

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by pjmatuck** [comment]
Just to add. I have tried in many different ways, with different python versions (3.7.x, 3.8.x and 3.9.x). I also tried strictly with installation instructions in official github page. At the log's end there's a error related with ONNX, but this is not the problem. Despite that, I also installed ONNX separately, but the behavior is always the same.

**Comment by miguelalonsojr** [comment]
I cannot reproduce this with ml-agents installed from source on the develop branch. Can you try to re-install ml-agents from the github repo?

`pip install ./ml-agents-envs`

then

`pip install  ./ml-agents`


The intended behavior is to stop training when the scene stops, but it does not stop the python trainer itself. This is not a bug. There is a limit on the number of disconnects as well, to make sure if there's a problem with an environment, it does not start and stop training for ever. The typical training use case is to train with a binary build of the environment, not training in the editor. In editor training is mostly recommended for debugging as you are building the environment. Once the environment is built, running training with an executable build is faster and the recommended approach. See: https://unity-technologies.github.io/ml-agents/Learning-Environment-Executable/

**Comment by pjmatuck** [comment]
In addition, I cloned the mlagents from tags release_19 and release_20, not from develop.

**Comment by miguelalonsojr** [comment]
Closing due to inactivity.
