### ISSUE TITLE
[pip install failure] Expected end or semicolon (after version specifier)

### ISSUE THREAD

**Issue by Draco18s** [Unity-Technologies/ml-agents#5947]
**Describe the bug**
gym_unity fails to install with exception `Expected end or semicolon (after version specifier)`

**To Reproduce**
1. Open Windows Powershell
2. Prior installed packages in same session: `pip install mlagents==0.26.0` `pip install mlagents_envs==0.26.0`
3. run `pip install gym_unity` 

**Console logs / stack traces**
```
      Copying gym.egg-info to build\bdist.win-amd64\wheel\.\gym-0.20.0-py3.9.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\vendored\packaging\requirements.py", line 35, in __init__
          parsed = parse_requirement(requirement_string)
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\vendored\packaging\_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\vendored\packaging\_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\vendored\packaging\_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\vendored\packaging\_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\vendored\packaging\_tokenizer.py", line 163, in raise_syntax_error
          raise ParserSyntaxError(
      wheel.vendored.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
          opencv-python>=3.
                       ~~~^

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\draco\AppData\Local\Temp\pip-install-4m07cm3t\gym_b5e35597a62d4bcbb53b8c580606ac51\setup.py", line 34, in <module>
          setup(
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\bdist_wheel.py", line 395, in run
          self.egg2dist(self.egginfo_dir, distinfo_dir)
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\bdist_wheel.py", line 534, in egg2dist
          pkg_info = pkginfo_to_metadata(egginfo_path, pkginfo_path)
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\metadata.py", line 160, in pkginfo_to_metadata
          for key, value in generate_requirements({extra: reqs}):
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\metadata.py", line 138, in generate_requirements
          for new_req in convert_requirements(depends):
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\metadata.py", line 103, in convert_requirements
          parsed_requirement = Requirement(req)
        File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\vendored\packaging\requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      wheel.vendored.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
          opencv-python>=3.
                       ~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gym
  Running setup.py clean for gym
Failed to build gym
ERROR: Could not build wheels for gym, which is required to install pyproject.toml-based projects
```

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: e.g. Unity 2020.1f1
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents v0.26.0
- _Torch version_: n/a
- _Environment_: Python 3.9.13, Command Prompt

I was able to install it by specifying a version number however; `pip install gym_unity==0.26.0`

**Comment by miguelalonsojr** [comment]
Gym unity has been deprecated and gym functionality has been moved into the ml-agents-envs package. Also, please update to the latest version of ML-Agents available on the develop branch of this repo. Also, please update to Unity version 2022.3 LTS as well.
