### ISSUE TITLE
TypeError: No loop matching the specified signature and casting was found for ufunc greater

### ISSUE THREAD

**Issue by Draco18s** [Unity-Technologies/ml-agents#5948]
**Describe the bug**
Unexpected error after training loop.

**To Reproduce**
1. After training, results copied, then an error occurred

**Console logs / stack traces**

```
[INFO] Copied results\PewPew\PewPew\PewPew-9978.onnx to results\PewPew\PewPew.onnx.
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\learn.py", line 250, in main
    run_cli(parse_command_line())
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\learn.py", line 246, in run_cli
    run_training(run_seed, options)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\learn.py", line 125, in run_training
    tc.start_learning(env_manager)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\trainer_controller.py", line 176, in start_learning
    n_steps = self.advance(env_manager)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\trainer_controller.py", line 251, in advance
    trainer.advance()
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\trainer\rl_trainer.py", line 306, in advance
    self._process_trajectory(t)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\ppo\trainer.py", line 67, in _process_trajectory
    super()._process_trajectory(trajectory)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\trainer\rl_trainer.py", line 236, in _process_trajectory
    self._maybe_write_summary(self.get_step + len(trajectory.steps))
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\trainer\rl_trainer.py", line 249, in _maybe_write_summary
    self._write_summary(self._next_summary_step)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\trainer\rl_trainer.py", line 228, in _write_summary
    self.stats_reporter.write_stats(int(step))
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\stats.py", line 376, in write_stats
    writer.write_stats(self.category, values, step)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mlagents\trainers\stats.py", line 246, in write_stats
    self.summary_writers[category].add_histogram(
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\tensorboard\writer.py", line 430, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\tensorboard\summary.py", line 300, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "C:\Users\draco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\utils\tensorboard\summary.py", line 324, in make_histogram
    cum_counts = np.cumsum(np.greater(counts, 0, dtype=np.int32))
TypeError: No loop matching the specified signature and casting was found for ufunc greater
```

**Environment (please complete the following information):**
- Unity Version: Unity 2020.1f1
- OS + version: Windows 10
- ML-Agents version: ML-Agents v0.26.0
- Torch version: 1.7.1
- Environment: Python 3.8.10, Command Prompt

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by miguelalonsojr** [comment]
Please update to the latest version of ML-Agents available on the develop branch of this repo. Also, please update to Unity version 2022.3 LTS as well.
