### ISSUE TITLE
ML Agent training error

### ISSUE THREAD

**Issue by cubestudioss** [Unity-Technologies/ml-agents#5949]
I am trying to run mlagents-learn in cmd to train my ml agent and I keep getting this error so as a normal person I search it up and look at the resource it tells me to go to and I can't figure it out the error is thank you for your time

Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "C:\Users\jtkie\My project (11)\venv\Scripts\mlagents-learn.exe\__main__.py", line 4, in <module> File "C:\Users\jtkie\My project (11)\venv\Lib\site-packages\mlagents\trainers\learn.py", line 2, in <module> from mlagents import torch_utils File "C:\Users\jtkie\My project (11)\venv\Lib\site-packages\mlagents\torch_utils\__init__.py", line 1, in <module> from mlagents.torch_utils.torch import torch as torch  # noqa ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\jtkie\My project (11)\venv\Lib\site-packages\mlagents\torch_utils\torch.py", line 6, in <module> from mlagents.trainers.settings import TorchSettings File "C:\Users\jtkie\My project (11)\venv\Lib\site-packages\mlagents\trainers\settings.py", line 25, in <module> from mlagents.trainers.cli_utils import StoreConfigFile, DetectDefault, parser File "C:\Users\jtkie\My project (11)\venv\Lib\site-packages\mlagents\trainers\cli_utils.py", line 5, in <module> from mlagents_envs.environment import UnityEnvironment File "C:\Users\jtkie\My project (11)\venv\Lib\site-packages\mlagents_envs\environment.py", line 12, in <module> from mlagents_envs.side_channel.side_channel import SideChannel File "C:\Users\jtkie\My project (11)\venv\Lib\site-packages\mlagents_envs\side_channel\__init__.py", line 5, in <module> from mlagents_envs.side_channel.default_training_analytics_side_channel import (  # noqa File "C:\Users\jtkie\My project (11)\venv\Lib\site-packages\mlagents_envs\side_channel\default_training_analytics_side_channel.py", line 7, in <module> from mlagents_envs.communicator_objects.training_analytics_pb2 import ( File "C:\Users\jtkie\My project (11)\venv\Lib\site-packages\mlagents_envs\communicator_objects\training_analytics_pb2.py", line 35, in <module> _descriptor.FieldDescriptor( File "C:\Users\jtkie\My project (11)\venv\Lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__ _message.Message._CheckCalledFromGeneratedFile() TypeError: Descriptors cannot not be created directly. If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0. If you cannot immediately regenerate your protos, some other possible workarounds are: 1. Downgrade the protobuf package to 3.20.x or lower. 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower). More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by FishyMine** [comment]
So, I figured out as I had the same problem. Even though it may make it slower, try running " Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python " in the Command prompt (if windows),

I do not know what to do for any OS's, but this solved it for me.

**Comment by jdmcgraw** [comment]
I would avoid setting the `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` for the sake of speed.

Try installing Protobuf 3.20.3
`pip3 install protobuf==3.20.3`

Release-20 installs the wrong version of protobuf.

**Comment by miguelalonsojr** [comment]
Please update to the latest version of ML-Agents available on the develop branch of this repo. Also, please update to Unity version 2022.3 LTS as well.
