### ISSUE TITLE
AttributeError: 'str' object has no attribute '_key'

### ISSUE THREAD

**Issue by SpadgerBoy** [Unity-Technologies/ml-agents#5954]
Version information:
  ml-agents: 0.29.0,
  ml-agents-envs: 0.29.0,
  Communicator API: 1.5.0,
  PyTorch: 1.8.1+cu102
Traceback (most recent call last):
  File "/home/......../bin/mlagents-learn", line 8, in <module>
    sys.exit(main())
  File "/home/......../lib/python3.7/site-packages/mlagents/trainers/learn.py", line 260, in main
    run_cli(parse_command_line())
  File "/home/......../lib/python3.7/site-packages/mlagents/trainers/learn.py", line 256, in run_cli
    run_training(run_seed, options, num_areas)
  File "/home/......../lib/python3.7/site-packages/mlagents/trainers/learn.py", line 89, in run_training
    stats_writers = register_stats_writer_plugins(options)
  File "/home/......../lib/python3.7/site-packages/mlagents/plugins/stats_writer.py", line 47, in register_stats_writer_plugins
    if ML_AGENTS_STATS_WRITER not in importlib_metadata.entry_points():
  File "/home/......../lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 261, in __eq__
    return self._key() == other._key()
AttributeError: 'str' object has no attribute '_key'

I encountered some issues with the mlagents library during runtime, such as reporting errors. May I know how to solve them?

**Comment by miguelalonsojr** [comment]
Please update to the latest version of ML-Agents available on the develop branch of this repo. Also, please update to Unity version 2022.3 LTS as well.
