### ISSUE TITLE
Had to change numpy version in setup.py to install ml-agents

### ISSUE THREAD

**Issue by barsgunduz** [Unity-Technologies/ml-agents#5996]
**Describe the bug**
When I use the following command to install ml-agents: `python -m pip install ./ml-agents-envs`

I get a long error. In summary it says: _ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects. setup.py:63: RuntimeWarning: NumPy 1.21.2 may not yet support Python 3.10.

Only solution was to change numpy version to 1.26.0 in setup.py

**To Reproduce**
1. Try to install ml agents in conda env: `python -m pip install ./ml-agents-envs`
2. See error

**Console logs / stack traces**
```
 python -m pip install ./ml-agents-envs
Processing c:\workspace\unityai\ml-agents\ml-agents-envs
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting cloudpickle (from mlagents-envs==1.0.0)
  Using cached cloudpickle-2.2.1-py3-none-any.whl (25 kB)
Collecting grpcio<=1.48.2,>=1.11.0 (from mlagents-envs==1.0.0)
  Using cached grpcio-1.48.2-cp310-cp310-win_amd64.whl (3.6 MB)
Collecting Pillow>=4.2.1 (from mlagents-envs==1.0.0)
  Obtaining dependency information for Pillow>=4.2.1 from https://files.pythonhosted.org/packages/23/ca/7296d769f62266c0f94bf76496bc77114e7a96d2de3d7bcba91d0ba2856f/Pillow-10.0.1-cp310-cp310-win_amd64.whl.metadata
  Using cached Pillow-10.0.1-cp310-cp310-win_amd64.whl.metadata (9.6 kB)
Collecting protobuf<3.20,>=3.6 (from mlagents-envs==1.0.0)
  Using cached protobuf-3.19.6-cp310-cp310-win_amd64.whl (895 kB)
Collecting pyyaml>=3.1.0 (from mlagents-envs==1.0.0)
  Obtaining dependency information for pyyaml>=3.1.0 from https://files.pythonhosted.org/packages/24/97/9b59b43431f98d01806b288532da38099cc6f2fea0f3d712e21e269c0279/PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata
  Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata (2.1 kB)
Collecting gym>=0.21.0 (from mlagents-envs==1.0.0)
  Using cached gym-0.26.2-py3-none-any.whl
Collecting pettingzoo==1.15.0 (from mlagents-envs==1.0.0)
  Using cached PettingZoo-1.15.0-py3-none-any.whl
Collecting numpy==1.21.2 (from mlagents-envs==1.0.0)
  Using cached numpy-1.21.2.zip (10.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting filelock>=3.4.0 (from mlagents-envs==1.0.0)
  Obtaining dependency information for filelock>=3.4.0 from https://files.pythonhosted.org/packages/5e/5d/97afbafd9d584ff1b45fcb354a479a3609bd97f912f8f1f6c563cb1fae21/filelock-3.12.4-py3-none-any.whl.metadata
  Using cached filelock-3.12.4-py3-none-any.whl.metadata (2.8 kB)
Collecting six>=1.5.2 (from grpcio<=1.48.2,>=1.11.0->mlagents-envs==1.0.0)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting gym-notices>=0.0.4 (from gym>=0.21.0->mlagents-envs==1.0.0)
  Using cached gym_notices-0.0.8-py3-none-any.whl (3.0 kB)
Using cached filelock-3.12.4-py3-none-any.whl (11 kB)
Using cached Pillow-10.0.1-cp310-cp310-win_amd64.whl (2.5 MB)
Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
Building wheels for collected packages: mlagents-envs, numpy
  Building wheel for mlagents-envs (setup.py): started
  Building wheel for mlagents-envs (setup.py): finished with status 'done'
  Created wheel for mlagents-envs: filename=mlagents_envs-1.0.0-py3-none-any.whl size=90227 sha256=9402ff4442e2b12ce0f49637903203fd477797b6c77635db786643fde3e83513
  Stored in directory: c:\users\username\appdata\local\pip\cache\wheels\46\64\49\3a4aa69d1930f05b4731d0ab278e9c1e1624cdbf39afd9b67b
  Building wheel for numpy (pyproject.toml): started
  Building wheel for numpy (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  Building wheel for numpy (pyproject.toml) did not run successfully.
  exit code: 1

  [288 lines of output]
  **setup.py:63: RuntimeWarning: NumPy 1.21.2 may not yet support Python 3.10.**
    warnings.warn(
  Running from numpy source directory.
  Processing numpy/random\_bounded_integers.pxd.in
  Processing numpy/random\bit_generator.pyx
  Processing numpy/random\mtrand.pyx
  Processing numpy/random\_bounded_integers.pyx.in
  Processing numpy/random\_common.pyx
  Processing numpy/random\_generator.pyx
  Processing numpy/random\_mt19937.pyx
  Processing numpy/random\_pcg64.pyx
  Processing numpy/random\_philox.pyx
  Processing numpy/random\_sfc64.pyx
  Cythonizing sources
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  blis_info:
    libraries blis not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  openblas_info:
    libraries openblas not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Found executable C:\Program Files\Git\usr\bin\DF.exe
  Could not locate executable C:\Program
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE

  accelerate_info:
    NOT AVAILABLE

  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  atlas_3_10_blas_info:
    libraries satlas not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  atlas_blas_info:
    libraries f77blas,cblas,atlas not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\system_info.py:2026: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  blas_info:
    libraries blas not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\system_info.py:2026: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  blas_src_info:
    NOT AVAILABLE

  C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\system_info.py:2026: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
    NOT AVAILABLE

  non-existing path in 'numpy\\distutils': 'site.cfg'
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  openblas_clapack_info:
    libraries openblas,lapack not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  flame_info:
    libraries flame not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in C:\Users\username\.conda\envs\mlagents\lib
    libraries tatlas,tatlas not found in C:\Users\username\.conda\envs\mlagents\lib
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in C:\Users\username\.conda\envs\mlagents\libs
    libraries tatlas,tatlas not found in C:\Users\username\.conda\envs\mlagents\libs
    libraries lapack_atlas not found in C:\ProgramData\anaconda3\Library\lib
    libraries tatlas,tatlas not found in C:\ProgramData\anaconda3\Library\lib
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries lapack_atlas not found in C:\Users\username\.conda\envs\mlagents\lib
    libraries satlas,satlas not found in C:\Users\username\.conda\envs\mlagents\lib
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in C:\Users\username\.conda\envs\mlagents\libs
    libraries satlas,satlas not found in C:\Users\username\.conda\envs\mlagents\libs
    libraries lapack_atlas not found in C:\ProgramData\anaconda3\Library\lib
    libraries satlas,satlas not found in C:\ProgramData\anaconda3\Library\lib
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in C:\Users\username\.conda\envs\mlagents\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\username\.conda\envs\mlagents\lib
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\Users\username\.conda\envs\mlagents\libs
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\username\.conda\envs\mlagents\libs
    libraries lapack_atlas not found in C:\ProgramData\anaconda3\Library\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\ProgramData\anaconda3\Library\lib
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries lapack_atlas not found in C:\Users\username\.conda\envs\mlagents\lib
    libraries f77blas,cblas,atlas not found in C:\Users\username\.conda\envs\mlagents\lib
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\Users\username\.conda\envs\mlagents\libs
    libraries f77blas,cblas,atlas not found in C:\Users\username\.conda\envs\mlagents\libs
    libraries lapack_atlas not found in C:\ProgramData\anaconda3\Library\lib
    libraries f77blas,cblas,atlas not found in C:\ProgramData\anaconda3\Library\lib
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  lapack_info:
    libraries lapack not found in ['C:\\Users\\username\\.conda\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\username\\.conda\\envs\\mlagents\\libs', 'C:\\ProgramData\\anaconda3\\Library\\lib']
    NOT AVAILABLE

  C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\system_info.py:1858: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  lapack_src_info:
    NOT AVAILABLE

  C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\system_info.py:1858: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
    NOT AVAILABLE

  numpy_linalg_lapack_lite:
    FOUND:
      language = c
      define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

  Warning: attempted relative import with no known parent package
  C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build\src.win-amd64-3.10
  creating build\src.win-amd64-3.10\numpy
  creating build\src.win-amd64-3.10\numpy\distutils
  building library "npymath" sources
  Traceback (most recent call last):
    File "C:\Users\username\.conda\envs\mlagents\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\username\.conda\envs\mlagents\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\username\.conda\envs\mlagents\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\build_meta.py", line 211, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\build_meta.py", line 197, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\build_meta.py", line 248, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 448, in <module>
      setup_package()
    File "setup.py", line 440, in setup_package
      setup(**metadata)
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\core.py", line 169, in setup
      return old_setup(**new_attr)
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\command\build.py", line 61, in run
      old_build.run(self)
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\command\build_src.py", line 144, in run
      self.build_sources()
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\command\build_src.py", line 155, in build_sources
      self.build_library_sources(*libname_info)
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\command\build_src.py", line 288, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\command\build_src.py", line 378, in generate_sources
      source = func(extension, build_dir)
    File "numpy\core\setup.py", line 661, in get_mathlib_info
      st = config_cmd.try_link('int main(void) { return 0;}')
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 243, in try_link
      self._link(body, headers, include_dirs,
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\command\config.py", line 163, in _link
      return self._wrap_method(old_config._link, lang,
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\command\config.py", line 98, in _wrap_method
      ret = mth(*((self,)+args))
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 137, in _link
      (src, obj) = self._compile(body, headers, include_dirs, lang)
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\command\config.py", line 106, in _compile
      src, obj = self._wrap_method(old_config._compile, lang,
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\command\config.py", line 98, in _wrap_method
      ret = mth(*((self,)+args))
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
      self.compiler.compile([src], include_dirs=include_dirs)
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 401, in compile
      self.spawn(args)
    File "C:\Users\username\AppData\Local\Temp\pip-build-env-6vfbekb9\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 505, in spawn
      return super().spawn(cmd, env=env)
    File "C:\Users\username\AppData\Local\Temp\pip-install-1f3aoz7f\numpy_3aed17f4fb234ddc87642376fcf95d2e\numpy\distutils\ccompiler.py", line 88, in <lambda>
      m = lambda self, *args, **kw: func(self, *args, **kw)
  TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Successfully built mlagents-envs
Failed to build numpy
**ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects**
(mlagents)

```

**Environment (please complete the following information):**
- Unity Version: Unity 2022.3
- OS + version: Windows 10
- _ML-Agents version_: release branch 21
- _Torch version_:  1.13.1+cu117
- _Environment_: conda

**Comment by barsgunduz** [comment]
This is a problem related with my env. I had to change Python version from 3.10.13 to 3.10.12, to pass version check. I changed it after installing packages, so some packages were having trouble. Closing the issue, since its a user problem

**Comment by 3D-Wizard** [comment]
I also got this error~~~
Python==3.10.12
windows 10.

**Comment by SedMeh** [comment]
Also, I got this error
Python==3.10.11
Environment: cmd
Unity Version: Unity 2022.1.24

**Comment by barsgunduz** [comment]
Hey, 

@miguelalonsojr solved this problem in a previous PR, but I don't know if this fix is included in a release yet. 

If you still get this problem, you can check your setup.py file. The numpy version in that file should be something like this:
"numpy>=1.14.1,<1.24"

And it installed numpy 1.23.5 for me using these settings.

Check this issue for more info: [Issue 5826](https://github.com/Unity-Technologies/ml-agents/issues/5826)
