### ISSUE TITLE
RuntimeError: Could not infer dtype of numpy.float32

### ISSUE THREAD

**Issue by Linnien** [Unity-Technologies/ml-agents#6010]
**Describe the bug**
I can excute mlagents-learn --help successfully. But when I try to test the example 3DBall of mlagents，I always get the bug：RuntimeError: Could not infer dtype of numpy.float32

**To Reproduce**
Steps I am taking are:
1. Run mlagents-learn config/ppo/3DBall.yaml --run-id=3DBallTest --force in my virtual environment.
2. Press the Play button in the Unity Editor.
3. See the bug: RuntimeError: Could not infer dtype of numpy.float32

**Console logs / stack traces**
```
>mlagents-learn config/ppo/3DBall.yaml --run-id=3DBallTest --force
[W ..\torch\csrc\utils\tensor_numpy.cpp:77] Warning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (function operator ())

            ┐  ╖
        ╓╖╬│╡  ││╬╖╖
    ╓╖╬│││││┘  ╬│││││╬╖
 ╖╬│││││╬╜        ╙╬│││││╖╖                               ╗╗╗
 ╬╬╬╬╖││╦╖        ╖╬││╗╣╣╣╬      ╟╣╣╬    ╟╣╣╣             ╜╜╜  ╟╣╣
 ╬╬╬╬╬╬╬╬╖│╬╖╖╓╬╪│╓╣╣╣╣╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╒╣╣╖╗╣╣╣╗   ╣╣╣ ╣╣╣╣╣╣ ╟╣╣╖   ╣╣╣
 ╬╬╬╬┐  ╙╬╬╬╬│╓╣╣╣╝╜  ╫╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╟╣╣╣╙ ╙╣╣╣  ╣╣╣ ╙╟╣╣╜╙  ╫╣╣  ╟╣╣
 ╬╬╬╬┐     ╙╬╬╣╣      ╫╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╟╣╣╬   ╣╣╣  ╣╣╣  ╟╣╣     ╣╣╣┌╣╣╜
 ╬╬╬╜       ╬╬╣╣      ╙╝╣╣╬      ╙╣╣╣╗╖╓╗╣╣╣╜ ╟╣╣╬   ╣╣╣  ╣╣╣  ╟╣╣╦╓    ╣╣╣╣╣
 ╙   ╓╦╖    ╬╬╣╣   ╓╗╗╖            ╙╝╣╣╣╣╝╜   ╘╝╝╜   ╝╝╝  ╝╝╝   ╙╣╣╣    ╟╣╣╣
   ╩╬╬╬╬╬╬╦╦╬╬╣╣╗╣╣╣╣╣╣╣╝                                             ╫╣╣╣╣
      ╙╬╬╬╬╬╬╬╣╣╣╣╣╣╝╜
          ╙╬╬╬╣╣╣╜
             ╙

 Version information:
  ml-agents: 1.0.0,
  ml-agents-envs: 1.0.0,
  Communicator API: 1.5.0,
  PyTorch: 1.13.1+cu117
[W ..\torch\csrc\utils\tensor_numpy.cpp:77] Warning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (function operator ())
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
[INFO] Connected to Unity environment with package version 3.0.0-exp.1 and communication version 1.5.0
[INFO] Connected new brain: 3DBall?team=0
[WARNING] Deleting TensorBoard data events.out.tfevents.1699857998.Katherine-Space.19184.0 that was left over from a previous run.
[INFO] Hyperparameters for behavior name 3DBall:
        trainer_type:   ppo
        hyperparameters:
          batch_size:   64
          buffer_size:  12000
          learning_rate:        0.0003
          beta: 0.001
          epsilon:      0.2
          lambd:        0.99
          num_epoch:    3
          shared_critic:        False
          learning_rate_schedule:       linear
          beta_schedule:        linear
          epsilon_schedule:     linear
        checkpoint_interval:    500000
        network_settings:
          normalize:    True
          hidden_units: 128
          num_layers:   2
          vis_encode_type:      simple
          memory:       None
          goal_conditioning_type:       hyper
          deterministic:        False
        reward_signals:
          extrinsic:
            gamma:      0.99
            strength:   1.0
            network_settings:
              normalize:        False
              hidden_units:     128
              num_layers:       2
              vis_encode_type:  simple
              memory:   None
              goal_conditioning_type:   hyper
              deterministic:    False
        init_path:      None
        keep_checkpoints:       5
        even_checkpoints:       False
        max_steps:      500000
        time_horizon:   1000
        summary_freq:   12000
        threaded:       False
        self_play:      None
        behavioral_cloning:     None
[INFO] Exported results\3DBallTest\3DBall\3DBall-0.onnx
[INFO] Copied results\3DBallTest\3DBall\3DBall-0.onnx to results\3DBallTest\3DBall.onnx.
Traceback (most recent call last):
  File "D:\Anaconda\envs\mlagents\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\envs\mlagents\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\mlagents\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\learn.py", line 267, in main
    run_cli(parse_command_line())
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\learn.py", line 263, in run_cli
    run_training(run_seed, options, num_areas)
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\learn.py", line 137, in run_training
    tc.start_learning(env_manager)
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 175, in start_learning
    n_steps = self.advance(env_manager)
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 233, in advance
    new_step_infos = env_manager.get_steps()
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\env_manager.py", line 124, in get_steps
    new_step_infos = self._step()
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 408, in _step
    self._queue_steps()
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 302, in _queue_steps
    env_action_info = self._take_step(env_worker.previous_step)
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 543, in _take_step
    all_action_info[brain_name] = self.policies[brain_name].get_action(
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\policy\torch_policy.py", line 130, in get_action
    run_out = self.evaluate(decision_requests, global_agent_ids)
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\policy\torch_policy.py", line 94, in evaluate
    tensor_obs = [torch.as_tensor(np_ob) for np_ob in obs]
  File "D:\Anaconda\envs\mlagents\lib\site-packages\mlagents\trainers\policy\torch_policy.py", line 94, in <listcomp>
    tensor_obs = [torch.as_tensor(np_ob) for np_ob in obs]
RuntimeError: Could not infer dtype of numpy.float32
```

**Environment (please complete the following information):**
- Unity Version: Unity 2022.3f1
- OS + version:  Windows 11
- _ML-Agents version_: ML-Agents v3.0.0(Unity), mlagents v1.0.0(Python)
- _Torch version_: Pytorch 1.13.1
- _Environment_: virtual environment.

**Comment by Linnien** [comment]
Numpy Version：numpy-1.22.4 
Python Version：python3.10.12

**Comment by Linnien** [comment]
I fixed it! Just don't execute follow code:
![图片](https://github.com/Unity-Technologies/ml-agents/assets/48547245/e5818432-93a0-420c-b1f8-11d992c3cd53)
Because this pytorch version is incompile with numpy==1.22.4, which is the mlagents-env's request.

**Comment by miguelalonsojr** [comment]
These version issues should be fixed on develop.

**Comment by Lemmy00** [comment]
> numpy==1.22.4

Can please share which torch version you have installed instead of what is instructed?
