### ISSUE TITLE
Visual observation did not have the expected shape

### ISSUE THREAD

**Issue by 871234342** [Unity-Technologies/ml-agents#6041]
**Describe the bug**
I tried to add visual observation to my agent but I got error message while I ran the training. I tried with my custom environment and with the provided 3DBall environment and I got the same result. 

**To Reproduce**
1. Setup the camera sensor in 3DBall (attach camera sensor component to the agent, add a camera to the agent and drag that camera into the agent)
2. Run ```mlagents-learn config/ppo/3DBall.yaml --run=3DBallVisual --force```
3. Press play in Unity Editor
4. The error appears

**Console logs / stack traces**
```
(mlagents) ➜  ml-agents git:(com.unity.ml-agents_3.0.0) ✗ mlagents-learn config/ppo/3DBall.yaml --run=3DBallVisual --force
/home/caig/anaconda3/envs/mlagents/lib/python3.10/site-packages/torch/__init__.py:614: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:451.)
  _C._set_default_tensor_type(t)

            ┐  ╖
        ╓╖╬│╡  ││╬╖╖
    ╓╖╬│││││┘  ╬│││││╬╖
 ╖╬│││││╬╜        ╙╬│││││╖╖                               ╗╗╗
 ╬╬╬╬╖││╦╖        ╖╬││╗╣╣╣╬      ╟╣╣╬    ╟╣╣╣             ╜╜╜  ╟╣╣
 ╬╬╬╬╬╬╬╬╖│╬╖╖╓╬╪│╓╣╣╣╣╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╒╣╣╖╗╣╣╣╗   ╣╣╣ ╣╣╣╣╣╣ ╟╣╣╖   ╣╣╣
 ╬╬╬╬┐  ╙╬╬╬╬│╓╣╣╣╝╜  ╫╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╟╣╣╣╙ ╙╣╣╣  ╣╣╣ ╙╟╣╣╜╙  ╫╣╣  ╟╣╣
 ╬╬╬╬┐     ╙╬╬╣╣      ╫╣╣╣╬      ╟╣╣╬    ╟╣╣╣ ╟╣╣╬   ╣╣╣  ╣╣╣  ╟╣╣     ╣╣╣┌╣╣╜
 ╬╬╬╜       ╬╬╣╣      ╙╝╣╣╬      ╙╣╣╣╗╖╓╗╣╣╣╜ ╟╣╣╬   ╣╣╣  ╣╣╣  ╟╣╣╦╓    ╣╣╣╣╣
 ╙   ╓╦╖    ╬╬╣╣   ╓╗╗╖            ╙╝╣╣╣╣╝╜   ╘╝╝╜   ╝╝╝  ╝╝╝   ╙╣╣╣    ╟╣╣╣
   ╩╬╬╬╬╬╬╦╦╬╬╣╣╗╣╣╣╣╣╣╣╝                                             ╫╣╣╣╣
      ╙╬╬╬╬╬╬╬╣╣╣╣╣╣╝╜
          ╙╬╬╬╣╣╣╜
             ╙
        
 Version information:
  ml-agents: 1.0.0,
  ml-agents-envs: 1.0.0,
  Communicator API: 1.5.0,
  PyTorch: 2.1.0+cu121
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
[INFO] Connected to Unity environment with package version 2.0.1 and communication version 1.5.0
[INFO] Connected new brain: 3DBall?team=0
[ERROR] UnityEnvironment worker 0: environment raised an unexpected exception.
Traceback (most recent call last):
  File "/home/caig/ml-agents/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 211, in worker
    env.reset()
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/environment.py", line 325, in reset
    self._update_state(rl_output)
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/environment.py", line 306, in _update_state
    self._env_state[brain_name] = steps_from_proto(
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/rpc_utils.py", line 332, in steps_from_proto
    _process_maybe_compressed_observation(
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/rpc_utils.py", line 259, in _process_maybe_compressed_observation
    batched_visual = [
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/rpc_utils.py", line 260, in <listcomp>
    _observation_to_np_array(agent_obs.observations[obs_index], shape)
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/rpc_utils.py", line 241, in _observation_to_np_array
    raise UnityObservationException(
mlagents_envs.exception.UnityObservationException: Decompressed observation did not have the expected shape - decompressed had (3, 64, 84) but expected [64, 84, 3]
Traceback (most recent call last):
  File "/home/caig/anaconda3/envs/mlagents/bin/mlagents-learn", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "/home/caig/ml-agents/ml-agents/mlagents/trainers/learn.py", line 267, in main
    run_cli(parse_command_line())
  File "/home/caig/ml-agents/ml-agents/mlagents/trainers/learn.py", line 263, in run_cli
    run_training(run_seed, options, num_areas)
  File "/home/caig/ml-agents/ml-agents/mlagents/trainers/learn.py", line 137, in run_training
    tc.start_learning(env_manager)
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/caig/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 172, in start_learning
    self._reset_env(env_manager)
  File "/home/caig/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/caig/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 105, in _reset_env
    env_manager.reset(config=new_config)
  File "/home/caig/ml-agents/ml-agents/mlagents/trainers/env_manager.py", line 68, in reset
    self.first_step_infos = self._reset_env(config)
  File "/home/caig/ml-agents/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 446, in _reset_env
    ew.previous_step = EnvironmentStep(ew.recv().payload, ew.worker_id, {}, {})
  File "/home/caig/ml-agents/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 101, in recv
    raise env_exception
mlagents_envs.exception.UnityObservationException: Decompressed observation did not have the expected shape - decompressed had (3, 64, 84) but expected [64, 84, 3]

```

**Screenshots**
The camera sensor component setting:
![CameraSensorComponent](https://github.com/Unity-Technologies/ml-agents/assets/74284329/10a05117-1a9b-484e-8ea1-0b467aa083ec)

**Comment by 871234342** [comment]
I updated the ML-Agent package to 3.0.0 and that solves the problem.
