### ISSUE TITLE
I cant install mlagents can someone help me?

### ISSUE THREAD

**Issue by simonu90** [Unity-Technologies/ml-agents#6044]
I cant install mlagents can someone help me?

Collecting onnx==1.12.0 (from mlagents==1.0.0)
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/4c/678ctd4n0pj4m7qcjrzq88400000gn/T/pip-install-9xpnu9xn/onnx_3c268c2966f94905b58f1a52ec4ed89b/setup.py", line 81, in <module>
          assert CMAKE, "Could not find cmake executable!"
      AssertionError: Could not find cmake executable!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by simonu90** [comment]
im on m2 macbook

**Comment by simonu90** [comment]
i do everything that i can googled it
plz help
