### ISSUE TITLE
RuntimeError: Continuous NaN action detected

### ISSUE THREAD

**Issue by trsh** [Unity-Technologies/ml-agents#6049]
**Describe the bug**
```
Traceback (most recent call last):
  File "C:\Projects\Unity\ML\env-ml-agents\Scripts\mlagents-learn-script.py", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\learn.py", line 270, in main
    run_cli(parse_command_line())
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\learn.py", line 266, in run_cli
    run_training(run_seed, options, num_areas)
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\learn.py", line 138, in run_training
    tc.start_learning(env_manager)
  File "c:\projects\unity\ml\ml-agents\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 175, in start_learning
    n_steps = self.advance(env_manager)
  File "c:\projects\unity\ml\ml-agents\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 233, in advance
    new_step_infos = env_manager.get_steps()
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\env_manager.py", line 124, in get_steps
    new_step_infos = self._step()
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 408, in _step
    self._queue_steps()
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 302, in _queue_steps
    env_action_info = self._take_step(env_worker.previous_step)
  File "c:\projects\unity\ml\ml-agents\ml-agents-envs\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\subprocess_env_manager.py", line 543, in _take_step
    all_action_info[brain_name] = self.policies[brain_name].get_action(
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\policy\torch_policy.py", line 132, in get_action
    self.check_nan_action(run_out.get("action"))
  File "c:\projects\unity\ml\ml-agents\ml-agents\mlagents\trainers\policy\policy.py", line 126, in check_nan_action
    raise RuntimeError("Continuous NaN action detected.")
RuntimeError: Continuous NaN action detected.
```

**To Reproduce**
I have no idea (i.e. there is no stable Reproduce scenario), and I can not share my project. Fact is, there a NaN internally produced and it kills the learning process with no chance to resume it. 

**Environment (please complete the following information):**
- Unity Version: Unity 2022.2.3f1
- OS + version: Windows 11
- _ML-Agents version_: latest `develop`
- _Torch version_: 2.1.2+cu121
- _Environment_: private

I use POCA for training

**Comment by trsh** [comment]
Related topic https://forum.unity.com/threads/training-crashes-after-multiple-days-running-unable-to-resume-or-recover.1419761/
