### ISSUE TITLE
Registry URL Permission Denied

### ISSUE THREAD

**Issue by rahulaggarwal965** [Unity-Technologies/ml-agents#6105]
**Describe the bug**
I am seeing both an HTTP error corresponding to the registry which also leads to an attribute error down the line. Not sure if they are related. Just wanted to make this post to ask about the status of the registry and when we can expect it to be up again.

**Console logs / stack traces**
```
Traceback (most recent call last):
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/site-packages/mlagents_envs/registry/binary_utils.py", line 218, in load_remote_manifest
    request = urllib.request.urlopen(url, timeout=30)
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Code/eval_model.py", line 6, in <module>
    from common import make_unity_env
  File "/home/infinity/repos/deepdriftingicra22/Code/common.py", line 5, in <module>
    from mlagents_envs.envs.unity_gym_env import UnityToGymWrapper
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/site-packages/mlagents_envs/envs/__init__.py", line 5, in <module>
    for key in default_registry:
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/site-packages/mlagents_envs/registry/unity_env_registry.py", line 118, in __iter__
    self._load_all_manifests()
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/site-packages/mlagents_envs/registry/unity_env_registry.py", line 83, in _load_all_manifests
    manifest = load_remote_manifest(path_to_yaml)
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/site-packages/mlagents_envs/registry/binary_utils.py", line 220, in load_remote_manifest
    e.reason = f"{e.reason} {url}"
AttributeError: can't set attribute
```

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2021.3.18f1]
- OS + version: Ubuntu 20.04
- _ML-Agents version_: v0.30.0
- _Torch version_: 1.11.0
- _Environment_: Custom

**Comment by alhasacademy96** [comment]
I'm as well as my team are also getting this from today. 
---
Unity Version: [e.g. Unity 2021.3.18f1]
OS + version: Windows 11
ML-Agents version: v0.30.0
Torch version: 1.11.0
Environment: Custom

**Comment by miguelalonsojr** [comment]
https://github.com/Unity-Technologies/ml-agents/issues/6104#issuecomment-2091174608

**Comment by alhasacademy96** [comment]
Why is this being closed?

**Comment by miguelalonsojr** [comment]
It's fixed on develop. https://github.com/Unity-Technologies/ml-agents/issues/6104#issuecomment-2091174608
