### ISSUE TITLE
Registry URL Permission Denied; Attribute Error

### ISSUE THREAD

**Issue by alhasacademy96** [Unity-Technologies/ml-agents#6106]
I am seeing both an HTTP error corresponding to the registry which also leads to an attribute error down the line. Not sure if they are related. Just wanted to make this post to ask about the status of the registry and when we can expect it to be up again.

Console logs / stack traces

```
HTTPError                                 Traceback (most recent call last)
File [c:\Users\ia424\anaconda.3\envs\animal-ai\lib\site-packages\mlagents_envs\registry\binary_utils.py:218](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/site-packages/mlagents_envs/registry/binary_utils.py:218), in load_remote_manifest(url)
    [217](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/site-packages/mlagents_envs/registry/binary_utils.py:217) try:
--> [218](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/site-packages/mlagents_envs/registry/binary_utils.py:218)     request = urllib.request.urlopen(url, timeout=30)
    [219](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/site-packages/mlagents_envs/registry/binary_utils.py:219) except urllib.error.HTTPError as e:  # type: ignore

File [c:\Users\ia424\anaconda.3\envs\animal-ai\lib\urllib\request.py:214](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:214), in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    [213](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:213)     opener = _opener
--> [214](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:214) return opener.open(url, data, timeout)

File [c:\Users\ia424\anaconda.3\envs\animal-ai\lib\urllib\request.py:523](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:523), in OpenerDirector.open(self, fullurl, data, timeout)
    [522](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:522)     meth = getattr(processor, meth_name)
--> [523](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:523)     response = meth(req, response)
    [525](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:525) return response

File [c:\Users\ia424\anaconda.3\envs\animal-ai\lib\urllib\request.py:632](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:632), in HTTPErrorProcessor.http_response(self, request, response)
    [631](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:631) if not (200 <= code < 300):
--> [632](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:632)     response = self.parent.error(
    [633](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:633)         'http', request, response, code, msg, hdrs)
    [635](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:635) return response

File [c:\Users\ia424\anaconda.3\envs\animal-ai\lib\urllib\request.py:561](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:561), in OpenerDirector.error(self, proto, *args)
    [560](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:560) args = (dict, 'default', 'http_error_default') + orig_args
--> [561](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/urllib/request.py:561) return self._call_chain(*args)
...
--> [220](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/site-packages/mlagents_envs/registry/binary_utils.py:220)     e.reason = f"{e.reason} {url}"
    [221](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/site-packages/mlagents_envs/registry/binary_utils.py:221)     raise
    [222](file:///C:/Users/ia424/anaconda.3/envs/animal-ai/lib/site-packages/mlagents_envs/registry/binary_utils.py:222) manifest_path = os.path.join(tmp_dir, str(uuid.uuid4()) + ".yaml")
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "Code/eval_model.py", line 6, in <module>
    from common import make_unity_env
  File "/home/infinity/repos/deepdriftingicra22/Code/common.py", line 5, in <module>
    from mlagents_envs.envs.unity_gym_env import UnityToGymWrapper
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/site-packages/mlagents_envs/envs/__init__.py", line 5, in <module>
    for key in default_registry:
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/site-packages/mlagents_envs/registry/unity_env_registry.py", line 118, in __iter__
    self._load_all_manifests()
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/site-packages/mlagents_envs/registry/unity_env_registry.py", line 83, in _load_all_manifests
    manifest = load_remote_manifest(path_to_yaml)
  File "/home/infinity/mambaforge/envs/deepdrifting/lib/python3.8/site-packages/mlagents_envs/registry/binary_utils.py", line 220, in load_remote_manifest
    e.reason = f"{e.reason} {url}"
AttributeError: can't set attribute
```

Environment (please complete the following information):

Unity Version: [e.g. Unity 2021.3.18f1]
OS + version: Windows 11
ML-Agents version: v0.30.0
Torch version: 1.11.0
Environment: Custom

**Comment by miguelalonsojr** [comment]
https://github.com/Unity-Technologies/ml-agents/issues/6104#issuecomment-2091174608

**Comment by alhasacademy96** [comment]
Give an explanation at least

**Comment by miguelalonsojr** [comment]
It's fixed on develop. https://github.com/Unity-Technologies/ml-agents/issues/6104#issuecomment-2091174608
