### ISSUE TITLE
Most common reasons of UnityTimeOutException

### ISSUE THREAD

**Issue by hejcz** [Unity-Technologies/ml-agents#620]
Hi!

What are the most common reasons of timeout exception. I successfully start learning process running learn.py and after ~20-30k   steps I receive below error. How can I detect what is wrong. May it be caused by training model with tensorflow for cpu?
 
```
INFO:unityagents: SuitcaseBrain: Step: 29000. Mean Reward: -0.500. Std of Reward: 0.000.
INFO:unityagents:

ERROR:unityagents:An error might have occured in the environment. You can check the logfile for more information at C:\Users\Julian\Desktop\ml-agents\python/unity-environment.log
Traceback (most recent call last):
  File "C:\Users\Julian\Desktop\ml-agents\python\unityagents\environment.py", line 218, in _recv_bytes
    s = self._conn.recv(self._buffer_size)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\learn.py", line 62, in <module>
    tc.start_learning()
  File "C:\Users\Julian\Desktop\ml-agents\python\unitytrainers\trainer_controller.py", line 249, in start_learning
    text_action=take_action_text)
  File "C:\Users\Julian\Desktop\ml-agents\python\unityagents\environment.py", line 471, in step
    return self._get_state()
  File "C:\Users\Julian\Desktop\ml-agents\python\unityagents\environment.py", line 287, in _get_state
    state_dict, end_of_message = self._get_state_dict()
  File "C:\Users\Julian\Desktop\ml-agents\python\unityagents\environment.py", line 243, in _get_state_dict
    state = self._recv_bytes().decode('utf-8')
  File "C:\Users\Julian\Desktop\ml-agents\python\unityagents\environment.py", line 224, in _recv_bytes
    raise UnityTimeOutException("The environment took too long to respond.", self._log_path)
unityagents.exception.UnityTimeOutException: The environment took too long to respond.
```
I use Unity 2018.1.0b13 with following settings of ml components:

![academy](https://user-images.githubusercontent.com/9708672/38736115-50bd20c8-3f2b-11e8-917b-c9389066f86e.png)
![brain](https://user-images.githubusercontent.com/9708672/38736116-50e2d3d6-3f2b-11e8-8731-e3af054adbb0.png)
![agent](https://user-images.githubusercontent.com/9708672/38736117-51029d56-3f2b-11e8-8fd7-80d0b8101c13.png)

**Comment by hejcz** [comment]
Ok. The problem was as simple as I expected. I did not checked "Run in Background" so every time game window was not focused the game wasn't running and I received error from socket.
