### ISSUE TITLE
In Windows Issue with Unity 2018.1 for those who build directly inside the python folder.

### ISSUE THREAD

**Issue by ALanMAttano** [Unity-Technologies/ml-agents#635]
## **Issue for those who build directly inside the python folder.**
Unity 2018.1.0b13 contain a window modification improvement: 
When you try to build a game, it saves the build into a subfolder.

_

> Windows: The Build Player location selection dialogue now asks for a folder rather than a file name when building Windows standalone player. The BuildPipeline.BuildPlayer API is not affected by this change.

_ 

So if you are building the .exe inside the python directly, now with Unity 2018.1 is no longer possible in Windows. You need to save it into a subfolder.

**Comment by ALanMAttano** [comment]
YES for Windows users. But that was the case of the 2018.1.beta. I do not know if persist. Discussion [LINK](https://forum.unity.com/threads/not-sure-if-bug-or-feature-in-unity-2018-1-beta-9.520088/)

**Comment by xiaomaogy** [comment]
@ALanMAttano Yes you are correct, during the test on Windows last week I've also faced this issue. Basically you just need to create a folder named <env_name>, then save inside that folder. Then you can still call 
```
python learn.py <env_name> --train
```
Within your ml-agents/python folder. I will change the corresponding Windows doc to make this clear.

**Comment by xiaomaogy** [comment]
Thanks for reaching out to us. Hopefully you were able to resolve your issue.  We are closing this due to inactivity, but if you need additional assistance, feel free to reopen the issue.

**Comment by hoffmannprojects** [comment]
Hey, i'm having that same issue with Unity 2018.2.1f1 on Windows 10.
I used a custom python installation on Ubuntu 18.04 running on WSL.

I don't know if it's something with my dev environment or simply a syntax/file naming issue.
Regarding the latter possibility, this is what my file/folder structure looks like:

Build of the 3DBall example is inside: `ml-agents/python/ball`
Full path to the .exe is:  `ml-agents/python/ball/Unity Environment.exe`

From inside the `python` folder, i tried to run the following command: 
`python3 learn.py ball --run-id=TestRun01 --train`

This throws the following message:
`INFO:unityagents:{'--curriculum': 'None',
 '--docker-target-name': 'Empty',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--run-id': 'TestRun01',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<env>': 'ball'}
Traceback (most recent call last):
  File "learn.py", line 83, in <module>
    no_graphics)
  File "/mnt/d/Tim/Documents/Github/ml-agents/python/unitytrainers/trainer_controller.py", line 84, in __init__
    no_graphics=no_graphics)
  File "/mnt/d/Tim/Documents/Github/ml-agents/python/unityagents/environment.py", line 55, in __init__
    self.executable_launcher(file_name, docker_training, no_graphics)
  File "/mnt/d/Tim/Documents/Github/ml-agents/python/unityagents/environment.py", line 184, in executable_launcher
    .format(true_filename))
unityagents.exception.UnityEnvironmentException: Couldn't launch the ball environment. Provided filename does not match any environments.`

Please help me figuring out what's going wrong.
Best,
Tim

**Comment by xiaomaogy** [comment]
@hoffmannprojects This is usually something related with the environment name issue. I would try to make the .exe file instead ml-agents/python/ball/ball.exe, then try both
python3 learn.py ball --run-id=TestRun01 --train

and 

python3 learn.py ball/ball --run-id=TestRun01 --train

And one of them should work.

**Comment by hoffmannprojects** [comment]
@xiaomaogy that didn't work unfortunately.

Out of curiosity, i tried setting the build target to Linux and building to `ml-agents/python/ballLinux/ballLinux.x86`

This gave me a different error:
`INFO:unityagents:{'--curriculum': 'None',
 '--docker-target-name': 'Empty',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--run-id': 'TestRun01',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<env>': 'ballLinux/ballLinux'}
Traceback (most recent call last):
  File "learn.py", line 83, in <module>
    no_graphics)
  File "/mnt/d/Tim/Documents/Github/ml-agents/python/unitytrainers/trainer_controller.py", line 84, in __init__
    no_graphics=no_graphics)
  File "/mnt/d/Tim/Documents/Github/ml-agents/python/unityagents/environment.py", line 55, in __init__
    self.executable_launcher(file_name, docker_training, no_graphics)
  File "/mnt/d/Tim/Documents/Github/ml-agents/python/unityagents/environment.py", line 195, in executable_launcher
    [launch_string, '--port', str(self.port)])
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/mnt/d/Tim/Documents/Github/ml-agents/python/ballLinux/ballLinux.x86'`

Could it be that it has to do with the build settings/my dev environment?
Maybe running python on Ubuntu (in WSL) but building on Windows could be the reason for the issue?

**Comment by timdhoffmann** [comment]
I installed Anaconda for Windows, following the official installation guide and got it to work with the following command in Anaconda Prompt:
`python learn.py "ball\Unity Environment" --run-id=TestRun01 --train`

Why does the documentation not mention more clearly that you have to specify it that way?
Or is it just acting weird in my scenario?
