### ISSUE TITLE
Imitation Learning Error

### ISSUE THREAD

**Issue by imankgoyal** [Unity-Technologies/ml-agents#643]
I am getting the following error when training imitation learning. I have added the complete terminal log below. The game starts as expected, but it ends as soon as I take the **second action** (for the agent with "Teacher" brain). On running the game in the Unity, I am able to control the agent with "Teacher" brain.  **Broadcast** is checked for the "Teacher" brain.

```
python learn.py ./games/EgpGame-StudentTeacher-1.0.1.x86 --run-id=Epggame-StudentTeacher-1.0.1.1 --train --slow
INFO:unityagents:{'--curriculum': 'None',
 '--docker-target-name': 'Empty',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--run-id': 'Epggame-StudentTeacher-1.0.1.1',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': True,
 '--train': True,
 '--worker-id': '0',
 '<env>': './games/EgpGame-StudentTeacher-1.0.1.x86'}
Found path: /home/ankgoyal/MEGA/Research/Codes/egp/ml-agents-0.3.0b/python/./games/EgpGame-StudentTeacher-1.0.1.x86
Mono path[0] = '/home/ankgoyal/MEGA/Research/Codes/egp/ml-agents-0.3.0b/python/./games/EgpGame-StudentTeacher-1.0.1_Data/Managed'
Mono config path = '/home/ankgoyal/MEGA/Research/Codes/egp/ml-agents-0.3.0b/python/./games/EgpGame-StudentTeacher-1.0.1_Data/MonoBleedingEdge/etc'
PlayerConnection initialized from /home/ankgoyal/MEGA/Research/Codes/egp/ml-agents-0.3.0b/python/./games/EgpGame-StudentTeacher-1.0.1_Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55112
Multi-casting "[IP] 141.212.109.104 [Port] 55112 [Flags] 2 [Guid] 2012999781 [EditorId] 1321939908 [Version] 1048832 [Id] LinuxPlayer(141.212.109.104) [Debug] 0" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55112]
Unable to preload the following plugins:
	ScreenSelector.so
PlayerConnection already initialized - listening to [0.0.0.0:55112]
Logging to /home/ankgoyal/.config/unity3d/DefaultCompany/egp_game/Player.log
INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 2
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: Teacher
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 19
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): 15
        Vector Action descriptions: , , , , , , , , , , , , , , 
Unity brain name: Student
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 19
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): 15
        Vector Action descriptions: , , , , , , , , , , , , , , 
2018-04-17 12:27:16.371054: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:unityagents:Hyperparameters for the Imitation Trainer of brain Student: 
	brain_to_imitate:	Teacher
	batch_size:	16
	time_horizon:	2048
	graph_scope:	
	summary_freq:	1000
	max_steps:	10000
	batches_per_epoch:	5
	use_recurrent:	True
	hidden_units:	64
	num_layers:	4
	sequence_length:	16
	memory_size:	256
Traceback (most recent call last):
  File "learn.py", line 62, in <module>
    tc.start_learning()
  File "/home/ankgoyal/MEGA/Research/Codes/egp/ml-agents-0.3.0b/python/unitytrainers/trainer_controller.py", line 252, in start_learning
    trainer.add_experiences(curr_info, new_info, take_action_outputs[brain_name])
  File "/home/ankgoyal/MEGA/Research/Codes/egp/ml-agents-0.3.0b/python/unitytrainers/bc/trainer.py", line 188, in add_experiences
    if info_teacher.text_observations[idx] != "":
IndexError: list index out of range
```

I would greatly appreciate any help. Thanks.

**Comment by vincentpierre** [comment]
I think you found a bug. I will try something about it. Can you try something for me ? In `python/unitytrainers/bc/trainer.py` replace lines 188 to 189 : 
Replace 
```
                if info_teacher.text_observations[idx] != "":
                    info_teacher_record, info_teacher_reset = info_teacher.text_observations[idx].lower().split(",")
```
with 
```
                if stored_info_teacher.text_observations[idx] != "":
                    info_teacher_record, info_teacher_reset = stored_info_teacher.text_observations[idx].lower().split(",")
```
Let me know if that does the trick.

**Comment by vincentpierre** [comment]
I was able to reproduce the bug by setting the decision frequency of the banana teacher to 2 instead of one. The above code seems to fix it. Let us know.

**Comment by imankgoyal** [comment]
Yes, it works now. Thanks!

**Comment by whiteGhost333** [comment]
I am not certain that this directly related but it is very similar. When trying to tensorboard, I receive the following message :


(ml-agents) C:\Users\msi>tensorboard --logdir=summaries
2019-01-21 11:46:59.095850: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
TensorBoard 1.7.0 at http://DESKTOP-DVLHIQK:6006 (Press CTRL+C to quit)

This occurs after an apparently(no reason to think otherwise) successful training in 3D Ball Learning.

Thanks
