### ISSUE TITLE
Running learn.py without —train

### ISSUE THREAD

**Issue by RossMelbourne** [Unity-Technologies/ml-agents#646]
I can run the sample 3DBall app in Internal mode in the editor and it works great.  However, if I build the app and try to run it without the —train parameter on learn.py I receive the following errors:

Using:   python3 learn.py 3DBall.app --run-id=3DBall_inference_1 --slow

Errors:
INFO:unityagents:
'Ball3DAcademy' started successfully!
Unity Academy name: Ball3DAcademy
        Number of Brains: 1
        Number of External Brains : 0
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: Ball3DBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 3
        Vector Action space type: continuous
        Vector Action space size (per agent): 2
        Vector Action descriptions: , 
WARNING:unityagents: No External Brains found in the Unity Environment. You will not be able to pass actions to your agent(s).
2018-04-18 09:35:28.884166: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "learn.py", line 62, in <module>
    tc.start_learning()
  File "/Users/rossmelbourne/ml-agents-master/ml-agents/python/unitytrainers/trainer_controller.py", line 217, in start_learning
    saver = tf.train.Saver(max_to_keep=self.keep_checkpoints)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1251, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

I believe I am using all the latest files from unity-ml.  The purpose of running in inference mode without training is to see if I can capture the predicted actions from the internal mode brain passed to the python code via broadcast.

**Comment by eshvk** [comment]
Hi @RossMelbourne 

`learn.py` is typically designed to do learning in four situations:

1. `--train` where you have an `ExternalBrain` where you are training the Policy using `UnityEnvironment`. 

2. `--train` + `--load` where you continue training from a previously loaded model. 

3. `--load` : Load and observe what happens when you use a previous model. This is inference, except that the inference is happening from the ExternalBrain in python. 

4. In the absence of both flags, the ExternalBrain in UnityEnvironment is controlled by a random policy, e.g. if you need some baselines of what random behavior looks like. 

In your particular scenario, I'd suggest using `UnityEnvironment` to capture the predicted actions.

**Comment by baggyg** [comment]
I encountered this error when my Unity build was set to Player controls rather than External, if that helps.

**Comment by xiaomaogy** [comment]
Thanks for reaching out to us. Hopefully you were able to resolve your issue.  We are closing this due to inactivity, but if you need additional assistance, feel free to reopen the issue.
