### ISSUE TITLE
Imitation Learning crashes

### ISSUE THREAD

**Issue by hsaikia** [Unity-Technologies/ml-agents#690]
My training using imitation learning crashes after just 2000 steps or so with this error:

```
Traceback (most recent call last):
  File "learn.py", line 62, in <module>
    tc.start_learning()
  File "D:\Code_Repositories\UnityML\ml-agents\python\unitytrainers\trainer_controller.py", line 252, in start_learning
    trainer.add_experiences(curr_info, new_info, take_action_outputs[brain_name])
  File "D:\Code_Repositories\UnityML\ml-agents\python\unitytrainers\bc\trainer.py", line 188, in add_experiences
    if info_teacher.text_observations[idx] != "":
IndexError: list index out of range
```

Anything I'm doing wrong?

**Comment by hsaikia** [comment]
My bad. Guess that this bug was already pull. I was using a slightly older version of the repository. 

Thanks nonetheless!
