### ISSUE TITLE
Tensorboard ModuleNotFound error

### ISSUE THREAD

**Issue by jlanis** [Unity-Technologies/ml-agents#959]
Trying to launch tensorboard gives me this error on OSX:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorboard/main.py", line 30, in <module>
    from tensorboard import default
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorboard/default.py", line 36, in <module>
    from tensorboard.plugins.beholder import beholder_plugin
ModuleNotFoundError: No module named 'tensorboard.plugins.beholder'
```
I have tensorflow 1.7.1 installed and tensorboard 0.4.0, using the latest version of ml-agents. It was working before I updated ml-agents.

**Comment by xiaomaogy** [comment]
Have you tried to import the tensorboard module in your current python environment?

**Comment by jlanis** [comment]
How do I do that?

**Comment by xiaomaogy** [comment]
type `python` in your command line. 
Then type `import tensorboard` and see if it can be correctly imported.

**Comment by jlanis** [comment]
@xiaomaogy importing works when I use python3 as the first command.

**Comment by xiaomaogy** [comment]
Does import tensorboard.plugins.beholder also work?

**Comment by jlanis** [comment]
@xiaomaogy  No

**Comment by xiaomaogy** [comment]
So it seems to be related with your tensorboard package.

**Comment by jlanis** [comment]
@xiaomaogy So this is the output from `sudo pip3 install .`:

```
Requirement already satisfied: tensorflow==1.7.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from unityagents==0.4.0) (1.7.1)
Requirement already satisfied: Pillow>=4.2.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from unityagents==0.4.0) (5.0.0)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from unityagents==0.4.0) (2.2.2)
Requirement already satisfied: numpy>=1.11.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from unityagents==0.4.0) (1.14.2)
Requirement already satisfied: jupyter in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from unityagents==0.4.0) (1.0.0)
Requirement already satisfied: pytest>=3.2.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from unityagents==0.4.0) (3.5.0)
Requirement already satisfied: docopt in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from unityagents==0.4.0) (0.6.2)
Requirement already satisfied: pyyaml in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from unityagents==0.4.0) (3.12)
Requirement already satisfied: protobuf==3.5.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from unityagents==0.4.0) (3.5.2)
Requirement already satisfied: grpcio==1.11.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from unityagents==0.4.0) (1.11.0)
Requirement already satisfied: tensorboard<1.8.0,>=1.7.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorflow==1.7.1->unityagents==0.4.0) (1.7.0)
Requirement already satisfied: six>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorflow==1.7.1->unityagents==0.4.0) (1.11.0)
Requirement already satisfied: termcolor>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorflow==1.7.1->unityagents==0.4.0) (1.1.0)
Requirement already satisfied: absl-py>=0.1.6 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorflow==1.7.1->unityagents==0.4.0) (0.2.2)
Requirement already satisfied: wheel>=0.26 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorflow==1.7.1->unityagents==0.4.0) (0.30.0)
Requirement already satisfied: astor>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorflow==1.7.1->unityagents==0.4.0) (0.6.2)
Requirement already satisfied: gast>=0.2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorflow==1.7.1->unityagents==0.4.0) (0.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib->unityagents==0.4.0) (1.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib->unityagents==0.4.0) (2.7.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib->unityagents==0.4.0) (2.2.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib->unityagents==0.4.0) (0.10.0)
Requirement already satisfied: pytz in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib->unityagents==0.4.0) (2018.3)
Requirement already satisfied: ipywidgets in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jupyter->unityagents==0.4.0) (7.2.0)
Requirement already satisfied: qtconsole in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jupyter->unityagents==0.4.0) (4.3.1)
Requirement already satisfied: ipykernel in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jupyter->unityagents==0.4.0) (4.8.2)
Requirement already satisfied: jupyter-console in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jupyter->unityagents==0.4.0) (5.2.0)
Requirement already satisfied: nbconvert in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jupyter->unityagents==0.4.0) (5.3.1)
Requirement already satisfied: notebook in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jupyter->unityagents==0.4.0) (5.4.1)
Requirement already satisfied: more-itertools>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=3.2.2->unityagents==0.4.0) (4.1.0)
Requirement already satisfied: pluggy<0.7,>=0.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=3.2.2->unityagents==0.4.0) (0.6.0)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=3.2.2->unityagents==0.4.0) (39.0.1)
Requirement already satisfied: attrs>=17.4.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=3.2.2->unityagents==0.4.0) (17.4.0)
Requirement already satisfied: py>=1.5.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest>=3.2.2->unityagents==0.4.0) (1.5.3)
Requirement already satisfied: markdown>=2.6.8 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow==1.7.1->unityagents==0.4.0) (2.6.11)
Requirement already satisfied: bleach==1.5.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow==1.7.1->unityagents==0.4.0) (1.5.0)
Requirement already satisfied: html5lib==0.9999999 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow==1.7.1->unityagents==0.4.0) (0.9999999)
Requirement already satisfied: werkzeug>=0.11.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow==1.7.1->unityagents==0.4.0) (0.14.1)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipywidgets->jupyter->unityagents==0.4.0) (6.2.1)
Requirement already satisfied: traitlets>=4.3.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipywidgets->jupyter->unityagents==0.4.0) (4.3.2)
Requirement already satisfied: widgetsnbextension~=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipywidgets->jupyter->unityagents==0.4.0) (3.2.0)
Requirement already satisfied: nbformat>=4.2.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipywidgets->jupyter->unityagents==0.4.0) (4.4.0)
Requirement already satisfied: pygments in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from qtconsole->jupyter->unityagents==0.4.0) (2.2.0)
Requirement already satisfied: ipython-genutils in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from qtconsole->jupyter->unityagents==0.4.0) (0.2.0)
Requirement already satisfied: jupyter-client>=4.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from qtconsole->jupyter->unityagents==0.4.0) (5.2.3)
Requirement already satisfied: jupyter-core in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from qtconsole->jupyter->unityagents==0.4.0) (4.4.0)
Requirement already satisfied: tornado>=4.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipykernel->jupyter->unityagents==0.4.0) (5.0.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jupyter-console->jupyter->unityagents==0.4.0) (1.0.15)
Requirement already satisfied: pandocfilters>=1.4.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nbconvert->jupyter->unityagents==0.4.0) (1.4.2)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nbconvert->jupyter->unityagents==0.4.0) (2.10)
Requirement already satisfied: mistune>=0.7.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nbconvert->jupyter->unityagents==0.4.0) (0.8.3)
Requirement already satisfied: entrypoints>=0.2.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nbconvert->jupyter->unityagents==0.4.0) (0.2.3)
Requirement already satisfied: testpath in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nbconvert->jupyter->unityagents==0.4.0) (0.3.1)
Requirement already satisfied: Send2Trash in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from notebook->jupyter->unityagents==0.4.0) (1.5.0)
Requirement already satisfied: terminado>=0.8.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from notebook->jupyter->unityagents==0.4.0) (0.8.1)
Requirement already satisfied: pickleshare in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->unityagents==0.4.0) (0.7.4)
Requirement already satisfied: jedi>=0.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->unityagents==0.4.0) (0.11.1)
Requirement already satisfied: simplegeneric>0.8 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->unityagents==0.4.0) (0.8.1)
Requirement already satisfied: appnope; sys_platform == "darwin" in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->unityagents==0.4.0) (0.1.0)
Requirement already satisfied: decorator in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->unityagents==0.4.0) (4.2.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->unityagents==0.4.0) (4.4.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nbformat>=4.2.0->ipywidgets->jupyter->unityagents==0.4.0) (2.6.0)
Requirement already satisfied: pyzmq>=13 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jupyter-client>=4.1->qtconsole->jupyter->unityagents==0.4.0) (17.0.0)
Requirement already satisfied: wcwidth in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.0->jupyter-console->jupyter->unityagents==0.4.0) (0.1.7)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jinja2->nbconvert->jupyter->unityagents==0.4.0) (1.0)
Requirement already satisfied: ptyprocess; os_name != "nt" in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from terminado>=0.8.1->notebook->jupyter->unityagents==0.4.0) (0.5.2)
Requirement already satisfied: parso==0.1.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->unityagents==0.4.0) (0.1.1)
Installing collected packages: unityagents
  Found existing installation: unityagents 0.4.0
    Uninstalling unityagents-0.4.0:
      Successfully uninstalled unityagents-0.4.0
  Running setup.py install for unityagents ... done
Successfully installed unityagents-0.4.0


```

**Comment by jlanis** [comment]
@xiaomaogy Never mind, I fixed it! Reinstalling python and then all the extras did the trick.
